const levelCLASS5_Words = [
    { id: 1, en: "CLASS 5", ar: "الصف الخامس", pronounce: "ليفل فايف", ex_en: "He in the CLASS 5 Sentence 1", ar_ex: " هو في الصف الخامس الجملة الاولى" },
    { id: 2, en: "CLASS 5", ar: "الصف الخامس", pronounce: "ليفل فايف", ex_en: "He in the CLASS 5 Sentence 2", ar_ex: " هو في الصف الخامس الجملة الاولى" },
    { id: 3, en: "CLASS 5", ar: "الصف الخامس", pronounce: "ليفل فايف", ex_en: "He in the CLASS 5 Sentence 3", ar_ex: " هو في الصف الخامس الجملة الاولى" },
    { id: 4, en: "CLASS 5", ar: "الصف الخامس", pronounce: "ليفل فايف", ex_en: "He in the CLASS 5 Sentence 4", ar_ex: " هو في الصف الخامس الجملة الاولى" },
    { id: 5, en: "CLASS 5", ar: "الصف الخامس", pronounce: "ليفل فايف", ex_en: "He in the CLASS 5 Sentence 5", ar_ex: " هو في الصف الخامس الجملة الاولى" },
    { id: 6, en: "CLASS 5", ar: "الصف الخامس", pronounce: "ليفل فايف", ex_en: "He in the CLASS 5 Sentence 6", ar_ex: " هو في الصف الخامس الجملة الاولى" },
    { id: 7, en: "CLASS 5", ar: "الصف الخامس", pronounce: "ليفل فايف", ex_en: "He in the CLASS 5 Sentence 7", ar_ex: " هو في الصف الخامس الجملة الاولى" },
    { id: 8, en: "CLASS 5", ar: "الصف الخامس", pronounce: "ليفل فايف", ex_en: "He in the CLASS 5 Sentence 8", ar_ex: " هو في الصف الخامس الجملة الاولى" },
    { id: 9, en: "CLASS 5", ar: "الصف الخامس", pronounce: "ليفل فايف", ex_en: "He in the CLASS 5 Sentence 9", ar_ex: " هو في الصف الخامس الجملة الاولى" },
    { id: 10, en: "CLASS 5", ar: "الصف الخامس", pronounce: "ليفل فايف", ex_en: "He in the CLASS 5 Sentence 10", ar_ex: " هو في الصف الخامس الجملة الاولى" },
    { id: 11, en: "CLASS 5", ar: "الصف الخامس", pronounce: "ليفل فايف", ex_en: "He in the CLASS 5 Sentence 11", ar_ex: " هو في الصف الخامس الجملة الاولى" },
    { id: 12, en: "CLASS 5", ar: "الصف الخامس", pronounce: "ليفل فايف", ex_en: "He in the CLASS 5 Sentence 12", ar_ex: " هو في الصف الخامس الجملة الاولى" },
    { id: 13, en: "CLASS 5", ar: "الصف الخامس", pronounce: "ليفل فايف", ex_en: "He in the CLASS 5 Sentence 13", ar_ex: " هو في الصف الخامس الجملة الاولى" },
    { id: 14, en: "CLASS 5", ar: "الصف الخامس", pronounce: "ليفل فايف", ex_en: "He in the CLASS 5 Sentence 14", ar_ex: " هو في الصف الخامس الجملة الاولى" },
    { id: 15, en: "CLASS 5", ar: "الصف الخامس", pronounce: "ليفل فايف", ex_en: "He in the CLASS 5 Sentence 15", ar_ex: " هو في الصف الخامس الجملة الاولى" },
    { id: 16, en: "CLASS 5", ar: "الصف الخامس", pronounce: "ليفل فايف", ex_en: "He in the CLASS 5 Sentence 16", ar_ex: " هو في الصف الخامس الجملة الاولى" },
    { id: 17, en: "CLASS 5", ar: "الصف الخامس", pronounce: "ليفل فايف", ex_en: "He in the CLASS 5 Sentence 17", ar_ex: " هو في الصف الخامس الجملة الاولى" },
    { id: 18, en: "CLASS 5", ar: "الصف الخامس", pronounce: "ليفل فايف", ex_en: "He in the CLASS 5 Sentence 18", ar_ex: " هو في الصف الخامس الجملة الاولى" },
    { id: 19, en: "CLASS 5", ar: "الصف الخامس", pronounce: "ليفل فايف", ex_en: "He in the CLASS 5 Sentence 19", ar_ex: " هو في الصف الخامس الجملة الاولى" },
    { id: 20, en: "CLASS 5", ar: "الصف الخامس", pronounce: "ليفل فايف", ex_en: "He in the CLASS 5 Sentence 20", ar_ex: " هو في الصف الخامس الجملة الاولى" },
    { id: 21, en: "CLASS 5", ar: "الصف الخامس", pronounce: "ليفل فايف", ex_en: "He in the CLASS 5 Sentence 21", ar_ex: " هو في الصف الخامس الجملة الاولى" },
    { id: 22, en: "CLASS 5", ar: "الصف الخامس", pronounce: "ليفل فايف", ex_en: "He in the CLASS 5 Sentence 22", ar_ex: " هو في الصف الخامس الجملة الاولى" },
    { id: 23, en: "CLASS 5", ar: "الصف الخامس", pronounce: "ليفل فايف", ex_en: "He in the CLASS 5 Sentence 23", ar_ex: " هو في الصف الخامس الجملة الاولى" },
    { id: 24, en: "CLASS 5", ar: "الصف الخامس", pronounce: "ليفل فايف", ex_en: "He in the CLASS 5 Sentence 24", ar_ex: " هو في الصف الخامس الجملة الاولى" },
    { id: 25, en: "CLASS 5", ar: "الصف الخامس", pronounce: "ليفل فايف", ex_en: "He in the CLASS 5 Sentence 25", ar_ex: " هو في الصف الخامس الجملة الاولى" }
];