const levelCLASS12_Words = [
  { "id": 1, "en": "associate", "ar": "يربط / يشارك", "pronounce": "أسُوشِيِيت", "ex_en": "Associate with good people", "ar_ex": "شارك الأشخاص الجيدين" },
  { "id": 2, "en": "coincide", "ar": "يتزامن", "pronounce": "كُويِنْسَايْد", "ex_en": "The events coincide", "ar_ex": "الأحداث تتزامن" },
  { "id": 3, "en": "drop", "ar": "يُسقط / ينخفض / يتخلى", "pronounce": "دْرُوپ", "ex_en": "Do not drop it", "ar_ex": "لا تسقطه" },
  { "id": 4, "en": "enthusiasm", "ar": "حماس", "pronounce": "إنْثُوزِيَازِم", "ex_en": "Show some enthusiasm", "ar_ex": "أظهر بعض الحماس" },
  { "id": 5, "en": "gratitude", "ar": "امتنان", "pronounce": "گْرَاتِتْيُود", "ex_en": "Express your gratitude", "ar_ex": "عبر عن امتنانك" },
  { "id": 6, "en": "in commemoration of", "ar": "إحياء لذكرى", "pronounce": "إن كُمِمُورِيْشِن أُوف", "ex_en": "In commemoration of the hero", "ar_ex": "إحياء لذكرى البطل" },
  { "id": 7, "en": "in favour of", "ar": "لصالح / مؤيد لـ", "pronounce": "إن فِيْڤَر أُوف", "ex_en": "I am in favour of this", "ar_ex": "أنا أؤيد هذا" },
  { "id": 8, "en": "in praise of", "ar": "في مدح / ثناء على", "pronounce": "إن پْرِيز أُوف", "ex_en": "A song in praise of peace", "ar_ex": "أغنية في مدح السلام" },
  { "id": 9, "en": "joint", "ar": "مشترك", "pronounce": "جُويْنْت", "ex_en": "A joint effort", "ar_ex": "جهد مشترك" },
  { "id": 10, "en": "lunar", "ar": "قمري", "pronounce": "لُونَر", "ex_en": "A lunar eclipse", "ar_ex": "خسوف قمري" },
  { "id": 11, "en": "make it", "ar": "ينجح / يصل", "pronounce": "مِيك إت", "ex_en": "You will make it", "ar_ex": "سوف تنجح" },
  { "id": 12, "en": "mark", "ar": "يعلّم / يمثل", "pronounce": "مَارْك", "ex_en": "Mark the correct answer", "ar_ex": "علّم الإجابة الصحيحة" },
  { "id": 13, "en": "occasion", "ar": "مناسبة", "pronounce": "أُوكِيْژِن", "ex_en": "A special occasion", "ar_ex": "مناسبة خاصة" },
  { "id": 14, "en": "optimistic", "ar": "متفائل", "pronounce": "أُوپْتِمِسْتِك", "ex_en": "Stay optimistic", "ar_ex": "ابق متفائلاً" },
  { "id": 15, "en": "owe", "ar": "يدين لـ", "pronounce": "أُو", "ex_en": "I owe you a favor", "ar_ex": "أنا أدين لك بمعروف" },
  { "id": 16, "en": "reflect", "ar": "يعكس", "pronounce": "رِفْلِكْت", "ex_en": "Mirrors reflect light", "ar_ex": "المرايا تعكس الضوء" },
  { "id": 17, "en": "stick to", "ar": "يلتزم بـ", "pronounce": "سْتِك تُو", "ex_en": "Stick to the plan", "ar_ex": "التزم بالخطة" },
  { "id": 18, "en": "symbol / symbolise", "ar": "رمز / يرمز", "pronounce": "سِمْبُل", "ex_en": "A symbol of peace", "ar_ex": "رمز للسلام" },
  { "id": 19, "en": "take up", "ar": "يبدأ (هواية) / يشغل", "pronounce": "تِيك أپ", "ex_en": "Take up a new hobby", "ar_ex": "ابدأ هواية جديدة" },
  { "id": 20, "en": "troupe", "ar": "فرقة (مسرحية أو استعراضية)", "pronounce": "تْرُوپ", "ex_en": "A dance troupe", "ar_ex": "فرقة رقص" },
  { "id": 21, "en": "common purpose", "ar": "هدف مشترك", "pronounce": "كُومُن پِيرْپَس", "ex_en": "We share a common purpose", "ar_ex": "نتشارك هدفاً مشتركاً" },
  { "id": 22, "en": "decline", "ar": "يرفض / ينحدر", "pronounce": "دِكْلَايْن", "ex_en": "He declined the offer", "ar_ex": "رفض العرض" },
  { "id": 23, "en": "cut off", "ar": "يقطع / يفصل", "pronounce": "كَط أُوف", "ex_en": "Cut off the electricity", "ar_ex": "اقطع الكهرباء" },
  { "id": 24, "en": "divide", "ar": "يقسم / فجوة", "pronounce": "دِڤَايْد", "ex_en": "A deep divide", "ar_ex": "انقسام عميق" },
  { "id": 25, "en": "deliberately", "ar": "عمداً", "pronounce": "دِلِبِرِتْلي", "ex_en": "He did it deliberately", "ar_ex": "فعلها عمداً" },
  { "id": 26, "en": "donate", "ar": "يتبرع", "pronounce": "دُونِيْت", "ex_en": "Donate to the poor", "ar_ex": "تبرع للفقراء" },
  { "id": 27, "en": "fit in", "ar": "ينسجم / يتأقلم", "pronounce": "فِت إن", "ex_en": "He wants to fit in", "ar_ex": "يريد أن ينسجم" },
  { "id": 28, "en": "elsewhere", "ar": "في مكان آخر", "pronounce": "إلْسْوِير", "ex_en": "Look elsewhere", "ar_ex": "ابحث في مكان آخر" },
  { "id": 29, "en": "grow out of", "ar": "يكبر على شيء / ينشأ من", "pronounce": "گْرُو آوْت أُوف", "ex_en": "He will grow out of it", "ar_ex": "سيكبر ويتخلى عن ذلك" },
  { "id": 30, "en": "idiom", "ar": "مصطلح (مجازي)", "pronounce": "إدْيَم", "ex_en": "An English idiom", "ar_ex": "مصطلح إنجليزي" },
  { "id": 31, "en": "implication", "ar": "تضمين / أثر متوقع", "pronounce": "إمْپْلِكِيْشِن", "ex_en": "A serious implication", "ar_ex": "أثر خطير متوقع" },
  { "id": 32, "en": "leave out", "ar": "يترك / يستبعد", "pronounce": "لِيڤ آوْت", "ex_en": "Do not leave me out", "ar_ex": "لا تستبعدني" },
  { "id": 33, "en": "lifestyle", "ar": "نمط الحياة", "pronounce": "لَايْفْسْتَايْل", "ex_en": "A healthy lifestyle", "ar_ex": "نمط حياة صحي" },
  { "id": 34, "en": "lone individual", "ar": "فرد وحيد", "pronounce": "لُون إنْدِڤِجْوَل", "ex_en": "A lone individual", "ar_ex": "فرد وحيد" },
  { "id": 35, "en": "more than likely", "ar": "على الأرجح", "pronounce": "مُور ذَان لَايْكْلي", "ex_en": "More than likely yes", "ar_ex": "نعم على الأرجح" },
  { "id": 36, "en": "outstanding", "ar": "بارز / متميز", "pronounce": "آوْتْسْتَانْدِنْغ", "ex_en": "Outstanding performance", "ar_ex": "أداء متميز" },
  { "id": 37, "en": "process", "ar": "عملية", "pronounce": "پْرُوسِس", "ex_en": "A slow process", "ar_ex": "عملية بطيئة" },
  { "id": 38, "en": "rare", "ar": "نادر", "pronounce": "رِير", "ex_en": "A rare bird", "ar_ex": "طائر نادر" },
  { "id": 39, "en": "stand out", "ar": "يبرز", "pronounce": "سْتَانْد آوْت", "ex_en": "Stand out from the crowd", "ar_ex": "البروز من بين الحشود" },
  { "id": 40, "en": "turn up", "ar": "يظهر / يرفع الصوت", "pronounce": "تِيرْن أپ", "ex_en": "He didn't turn up", "ar_ex": "لم يظهر" },
  { "id": 41, "en": "undesirable", "ar": "غير مرغوب فيه", "pronounce": "أنْدِزَايْرَبِل", "ex_en": "Undesirable effects", "ar_ex": "تأثيرات غير مرغوب فيها" },
  { "id": 42, "en": "unquestionably", "ar": "بلا شك", "pronounce": "أنْكْوِسْتْشِنَبْلي", "ex_en": "Unquestionably true", "ar_ex": "صحيح بلا شك" },
  { "id": 43, "en": "wool", "ar": "صوف", "pronounce": "وُول", "ex_en": "A wool sweater", "ar_ex": "سترة صوفية" },
  { "id": 44, "en": "worthless", "ar": "عديم القيمة", "pronounce": "وِيرْثْلِس", "ex_en": "A worthless coin", "ar_ex": "عملة عديمة القيمة" },
  { "id": 45, "en": "connotation", "ar": "دلالة / معنى خفي", "pronounce": "كُونُوتِيْشِن", "ex_en": "A negative connotation", "ar_ex": "دلالة سلبية" },
  { "id": 46, "en": "currency", "ar": "عملة", "pronounce": "كَرِنْسي", "ex_en": "Foreign currency", "ar_ex": "عملة أجنبية" },
  { "id": 47, "en": "entire", "ar": "كامل", "pronounce": "إنْتَايَر", "ex_en": "The entire day", "ar_ex": "اليوم بأكمله" },
  { "id": 48, "en": "far from", "ar": "بعيد عن", "pronounce": "فَار فْرُوم", "ex_en": "Far from the truth", "ar_ex": "بعيد عن الحقيقة" },
  { "id": 49, "en": "key", "ar": "رئيسي / مفتاح", "pronounce": "كِي", "ex_en": "The key factor", "ar_ex": "العامل الرئيسي" },
  { "id": 50, "en": "linked", "ar": "مرتبط", "pronounce": "لِنْكْد", "ex_en": "Linked together", "ar_ex": "مرتبطان ببعضهما" },
  { "id": 51, "en": "manufactured", "ar": "مُصنع", "pronounce": "مَانْيُوفَاكْتْشَرْد", "ex_en": "Manufactured goods", "ar_ex": "بضائع مصنعة" },
  { "id": 52, "en": "raw materials", "ar": "مواد خام", "pronounce": "رُو مَاتِيرْيَلْز", "ex_en": "Needs raw materials", "ar_ex": "يحتاج مواد خام" },
  { "id": 53, "en": "stock exchange", "ar": "بورصة", "pronounce": "سْتُوك إكْسْتْشِيْنْج", "ex_en": "Stock exchange market", "ar_ex": "سوق البورصة" },
  { "id": 54, "en": "take place", "ar": "يحدث", "pronounce": "تِيك پْلِيس", "ex_en": "The event will take place", "ar_ex": "الحدث سيقع" },
  { "id": 55, "en": "term", "ar": "مصطلح / فصل دراسي", "pronounce": "تِيرْم", "ex_en": "A medical term", "ar_ex": "مصطلح طبي" },
  { "id": 56, "en": "to see the point", "ar": "يفهم القصد", "pronounce": "تُو سِي ذَا پُويْنْت", "ex_en": "I see the point", "ar_ex": "أنا أفهم القصد" },
  { "id": 57, "en": "transform", "ar": "يحول", "pronounce": "تْرَانْسْفُورْم", "ex_en": "Transform the room", "ar_ex": "يغيّر الغرفة" },
  { "id": 58, "en": "underestimate", "ar": "يقلل من شأن", "pronounce": "أنْدَرْإسْتِمِيْت", "ex_en": "Do not underestimate him", "ar_ex": "لا تقلل من شأنه" },
  { "id": 59, "en": "vast", "ar": "شاسع / هائل", "pronounce": "ڤَاسْت", "ex_en": "A vast desert", "ar_ex": "صحراء شاسعة" },
  { "id": 60, "en": "widely", "ar": "على نطاق واسع", "pronounce": "وَايْدْلي", "ex_en": "Widely used", "ar_ex": "يُستخدم على نطاق واسع" },
  { "id": 61, "en": "addiction", "ar": "إدمان", "pronounce": "أدِكْشِن", "ex_en": "Internet addiction", "ar_ex": "إدمان الإنترنت" },
  { "id": 62, "en": "associated", "ar": "مرتبط بـ", "pronounce": "أسُوشِيِيْتِد", "ex_en": "Associated with success", "ar_ex": "مرتبط بالنجاح" },
  { "id": 63, "en": "barter", "ar": "مقايضة", "pronounce": "بَارْتَر", "ex_en": "Barter for goods", "ar_ex": "المقايضة بالبضائع" },
  { "id": 64, "en": "bonus", "ar": "مكافأة", "pronounce": "بُونَس", "ex_en": "A cash bonus", "ar_ex": "مكافأة نقدية" },
  { "id": 65, "en": "competitive", "ar": "تنافسي", "pronounce": "كُمْپِتِتِڤ", "ex_en": "A competitive price", "ar_ex": "سعر تنافسي" },
  { "id": 66, "en": "controversial", "ar": "مثير للجدل", "pronounce": "كُونْتْرُوڤِيرْشَل", "ex_en": "A controversial topic", "ar_ex": "موضوع مثير للجدل" },
  { "id": 67, "en": "excessive", "ar": "مفرط", "pronounce": "إكْسِسِڤ", "ex_en": "Excessive heat", "ar_ex": "حرارة مفرطة" },
  { "id": 68, "en": "fund", "ar": "يموّل / صندوق مالي", "pronounce": "فَنْد", "ex_en": "Fund the project", "ar_ex": "موّل المشروع" },
  { "id": 69, "en": "otherwise", "ar": "وإلا", "pronounce": "أذَرْوَايْز", "ex_en": "Hurry up, otherwise we stay", "ar_ex": "أسرع، وإلا سنبقى" },
  { "id": 70, "en": "peak", "ar": "ذروة / يبلغ القمة", "pronounce": "پِيك", "ex_en": "Reach the peak", "ar_ex": "يصل إلى الذروة" },
  { "id": 71, "en": "prediction", "ar": "تنبؤ", "pronounce": "پْرِدِكْشِن", "ex_en": "An accurate prediction", "ar_ex": "تنبؤ دقيق" },
  { "id": 72, "en": "proposal", "ar": "اقتراح / عرض", "pronounce": "پْرُوپُوزَل", "ex_en": "A good proposal", "ar_ex": "اقتراح جيد" },
  { "id": 73, "en": "represent", "ar": "يمثل", "pronounce": "رِپْرِزِنْت", "ex_en": "Represent your country", "ar_ex": "مثّل بلدك" },
  { "id": 74, "en": "socialise", "ar": "يختلط بالناس", "pronounce": "سُوشَلَايْز", "ex_en": "Socialise with friends", "ar_ex": "يختلط مع الأصدقاء" },
  { "id": 75, "en": "talent", "ar": "موهبة", "pronounce": "تَالِنْت", "ex_en": "A great talent", "ar_ex": "موهبة عظيمة" },
  { "id": 76, "en": "value / valuable", "ar": "قيمة / ذو قيمة", "pronounce": "ڤَالْيُو / ڤَالْيُوبَل", "ex_en": "High value", "ar_ex": "قيمة عالية" },
  { "id": 77, "en": "wealth", "ar": "ثروة", "pronounce": "وِلْث", "ex_en": "Great wealth", "ar_ex": "ثروة هائلة" },
  { "id": 78, "en": "apply", "ar": "يطبق / يتقدم بطلب", "pronounce": "أپْلَاي", "ex_en": "Apply the rule", "ar_ex": "طبق القاعدة" },
  { "id": 79, "en": "blame", "ar": "يلوم", "pronounce": "بْلِيْم", "ex_en": "Do not blame me", "ar_ex": "لا تلمني" },
  { "id": 80, "en": "deal in", "ar": "يتاجر بـ", "pronounce": "دِيل إن", "ex_en": "Deal in cars", "ar_ex": "يتاجر بالسيارات" },
  { "id": 81, "en": "dismiss", "ar": "يرفض / يصرف", "pronounce": "دِسْمِس", "ex_en": "Dismiss the idea", "ar_ex": "يرفض الفكرة" },
  { "id": 82, "en": "doubt", "ar": "يشك", "pronounce": "دَاوْت", "ex_en": "I doubt it", "ar_ex": "أنا أشك في ذلك" },
  { "id": 83, "en": "give way to", "ar": "يفسح المجال لـ", "pronounce": "گِڤ وِي تُو", "ex_en": "Give way to traffic", "ar_ex": "أفسح المجال للمرور" },
  { "id": 84, "en": "inspiration", "ar": "إلهام", "pronounce": "إنْسْپِرِيْشِن", "ex_en": "A source of inspiration", "ar_ex": "مصدر للإلهام" },
  { "id": 85, "en": "keep / lose your head", "ar": "يحافظ على هدوئه / يفقد أعصابه", "pronounce": "كِيب هِد", "ex_en": "Keep your head calm", "ar_ex": "حافظ على هدوء أعصابك" },
  { "id": 86, "en": "make allowance(s) for", "ar": "يراعي / يأخذ بعين الاعتبار", "pronounce": "مِيك ألَاوَنْس", "ex_en": "Make allowances for his age", "ar_ex": "راعِ عمره" },
  { "id": 87, "en": "pick", "ar": "يختار / يقطف", "pronounce": "پِك", "ex_en": "Pick a color", "ar_ex": "اختر لوناً" },
  { "id": 88, "en": "potential", "ar": "إمكانية / محتمل", "pronounce": "پُوتِنْشَل", "ex_en": "High potential", "ar_ex": "إمكانية عالية" },
  { "id": 89, "en": "recall", "ar": "يتذكر / يستدعي", "pronounce": "رِكُول", "ex_en": "I cannot recall his name", "ar_ex": "لا أستطيع تذكر اسمه" },
  { "id": 90, "en": "recommendation", "ar": "توصية", "pronounce": "رِكُمِنْدِيْشِن", "ex_en": "A good recommendation", "ar_ex": "توصية جيدة" },
  { "id": 91, "en": "treat", "ar": "يعامل / يعالج", "pronounce": "تْرِيت", "ex_en": "Treat him well", "ar_ex": "عامله بلطف" },
  { "id": 92, "en": "vital", "ar": "حيوي", "pronounce": "ڤَايْتَل", "ex_en": "Vital signs", "ar_ex": "علامات حيوية" },
  { "id": 93, "en": "cause", "ar": "سبب / قضية", "pronounce": "كُوز", "ex_en": "A good cause", "ar_ex": "قضية نبيلة" },
  { "id": 94, "en": "compromise", "ar": "تسوية / حل وسط", "pronounce": "كُومْپْرُمَايْز", "ex_en": "Reach a compromise", "ar_ex": "التوصل لتسوية" },
  { "id": 95, "en": "constant", "ar": "ثابت / مستمر", "pronounce": "كُونْسْتَانْت", "ex_en": "Constant pain", "ar_ex": "ألم مستمر" },
  { "id": 96, "en": "diplomatic", "ar": "دبلوماسي", "pronounce": "دِپْلُومَاتِك", "ex_en": "A diplomatic answer", "ar_ex": "إجابة دبلوماسية" },
  { "id": 97, "en": "displaced", "ar": "نازح / مهجر", "pronounce": "دِسْپْلِيْسْد", "ex_en": "Displaced people", "ar_ex": "أشخاص نازحون" },
  { "id": 98, "en": "equality", "ar": "مساواة", "pronounce": "إكْوَالِتي", "ex_en": "Gender equality", "ar_ex": "المساواة بين الجنسين" },
  { "id": 99, "en": "founded (on)", "ar": "مبني على / مؤسس", "pronounce": "فَاوْنْدِد", "ex_en": "Founded on truth", "ar_ex": "مبني على الحقيقة" },
  { "id": 100, "en": "immigrant", "ar": "مهاجر", "pronounce": "إمِگْرَانْت", "ex_en": "A legal immigrant", "ar_ex": "مهاجر شرعي" },
  { "id": 101, "en": "insistent", "ar": "مُصِرّ", "pronounce": "إنْسِسْتِنْت", "ex_en": "He was insistent", "ar_ex": "كان مصراً" },
  { "id": 102, "en": "inspire", "ar": "يلهم", "pronounce": "إنْسْپَايَر", "ex_en": "Inspire the youth", "ar_ex": "ألهم الشباب" },
  { "id": 103, "en": "intellectual", "ar": "فكري / مثقف", "pronounce": "إنْتِلِكْتْشُوَل", "ex_en": "Intellectual property", "ar_ex": "ملكية فكرية" },
  { "id": 104, "en": "issue", "ar": "قضية / مسألة", "pronounce": "إشُو", "ex_en": "A political issue", "ar_ex": "قضية سياسية" },
  { "id": 105, "en": "justice", "ar": "عدالة", "pronounce": "جَسْتِس", "ex_en": "Seek justice", "ar_ex": "اطلب العدالة" },
  { "id": 106, "en": "late", "ar": "راحل / متأخر", "pronounce": "لِيْت", "ex_en": "The late king", "ar_ex": "الملك الراحل" },
  { "id": 107, "en": "motivated", "ar": "متحفز", "pronounce": "مُوتِڤِيْتِد", "ex_en": "Highly motivated", "ar_ex": "متحفز جداً" },
  { "id": 108, "en": "prominent", "ar": "بارز / مشهور", "pronounce": "پْرُومِنِنْت", "ex_en": "A prominent figure", "ar_ex": "شخصية بارزة" },
  { "id": 109, "en": "reassure", "ar": "يطمئن", "pronounce": "رِيأشُور", "ex_en": "Reassure the patient", "ar_ex": "طمئن المريض" },
  { "id": 110, "en": "representative", "ar": "ممثل / مندوب", "pronounce": "رِپْرِزِنْتَتِڤ", "ex_en": "A sales representative", "ar_ex": "مندوب مبيعات" },
  { "id": 111, "en": "ring out", "ar": "يدوي / يرن بصوت عال", "pronounce": "رِنْغ آوْت", "ex_en": "Shots ring out", "ar_ex": "دوت الطلقات" },
  { "id": 112, "en": "scale", "ar": "مقياس / نطاق", "pronounce": "سْكِيل", "ex_en": "Large scale", "ar_ex": "نطاق واسع" },
  { "id": 113, "en": "setback", "ar": "انتكاسة / عائق", "pronounce": "سِتْبَاك", "ex_en": "A minor setback", "ar_ex": "انتكاسة بسيطة" },
  { "id": 114, "en": "status", "ar": "مكانة / حالة", "pronounce": "سْتِيْتَس", "ex_en": "Social status", "ar_ex": "مكانة اجتماعية" },
  { "id": 115, "en": "struggle", "ar": "كفاح / يكافح", "pronounce": "سْتْرَگِل", "ex_en": "Struggle for life", "ar_ex": "كفاح من أجل الحياة" },
  { "id": 116, "en": "upgrade", "ar": "يرقّي / تحديث", "pronounce": "أپْگْرِيد", "ex_en": "Upgrade the system", "ar_ex": "حدّث النظام" },
  { "id": 117, "en": "be / get used to", "ar": "يعتاد على", "pronounce": "گِت يُوزْد تُو", "ex_en": "Get used to it", "ar_ex": "اعتَد على ذلك" },
  { "id": 118, "en": "confident", "ar": "واثق", "pronounce": "كُونْفِدِنْت", "ex_en": "Be confident", "ar_ex": "كن واثقاً" },
  { "id": 119, "en": "creative", "ar": "مبدع", "pronounce": "كْرِيِيْتِڤ", "ex_en": "A creative idea", "ar_ex": "فكرة مبدعة" },
  { "id": 120, "en": "excuse", "ar": "عذر", "pronounce": "إكْسْكْيُوز", "ex_en": "A good excuse", "ar_ex": "عذر جيد" },
  { "id": 121, "en": "factor", "ar": "عامل", "pronounce": "فَاكْتَر", "ex_en": "An important factor", "ar_ex": "عامل مهم" },
  { "id": 122, "en": "field", "ar": "مجال / حقل", "pronounce": "فِيلْد", "ex_en": "Medical field", "ar_ex": "مجال طبي" },
  { "id": 123, "en": "foundation course", "ar": "دورة تأسيسية", "pronounce": "فَاوْنْدِيْشِن كُورْس", "ex_en": "Take a foundation course", "ar_ex": "خذ دورة تأسيسية" },
  { "id": 124, "en": "like-minded", "ar": "متوافق في التفكير", "pronounce": "لَايْك مَايْنْدِد", "ex_en": "Like-minded people", "ar_ex": "أشخاص متوافقون فكرياً" },
  { "id": 125, "en": "on show", "ar": "معروض", "pronounce": "أُون شُو", "ex_en": "Art on show", "ar_ex": "فن معروض" },
  { "id": 126, "en": "optional", "ar": "اختياري", "pronounce": "أُوپْشِنَل", "ex_en": "An optional subject", "ar_ex": "مادة اختيارية" },
  { "id": 127, "en": "participate (in)", "ar": "يشارك في", "pronounce": "پَارْتِسِپِيت", "ex_en": "Participate in class", "ar_ex": "شارك في الصف" },
  { "id": 128, "en": "routine", "ar": "روتين", "pronounce": "رُوتِين", "ex_en": "A daily routine", "ar_ex": "روتين يومي" },
  { "id": 129, "en": "set", "ar": "يحدد / مجموعة", "pronounce": "سِت", "ex_en": "Set a goal", "ar_ex": "حدد هدفاً" },
  { "id": 130, "en": "stuck", "ar": "عالق", "pronounce": "سْتَك", "ex_en": "Stuck in traffic", "ar_ex": "عالق في الزحام" },
  { "id": 131, "en": "zone", "ar": "منطقة", "pronounce": "زُون", "ex_en": "Danger zone", "ar_ex": "منطقة خطر" },
  { "id": 132, "en": "aware (of)", "ar": "مدرك لـ", "pronounce": "أوِير أُوف", "ex_en": "Aware of the danger", "ar_ex": "مدرك للخطر" },
  { "id": 133, "en": "convinced", "ar": "مقتنع", "pronounce": "كُنْڤِنْسْد", "ex_en": "I am convinced", "ar_ex": "أنا مقتنع" },
  { "id": 134, "en": "disappointed", "ar": "محبط / خائب الأمل", "pronounce": "دِسأپُويْنْتِد", "ex_en": "Do not be disappointed", "ar_ex": "لا تكن محبطاً" },
  { "id": 135, "en": "fees", "ar": "رسوم", "pronounce": "فِيز", "ex_en": "Pay the fees", "ar_ex": "ادفع الرسوم" },
  { "id": 136, "en": "inevitable", "ar": "حتمي", "pronounce": "إنِڤِتَبِل", "ex_en": "Death is inevitable", "ar_ex": "الموت حتمي" },
  { "id": 137, "en": "nowadays", "ar": "في هذه الأيام", "pronounce": "نَاوَادِيز", "ex_en": "Nowadays it is easy", "ar_ex": "في هذه الأيام الأمر سهل" },
  { "id": 138, "en": "persevere", "ar": "يثابر", "pronounce": "پِرْسِڤِير", "ex_en": "Persevere to win", "ar_ex": "ثابر لتفوز" },
  { "id": 139, "en": "patient / impatient", "ar": "صبور / غير صبور", "pronounce": "پِيْشِنْت", "ex_en": "Be patient", "ar_ex": "كن صبوراً" },
  { "id": 140, "en": "personal", "ar": "شخصي", "pronounce": "پِرْسُنَل", "ex_en": "Personal life", "ar_ex": "حياة شخصية" },
  { "id": 141, "en": "point", "ar": "غرض / نقطة", "pronounce": "پُويْنْت", "ex_en": "The main point", "ar_ex": "النقطة الرئيسية" },
  { "id": 142, "en": "priority", "ar": "أولوية", "pronounce": "پْرَايُورِتي", "ex_en": "A top priority", "ar_ex": "أولوية قصوى" },
  { "id": 143, "en": "revise / revision", "ar": "يراجع / مراجعة", "pronounce": "رِڤَايْز", "ex_en": "Revise for the exam", "ar_ex": "راجع للامتحان" },
  { "id": 144, "en": "reward", "ar": "مكافأة / يكافئ", "pronounce": "رِوُورْد", "ex_en": "A big reward", "ar_ex": "مكافأة كبيرة" },
  { "id": 145, "en": "bald", "ar": "أصلع", "pronounce": "بُولْد", "ex_en": "A bald man", "ar_ex": "رجل أصلع" },
  { "id": 146, "en": "catch up", "ar": "يلحق بـ", "pronounce": "كَاتْش أپ", "ex_en": "Catch up with friends", "ar_ex": "اللحاق بالأصدقاء" },
  { "id": 147, "en": "coincidence", "ar": "صدفة", "pronounce": "كُوإنْسِدِنْس", "ex_en": "A strange coincidence", "ar_ex": "صدفة غريبة" },
  { "id": 148, "en": "colleague", "ar": "زميل عمل", "pronounce": "كُولِيگ", "ex_en": "My office colleague", "ar_ex": "زميلي في المكتب" },
  { "id": 149, "en": "come across", "ar": "يصادف", "pronounce": "كَم أكْرُوس", "ex_en": "Come across an old friend", "ar_ex": "يصادف صديقاً قديماً" },
  { "id": 150, "en": "error", "ar": "خطأ", "pronounce": "إرُور", "ex_en": "A human error", "ar_ex": "خطأ بشري" },
  { "id": 151, "en": "(un)intended", "ar": "(غير) مقصود", "pronounce": "إنْتِنْدِد", "ex_en": "An intended mistake", "ar_ex": "خطأ مقصود" },
  { "id": 152, "en": "mention", "ar": "يذكر", "pronounce": "مِنْشِن", "ex_en": "Do not mention it", "ar_ex": "لا تذكر ذلك" },
  { "id": 153, "en": "misunderstanding", "ar": "سوء فهم", "pronounce": "مِسْأنْدَرْسْتَانْدِنْغ", "ex_en": "A simple misunderstanding", "ar_ex": "سوء فهم بسيط" },
  { "id": 154, "en": "pat", "ar": "يربت", "pronounce": "پَات", "ex_en": "Pat on the back", "ar_ex": "الربت على الظهر" },
  { "id": 155, "en": "put (someone) up", "ar": "يستضيف شخصاً", "pronounce": "پُت أپ", "ex_en": "Put me up for the night", "ar_ex": "استضفني لهذه الليلة" },
  { "id": 156, "en": "reluctant", "ar": "متردد", "pronounce": "رِلَكْتَانْت", "ex_en": "Reluctant to go", "ar_ex": "متردد في الذهاب" },
  { "id": 157, "en": "run into", "ar": "يصادف / يلتقي فجأة", "pronounce": "رَن إنْتُو", "ex_en": "Run into a friend", "ar_ex": "التقى بصديق فجأة" },
  { "id": 158, "en": "straight", "ar": "مباشرة / مستقيم", "pronounce": "سْتْرِيْت", "ex_en": "Go straight home", "ar_ex": "اذهب للمنزل مباشرة" },
  { "id": 159, "en": "stranger", "ar": "غريب", "pronounce": "سْتْرِيْنْجَر", "ex_en": "A total stranger", "ar_ex": "شخص غريب تماماً" },
  { "id": 160, "en": "the latter", "ar": "الأخير (من شيئين)", "pronounce": "ذَا لَاتَر", "ex_en": "Choose the latter", "ar_ex": "اختر الخيار الأخير" },
  { "id": 161, "en": "turn out", "ar": "يتبين", "pronounce": "تِيرْن آوْت", "ex_en": "It turned out well", "ar_ex": "تبين أن الأمر جيد" },
  { "id": 162, "en": "addicted (to)", "ar": "مدمن على", "pronounce": "أدِكْتِد تُو", "ex_en": "Addicted to drugs", "ar_ex": "مدمن على المخدرات" },
  { "id": 163, "en": "border", "ar": "حدود", "pronounce": "بُورْدَر", "ex_en": "Cross the border", "ar_ex": "اعبر الحدود" },
  { "id": 164, "en": "capable", "ar": "قادر", "pronounce": "كِيْپَبِل", "ex_en": "Capable of winning", "ar_ex": "قادر على الفوز" },
  { "id": 165, "en": "citizen", "ar": "مواطن", "pronounce": "سِتِزِن", "ex_en": "A good citizen", "ar_ex": "مواطن صالح" },
  { "id": 166, "en": "fear", "ar": "خوف", "pronounce": "فِير", "ex_en": "Face your fear", "ar_ex": "واجه خوفك" },
  { "id": 167, "en": "hub", "ar": "مركز / محور", "pronounce": "هَب", "ex_en": "A business hub", "ar_ex": "مركز تجاري" },
  { "id": 168, "en": "justified", "ar": "مبرر", "pronounce": "جَسْتِفَايْد", "ex_en": "A justified reason", "ar_ex": "سبب مبرر" },
  { "id": 169, "en": "network", "ar": "شبكة", "pronounce": "نِتْوُورْك", "ex_en": "A large network", "ar_ex": "شبكة واسعة" },
  { "id": 170, "en": "panic", "ar": "ذعر / يهلع", "pronounce": "پَانِك", "ex_en": "Do not panic", "ar_ex": "لا تصب بالذعر" },
  { "id": 171, "en": "questionnaire", "ar": "استبيان", "pronounce": "كْوِسْتْشِنِير", "ex_en": "Fill the questionnaire", "ar_ex": "املأ الاستبيان" },
  { "id": 172, "en": "remote", "ar": "بعيد / ناءٍ", "pronounce": "رِمُوت", "ex_en": "A remote village", "ar_ex": "قرية نائية" },
  { "id": 173, "en": "restrictions", "ar": "قيود", "pronounce": "رِسْتْرِكْشِنْز", "ex_en": "Travel restrictions", "ar_ex": "قيود السفر" },
  { "id": 174, "en": "shrink", "ar": "ينكمش", "pronounce": "شْرِنْك", "ex_en": "Clothes shrink in wash", "ar_ex": "الملابس تنكمش بالغسيل" },
  { "id": 175, "en": "trend", "ar": "توجه / نزعة", "pronounce": "تْرِنْد", "ex_en": "A new trend", "ar_ex": "توجه جديد" },
  { "id": 176, "en": "vary", "ar": "يختلف / يتنوع", "pronounce": "ڤِيري", "ex_en": "Prices vary", "ar_ex": "الأسعار تختلف" },
  { "id": 177, "en": "acquaintance", "ar": "معرفة (شخص تعرفه)", "pronounce": "أكْوِيْنْتَانْس", "ex_en": "An old acquaintance", "ar_ex": "أحد المعارف القدامى" },
  { "id": 178, "en": "boast", "ar": "يتهابى / يتفاخر", "pronounce": "بُوسْت", "ex_en": "Do not boast", "ar_ex": "لا تتباهى" },
  { "id": 179, "en": "claim", "ar": "يدعي / يطالب", "pronounce": "كْلِيْم", "ex_en": "Claim your prize", "ar_ex": "طالب بجائزتك" },
  { "id": 180, "en": "extreme", "ar": "متطرف / شديد", "pronounce": "إكْسْتْرِيم", "ex_en": "Extreme cold", "ar_ex": "برد شديد" },
  { "id": 181, "en": "genuine", "ar": "حقيقي / أصيل", "pronounce": "جِنْيُوِن", "ex_en": "Genuine leather", "ar_ex": "جلد أصلي" },
  { "id": 182, "en": "guarantee", "ar": "ضمان / يضمن", "pronounce": "گَارَانْتِي", "ex_en": "A money guarantee", "ar_ex": "ضمان مالي" },
  { "id": 183, "en": "happen to (be / do)", "ar": "يصادف أن", "pronounce": "هَاپِن تُو", "ex_en": "I happen to know him", "ar_ex": "يصادف أنني أعرفه" },
  { "id": 184, "en": "impress", "ar": "يثير إعجاب", "pronounce": "إمْپْرِس", "ex_en": "Impress the boss", "ar_ex": "أثر إعجاب المدير" },
  { "id": 185, "en": "in common", "ar": "مشترك", "pronounce": "إن كُومُن", "ex_en": "We have a lot in common", "ar_ex": "لدينا الكثير من الأشياء المشتركة" },
  { "id": 186, "en": "in confidence", "ar": "بسرية", "pronounce": "إن كُونْفِدِنْس", "ex_en": "Tell me in confidence", "ar_ex": "أخبرني بسرية" },
  { "id": 187, "en": "inflexible", "ar": "غير مرن", "pronounce": "إنْفْلِكْسِبِل", "ex_en": "An inflexible rule", "ar_ex": "قاعدة غير مرنة" },
  { "id": 188, "en": "initial", "ar": "مبدئي / أولي", "pronounce": "إنِشَل", "ex_en": "The initial plan", "ar_ex": "الخطة الأولية" },
  { "id": 189, "en": "keep in touch", "ar": "يبقى على تواصل", "pronounce": "كِيب إن تَطْش", "ex_en": "Keep in touch with me", "ar_ex": "ابق على تواصل معي" },
  { "id": 190, "en": "knowledge", "ar": "معرفة", "pronounce": "نُولِدْج", "ex_en": "Seek knowledge", "ar_ex": "اطلب المعرفة" },
  { "id": 191, "en": "lasting", "ar": "دائم", "pronounce": "لَاسْتِنْغ", "ex_en": "A lasting peace", "ar_ex": "سلام دائم" },
  { "id": 192, "en": "nature", "ar": "طبيعة / فطرة", "pronounce": "نِيْتْشَر", "ex_en": "Human nature", "ar_ex": "الطبيعة البشرية" },
  { "id": 193, "en": "regard (as)", "ar": "يعتبر", "pronounce": "رِگَارْد", "ex_en": "Regard him as a hero", "ar_ex": "يعتبره بطلاً" },
  { "id": 194, "en": "roughly", "ar": "تقريباً / بخشونة", "pronounce": "رَفْلي", "ex_en": "Roughly speaking", "ar_ex": "بشكل تقريبي" },
  { "id": 195, "en": "via", "ar": "عبر / عن طريق", "pronounce": "ڤَايَا", "ex_en": "Travel via London", "ar_ex": "السفر عبر لندن" },
  { "id": 196, "en": "charity", "ar": "مؤسسة خيرية", "pronounce": "تْشَارِتي", "ex_en": "Donate to charity", "ar_ex": "تبرع للمؤسسة الخيرية" },
  { "id": 197, "en": "co-ordinated", "ar": "منسق", "pronounce": "كُو-أُورْدِنِيْتِد", "ex_en": "A co-ordinated attack", "ar_ex": "هجوم منسق" },
  { "id": 198, "en": "employment", "ar": "توظيف / عمل", "pronounce": "إمْپْلُويْمِنْت", "ex_en": "Seek employment", "ar_ex": "ابحث عن عمل" },
  { "id": 199, "en": "fantasy", "ar": "خيال", "pronounce": "فَانْتَسِي", "ex_en": "A fantasy world", "ar_ex": "عالم خيالي" },
  { "id": 200, "en": "job security", "ar": "أمان وظيفي", "pronounce": "جُوب سِكْيُورِتي", "ex_en": "Seek job security", "ar_ex": "اطلب الأمان الوظيفي" },
  { "id": 201, "en": "make a living", "ar": "يكسب لقمة العيش", "pronounce": "مِيك أ لِڤِنْغ", "ex_en": "Make a decent living", "ar_ex": "يكسب لقمة عيش كريمة" },
  { "id": 202, "en": "neglect", "ar": "يهمل", "pronounce": "نِگْلِكْت", "ex_en": "Do not neglect your duties", "ar_ex": "لا تهمل واجباتك" },
  { "id": 203, "en": "outweigh", "ar": "يفوق / يرجح على", "pronounce": "آوْتْوِيْ", "ex_en": "Benefits outweigh costs", "ar_ex": "الفوائد تفوق التكاليف" },
  { "id": 204, "en": "prospects", "ar": "آفاق / احتمالات", "pronounce": "پْرُوسْپِكْتْس", "ex_en": "Good career prospects", "ar_ex": "آفاق مهنية جيدة" },
  { "id": 205, "en": "reveal", "ar": "يكشف", "pronounce": "رِڤِيل", "ex_en": "Reveal the truth", "ar_ex": "اكشف الحقيقة" },
  { "id": 206, "en": "stage fright", "ar": "رهبة المسرح", "pronounce": "سْتِيْج فْرَايْت", "ex_en": "He suffers from stage fright", "ar_ex": "يعاني من رهبة المسرح" },
  { "id": 207, "en": "throughout", "ar": "طوال / في كل أنحاء", "pronounce": "ثْرُوآوْت", "ex_en": "Throughout the year", "ar_ex": "طوال العام" },
  { "id": 208, "en": "worth", "ar": "يستحق / قيمة", "pronounce": "وِيرْث", "ex_en": "It is worth it", "ar_ex": "الأمر يستحق ذلك" },
  { "id": 209, "en": "attempt", "ar": "محاولة", "pronounce": "أتِمْپْت", "ex_en": "A brave attempt", "ar_ex": "محاولة شجاعة" },
  { "id": 210, "en": "breakthrough", "ar": "اختراق / تقدم علمي", "pronounce": "بْرِيْكْثْرُو", "ex_en": "A medical breakthrough", "ar_ex": "تقدم طبي كبير" },
  { "id": 211, "en": "currently", "ar": "حالياً", "pronounce": "كَرِنْتْلي", "ex_en": "Currently unavailable", "ar_ex": "غير متاح حالياً" },
  { "id": 212, "en": "distribute", "ar": "يوزع", "pronounce": "دِسْتْرِبْيُوت", "ex_en": "Distribute the books", "ar_ex": "وزّع الكتب" },
  { "id": 213, "en": "graphic", "ar": "تصويري / جرافيك", "pronounce": "گْرَافِك", "ex_en": "Graphic design", "ar_ex": "تصميم جرافيك" },
  { "id": 214, "en": "humanitarian", "ar": "إنساني", "pronounce": "هْيُومَانِتِيرْيَن", "ex_en": "Humanitarian aid", "ar_ex": "مساعدات إنسانية" },
  { "id": 215, "en": "lack", "ar": "نقص / يفتقر إلى", "pronounce": "لَاك", "ex_en": "Lack of money", "ar_ex": "نقص في المال" },
  { "id": 216, "en": "marketing", "ar": "تسويق", "pronounce": "مَارْكِتِنْغ", "ex_en": "A marketing strategy", "ar_ex": "استراتيجية تسويق" },
  { "id": 217, "en": "market share", "ar": "حصة سوقية", "pronounce": "مَارْكِت شِير", "ex_en": "Large market share", "ar_ex": "حصة سوقية كبيرة" },
  { "id": 218, "en": "market value", "ar": "قيمة سوقية", "pronounce": "مَارْكِت ڤَالْيُو", "ex_en": "High market value", "ar_ex": "قيمة سوقية عالية" },
  { "id": 219, "en": "returns", "ar": "عائدات / أرباح", "pronounce": "رِتِيرْنْز", "ex_en": "High financial returns", "ar_ex": "عائدات مالية عالية" },
  { "id": 220, "en": "objective", "ar": "هدف / موضوعي", "pronounce": "أُوبْجِكْتِڤ", "ex_en": "The main objective", "ar_ex": "الهدف الرئيسي" },
  { "id": 221, "en": "promising", "ar": "واعد", "pronounce": "پْرُومِسِنْغ", "ex_en": "A promising future", "ar_ex": "مستقبل واعد" },
  { "id": 222, "en": "reserve", "ar": "حجز / احتياطي", "pronounce": "رِزِيرْڤ", "ex_en": "Reserve a table", "ar_ex": "احجز طاولة" },
  { "id": 223, "en": "rule out", "ar": "يستبعد", "pronounce": "رُول آوْت", "ex_en": "Rule out the possibility", "ar_ex": "استبعد الاحتمال" },
  { "id": 224, "en": "terror", "ar": "رعب / إرهاب", "pronounce": "تِرُور", "ex_en": "A feeling of terror", "ar_ex": "شعور بالرعب" },
  { "id": 225, "en": "tragedy", "ar": "مأساة", "pronounce": "تْرَاجِدِي", "ex_en": "A terrible tragedy", "ar_ex": "مأساة فظيعة" },
  { "id": 226, "en": "trial", "ar": "محاكمة / تجربة", "pronounce": "تْرَايَل", "ex_en": "A fair trial", "ar_ex": "محاكمة عادلة" },
  { "id": 227, "en": "appeal", "ar": "جاذبية / مناشدة", "pronounce": "أپِيل", "ex_en": "An urgent appeal", "ar_ex": "مناشدة عاجلة" },
  { "id": 228, "en": "at all costs", "ar": "بأي ثمن", "pronounce": "أت أُول كُوسْتْس", "ex_en": "Win at all costs", "ar_ex": "الفوز بأي ثمن" },
  { "id": 229, "en": "bring up / upbringing", "ar": "يربي / تربية", "pronounce": "بْرِنْغ أپ", "ex_en": "Bring up children well", "ar_ex": "ربّ الأطفال جيداً" },
  { "id": 230, "en": "commerce", "ar": "تجارة", "pronounce": "كُومِيرْس", "ex_en": "Chamber of commerce", "ar_ex": "غرفة التجارة" },
  { "id": 231, "en": "conform", "ar": "يمتثل / يتوافق", "pronounce": "كُنْفُورْم", "ex_en": "Conform to the rules", "ar_ex": "الامتثال للقواعد" },
  { "id": 232, "en": "consensus", "ar": "إجماع", "pronounce": "كُنْسِنْسَس", "ex_en": "Reach a consensus", "ar_ex": "الوصول إلى إجماع" },
  { "id": 233, "en": "consumption", "ar": "استهلاك", "pronounce": "كُنْسَمْپْشِن", "ex_en": "Water consumption", "ar_ex": "استهلاك المياه" },
  { "id": 234, "en": "identity", "ar": "هوية", "pronounce": "آيْدِنْتِتي", "ex_en": "National identity", "ar_ex": "هوية وطنية" },
  { "id": 235, "en": "image", "ar": "صورة", "pronounce": "إمِج", "ex_en": "A clear image", "ar_ex": "صورة واضحة" },
  { "id": 236, "en": "loyal / loyalty", "ar": "مخلص / ولاء", "pronounce": "لُويَل", "ex_en": "A loyal friend", "ar_ex": "صديق مخلص" },
  { "id": 237, "en": "manufacturing", "ar": "تصنيع", "pronounce": "مَانْيُوفَاكْتْشَرِنْغ", "ex_en": "Car manufacturing", "ar_ex": "تصنيع السيارات" },
  { "id": 238, "en": "peers", "ar": "أقران / زملاء", "pronounce": "پِيرْز", "ex_en": "Peer pressure", "ar_ex": "ضغط الأقران" },
  { "id": 239, "en": "perceptions", "ar": "تصورات", "pronounce": "پِرْسِپْشِنْز", "ex_en": "Public perceptions", "ar_ex": "التصورات العامة" },
  { "id": 240, "en": "psychology", "ar": "علم النفس", "pronounce": "سَايْكُولُوجِي", "ex_en": "Child psychology", "ar_ex": "علم نفس الطفل" },
  { "id": 241, "en": "selfish / selfishness", "ar": "أناني / أنانية", "pronounce": "سِلْفِش", "ex_en": "A selfish act", "ar_ex": "تصرف أناني" },
  { "id": 242, "en": "strategy", "ar": "استراتيجية", "pronounce": "سْتْرَاتِجِي", "ex_en": "A good strategy", "ar_ex": "استراتيجية جيدة" },
  { "id": 243, "en": "accent", "ar": "لهجة", "pronounce": "أكْسِنْت", "ex_en": "An American accent", "ar_ex": "لهجة أمريكية" },
  { "id": 244, "en": "accustomed", "ar": "معتاد", "pronounce": "أكَسْتُمْد", "ex_en": "Accustomed to cold", "ar_ex": "معتاد على البرد" },
  { "id": 245, "en": "cling (onto)", "ar": "يتشبث بـ", "pronounce": "كْلِنْغ أُونْتُو", "ex_en": "Cling onto hope", "ar_ex": "يتشبث بالأمل" },
  { "id": 246, "en": "committed", "ar": "ملتزم", "pronounce": "كُمِتِد", "ex_en": "Committed to the team", "ar_ex": "ملتزم مع الفريق" },
  { "id": 247, "en": "conviction", "ar": "قناعة / إدانة", "pronounce": "كُنْڤِكْشِن", "ex_en": "A strong conviction", "ar_ex": "قناعة قوية" },
  { "id": 248, "en": "essential", "ar": "أساسي", "pronounce": "إسِنْشَل", "ex_en": "Water is essential", "ar_ex": "الماء أساسي" },
  { "id": 249, "en": "expatriate", "ar": "مغترب", "pronounce": "إكْسْپَاتْرِيِيت", "ex_en": "An expatriate worker", "ar_ex": "عامل مغترب" },
  { "id": 250, "en": "run", "ar": "يدير (عمل)", "pronounce": "رَن", "ex_en": "Run a business", "ar_ex": "يدير عملاً تجارياً" },
  { "id": 251, "en": "sector", "ar": "قطاع", "pronounce": "سِكْتَر", "ex_en": "The public sector", "ar_ex": "القطاع العام" },
  { "id": 252, "en": "upmarket", "ar": "راقٍ / فخم", "pronounce": "أپْمَارْكِت", "ex_en": "An upmarket restaurant", "ar_ex": "مطعم راقٍ" },
  { "id": 253, "en": "fellow countrymen", "ar": "أبناء البلد", "pronounce": "فِلُو كَنْتْرِيمَان", "ex_en": "Help your fellow countrymen", "ar_ex": "ساعد أبناء بلدك" },
  { "id": 254, "en": "fluent", "ar": "طليق / فصيح", "pronounce": "فْلُووِنْت", "ex_en": "Fluent in English", "ar_ex": "طليق في الإنجليزية" },
  { "id": 255, "en": "amateur", "ar": "هاوٍ", "pronounce": "أمَاتُور", "ex_en": "An amateur photographer", "ar_ex": "مصور هاوٍ" },
  { "id": 256, "en": "object (to)", "ar": "يعترض على", "pronounce": "أُوبْجِكْت تُو", "ex_en": "Object to the plan", "ar_ex": "يعترض على الخطة" },
  { "id": 257, "en": "astonishing", "ar": "مذهل", "pronounce": "أسْتُونِشِنْغ", "ex_en": "An astonishing view", "ar_ex": "منظر مذهل" },
  { "id": 258, "en": "puzzle", "ar": "لغز / يحير", "pronounce": "پَزِل", "ex_en": "Solve the puzzle", "ar_ex": "حل اللغز" },
  { "id": 259, "en": "combination", "ar": "مزيج / دمج", "pronounce": "كُومْبِنِيْشِن", "ex_en": "A great combination", "ar_ex": "مزيج رائع" },
  { "id": 260, "en": "stubborn", "ar": "عنيد", "pronounce": "سْتَبُورْن", "ex_en": "A stubborn child", "ar_ex": "طفل عنيد" },
  { "id": 261, "en": "criteria", "ar": "معايير", "pronounce": "كْرَايْتِيرْيَا", "ex_en": "Meet the criteria", "ar_ex": "يستوفي المعايير" },
  { "id": 262, "en": "unconsciously", "ar": "بغير وعي", "pronounce": "أنْكُونْشَسْلي", "ex_en": "Doing it unconsciously", "ar_ex": "يفعل ذلك بغير وعي" },
  { "id": 263, "en": "get on (with)", "ar": "ينسجم مع / يواصل", "pronounce": "گِت أُون وِذ", "ex_en": "Get on with him", "ar_ex": "ينسجم معه" },
  { "id": 264, "en": "infuriated", "ar": "غاضب جداً", "pronounce": "إنْفْيُورِيِيْتِد", "ex_en": "He was infuriated", "ar_ex": "كان غاضباً جداً" },
  { "id": 265, "en": "judge", "ar": "يحكم / قاضٍ", "pronounce": "جَدْج", "ex_en": "Do not judge him", "ar_ex": "لا تحكم عليه" }
];