const levelCLASS7_Words = [
  { "id": 1, "en": "nod", "ar": "يومئ برأسه", "pronounce": "نود", "ex_en": "He will nod to agree", "ar_ex": "سوف يومئ برأسه ليوافق" },
  { "id": 2, "en": "shake hands", "ar": "يصافح", "pronounce": "شيك هاندز", "ex_en": "Please shake hands with him", "ar_ex": "من فضلك صافحه بيدك" },
  { "id": 3, "en": "smile", "ar": "يبتسم", "pronounce": "سمايل", "ex_en": "Always smile to your friends", "ar_ex": "ابتسم دائماً لأصدقائك" },
  { "id": 4, "en": "ages", "ar": "مدة طويلة", "pronounce": "إيدجِز", "ex_en": "I waited for ages today", "ar_ex": "انتظرت لمدة طويلة اليوم" },
  { "id": 5, "en": "artist", "ar": "فنان", "pronounce": "آرتِست", "ex_en": "He is a great artist", "ar_ex": "هو فنان عظيم" },
  { "id": 6, "en": "billion", "ar": "مليار", "pronounce": "بِلْيَن", "ex_en": "There are a billion stars", "ar_ex": "هناك مليار نجمة" },
  { "id": 7, "en": "businessman", "ar": "رجل أعمال", "pronounce": "بِزْنِس مان", "ex_en": "My father is a businessman", "ar_ex": "والدي رجل أعمال" },
  { "id": 8, "en": "ceramic", "ar": "خزف", "pronounce": "سِرامِك", "ex_en": "I like this ceramic vase", "ar_ex": "أحب هذه المزهرية الخزفية" },
  { "id": 9, "en": "clay", "ar": "طين", "pronounce": "كْلاي", "ex_en": "We make pots from clay", "ar_ex": "نصنع الأواني من الطين" },
  { "id": 10, "en": "crafts", "ar": "حرف", "pronounce": "كرافتس", "ex_en": "She likes traditional crafts", "ar_ex": "هي تحب الحرف التقليدية" },
  { "id": 11, "en": "arts", "ar": "فنون", "pronounce": "آرتس", "ex_en": "I study arts at school", "ar_ex": "أنا أدرس الفنون بالمدرسة" },
  { "id": 12, "en": "distance", "ar": "مسافة", "pronounce": "دِسْتَنْس", "ex_en": "The distance is very long", "ar_ex": "المسافة طويلة جداً" },
  { "id": 13, "en": "gorilla", "ar": "غوريلا", "pronounce": "غُرِلّا", "ex_en": "The gorilla is very strong", "ar_ex": "الغوريلا قوية جداً" },
  { "id": 14, "en": "group", "ar": "مجموعة", "pronounce": "گروب", "ex_en": "Work in a small group", "ar_ex": "اعمل في مجموعة صغيرة" },
  { "id": 15, "en": "half", "ar": "نصف", "pronounce": "هاف", "ex_en": "I ate half the apple", "ar_ex": "أكلت نصف التفاحة" },
  { "id": 16, "en": "Holy Qur’an", "ar": "القرآن الكريم", "pronounce": "هولي قُرآن", "ex_en": "I read the Holy Qur’an", "ar_ex": "أنا أقرأ القرآن الكريم" },
  { "id": 17, "en": "home", "ar": "وطن", "pronounce": "هوم", "ex_en": "Palestine is my home", "ar_ex": "فلسطين هي وطني" },
  { "id": 18, "en": "instructions", "ar": "تعليمات", "pronounce": "إنستْرَكشِنز", "ex_en": "Read the instructions carefully", "ar_ex": "اقرأ التعليمات بحذر" },
  { "id": 19, "en": "kilometer", "ar": "كيلومتر", "pronounce": "كِلُومِتر", "ex_en": "It is one kilometer away", "ar_ex": "إنها على بعد كيلومتر" },
  { "id": 20, "en": "leader", "ar": "قائد", "pronounce": "ليدر", "ex_en": "He is a good leader", "ar_ex": "هو قائد جيد" },
  { "id": 21, "en": "loads of", "ar": "الكثير من", "pronounce": "لودز أُف", "ex_en": "I have loads of books", "ar_ex": "لدي الكثير من الكتب" },
  { "id": 22, "en": "moment", "ar": "لحظة", "pronounce": "مومِنت", "ex_en": "Wait for a moment please", "ar_ex": "انتظر لحظة من فضلك" },
  { "id": 23, "en": "neck", "ar": "رقبة", "pronounce": "نِك", "ex_en": "The giraffe has a neck", "ar_ex": "الزرافة لديها رقبة" },
  { "id": 24, "en": "part", "ar": "جزء", "pronounce": "پارت", "ex_en": "This is a small part", "ar_ex": "هذا جزء صغير" },
  { "id": 25, "en": "report", "ar": "تقرير", "pronounce": "رِپورت", "ex_en": "I wrote a school report", "ar_ex": "كتبت تقريراً مدرسياً" },
  { "id": 26, "en": "shade", "ar": "ظل", "pronounce": "شِيد", "ex_en": "Sit in the shade now", "ar_ex": "اجلس في الظل الآن" },
  { "id": 27, "en": "shape", "ar": "شكل", "pronounce": "شيب", "ex_en": "What is the circle shape?", "ar_ex": "ما هو الشكل الدائري؟" },
  { "id": 28, "en": "standard", "ar": "فصيح / قياسي", "pronounce": "سْتاندرْد", "ex_en": "He speaks standard Arabic", "ar_ex": "هو يتحدث العربية الفصحى" },
  { "id": 29, "en": "story", "ar": "قصة", "pronounce": "سْتوري", "ex_en": "Tell me a nice story", "ar_ex": "احكِ لي قصة لطيفة" },
  { "id": 30, "en": "tail", "ar": "ذيل", "pronounce": "تِيل", "ex_en": "The cat has a tail", "ar_ex": "القطة لديها ذيل" },
  { "id": 31, "en": "technology", "ar": "تكنولوجيا", "pronounce": "تِكنولُجي", "ex_en": "I love using new technology", "ar_ex": "أحب استخدام التكنولوجيا الجديدة" },
  { "id": 32, "en": "warning", "ar": "تحذير", "pronounce": "وورنِنغ", "ex_en": "He gave me a warning", "ar_ex": "أعطاني تحذيراً" },
  { "id": 33, "en": "way", "ar": "طريق / طريقة", "pronounce": "واي", "ex_en": "This is the right way", "ar_ex": "هذه هي الطريقة الصحيحة" },
  { "id": 34, "en": "world", "ar": "العالم", "pronounce": "وورلد", "ex_en": "We live in this world", "ar_ex": "نحن نعيش في هذا العالم" },
  { "id": 35, "en": "each other", "ar": "بعضهم بعضًا", "pronounce": "إيتش أَذَر", "ex_en": "They help each other", "ar_ex": "هم يساعدون بعضهم بعضاً" },
  { "id": 36, "en": "yourself", "ar": "نفسك", "pronounce": "يورْسِلف", "ex_en": "Take care of yourself", "ar_ex": "اعتنِ بنفسك" },
  { "id": 37, "en": "bark", "ar": "ينبح", "pronounce": "بارك", "ex_en": "The dog starts to bark", "ar_ex": "الكلب يبدأ بالنباح" },
  { "id": 38, "en": "come over", "ar": "يزور", "pronounce": "كَم أوڤَر", "ex_en": "Come over to my house", "ar_ex": "زر منزلي" },
  { "id": 39, "en": "know", "ar": "يعرف", "pronounce": "نو", "ex_en": "I know the answer now", "ar_ex": "أعرف الإجابة الآن" },
  { "id": 40, "en": "learn", "ar": "يتعلم", "pronounce": "لِرن", "ex_en": "I want to learn English", "ar_ex": "أريد تعلم الإنجليزية" },
  { "id": 41, "en": "lose", "ar": "يخسر", "pronounce": "لوز", "ex_en": "Do not lose your money", "ar_ex": "لا تخسر مالك" },
  { "id": 42, "en": "plan", "ar": "خطة", "pronounce": "بلان", "ex_en": "We have a good plan", "ar_ex": "لدينا خطة جيدة" },
  { "id": 43, "en": "prepare", "ar": "يجهّز", "pronounce": "پْرِپير", "ex_en": "Prepare your school bag now", "ar_ex": "جهز حقيبتك المدرسية الآن" },
  { "id": 44, "en": "remember", "ar": "يتذكر", "pronounce": "رِمِمبر", "ex_en": "I remember the old days", "ar_ex": "أتذكر الأيام القديمة" },
  { "id": 45, "en": "return", "ar": "يعود", "pronounce": "رِتِرن", "ex_en": "He will return soon", "ar_ex": "سوف يعود قريباً" },
  { "id": 46, "en": "rub", "ar": "يفرك", "pronounce": "رَب", "ex_en": "Rub your hands together", "ar_ex": "افرك يديك معاً" },
  { "id": 47, "en": "route", "ar": "مسار", "pronounce": "روت", "ex_en": "This is the best route", "ar_ex": "هذا هو أفضل مسار" },
  { "id": 48, "en": "straight ahead", "ar": "مباشرة للأمام", "pronounce": "ستريت أَهِد", "ex_en": "Go straight ahead now", "ar_ex": "اذهب مباشرة للأمام الآن" },
  { "id": 49, "en": "traffic", "ar": "سير", "pronounce": "ترافِك", "ex_en": "The traffic is very busy", "ar_ex": "حركة السير مزدحمة" },
  { "id": 50, "en": "way (to)", "ar": "الطريق إلى", "pronounce": "واي تو", "ex_en": "Show me the way to", "ar_ex": "أرني الطريق إلى المدرسة" },
  { "id": 51, "en": "design", "ar": "تصميم", "pronounce": "دِزاين", "ex_en": "I like this new design", "ar_ex": "أحب هذا التصميم الجديد" },
  { "id": 52, "en": "embroidery", "ar": "تطريز", "pronounce": "إِمبرُودَري", "ex_en": "She likes Palestinian embroidery", "ar_ex": "هي تحب التطريز الفلسطيني" },
  { "id": 53, "en": "gift", "ar": "هدية", "pronounce": "گِفت", "ex_en": "This is a nice gift", "ar_ex": "هذه هدية لطيفة" },
  { "id": 54, "en": "jug", "ar": "إبريق", "pronounce": "جَغ", "ex_en": "Fill the jug with water", "ar_ex": "املأ الإبريق بالماء" },
  { "id": 55, "en": "pattern", "ar": "نمط", "pronounce": "پاتِرن", "ex_en": "I like this color pattern", "ar_ex": "أحب نمط الألوان هذا" },
  { "id": 56, "en": "plate", "ar": "طبق", "pronounce": "پْلايت", "ex_en": "Put food on the plate", "ar_ex": "ضع الطعام في الطبق" },
  { "id": 57, "en": "style", "ar": "طراز", "pronounce": "ستايل", "ex_en": "I like your new style", "ar_ex": "أحب طرازك الجديد" },
  { "id": 58, "en": "vase", "ar": "مزهرية", "pronounce": "ڤاز", "ex_en": "Put flowers in the vase", "ar_ex": "ضع الزهور في المزهرية" },
  { "id": 59, "en": "glass", "ar": "زجاج", "pronounce": "غلاس", "ex_en": "The glass is very clear", "ar_ex": "الزجاج صافٍ جداً" },
  { "id": 60, "en": "plastic", "ar": "بلاستيك", "pronounce": "پْلاستِك", "ex_en": "Don't use plastic bags", "ar_ex": "لا تستخدم أكياس البلاستيك" },
  { "id": 61, "en": "wicker", "ar": "خوص", "pronounce": "وِكَر", "ex_en": "The chair is made of", "ar_ex": "الكرسي مصنوع من الخوص" },
  { "id": 62, "en": "wood", "ar": "خشب", "pronounce": "وود", "ex_en": "This table is of wood", "ar_ex": "هذه الطاولة من الخشب" },
  { "id": 63, "en": "century", "ar": "قرن", "pronounce": "سِنْتشُري", "ex_en": "We are in this century", "ar_ex": "نحن في هذا القرن" },
  { "id": 64, "en": "children", "ar": "أطفال", "pronounce": "تشِلدرِن", "ex_en": "The children play outside", "ar_ex": "الأطفال يلعبون في الخارج" },
  { "id": 65, "en": "choice", "ar": "اختيار", "pronounce": "تشويس", "ex_en": "It was a hard choice", "ar_ex": "كان اختياراً صعباً" },
  { "id": 66, "en": "civilization", "ar": "حضارة", "pronounce": "سِڤِلَزَيْشَن", "ex_en": "History of our great civilization", "ar_ex": "تاريخ حضارتنا العظيمة" },
  { "id": 67, "en": "corner", "ar": "زاوية", "pronounce": "كورنَر", "ex_en": "Sit in the room corner", "ar_ex": "اجلس في زاوية الغرفة" },
  { "id": 68, "en": "daughter", "ar": "ابنة", "pronounce": "دُوتر", "ex_en": "She is my smart daughter", "ar_ex": "هي ابنتي الذكية" },
  { "id": 69, "en": "decade", "ar": "عقد", "pronounce": "دِكِيد", "ex_en": "Ten years make a decade", "ar_ex": "عشر سنوات تشكل عقداً" },
  { "id": 70, "en": "example", "ar": "مثال", "pronounce": "إِگزَامپُل", "ex_en": "Give me an example please", "ar_ex": "أعطني مثالاً من فضلك" },
  { "id": 71, "en": "furniture", "ar": "أثاث", "pronounce": "فِرنيتشر", "ex_en": "We bought new house furniture", "ar_ex": "اشترينا أثاث منزل جديد" },
  { "id": 72, "en": "history", "ar": "تاريخ", "pronounce": "هِستري", "ex_en": "I love studying world history", "ar_ex": "أحب دراسة تاريخ العالم" },
  { "id": 73, "en": "life", "ar": "حياة", "pronounce": "لايف", "ex_en": "Life is very beautiful today", "ar_ex": "الحياة جميلة جداً اليوم" },
  { "id": 74, "en": "magazine", "ar": "مجلة", "pronounce": "ماگزين", "ex_en": "I read this science magazine", "ar_ex": "قرأت هذه المجلة العلمية" },
  { "id": 75, "en": "meal", "ar": "وجبة", "pronounce": "ميل", "ex_en": "Eat a healthy meal now", "ar_ex": "تناول وجبة صحية الآن" },
  { "id": 76, "en": "meaning", "ar": "معنى", "pronounce": "مينِنغ", "ex_en": "What is the word meaning?", "ar_ex": "ما معنى هذه الكلمة؟" },
  { "id": 77, "en": "mistake", "ar": "خطأ", "pronounce": "مِسْتيك", "ex_en": "It is a small mistake", "ar_ex": "إنه خطأ صغير" },
  { "id": 78, "en": "money", "ar": "مال", "pronounce": "مَني", "ex_en": "Do not waste your money", "ar_ex": "لا تضيع مالك" },
  { "id": 79, "en": "nature", "ar": "طبيعة", "pronounce": "نَيْتشر", "ex_en": "I love the green nature", "ar_ex": "أحب الطبيعة الخضراء" },
  { "id": 80, "en": "past", "ar": "الماضي", "pronounce": "پاست", "ex_en": "Forget about the past now", "ar_ex": "انسَ الماضي الآن" },
  { "id": 81, "en": "pollution", "ar": "تلوث", "pronounce": "پُلُوشَن", "ex_en": "We must stop the pollution", "ar_ex": "يجب أن نوقف التلوث" },
  { "id": 82, "en": "revolution", "ar": "ثورة", "pronounce": "رِڤُلُوشَن", "ex_en": "History of the great revolution", "ar_ex": "تاريخ الثورة العظيمة" },
  { "id": 83, "en": "sandwich", "ar": "شطيرة", "pronounce": "ساندويتش", "ex_en": "I ate a cheese sandwich", "ar_ex": "أكلت شطيرة جبن" },
  { "id": 84, "en": "skill", "ar": "مهارة", "pronounce": "سْكِل", "ex_en": "Reading is a good skill", "ar_ex": "القراءة مهارة جيدة" },
  { "id": 85, "en": "stick", "ar": "يلتصق", "pronounce": "سْتِك", "ex_en": "The paper will stick now", "ar_ex": "الورقة ستلتصق الآن" },
  { "id": 86, "en": "suggestion", "ar": "اقتراح", "pronounce": "سَجِسْتشَن", "ex_en": "Do you have a suggestion?", "ar_ex": "هل لديك أي اقتراح؟" },
  { "id": 87, "en": "visitor", "ar": "زائر", "pronounce": "ڤِزِتَر", "ex_en": "There is a new visitor", "ar_ex": "هناك زائر جديد" },
  { "id": 88, "en": "waiter", "ar": "نادل", "pronounce": "وِيتَر", "ex_en": "Call the waiter for help", "ar_ex": "نادِ النادل للمساعدة" },
  { "id": 89, "en": "weekend", "ar": "عطلة نهاية الأسبوع", "pronounce": "ويك إند", "ex_en": "I enjoy the weekend time", "ar_ex": "أستمتع بوقت العطلة" },
  { "id": 90, "en": "woods", "ar": "غابة", "pronounce": "وودز", "ex_en": "They walk in the woods", "ar_ex": "هم يمشون في الغابة" },
  { "id": 91, "en": "allow", "ar": "يسمح", "pronounce": "أَلّاو", "ex_en": "They don't allow it here", "ar_ex": "هم لا يسمحون بهذا هنا" },
  { "id": 92, "en": "bring", "ar": "يحضر", "pronounce": "بْرِنغ", "ex_en": "Bring me the book please", "ar_ex": "أحضر لي الكتاب من فضلك" },
  { "id": 93, "en": "Arabic", "ar": "اللغة العربية", "pronounce": "آرَبِك", "ex_en": "I study Arabic language now", "ar_ex": "أدرس اللغة العربية الآن" },
  { "id": 94, "en": "Australia", "ar": "أستراليا", "pronounce": "أُسترَيْليا", "ex_en": "He lives in Australia now", "ar_ex": "هو يعيش في أستراليا" },
  { "id": 95, "en": "brazil", "ar": "البرازيل", "pronounce": "برازيـل", "ex_en": "Brazil is a big country", "ar_ex": "البرازيل بلد كبير" },
  { "id": 96, "en": "Brazilian", "ar": "برازيلي", "pronounce": "برازيليان", "ex_en": "He is a Brazilian player", "ar_ex": "هو لاعب برازيلي" },
  { "id": 97, "en": "Britain", "ar": "بريطانيا", "pronounce": "بِرِتن", "ex_en": "He travels to Britain today", "ar_ex": "يسافر إلى بريطانيا اليوم" },
  { "id": 98, "en": "Canada", "ar": "كندا", "pronounce": "كانَدا", "ex_en": "Canada is a cold country", "ar_ex": "كندا بلد بارد" },
  { "id": 99, "en": "Egypt", "ar": "مصر", "pronounce": "إيجيبت", "ex_en": "I love visiting Egypt now", "ar_ex": "أحب زيارة مصر الآن" },
  { "id": 100, "en": "Egyptian", "ar": "مصري", "pronounce": "إيجيپشن", "ex_en": "My friend is very Egyptian", "ar_ex": "صديقي مصري جداً" },
  { "id": 101, "en": "Japanese", "ar": "ياباني", "pronounce": "جابانِيز", "ex_en": "I like Japanese food much", "ar_ex": "أحب الطعام الياباني كثيراً" },
  { "id": 102, "en": "Jordan", "ar": "الأردن", "pronounce": "جوردَن", "ex_en": "I visit Jordan with family", "ar_ex": "أزور الأردن مع عائلتي" },
  { "id": 103, "en": "Jordanian", "ar": "أردني", "pronounce": "جوردَيْنيان", "ex_en": "He is a Jordanian friend", "ar_ex": "هو صديق أردني" },
  { "id": 104, "en": "Middle East", "ar": "الشرق الأوسط", "pronounce": "مِدِل إيست", "ex_en": "We live in Middle East", "ar_ex": "نحن نعيش في الشرق الأوسط" },
  { "id": 105, "en": "North Africa", "ar": "شمال إفريقيا", "pronounce": "نورث أَفريكا", "ex_en": "Travel to North Africa today", "ar_ex": "سافر إلى شمال إفريقيا" },
  { "id": 106, "en": "Palestine", "ar": "فلسطين", "pronounce": "پالِسْتاين", "ex_en": "Palestine is in my heart", "ar_ex": "فلسطين في قلبي دائماً" },
  { "id": 107, "en": "Palestinian", "ar": "فلسطيني", "pronounce": "پالِسْتينيان", "ex_en": "I am a Palestinian boy", "ar_ex": "أنا ولد فلسطيني" },
  { "id": 108, "en": "Qatar", "ar": "قطر", "pronounce": "كَتَر", "ex_en": "He lives in Qatar now", "ar_ex": "هو يعيش في قطر الآن" },
  { "id": 109, "en": "Russian", "ar": "روسي", "pronounce": "رَشَن", "ex_en": "He is a Russian friend", "ar_ex": "هو صديق روسي" },
  { "id": 110, "en": "South Africa", "ar": "جنوب إفريقيا", "pronounce": "ساوث أَفريكا", "ex_en": "Travel to South Africa now", "ar_ex": "سافر إلى جنوب إفريقيا" },
  { "id": 111, "en": "UK", "ar": "المملكة المتحدة", "pronounce": "يو كيه", "ex_en": "He works in the UK", "ar_ex": "هو يعمل في المملكة المتحدة" },
  { "id": 112, "en": "United Nations (UN)", "ar": "الأمم المتحدة", "pronounce": "يُونايتِد نَيْشِنز", "ex_en": "Work at United Nations now", "ar_ex": "اعمل في الأمم المتحدة" },
  { "id": 113, "en": "United States (US)", "ar": "الولايات المتحدة", "pronounce": "يُونايتِد سْتيتس", "ex_en": "Travel to United States today", "ar_ex": "سافر إلى الولايات المتحدة" },
  { "id": 114, "en": "already", "ar": "بالفعل", "pronounce": "أُلرِدي", "ex_en": "I have already finished work", "ar_ex": "لقد أنهيت العمل بالفعل" },
  { "id": 115, "en": "just", "ar": "لتوّه", "pronounce": "جَست", "ex_en": "I have just arrived here", "ar_ex": "لقد وصلت هنا لتوّي" },
  { "id": 116, "en": "often", "ar": "غالبًا", "pronounce": "أُوفِن", "ex_en": "I often visit my friend", "ar_ex": "غالباً أزور صديقي" },
  { "id": 117, "en": "soon", "ar": "قريبًا", "pronounce": "سون", "ex_en": "I will see you soon", "ar_ex": "سأراك قريباً" },
  { "id": 118, "en": "yet", "ar": "حتى الآن", "pronounce": "يِت", "ex_en": "I have not finished yet", "ar_ex": "لم أنتهِ حتى الآن" },
  { "id": 119, "en": "carry on", "ar": "يُواصل", "pronounce": "كاري أون", "ex_en": "Carry on with your work", "ar_ex": "واصل عملك" },
  { "id": 120, "en": "cut up", "ar": "يقطع", "pronounce": "كَت أپ", "ex_en": "Cut up the apple now", "ar_ex": "قطع التفاحة الآن" },
  { "id": 121, "en": "go on", "ar": "يستمر", "pronounce": "غو أون", "ex_en": "Go on, tell me more", "ar_ex": "استمر، أخبرني المزيد" },
  { "id": 122, "en": "put away", "ar": "يضع جانبًا", "pronounce": "پُت أواي", "ex_en": "Put away your toys please", "ar_ex": "ضع ألعابك جانباً" },
  { "id": 123, "en": "put on", "ar": "يلبس", "pronounce": "پُت أون", "ex_en": "Put on your warm coat", "ar_ex": "البس معطفك الدافئ" },
  { "id": 124, "en": "sweep (up)", "ar": "يكنس", "pronounce": "سْوِيب", "ex_en": "Please sweep up the floor", "ar_ex": "من فضلك اكنس الأرضية" },
  { "id": 125, "en": "throw (away)", "ar": "يرمي", "pronounce": "ثْرو", "ex_en": "Throw away the old trash", "ar_ex": "ارمم القمامة القديمة" },
  { "id": 126, "en": "tidy up", "ar": "يرتّب", "pronounce": "تايدي أپ", "ex_en": "Tidy up your small room", "ar_ex": "رتب غرفتك الصغيرة" },
  { "id": 127, "en": "address", "ar": "عنوان", "pronounce": "أَدْرِس", "ex_en": "What is your home address?", "ar_ex": "ما هو عنوان منزلك؟" },
  { "id": 128, "en": "chat", "ar": "دردشة", "pronounce": "تشات", "ex_en": "I love a friendly chat", "ar_ex": "أحب الدردشة الودودة" },
  { "id": 129, "en": "communicate", "ar": "يتواصل", "pronounce": "كُمِيونيكيت", "ex_en": "We communicate with each other", "ar_ex": "نحن نتواصل مع بعضنا" },
  { "id": 130, "en": "contact", "ar": "اتصال", "pronounce": "كونتاكت", "ex_en": "Keep in contact with me", "ar_ex": "ابقَ على اتصال معي" },
  { "id": 131, "en": "message", "ar": "رسالة", "pronounce": "مِسِج", "ex_en": "I sent a nice message", "ar_ex": "أرسلت رسالة لطيفة" },
  { "id": 132, "en": "postcard", "ar": "بطاقة", "pronounce": "پوسْتكارد", "ex_en": "I sent a cool postcard", "ar_ex": "أرسلت بطاقة بريدية رائعة" },
  { "id": 133, "en": "send", "ar": "يرسل", "pronounce": "سِند", "ex_en": "Send me the letter now", "ar_ex": "أرسل لي الرسالة الآن" },
  { "id": 134, "en": "receive", "ar": "يستقبل", "pronounce": "رِسيف", "ex_en": "I did receive the message", "ar_ex": "لقد استقبلت الرسالة بالفعل" },
  { "id": 135, "en": "text", "ar": "رسالة نصية", "pronounce": "تِكست", "ex_en": "Send a text to me", "ar_ex": "أرسل لي رسالة نصية" },
  { "id": 136, "en": "bow", "ar": "ينحني", "pronounce": "باو", "ex_en": "They bow to show respect", "ar_ex": "هم ينحنون لإظهار الاحترام" },
  { "id": 137, "en": "fold arms", "ar": "يطوي ذراعيه", "pronounce": "فولد آرمز", "ex_en": "Do not fold your arms", "ar_ex": "لا تطوِ ذراعيك" },
  { "id": 138, "en": "hug", "ar": "يعانق", "pronounce": "هَغ", "ex_en": "Give me a big hug", "ar_ex": "عانقني عناقاً كبيراً" },
  { "id": 139, "en": "kiss", "ar": "يقبّل", "pronounce": "كِس", "ex_en": "She will kiss the baby", "ar_ex": "هي ستقبل الطفل" },
  { "id": 140, "en": "save", "ar": "ينقذ", "pronounce": "سيف", "ex_en": "He tried to save him", "ar_ex": "هو حاول إنقاذه" },
  { "id": 141, "en": "competition", "ar": "منافسة", "pronounce": "كومپِتِشَن", "ex_en": "I won the hard competition", "ar_ex": "فزت في المنافسة الصعبة" },
  { "id": 142, "en": "final", "ar": "نهائي", "pronounce": "فاينَل", "ex_en": "This is the final game", "ar_ex": "هذه هي المباراة النهائية" },
  { "id": 143, "en": "goal", "ar": "هدف", "pronounce": "گول", "ex_en": "He scored a good goal", "ar_ex": "سجل هدفاً جيداً" },
  { "id": 144, "en": "match", "ar": "مباراة", "pronounce": "ماتش", "ex_en": "I watched the football match", "ar_ex": "شاهدت مباراة كرة القدم" },
  { "id": 145, "en": "pitch", "ar": "ملعب", "pronounce": "پِتش", "ex_en": "The players enter the pitch", "ar_ex": "اللاعبون يدخلون الملعب" },
  { "id": 146, "en": "score", "ar": "يسجل هدفًا", "pronounce": "سْكور", "ex_en": "They want to score goals", "ar_ex": "هم يريدون تسجيل أهداف" },
  { "id": 147, "en": "team", "ar": "فريق", "pronounce": "تيم", "ex_en": "Our team is very strong", "ar_ex": "فريقنا قوي جداً" },
  { "id": 148, "en": "win", "ar": "يفوز", "pronounce": "وِن", "ex_en": "We will win the match", "ar_ex": "سوف نفوز في المباراة" },
  { "id": 149, "en": "afraid", "ar": "خائف", "pronounce": "أَفريد", "ex_en": "Don't be afraid of me", "ar_ex": "لا تكن خائفاً مني" },
  { "id": 150, "en": "amazing", "ar": "مذهل", "pronounce": "أَمَيْزِنغ", "ex_en": "This is an amazing idea", "ar_ex": "هذه فكرة مذهلة" },
  { "id": 151, "en": "bored", "ar": "ضجر", "pronounce": "بورد", "ex_en": "I am so bored today", "ar_ex": "أنا ضجر جداً اليوم" },
  { "id": 152, "en": "common", "ar": "شائع", "pronounce": "كومن", "ex_en": "This is a common name", "ar_ex": "هذا اسم شائع" },
  { "id": 153, "en": "dangerous", "ar": "خطير", "pronounce": "دِينجِرَس", "ex_en": "The snake is very dangerous", "ar_ex": "الثعبان خطير جداً" },
  { "id": 154, "en": "dark", "ar": "مظلم", "pronounce": "دارك", "ex_en": "The room is very dark", "ar_ex": "الغرفة مظلمة جداً" },
  { "id": 155, "en": "different", "ar": "مختلف", "pronounce": "دِفْرِنت", "ex_en": "We have different ideas now", "ar_ex": "لدينا أفكار مختلفة الآن" },
  { "id": 156, "en": "the same", "ar": "نفس الشيء", "pronounce": "ذَ سيم", "ex_en": "This is the same thing", "ar_ex": "هذا هو نفس الشيء" },
  { "id": 157, "en": "enormous", "ar": "ضخم", "pronounce": "إِنورمَس", "ex_en": "The whale is very enormous", "ar_ex": "الحوت ضخم جداً" },
  { "id": 158, "en": "excellent", "ar": "ممتاز", "pronounce": "إِكسِلِنت", "ex_en": "You did an excellent job", "ar_ex": "لقد قمت بعمل ممتاز" },
  { "id": 159, "en": "excited", "ar": "متحمس", "pronounce": "إكسايتِد", "ex_en": "I am excited to travel", "ar_ex": "أنا متحمس للسفر" },
  { "id": 160, "en": "fascinating", "ar": "رائع", "pronounce": "فاسِنَيْتِنغ", "ex_en": "That is a fascinating story", "ar_ex": "تلك قصة رائعة" },
  { "id": 161, "en": "freezing", "ar": "شديد البرودة", "pronounce": "فْريزِنغ", "ex_en": "The weather is freezing now", "ar_ex": "الطقس شديد البرودة الآن" },
  { "id": 162, "en": "hard", "ar": "صعب", "pronounce": "هارد", "ex_en": "The test is very hard", "ar_ex": "الاختبار صعب جداً" },
  { "id": 163, "en": "important", "ar": "مهم", "pronounce": "إمپورتَنت", "ex_en": "This is an important lesson", "ar_ex": "هذا درس مهم" },
  { "id": 164, "en": "intelligent", "ar": "ذكي", "pronounce": "إنتِلِجِنت", "ex_en": "He is an intelligent student", "ar_ex": "هو طالب ذكي" },
  { "id": 165, "en": "pleased", "ar": "مسرور", "pronounce": "پْليزد", "ex_en": "I am pleased to meet", "ar_ex": "أنا مسرور بلقائك" },
  { "id": 166, "en": "popular", "ar": "مشهور", "pronounce": "پوبْيولَر", "ex_en": "He is a popular actor", "ar_ex": "هو ممثل مشهور" },
  { "id": 167, "en": "strange", "ar": "غريب", "pronounce": "سْترينج", "ex_en": "I saw a strange bird", "ar_ex": "رأيت طائراً غريباً" },
  { "id": 168, "en": "sure", "ar": "متأكد", "pronounce": "شور", "ex_en": "I am sure about this", "ar_ex": "أنا متأكد من هذا" },
  { "id": 169, "en": "surprised", "ar": "مندهش", "pronounce": "سِرپْرايزد", "ex_en": "I am surprised to see", "ar_ex": "أنا مندهش لرؤيتك" },
  { "id": 170, "en": "traditional", "ar": "تقليدي", "pronounce": "تْرادِشَنَل", "ex_en": "I like the traditional clothes", "ar_ex": "أحب الملابس التقليدية" },
  { "id": 171, "en": "upset", "ar": "منزعج", "pronounce": "أَبْسِت", "ex_en": "Do not be upset today", "ar_ex": "لا تكن منزعجاً اليوم" },
  { "id": 172, "en": "wrong", "ar": "خطأ", "pronounce": "رونغ", "ex_en": "You made a wrong turn", "ar_ex": "لقد اتخذت منعطفاً خاطئاً" },
  { "id": 173, "en": "maybe", "ar": "ربما", "pronounce": "مَيْبي", "ex_en": "Maybe he will come later", "ar_ex": "ربما سيأتي لاحقاً" },
  { "id": 174, "en": "perhaps", "ar": "ربما", "pronounce": "پَرهابْس", "ex_en": "Perhaps we will go tomorrow", "ar_ex": "ربما سنذهب غداً" },
  { "id": 175, "en": "camera", "ar": "كاميرا", "pronounce": "كامِرا", "ex_en": "Use the camera for photos", "ar_ex": "استخدم الكاميرا للصور" },
  { "id": 176, "en": "machine", "ar": "آلة", "pronounce": "مَشين", "ex_en": "The machine works very well", "ar_ex": "الآلة تعمل جيداً" },
  { "id": 177, "en": "microphone", "ar": "ميكروفون", "pronounce": "مايكروفون", "ex_en": "Speak into the microphone now", "ar_ex": "تحدث في الميكروفون الآن" },
  { "id": 178, "en": "network", "ar": "شبكة", "pronounce": "نِتْوُورك", "ex_en": "The network is very fast", "ar_ex": "الشبكة سريعة جداً" },
  { "id": 179, "en": "program", "ar": "برنامج", "pronounce": "پروغرام", "ex_en": "Watch this funny TV program", "ar_ex": "شاهد هذا البرنامج المضحك" },
  { "id": 180, "en": "pump", "ar": "مضخة", "pronounce": "پَمپ", "ex_en": "Use the water pump now", "ar_ex": "استخدم مضخة الماء الآن" },
  { "id": 181, "en": "radio", "ar": "راديو", "pronounce": "رَيْديو", "ex_en": "Listen to the radio now", "ar_ex": "استمع للراديو الآن" },
  { "id": 182, "en": "satellite", "ar": "قمر صناعي", "pronounce": "ساتِلّايت", "ex_en": "We use a satellite signal", "ar_ex": "نحن نستخدم إشارة قمر صناعي" },
  { "id": 183, "en": "video call", "ar": "مكالمة فيديو", "pronounce": "ڤيديو كول", "ex_en": "I make a video call", "ar_ex": "أقوم بإجراء مكالمة فيديو" },
  { "id": 184, "en": "pass on", "ar": "يمرّر", "pronounce": "پاس أون", "ex_en": "Please pass on the message", "ar_ex": "من فضلك مرر الرسالة" }
];