const levelCLASS5_Words = [
  { id: 1, en: "parents", ar: "والدان", pronounce: "پيرِنتس", ex_en: "I love my parents", ar_ex: "أنا أحب والدي" },
  { id: 2, en: "Palestinian", ar: "فلسطيني", pronounce: "پالِسْتينيان", ex_en: "I am a Palestinian boy", ar_ex: "أنا ولد فلسطيني" },
  { id: 3, en: "Jordanian", ar: "أردني", pronounce: "جوردَيْنيان", ex_en: "My friend is Jordanian", ar_ex: "صديقي أردني" },
  { id: 4, en: "Egyptian", ar: "مصري", pronounce: "إيجيپشن", ex_en: "The doctor is Egyptian", ar_ex: "الطبيب مصري" },
  { id: 5, en: "Australian", ar: "أسترالي", pronounce: "أُسترَيْليان", ex_en: "He is an Australian man", ar_ex: "هو رجل أسترالي" },
  { id: 6, en: "American", ar: "أمريكي", pronounce: "أَمِرِكن", ex_en: "They are American students", ar_ex: "هم طلاب أمريكيون" },
  { id: 7, en: "Canadian", ar: "كندي", pronounce: "كَنَيْديان", ex_en: "She is a Canadian nurse", ar_ex: "هي ممرضة كندية" },
  { id: 8, en: "Canada", ar: "كندا", pronounce: "كَنَدَا", ex_en: "Canada is a big country", ar_ex: "كندا دولة كبيرة" },
  { id: 9, en: "million", ar: "مليون", pronounce: "مِلْيَن", ex_en: "I have a million ideas", ar_ex: "لدي مليون فكرة" },
  { id: 10, en: "state", ar: "دولة", pronounce: "سْتيت", ex_en: "Palestine is a beautiful state", ar_ex: "فلسطين دولة جميلة" },
  { id: 11, en: "old", ar: "كبير السن", pronounce: "أُولد", ex_en: "The man is very old", ar_ex: "الرجل كبير جداً في السن" },
  { id: 12, en: "young", ar: "صغير السن", pronounce: "يَنگ", ex_en: "He is a young boy", ar_ex: "هو ولد صغير السن" },
  { id: 13, en: "speak", ar: "يتكلم", pronounce: "سْپييك", ex_en: "I speak English well", ar_ex: "أنا أتكلم الإنجليزية جيداً" },
  { id: 14, en: "work", ar: "يعمل", pronounce: "وورك", ex_en: "My dad works here", ar_ex: "أبي يعمل هنا" },
  { id: 15, en: "building", ar: "بناية", pronounce: "بِلْدِنغ", ex_en: "This is a tall building", ar_ex: "هذه بناية طويلة" },
  { id: 16, en: "camp", ar: "مخيم", pronounce: "كامپ", ex_en: "We live in a camp", ar_ex: "نحن نعيش في مخيم" },
  { id: 17, en: "by", ar: "بواسطة", pronounce: "باي", ex_en: "I go by car", ar_ex: "أنا أذهب بالسيارة" },
  { id: 18, en: "with", ar: "مع", pronounce: "وِذ", ex_en: "Come with me", ar_ex: "تعال معي" },
  { id: 19, en: "near", ar: "قريب من", pronounce: "نِير", ex_en: "My house is near", ar_ex: "بيتي قريب" },
  { id: 20, en: "for", ar: "لأجل", pronounce: "فور", ex_en: "This gift is for you", ar_ex: "هذه الهدية لك" },
  { id: 21, en: "from", ar: "من", pronounce: "فرُم", ex_en: "I am from Gaza", ar_ex: "أنا من غزة" },
  { id: 22, en: "during", ar: "خلال", pronounce: "دْيُورِنغ", ex_en: "Sleep during the night", ar_ex: "نم خلال الليل" },
  { id: 23, en: "since", ar: "منذ", pronounce: "سِنْس", ex_en: "I am here since morning", ar_ex: "أنا هنا منذ الصباح" },
  { id: 24, en: "ago", ar: "قبل", pronounce: "أَگو", ex_en: "I ate an hour ago", ar_ex: "أكلت قبل ساعة" },
  { id: 25, en: "clock", ar: "ساعة حائط", pronounce: "كْلوك", ex_en: "The clock is on wall", ar_ex: "الساعة على الحائط" },
  { id: 26, en: "cycling", ar: "ركوب الدراجة", pronounce: "سايكلِنغ", ex_en: "I like cycling", ar_ex: "أنا أحب ركوب الدراجة" },
  { id: 27, en: "invite", ar: "يدعو", pronounce: "إنڤايت", ex_en: "I invite my friends", ar_ex: "أنا أدعو أصدقائي" },
  { id: 28, en: "spacesuit", ar: "بدلة فضاء", pronounce: "سْپيس سوت", ex_en: "The suit is new", ar_ex: "البدلة جديدة" },
  { id: 29, en: "nice", ar: "لطيف", pronounce: "نايس", ex_en: "You are very nice", ar_ex: "أنت لطيف جداً" },
  { id: 30, en: "last", ar: "الماضي", pronounce: "لاست", ex_en: "I went last week", ar_ex: "ذهبت الأسبوع الماضي" },
  { id: 31, en: "museum", ar: "متحف", pronounce: "ميوزِيَم", ex_en: "I visited the museum", ar_ex: "زرت المتحف" },
  { id: 32, en: "country", ar: "دولة", pronounce: "كَنْتري", ex_en: "I love my country", ar_ex: "أنا أحب دولتي" },
  { id: 33, en: "image", ar: "صورة", pronounce: "إيمِج", ex_en: "Take a nice image", ar_ex: "التقط صورة جميلة" },
  { id: 34, en: "River Thames", ar: "نهر التايمز", pronounce: "رِڤَر تِمْز", ex_en: "The river is long", ar_ex: "النهر طويل" },
  { id: 35, en: "showed", ar: "أظهر", pronounce: "شُود", ex_en: "He showed me photos", ar_ex: "أراني صوراً" },
  { id: 36, en: "talked", ar: "تحدّث", pronounce: "توكْت", ex_en: "We talked about school", ar_ex: "تحدثنا عن المدرسة" },
  { id: 37, en: "tourist", ar: "سائح", pronounce: "تورِست", ex_en: "He is a tourist", ar_ex: "هو سائح" },
  { id: 38, en: "twins", ar: "توأمان", pronounce: "توينز", ex_en: "They are twins", ar_ex: "هم توأمان" },
  { id: 39, en: "vegetables", ar: "خضروات", pronounce: "ڤِجِتَبُلز", ex_en: "Eat your vegetables", ar_ex: "كل خضرواتك" },
  { id: 40, en: "assembly", ar: "اجتماع", pronounce: "أَسِمْبْلي", ex_en: "Attend the school assembly", ar_ex: "احضر اجتماع المدرسة" },
  { id: 41, en: "break", ar: "استراحة", pronounce: "بريك", ex_en: "Time for a break", ar_ex: "وقت للاستراحة" },
  { id: 42, en: "religious education", ar: "تعليم ديني", pronounce: "رِلِجَس إديوكيشن", ex_en: "Study religious education", ar_ex: "ادرس التربية الدينية" },
  { id: 43, en: "alphabet", ar: "الأبجدية", pronounce: "أَلْفابِت", ex_en: "Learn the alphabet", ar_ex: "تعلم الأبجدية" },
  { id: 44, en: "alphabetical order", ar: "ترتيب أبجدي", pronounce: "أَلْفابِتِكَل أُوردَر", ex_en: "Use alphabetical order", ar_ex: "استخدم الترتيب الأبجدي" },
  { id: 45, en: "best", ar: "الأفضل", pronounce: "بِسْت", ex_en: "You are the best", ar_ex: "أنت الأفضل" },
  { id: 46, en: "bounce", ar: "يطبّط", pronounce: "باوْنس", ex_en: "Bounce the ball", ar_ex: "اطبطب الكرة" },
  { id: 47, en: "court", ar: "ملعب", pronounce: "كورت", ex_en: "Go to the court", ar_ex: "اذهب للملعب" },
  { id: 48, en: "ruin", ar: "آثار", pronounce: "رُوين", ex_en: "We saw old ruins", ar_ex: "رأينا آثاراً قديمة" },
  { id: 49, en: "kick", ar: "يركل", pronounce: "كِك", ex_en: "Kick the ball", ar_ex: "اركل الكرة" },
  { id: 50, en: "mystery", ar: "لغز", pronounce: "مِسْتِري", ex_en: "Solve the mystery", ar_ex: "حل اللغز" },
  { id: 51, en: "net", ar: "شبكة", pronounce: "نِت", ex_en: "The ball hit the net", ar_ex: "الكرة ضربت الشبكة" },
  { id: 52, en: "question", ar: "سؤال", pronounce: "كْوِسْتشَن", ex_en: "Answer the question", ar_ex: "أجب عن السؤال" },
  { id: 53, en: "question mark", ar: "علامة استفهام", pronounce: "كْوِسْتشَن مارك", ex_en: "Use a question mark", ar_ex: "استخدم علامة الاستفهام" },
  { id: 54, en: "fruit", ar: "فواكه", pronounce: "فروت", ex_en: "Eat fresh fruit", ar_ex: "كل فواكه طازجة" },
  { id: 55, en: "thin", ar: "نحيف", pronounce: "ثِن", ex_en: "He is very thin", ar_ex: "هو نحيف جداً" },
  { id: 56, en: "throw", ar: "يرمي", pronounce: "ثْرو", ex_en: "Throw the ball", ar_ex: "ارمِ الكرة" },
  { id: 57, en: "world", ar: "العالم", pronounce: "وورلد", ex_en: "I want to see the world", ar_ex: "أريد رؤية العالم" },
  { id: 58, en: "channel", ar: "قناة", pronounce: "تشانَل", ex_en: "Change the TV channel", ar_ex: "غير قناة التلفاز" },
  { id: 59, en: "news", ar: "أخبار", pronounce: "نيوز", ex_en: "Watch the daily news", ar_ex: "شاهد الأخبار اليومية" },
  { id: 60, en: "sailing", ar: "إبحار", pronounce: "سَيْلِنغ", ex_en: "I like sailing", ar_ex: "أنا أحب الإبحار" },
  { id: 61, en: "wrestling", ar: "مصارعة", pronounce: "رِسْلِنغ", ex_en: "Wrestling is a hard sport", ar_ex: "المصارعة رياضة صعبة" },
  { id: 62, en: "China", ar: "الصين", pronounce: "تشاينا", ex_en: "China is very big", ar_ex: "الصين كبيرة جداً" },
  { id: 63, en: "car racing", ar: "سباق سيارات", pronounce: "كار ريسِنغ", ex_en: "I watch car racing", ar_ex: "أنا أشاهد سباق السيارات" },
  { id: 64, en: "expensive", ar: "غالي", pronounce: "إكْسْپِنْسِف", ex_en: "This is too expensive", ar_ex: "هذا غالٍ جداً" },
  { id: 65, en: "floor", ar: "أرضية", pronounce: "فلور", ex_en: "Clean the floor", ar_ex: "نظف الأرضية" },
  { id: 66, en: "ground", ar: "أرض", pronounce: "غْراوند", ex_en: "Sit on the ground", ar_ex: "اجلس على الأرض" },
  { id: 67, en: "take", ar: "يلتقط", pronounce: "تيك", ex_en: "Take a photo now", ar_ex: "التقط صورة الآن" },
  { id: 68, en: "dictionary", ar: "قاموس", pronounce: "دِكْشَنَري", ex_en: "Use your dictionary", ar_ex: "استخدم قاموسك" },
  { id: 69, en: "meaning", ar: "معنى", pronounce: "مينِنغ", ex_en: "What is the meaning?", ar_ex: "ما هو المعنى؟" },
  { id: 70, en: "rhyme", ar: "قافية", pronounce: "رايم", ex_en: "Find a word rhyme", ar_ex: "جد قافية للكلمة" },
  { id: 71, en: "foot", ar: "قدم", pronounce: "فوت", ex_en: "I use my foot", ar_ex: "أنا أستخدم قدمي" },
  { id: 72, en: "toe", ar: "إصبع القدم", pronounce: "تو", ex_en: "I hurt my toe", ar_ex: "أذيت إصبع قدمي" },
  { id: 73, en: "wear", ar: "يلبس", pronounce: "وِير", ex_en: "Wear your coat", ar_ex: "البس معطفك" },
  { id: 74, en: "take off", ar: "يخلع", pronounce: "تيك أوف", ex_en: "Take off your shoes", ar_ex: "اخلع حذاءك" },
  { id: 75, en: "badminton", ar: "تنس الريشة", pronounce: "بادمِنْتَن", ex_en: "We play badminton", ar_ex: "نحن نلعب تنس الريشة" },
  { id: 76, en: "period", ar: "فترة", pronounce: "پيريود", ex_en: "The next period starts", ar_ex: "الفترة القادمة تبدأ" },
  { id: 77, en: "boat", ar: "قارب", pronounce: "بوت", ex_en: "This boat is small", ar_ex: "هذا القارب صغير" },
  { id: 78, en: "canoe", ar: "زورق صغير", pronounce: "كَنو", ex_en: "Row the small canoe", ar_ex: "جدف الزورق الصغير" },
  { id: 79, en: "bell", ar: "جرس", pronounce: "بِل", ex_en: "Ring the school bell", ar_ex: "دق جرس المدرسة" },
  { id: 80, en: "end", ar: "نهاية", pronounce: "إِند", ex_en: "This is the end", ar_ex: "هذه هي النهاية" },
  { id: 81, en: "special", ar: "خاص", pronounce: "سْپِشَل", ex_en: "You are very special", ar_ex: "أنت مميز جداً" },
  { id: 82, en: "game", ar: "لعبة", pronounce: "گيم", ex_en: "Play a new game", ar_ex: "العب لعبة جديدة" },
  { id: 83, en: "grades", ar: "علامات", pronounce: "غْرَيْدز", ex_en: "I want good grades", ar_ex: "أريد علامات جيدة" },
  { id: 84, en: "happy", ar: "سعيد", pronounce: "هابي", ex_en: "I feel very happy", ar_ex: "أشعر بسعادة كبيرة" },
  { id: 85, en: "sad", ar: "حزين", pronounce: "ساد", ex_en: "Why are you sad?", ar_ex: "لماذا أنت حزين؟" },
  { id: 86, en: "angry", ar: "غاضب", pronounce: "أَنْغري", ex_en: "Don't be angry", ar_ex: "لا تكن غاضباً" },
  { id: 87, en: "annoyed", ar: "منزعج", pronounce: "أَنُويد", ex_en: "He looks very annoyed", ar_ex: "هو يبدو منزعجاً جداً" },
  { id: 88, en: "upset", ar: "زعلان", pronounce: "أَبْسِت", ex_en: "Are you upset now?", ar_ex: "هل أنت زعلان الآن؟" },
  { id: 89, en: "string", ar: "خيط", pronounce: "سْتْرِنغ", ex_en: "Cut the long string", ar_ex: "اقطع الخيط الطويل" },
  { id: 90, en: "trip", ar: "رحلة", pronounce: "تْرِپ", ex_en: "We went on trip", ar_ex: "ذهبنا في رحلة" },
  { id: 91, en: "picnic", ar: "نزهة", pronounce: "پِكنِك", ex_en: "Go on a picnic", ar_ex: "اذهب في نزهة" },
  { id: 92, en: "wonderful", ar: "رائع", pronounce: "وَنْْدِرفُل", ex_en: "The weather is wonderful", ar_ex: "الطقس رائع" },
  { id: 93, en: "journey", ar: "رحلة", pronounce: "جيرني", ex_en: "It was long journey", ar_ex: "كانت رحلة طويلة" },
  { id: 94, en: "left", ar: "يسار", pronounce: "لِفت", ex_en: "Turn to the left", ar_ex: "انعطف لليسار" },
  { id: 95, en: "right", ar: "يمين", pronounce: "رايت", ex_en: "Go to the right", ar_ex: "اذهب لليمين" },
  { id: 96, en: "clever", ar: "ذكي", pronounce: "كْلِڤَر", ex_en: "He is very clever", ar_ex: "هو ذكي جداً" },
  { id: 97, en: "hide", ar: "يختبئ", pronounce: "هايد", ex_en: "Hide behind the door", ar_ex: "اختبئ خلف الباب" },
  { id: 98, en: "both", ar: "كلا", pronounce: "بوث", ex_en: "Both are my friends", ar_ex: "كلاهما صديقاي" },
  { id: 99, en: "back", ar: "يعود", pronounce: "باك", ex_en: "Go back home now", ar_ex: "عد للمنزل الآن" },
  { id: 100, en: "have", ar: "يملك", pronounce: "هاف", ex_en: "I have a pen", ar_ex: "أنا أملك قلماً" },
  { id: 101, en: "bought", ar: "اشترى", pronounce: "بوت", ex_en: "I bought a cake", ar_ex: "اشتريت كعكة" },
  { id: 102, en: "deer", ar: "غزال", pronounce: "دِير", ex_en: "I saw a deer", ar_ex: "رأيت غزالاً" },
  { id: 103, en: "cheetah", ar: "فهد", pronounce: "تشيتا", ex_en: "Cheetah is very fast", ar_ex: "الفهد سريع جداً" },
  { id: 104, en: "wolf", ar: "ذئب", pronounce: "وولف", ex_en: "The wolf is wild", ar_ex: "الذئب متوحش" },
  { id: 105, en: "pack", ar: "حزمة", pronounce: "پاك", ex_en: "Carry the small pack", ar_ex: "احمل الحزمة الصغيرة" },
  { id: 106, en: "submarine", ar: "غواصة", pronounce: "سَبْمَرِين", ex_en: "The submarine is deep", ar_ex: "الغواصة في العمق" },
  { id: 107, en: "program", ar: "برنامج", pronounce: "بروغرام", ex_en: "I like this program", ar_ex: "أحب هذا البرنامج" },
  { id: 108, en: "often", ar: "غالبًا", pronounce: "أُوفِن", ex_en: "I often play ball", ar_ex: "غالباً ألعب الكرة" },
  { id: 109, en: "forest", ar: "غابة", pronounce: "فُورِست", ex_en: "The forest is big", ar_ex: "الغابة كبيرة" },
  { id: 110, en: "wildlife", ar: "الحياة البرية", pronounce: "وايلدلايف", ex_en: "Protect the wildlife", ar_ex: "احمِ الحياة البرية" },
  { id: 111, en: "turn off", ar: "يطفئ", pronounce: "تِرن أوف", ex_en: "Turn off the light", ar_ex: "أطفئ الضوء" },
  { id: 112, en: "seaside", ar: "شاطئ البحر", pronounce: "سي سايد", ex_en: "Go to the seaside", ar_ex: "اذهب لشاطئ البحر" },
  { id: 113, en: "else", ar: "آخر", pronounce: "إِلس", ex_en: "Anything else, please?", ar_ex: "أي شيء آخر؟" },
  { id: 114, en: "action films", ar: "أفلام تشويق", pronounce: "آكشن فيلمز", ex_en: "I watch action films", ar_ex: "أشاهد أفلام تشويق" },
  { id: 115, en: "drama", ar: "دراما", pronounce: "دراما", ex_en: "She likes drama films", ar_ex: "هي تحب أفلام الدراما" },
  { id: 116, en: "cartoon", ar: "أفلام كرتون", pronounce: "كارتون", ex_en: "I watch funny cartoon", ar_ex: "أشاهد كرتوناً مضحكاً" },
  { id: 117, en: "how often", ar: "كم مرة", pronounce: "هاو أُوفِن", ex_en: "How often you swim?", ar_ex: "كم مرة تسبح؟" },
  { id: 118, en: "pop music", ar: "موسيقى شعبية", pronounce: "پوب ميوزِك", ex_en: "He likes pop music", ar_ex: "هو يحب الموسيقى" },
  { id: 119, en: "late", ar: "متأخر", pronounce: "لِيت", ex_en: "Don't be late", ar_ex: "لا تتأخر" },
  { id: 120, en: "early", ar: "مبكر", pronounce: "إيرلي", ex_en: "Wake up early", ar_ex: "استيقظ مبكراً" },
  { id: 121, en: "carefully", ar: "بعناية", pronounce: "كيرفُلي", ex_en: "Drive carefully now", ar_ex: "قد بعناية الآن" },
  { id: 122, en: "carelessly", ar: "بإهمال", pronounce: "كيرلِسلي", ex_en: "Don't work carelessly", ar_ex: "لا تعمل بإهمال" },
  { id: 123, en: "change", ar: "يغيّر", pronounce: "تشينج", ex_en: "Change your wet clothes", ar_ex: "غير ملابسك المبللة" },
  { id: 124, en: "comma", ar: "فاصلة", pronounce: "كُوما", ex_en: "Use a small comma", ar_ex: "استخدم فاصلة صغيرة" },
  { id: 125, en: "later", ar: "لاحقًا", pronounce: "لِيتَر", ex_en: "I will call later", ar_ex: "سأتصل لاحقاً" },
  { id: 126, en: "list", ar: "قائمة", pronounce: "لِست", ex_en: "Write a new list", ar_ex: "اكتب قائمة جديدة" },
  { id: 127, en: "look after", ar: "يعتني بـ", pronounce: "لوك آفتر", ex_en: "Look after your books", ar_ex: "اعتنِ بكتبك" },
  { id: 128, en: "look for", ar: "يبحث عن", pronounce: "لوك فور", ex_en: "I look for pen", ar_ex: "أنا أبحث عن قلم" },
  { id: 129, en: "neatly", ar: "بشكل أنيق", pronounce: "نِيتلي", ex_en: "Write neatly here", ar_ex: "اكتب بشكل أنيق هنا" },
  { id: 130, en: "noisy", ar: "مزعج", pronounce: "نويزي", ex_en: "The room is noisy", ar_ex: "الغرفة مزعجة" },
  { id: 131, en: "perform", ar: "يمثل", pronounce: "پِرفورم", ex_en: "They perform a play", ar_ex: "هم يمثلون مسرحية" },
  { id: 132, en: "pipe", ar: "أنبوب", pronounce: "پايب", ex_en: "Fix the broken pipe", ar_ex: "أصلح الأنبوب المكسور" },
  { id: 133, en: "play", ar: "مسرحية", pronounce: "بلاي", ex_en: "The play was good", ar_ex: "المسرحية كانت جيدة" },
  { id: 134, en: "poor", ar: "فقير", pronounce: "پور", ex_en: "Help the poor man", ar_ex: "ساعد الرجل الفقير" },
  { id: 135, en: "rich", ar: "غني", pronounce: "رِتش", ex_en: "The rich man helped", ar_ex: "الرجل الغني ساعد" },
  { id: 136, en: "click", ar: "ينقر", pronounce: "كْلِك", ex_en: "Click the mouse button", ar_ex: "انقر زر الفأرة" },
  { id: 137, en: "connect", ar: "يوصل", pronounce: "كَنِكت", ex_en: "Connect the internet", ar_ex: "وصل الإنترنت" },
  { id: 138, en: "control", ar: "تحكم", pronounce: "كونترول", ex_en: "Control the TV now", ar_ex: "تحكم بالتلفاز الآن" },
  { id: 139, en: "screen", ar: "شاشة", pronounce: "سْكرين", ex_en: "Clean the computer screen", ar_ex: "نظف شاشة الكمبيوتر" },
  { id: 140, en: "try", ar: "يحاول", pronounce: "تراي", ex_en: "Try again my friend", ar_ex: "حاول مجدداً يا صديقي" },
  { id: 141, en: "video", ar: "فيديو", pronounce: "ڤيديو", ex_en: "Watch this short video", ar_ex: "شاهد هذا الفيديو" },
  { id: 142, en: "button", ar: "زر", pronounce: "بَتن", ex_en: "Press the red button", ar_ex: "اضغط الزر الأحمر" },
  { id: 143, en: "video player", ar: "مشغل فيديو", pronounce: "ڤيديو پْلايَر", ex_en: "Open the video player", ar_ex: "افتح مشغل الفيديو" },
  { id: 144, en: "press", ar: "يضغط", pronounce: "پْرِس", ex_en: "Press the button now", ar_ex: "اضغط الزر الآن" },
  { id: 145, en: "future", ar: "مستقبل", pronounce: "فيوتشر", ex_en: "Plan for your future", ar_ex: "خطط لمستقبلك" },
  { id: 146, en: "think", ar: "يفكر", pronounce: "ثِنك", ex_en: "Think about your answers", ar_ex: "فكر في إجاباتك" },
  { id: 147, en: "moon", ar: "قمر", pronounce: "مون", ex_en: "The moon is beautiful", ar_ex: "القمر جميل" },
  { id: 148, en: "planet", ar: "كوكب", pronounce: "پلانِت", ex_en: "Earth is a planet", ar_ex: "الأرض كوكب" },
  { id: 149, en: "spaceship", ar: "سفينة فضاء", pronounce: "سْپيس شِپ", ex_en: "Fly the big spaceship", ar_ex: "قد سفينة الفضاء" },
  { id: 150, en: "pilot", ar: "طيار", pronounce: "پايلَت", ex_en: "My uncle is pilot", ar_ex: "عمي طيار" },
  { id: 151, en: "everyone", ar: "الجميع", pronounce: "إِفري وُن", ex_en: "Everyone is here now", ar_ex: "الجميع هنا الآن" },
  { id: 152, en: "cheap", ar: "رخيص", pronounce: "تشيب", ex_en: "This book is cheap", ar_ex: "هذا الكتاب رخيص" },
  { id: 153, en: "mechanic", ar: "ميكانيكي", pronounce: "مِكانِك", ex_en: "He is a mechanic", ar_ex: "هو ميكانيكي" },
  { id: 154, en: "computer operator", ar: "مشغّل كمبيوتر", pronounce: "كومبيوتر أوبِرَيْتَر", ex_en: "He is computer operator", ar_ex: "هو مشغل كمبيوتر" },
  { id: 155, en: "vet", ar: "طبيب بيطري", pronounce: "ڤِت", ex_en: "Go to the vet", ar_ex: "اذهب للطبيب البيطري" },
  { id: 156, en: "astronaut", ar: "رائد فضاء", pronounce: "أسترونوت", ex_en: "Be a brave astronaut", ar_ex: "كن رائد فضاء شجاع" },
  { id: 157, en: "answer", ar: "يجيب", pronounce: "آنسَر", ex_en: "Please answer the phone", ar_ex: "أرجوك أجب الهاتف" },
  { id: 158, en: "hike", ar: "يتنزه", pronounce: "هايك", ex_en: "Let us go hike", ar_ex: "دعنا نتنزه" },
  { id: 159, en: "grow", ar: "ينمو", pronounce: "غرو", ex_en: "Plants grow very fast", ar_ex: "النباتات تنمو سريعاً" },
  { id: 160, en: "greedy", ar: "طمّاع", pronounce: "غْريدي", ex_en: "Don't be a greedy", ar_ex: "لا تكن طماعاً" },
  { id: 161, en: "move", ar: "يتحرك", pronounce: "موف", ex_en: "Move to the right", ar_ex: "تحرك لليمين" },
  { id: 162, en: "again", ar: "مرة أخرى", pronounce: "أَگين", ex_en: "Do it again now", ar_ex: "افعلها مجدداً الآن" },
  { id: 163, en: "also", ar: "أيضًا", pronounce: "أولسو", ex_en: "I also like fish", ar_ex: "أنا أيضاً أحب السمك" },
  { id: 164, en: "before", ar: "قبل", pronounce: "بِفور", ex_en: "Wash hands before food", ar_ex: "اغسل يدك قبل الطعام" },
  { id: 165, en: "after", ar: "بعد", pronounce: "آفتر", ex_en: "Play after your homework", ar_ex: "العب بعد واجبك" },
  { id: 166, en: "love", ar: "يحب", pronounce: "لَڤ", ex_en: "I love my family", ar_ex: "أنا أحب عائلتي" },
  { id: 167, en: "miss", ar: "يفتقد", pronounce: "مِس", ex_en: "I miss my friend", ar_ex: "أنا أفتقد صديقي" },
  { id: 168, en: "prefer", ar: "يفضّل", pronounce: "پْرِفِر", ex_en: "I prefer red apples", ar_ex: "أفضل التفاح الأحمر" },
  { id: 169, en: "push", ar: "يدفع", pronounce: "پُش", ex_en: "Push the door open", ar_ex: "ادفع الباب ليفتح" },
  { id: 170, en: "share", ar: "يشارك", pronounce: "شير", ex_en: "Share with your friend", ar_ex: "شارك مع صديقك" },
  { id: 171, en: "smell", ar: "يشم", pronounce: "سْمِل", ex_en: "Smell the nice flower", ar_ex: "اشم الزهرة الجميلة" },
  { id: 172, en: "turn", ar: "يقلب", pronounce: "تِرن", ex_en: "Turn the page now", ar_ex: "اقلب الصفحة الآن" },
  { id: 173, en: "understand", ar: "يفهم", pronounce: "أندِرستاند", ex_en: "Do you understand me?", ar_ex: "هل تفهمني؟" },
  { id: 174, en: "dish", ar: "طبق", pronounce: "دِش", ex_en: "A clean white dish", ar_ex: "طبق أبيض نظيف" },
  { id: 175, en: "oil", ar: "زيت", pronounce: "أويل", ex_en: "Use some good oil", ar_ex: "استخدم بعض الزيت" },
  { id: 176, en: "soap", ar: "صابون", pronounce: "سوب", ex_en: "Use soap for hands", ar_ex: "استخدم الصابون لليد" },
  { id: 177, en: "could", ar: "استطاع", pronounce: "كُد", ex_en: "He could help me", ar_ex: "استطاع مساعدتي" },
  { id: 178, en: "may", ar: "ربما", pronounce: "ماي", ex_en: "It may rain today", ar_ex: "ربما تمطر اليوم" },
  { id: 179, en: "must", ar: "يجب", pronounce: "مَست", ex_en: "You must listen now", ar_ex: "يجب أن تستمع" },
  { id: 180, en: "mustn’t", ar: "ممنوع", pronounce: "مَسنت", ex_en: "You mustn't run here", ar_ex: "ممنوع الركض هنا" },
  { id: 181, en: "should", ar: "ينبغي", pronounce: "شُد", ex_en: "You should be kind", ar_ex: "ينبغي أن تكون لطيفاً" },
  { id: 182, en: "shouldn’t", ar: "لا ينبغي", pronounce: "شُدنت", ex_en: "You shouldn't lie ever", ar_ex: "لا ينبغي أن تكذب" },
  { id: 183, en: "quiz", ar: "اختبار قصير", pronounce: "كْوِز", ex_en: "Take a small quiz", ar_ex: "قدم اختباراً قصيراً" },
  { id: 184, en: "face of clock", ar: "وجه الساعة", pronounce: "فيس أُف كلوك", ex_en: "Look at the face", ar_ex: "انظر لوجه الساعة" },
  { id: 185, en: "to go home", ar: "يذهب للبيت", pronounce: "تو غو هوم", ex_en: "Time to go home", ar_ex: "وقت الذهاب للبيت" },
  { id: 186, en: "hands of clock", ar: "عقارب الساعة", pronounce: "هاندز أُف كلوك", ex_en: "The clock has hands", ar_ex: "الساعة لها عقارب" },
  { id: 187, en: "quarter", ar: "ربع", pronounce: "كْوورْتَر", ex_en: "It is quarter past", ar_ex: "إنها وربع" },
  { id: 188, en: "civic education", ar: "تربية وطنية", pronounce: "سِڤِك إديوكيشن", ex_en: "Study civic education", ar_ex: "ادرس التربية الوطنية" },
  { id: 189, en: "physical education", ar: "تربية بدنية", pronounce: "فِزيكَل إديوكيشن", ex_en: "I like physical education", ar_ex: "أحب التربية البدنية" },
  { id: 190, en: "education", ar: "التعليم", pronounce: "إديوكيشن", ex_en: "Education is very important", ar_ex: "التعليم مهم جداً" },
  { id: 191, en: "start", ar: "بداية", pronounce: "ستارت", ex_en: "The start is easy", ar_ex: "البداية سهلة" },
  { id: 192, en: "time", ar: "الوقت", pronounce: "تايم", ex_en: "Time is very valuable", ar_ex: "الوقت ثمين جداً" },
  { id: 193, en: "fall asleep", ar: "ينام", pronounce: "فول أَسليب", ex_en: "I fall asleep late", ar_ex: "أنا أنام متأخراً" },
  { id: 194, en: "hare", ar: "أرنب", pronounce: "هِير", ex_en: "The hare is fast", ar_ex: "الأرنب سريع" },
  { id: 195, en: "laugh", ar: "يضحك", pronounce: "لاف", ex_en: "Don't laugh at him", ar_ex: "لا تضحك عليه" },
  { id: 196, en: "past", ar: "الماضي", pronounce: "پاست", ex_en: "Forget the sad past", ar_ex: "انسَ الماضي الحزين" },
  { id: 197, en: "race", ar: "سباق", pronounce: "ريس", ex_en: "Win the long race", ar_ex: "اربح السباق الطويل" },
  { id: 198, en: "slowly", ar: "ببطء", pronounce: "سْلَوْلي", ex_en: "Walk slowly please", ar_ex: "امشِ ببطء أرجوك" },
  { id: 199, en: "stop", ar: "يتوقف", pronounce: "ستوب", ex_en: "Stop the car now", ar_ex: "أوقف السيارة الآن" },
  { id: 200, en: "tortoise", ar: "سلحفاة", pronounce: "تورْتُس", ex_en: "The tortoise is slow", ar_ex: "السلحفاة بطيئة" },
  { id: 201, en: "wake up", ar: "يستيقظ", pronounce: "ويك أپ", ex_en: "Wake up early daily", ar_ex: "استيقظ مبكراً يومياً" },
  { id: 202, en: "agree", ar: "يوافق", pronounce: "أگري", ex_en: "I agree with you", ar_ex: "أنا أوافقك الرأي" },
  { id: 203, en: "all", ar: "الجميع", pronounce: "أول", ex_en: "All my friends came", ar_ex: "جميع أصدقائي جاؤوا" },
  { id: 204, en: "some", ar: "بعض", pronounce: "سَم", ex_en: "Take some water now", ar_ex: "خذ بعض الماء" },
  { id: 205, en: "wait", ar: "ينتظر", pronounce: "وِيت", ex_en: "Wait for me here", ar_ex: "انتظرني هنا" },
  { id: 206, en: "famous", ar: "مشهور", pronounce: "فَيْمَس", ex_en: "He is famous man", ar_ex: "هو رجل مشهور" },
  { id: 207, en: "do not agree", ar: "لا يوافق", pronounce: "دو نوت أگري", ex_en: "They do not agree", ar_ex: "هم لا يوافقون" },
  { id: 208, en: "exciting", ar: "ممتع", pronounce: "إكْسايتِنغ", ex_en: "This is exciting film", ar_ex: "هذا فيلم ممتع" },
  { id: 209, en: "people", ar: "الناس", pronounce: "پيپل", ex_en: "People are very kind", ar_ex: "الناس لطفاء جداً" },
  { id: 210, en: "stadium", ar: "ملعب", pronounce: "سْتَيْديَم", ex_en: "Go to the stadium", ar_ex: "اذهب للملعب" },
  { id: 211, en: "valley", ar: "وادٍ", pronounce: "ڤالي", ex_en: "The valley is deep", ar_ex: "الوادي عميق" },
  { id: 212, en: "first", ar: "الأول", pronounce: "فِرْست", ex_en: "You are the first", ar_ex: "أنت الأول" },
  { id: 213, en: "second", ar: "الثاني", pronounce: "سِكَنْد", ex_en: "He is the second", ar_ex: "هو الثاني" },
  { id: 214, en: "third", ar: "الثالث", pronounce: "ثِرْد", ex_en: "Take the third book", ar_ex: "خذ الكتاب الثالث" },
  { id: 215, en: "fourth", ar: "الرابع", pronounce: "فورث", ex_en: "The fourth day now", ar_ex: "اليوم الرابع الآن" },
  { id: 216, en: "fifth", ar: "الخامس", pronounce: "فِفْث", ex_en: "I am fifth one", ar_ex: "أنا الخامس" },
  { id: 217, en: "sixth", ar: "السادس", pronounce: "سِكْسْث", ex_en: "The sixth month here", ar_ex: "الشهر السادس هنا" },
  { id: 218, en: "seventh", ar: "السابع", pronounce: "سِڤِنْث", ex_en: "The seventh day is", ar_ex: "اليوم السابع هو" },
  { id: 219, en: "eighth", ar: "الثامن", pronounce: "إيتْث", ex_en: "The eighth lesson today", ar_ex: "الدرس الثامن اليوم" },
  { id: 220, en: "ninth", ar: "التاسع", pronounce: "ناينْث", ex_en: "The ninth month is", ar_ex: "الشهر التاسع هو" },
  { id: 221, en: "tenth", ar: "العاشر", pronounce: "تِنْث", ex_en: "The tenth one wins", ar_ex: "العاشر هو الفائز" },
  { id: 222, en: "choose", ar: "يختار", pronounce: "تشوز", ex_en: "Choose your favorite book", ar_ex: "اختر كتابك المفضل" },
  { id: 223, en: "arts and crafts", ar: "الفنون والحرف", pronounce: "آرتس أند كرافتس", ex_en: "I love doing arts", ar_ex: "أحب ممارسة الفنون" },
  { id: 224, en: "scored", ar: "سجّل هدفًا", pronounce: "سْكورد", ex_en: "He scored a goal", ar_ex: "سجل هدفاً" },
  { id: 225, en: "basket", ar: "سلة", pronounce: "باسكِت", ex_en: "Put in the basket", ar_ex: "ضعها في السلة" },
  { id: 226, en: "tallest", ar: "الأطول", pronounce: "تولِسْت", ex_en: "He is the tallest", ar_ex: "هو الأطول" },
  { id: 227, en: "team", ar: "فريق", pronounce: "تيم", ex_en: "I love my team", ar_ex: "أنا أحب فريقي" },
  { id: 228, en: "test", ar: "اختبار", pronounce: "تيست", ex_en: "I passed the test", ar_ex: "اجتزت الاختبار" },
  { id: 229, en: "won", ar: "فاز", pronounce: "وُن", ex_en: "We won the game", ar_ex: "فزنا باللعبة" },
  { id: 230, en: "worse", ar: "أسوأ", pronounce: "وِرس", ex_en: "This is worse today", ar_ex: "هذا أسوأ اليوم" },
  { id: 231, en: "the worst", ar: "الأسوأ", pronounce: "ذَ وِرسْت", ex_en: "He is the worst", ar_ex: "هو الأسوأ" },
  { id: 232, en: "interesting", ar: "ممتع", pronounce: "إِنترِسْتِنغ", ex_en: "That is interesting book", ar_ex: "ذلك كتاب ممتع" },
  { id: 233, en: "month", ar: "شهر", pronounce: "مَنث", ex_en: "One month to go", ar_ex: "شهر واحد للذهاب" },
  { id: 234, en: "another", ar: "آخر", pronounce: "أَنَذَر", ex_en: "Give me another one", ar_ex: "أعطني واحداً آخر" },
  { id: 235, en: "pyramid", ar: "هرم", pronounce: "پيرَمِد", ex_en: "The pyramid is tall", ar_ex: "الهرم طويل" },
  { id: 236, en: "Beirut", ar: "بيروت", pronounce: "بَيْروت", ex_en: "Beirut is very nice", ar_ex: "بيروت لطيفة جداً" },
  { id: 237, en: "Jericho", ar: "أريحا", pronounce: "جِرِيكو", ex_en: "Jericho is very old", ar_ex: "أريحا قديمة جداً" },
  { id: 238, en: "Damascus", ar: "دمشق", pronounce: "دِماسْكَس", ex_en: "Damascus is a city", ar_ex: "دمشق مدينة" },
  { id: 239, en: "Aswan", ar: "أسوان", pronounce: "أَسوان", ex_en: "Aswan is in Egypt", ar_ex: "أسوان في مصر" },
  { id: 240, en: "Saudi Arabia", ar: "السعودية", pronounce: "ساودي أَرِيبيا", ex_en: "Saudi Arabia is big", ar_ex: "السعودية كبيرة" },
  { id: 241, en: "Iraq", ar: "العراق", pronounce: "إيراك", ex_en: "Iraq is a country", ar_ex: "العراق دولة" },
  { id: 242, en: "River Nile", ar: "نهر النيل", pronounce: "رِڤَر نايل", ex_en: "The Nile is long", ar_ex: "النيل طويل" },
  { id: 243, en: "Syria", ar: "سوريا", pronounce: "سِيرْيا", ex_en: "Syria is a country", ar_ex: "سوريا دولة" },
  { id: 244, en: "Great Wall", ar: "سور الصين", pronounce: "غريت وول", ex_en: "The wall is long", ar_ex: "السور طويل" },
  { id: 245, en: "Solomon’s Pools", ar: "برك سليمان", pronounce: "سُولومَنز بولز", ex_en: "Visit Solomon's Pools", ar_ex: "زر برك سليمان" },
  { id: 246, en: "visit", ar: "يزور", pronounce: "ڤِزِت", ex_en: "Visit your family now", ar_ex: "زر عائلتك الآن" },
  { id: 247, en: "fall", ar: "يسقط", pronounce: "فول", ex_en: "Don't fall down here", ar_ex: "لا تسقط هنا" },
  { id: 248, en: "sail", ar: "يبحر", pronounce: "سَيْل", ex_en: "Sail in the sea", ar_ex: "أبحر في البحر" },
  { id: 249, en: "top", ar: "قمة", pronounce: "توب", ex_en: "At the top now", ar_ex: "في القمة الآن" },
  { id: 250, en: "travel", ar: "يسافر", pronounce: "تْرَافِل", ex_en: "I love to travel", ar_ex: "أحب السفر" },
  { id: 251, en: "climb", ar: "يتسلّق", pronounce: "كْلايم", ex_en: "Climb the tree now", ar_ex: "تسلق الشجرة الآن" },
  { id: 252, en: "crocodile", ar: "تمساح", pronounce: "كْروكودايل", ex_en: "The crocodile is big", ar_ex: "التمساح كبير" },
  { id: 253, en: "eagle", ar: "نسر", pronounce: "إيگُل", ex_en: "The eagle flies high", ar_ex: "النسر يطير عالياً" },
  { id: 254, en: "hyena", ar: "ضبع", pronounce: "هايينا", ex_en: "The hyena is wild", ar_ex: "الضبع متوحش" },
  { id: 255, en: "machine", ar: "آلة", pronounce: "مَشين", ex_en: "Fix the old machine", ar_ex: "أصلح الآلة القديمة" },
  { id: 256, en: "outer space", ar: "الفضاء الخارجي", pronounce: "آوتَر سْپيس", ex_en: "Travel to outer space", ar_ex: "سافر للفضاء الخارجي" },
  { id: 257, en: "outside", ar: "الخارج", pronounce: "آوتسايد", ex_en: "Go play outside now", ar_ex: "اذهب والعب بالخارج" },
  { id: 258, en: "prize", ar: "جائزة", pronounce: "برايز", ex_en: "Win a big prize", ar_ex: "اربح جائزة كبيرة" },
  { id: 259, en: "ticket", ar: "تذكرة", pronounce: "تِكِت", ex_en: "Buy a new ticket", ar_ex: "اشتر تذكرة جديدة" },
  { id: 260, en: "well done", ar: "أحسنت", pronounce: "وِل دان", ex_en: "Well done my friend", ar_ex: "أحسنت يا صديقي" },
  { id: 261, en: "roar", ar: "يزأر", pronounce: "رُور", ex_en: "The lion can roar", ar_ex: "الأسد يستطيع الزئير" },
  { id: 262, en: "get out", ar: "يخرج", pronounce: "گِت آوت", ex_en: "Get out of here", ar_ex: "اخرج من هنا" },
  { id: 263, en: "science lab", ar: "مختبر علوم", pronounce: "سايَنس لاب", ex_en: "Go to the lab", ar_ex: "اذهب للمختبر" },
  { id: 264, en: "lock", ar: "يُغلق", pronounce: "لوك", ex_en: "Lock the door now", ar_ex: "أغلق الباب الآن" },
  { id: 265, en: "high", ar: "عالٍ", pronounce: "هاي", ex_en: "Fly very high now", ar_ex: "طر عالياً جداً" },
  { id: 266, en: "low", ar: "منخفض", pronounce: "لو", ex_en: "The plane is low", ar_ex: "الطائرة منخفضة" },
  { id: 267, en: "hospital", ar: "مستشفى", pronounce: "هوسپِتَل", ex_en: "Go to the hospital", ar_ex: "اذهب للمستشفى" },
  { id: 268, en: "animal", ar: "حيوان", pronounce: "أَنِمَل", ex_en: "Love every animal here", ar_ex: "أحب كل حيوان هنا" },
  { id: 269, en: "singer", ar: "مغنّي", pronounce: "سِنغَر", ex_en: "He is good singer", ar_ex: "هو مغنٍ جيد" },
  { id: 270, en: "song", ar: "أغنية", pronounce: "سُونغ", ex_en: "Sing a nice song", ar_ex: "غنِّ أغنية جميلة" },
  { id: 271, en: "star", ar: "نجم", pronounce: "ستار", ex_en: "Look at the star", ar_ex: "انظر للنجم" },
  { id: 272, en: "movie", ar: "فيلم", pronounce: "موڤي", ex_en: "Watch a funny movie", ar_ex: "شاهد فيلماً مضحكاً" },
  { id: 273, en: "adventure", ar: "مغامرة", pronounce: "أَدڤِنْتْشَر", ex_en: "What a great adventure", ar_ex: "يا لها من مغامرة" },
  { id: 274, en: "backwards", ar: "للخلف", pronounce: "باكْوَردز", ex_en: "Walk backwards right now", ar_ex: "امشِ للخلف الآن" },
  { id: 275, en: "deep", ar: "عميق", pronounce: "ديپ", ex_en: "The sea is deep", ar_ex: "البحر عميق" },
  { id: 276, en: "frog", ar: "ضفدع", pronounce: "فروغ", ex_en: "The frog jumps high", ar_ex: "الضفدع يقفز عالياً" },
  { id: 277, en: "oar", ar: "مجداف", pronounce: "أور", ex_en: "Use the wooden oar", ar_ex: "استخدم المجداف الخشبي" },
  { id: 278, en: "octopus", ar: "أخطبوط", pronounce: "أُكْتُپَس", ex_en: "I saw an octopus", ar_ex: "رأيت أخطبوطاً" },
  { id: 279, en: "penguin", ar: "بطريق", pronounce: "پِنغْوِن", ex_en: "The penguin is cute", ar_ex: "البطريق لطيف" },
  { id: 280, en: "pineapple", ar: "أناناس", pronounce: "پاينابل", ex_en: "Eat fresh pineapple now", ar_ex: "كل أناناساً طازجاً" },
  { id: 281, en: "ostrich", ar: "نعامة", pronounce: "أُسْتْرِتش", ex_en: "The ostrich is tall", ar_ex: "النعامة طويلة" },
  { id: 282, en: "poster", ar: "ملصق", pronounce: "پوسْتَر", ex_en: "Hang the nice poster", ar_ex: "علق الملصق الجميل" },
  { id: 283, en: "row", ar: "يجدف", pronounce: "رو", ex_en: "Row the boat now", ar_ex: "جدف القارب الآن" },
  { id: 284, en: "shark", ar: "سمك القرش", pronounce: "شارك", ex_en: "The shark is scary", ar_ex: "القرش مخيف" },
  { id: 285, en: "whale", ar: "حوت", pronounce: "وِيل", ex_en: "The whale is big", ar_ex: "الحوت كبير" },
  { id: 286, en: "sweet", ar: "حلو", pronounce: "سْوِيت", ex_en: "This is sweet cake", ar_ex: "هذه كعكة حلوة" },
  { id: 287, en: "salty", ar: "مالح", pronounce: "سُولتي", ex_en: "The food is salty", ar_ex: "الطعام مالح" },
  { id: 288, en: "underwater", ar: "تحت الماء", pronounce: "أندر وُوتر", ex_en: "Live underwater for long", ar_ex: "عش تحت الماء طويلاً" },
  { id: 289, en: "of course", ar: "طبعًا", pronounce: "أُف كورس", ex_en: "Yes, of course, friend", ar_ex: "نعم، طبعاً يا صديقي" },
  { id: 290, en: "princess", ar: "أميرة", pronounce: "پرِنْسِس", ex_en: "She is a princess", ar_ex: "هي أميرة" },
  { id: 291, en: "marry", ar: "يتزوج", pronounce: "ماري", ex_en: "They will marry soon", ar_ex: "سيتزوجان قريباً" },
  { id: 292, en: "dowry", ar: "مهر", pronounce: "داوْري", ex_en: "The dowry is ready", ar_ex: "المهر جاهز" },
  { id: 293, en: "magic", ar: "سحر", pronounce: "ماجِك", ex_en: "It is magic trick", ar_ex: "إنها خدعة سحرية" },
  { id: 294, en: "mirror", ar: "مرآة", pronounce: "مِرَر", ex_en: "Look in the mirror", ar_ex: "انظر في المرآة" },
  { id: 295, en: "carpet", ar: "سجادة", pronounce: "كارپِت", ex_en: "Clean the small carpet", ar_ex: "نظف السجادة الصغيرة" },
  { id: 296, en: "palace", ar: "قصر", pronounce: "پالِس", ex_en: "Live in a palace", ar_ex: "عش في قصر" },
  { id: 297, en: "about", ar: "حوالي", pronounce: "أباوت", ex_en: "About ten come here", ar_ex: "حوالي عشرة أتوا هنا" },
  { id: 298, en: "apricot", ar: "مشمش", pronounce: "إيبريكوت", ex_en: "Eat some fresh apricot", ar_ex: "كل بعض المشمش" },
  { id: 299, en: "ask for", ar: "يطلب", pronounce: "آسك فور", ex_en: "Ask for your rights", ar_ex: "اطلب حقوقك" },
  { id: 300, en: "then", ar: "ثم", pronounce: "ذِن", ex_en: "Do this, then that", ar_ex: "افعل هذا، ثم ذاك" },
  { id: 301, en: "jelly", ar: "جيلي", pronounce: "جِلّي", ex_en: "I like cold jelly", ar_ex: "أحب الجيلي البارد" },
  { id: 302, en: "chips", ar: "بطاطا مقلية", pronounce: "تشِپس", ex_en: "Do you want chips?", ar_ex: "هل تريد بطاطا مقلية؟" },
  { id: 303, en: "popcorn", ar: "فشار", pronounce: "پوبكورن", ex_en: "Eat tasty popcorn now", ar_ex: "كل فشاراً لذيذاً الآن" },
  { id: 304, en: "lollipop", ar: "مصاصة", pronounce: "لوليبوب", ex_en: "Take the sweet lollipop", ar_ex: "خذ المصاصة الحلوة" },
  { id: 305, en: "neighborhood", ar: "حارة", pronounce: "نِيبرهود", ex_en: "Our neighborhood is quiet", ar_ex: "حارتنا هادئة" },
  { id: 306, en: "road", ar: "طريق", pronounce: "رود", ex_en: "Cross the road carefully", ar_ex: "اعبر الطريق بعناية" },
  { id: 307, en: "street", ar: "شارع", pronounce: "ستريت", ex_en: "Clean our long street", ar_ex: "نظف شارعنا الطويل" },
  { id: 308, en: "address", ar: "عنوان", pronounce: "أدرِس", ex_en: "Give me your address", ar_ex: "أعطني عنوانك" },
  { id: 309, en: "address book", ar: "دفتر عناوين", pronounce: "أدرِس بوك", ex_en: "Use the address book", ar_ex: "استخدم دفتر العناوين" },
  { id: 310, en: "borrow", ar: "يستعير", pronounce: "بورو", ex_en: "Borrow a new book", ar_ex: "استعر كتاباً جديداً" },
  { id: 311, en: "CD", ar: "قرص مدمج", pronounce: "سي دي", ex_en: "Put the CD here", ar_ex: "ضع القرص هنا" },
  { id: 312, en: "Cassette", ar: "شريط", pronounce: "كاسِت", ex_en: "Use the old cassette", ar_ex: "استخدم الشريط القديم" },
  { id: 313, en: "CD-ROM", ar: "قرص مدمج", pronounce: "سي دي روم", ex_en: "Open the CD-ROM", ar_ex: "افتح القرص المدمج" },
  { id: 314, en: "tell", ar: "يخبر", pronounce: "تِل", ex_en: "Tell me the truth", ar_ex: "أخبرني الحقيقة" },
  { id: 315, en: "call", ar: "يتصل", pronounce: "كول", ex_en: "Call me tonight please", ar_ex: "اتصل بي الليلة" },
  { id: 316, en: "police", ar: "شرطة", pronounce: "پوليس", ex_en: "Call the police now", ar_ex: "اتصل بالشرطة الآن" },
  { id: 317, en: "hungry", ar: "جائع", pronounce: "هَنگري", ex_en: "I am very hungry", ar_ex: "أنا جائع جداً" },
  { id: 318, en: "ill", ar: "مريض", pronounce: "إِل", ex_en: "He is ill today", ar_ex: "هو مريض اليوم" },
  { id: 319, en: "tired", ar: "متعب", pronounce: "تايِرد", ex_en: "I am really tired", ar_ex: "أنا متعب حقاً" },
  { id: 320, en: "rescue", ar: "ينقذ", pronounce: "رِسكيو", ex_en: "Please rescue him now", ar_ex: "أرجوك أنقذه الآن" },
  { id: 321, en: "diver", ar: "غواص", pronounce: "دايڤَر", ex_en: "The diver is brave", ar_ex: "الغواص شجاع" },
  { id: 322, en: "happen", ar: "يحدث", pronounce: "هابِن", ex_en: "What did happen here?", ar_ex: "ماذا حدث هنا؟" },
  { id: 323, en: "arrow", ar: "سهم", pronounce: "أرو", ex_en: "Use the sharp arrow", ar_ex: "استخدم السهم الحاد" },
  { id: 324, en: "competition", ar: "منافسة", pronounce: "كومپِتِشَن", ex_en: "Win this big competition", ar_ex: "اربح هذه المنافسة" },
  { id: 325, en: "discuss", ar: "يناقش", pronounce: "دِسكَس", ex_en: "Discuss it with him", ar_ex: "ناقش الأمر معه" },
  { id: 326, en: "correctly", ar: "بشكل صحيح", pronounce: "كُرِكتلي", ex_en: "Answer it correctly now", ar_ex: "أجب بشكل صحيح" },
  { id: 327, en: "afraid", ar: "خائف", pronounce: "أَفْريد", ex_en: "Don't be afraid here", ar_ex: "لا تكن خائفاً هنا" },
  { id: 328, en: "plate", ar: "طبق", pronounce: "پْلايت", ex_en: "Wash the dirty plate", ar_ex: "اغسل الطبق المتسخ" },
  { id: 329, en: "ring", ar: "يرنّ", pronounce: "رِنغ", ex_en: "Let the phone ring", ar_ex: "دع الهاتف يرن" },
  { id: 330, en: "drive", ar: "يقود", pronounce: "درايف", ex_en: "Drive the car well", ar_ex: "قد السيارة جيداً" },
  { id: 331, en: "drop", ar: "يسقط", pronounce: "دروب", ex_en: "Don't drop your pen", ar_ex: "لا تسقط قلمك" },
  { id: 332, en: "leave", ar: "يغادر", pronounce: "ليف", ex_en: "Leave the house now", ar_ex: "غادر المنزل الآن" },
  { id: 333, en: "arrive", ar: "يصل", pronounce: "أرايف", ex_en: "When do you arrive?", ar_ex: "متى تصل؟" },
  { id: 334, en: "ask", ar: "يسأل", pronounce: "آسك", ex_en: "Ask me anything now", ar_ex: "اسألني أي شيء" },
  { id: 335, en: "wheel", ar: "عجلة", pronounce: "وِيل", ex_en: "The car wheel broke", ar_ex: "عجلة السيارة انكسرت" },
  { id: 336, en: "look like", ar: "يشبه", pronounce: "لوك لايك", ex_en: "You look like dad", ar_ex: "أنت تشبه أبي" },
  { id: 337, en: "use", ar: "يستعمل", pronounce: "يوز", ex_en: "Use the new tool", ar_ex: "استعمل الأداة الجديدة" },
  { id: 338, en: "busy", ar: "مشغول", pronounce: "بِزي", ex_en: "I am very busy", ar_ex: "أنا مشغول جداً" },
  { id: 339, en: "float", ar: "يطفو", pronounce: "فْلوت", ex_en: "Watch the wood float", ar_ex: "راقب الخشب يطفو" },
  { id: 340, en: "hear", ar: "يسمع", pronounce: "هير", ex_en: "Can you hear me?", ar_ex: "هل تستطيع سماعي؟" },
  { id: 341, en: "wedding", ar: "عرس", pronounce: "وِدِنغ", ex_en: "Go to the wedding", ar_ex: "اذهب للعرس" },
  { id: 342, en: "robot", ar: "إنسان آلي", pronounce: "روبوت", ex_en: "This is a robot", ar_ex: "هذا إنسان آلي" },
  { id: 343, en: "next", ar: "القادم", pronounce: "نِكست", ex_en: "See you next week", ar_ex: "أراك الأسبوع القادم" },
  { id: 344, en: "mouse", ar: "فأر", pronounce: "ماوس", ex_en: "The mouse is fast", ar_ex: "الفأر سريع" },
  { id: 345, en: "ox", ar: "ثور", pronounce: "أُكس", ex_en: "The ox is strong", ar_ex: "الثور قوي" },
  { id: 346, en: "advice", ar: "نصيحة", pronounce: "أَدڤايس", ex_en: "Follow my good advice", ar_ex: "اتبع نصيحتي الجيدة" },
  { id: 347, en: "burger", ar: "برغر", pronounce: "بُرغَر", ex_en: "I like the burger", ar_ex: "أنا أحب البرغر" },
  { id: 348, en: "fizzy drink", ar: "مشروب غازي", pronounce: "فِزي دْرِنك", ex_en: "Avoid the fizzy drink", ar_ex: "تجنب المشروب الغازي" },
  { id: 349, en: "food pyramid", ar: "الهرم الغذائي", pronounce: "فود پيرامِد", ex_en: "Study the food pyramid", ar_ex: "ادرس الهرم الغذائي" },
  { id: 350, en: "fried", ar: "مقلي", pronounce: "فْرايد", ex_en: "I love fried fish", ar_ex: "أحب السمك المقلي" },
  { id: 351, en: "garlic", ar: "ثوم", pronounce: "غارلِك", ex_en: "Use some good garlic", ar_ex: "استخدم بعض الثوم" },
  { id: 352, en: "pepper", ar: "فلفل", pronounce: "پِپَر", ex_en: "The pepper is hot", ar_ex: "الفلفل حار" },
  { id: 353, en: "salt", ar: "ملح", pronounce: "سُولت", ex_en: "Add some salt now", ar_ex: "أضف بعض الملح" },
  { id: 354, en: "fire", ar: "نار", pronounce: "فاير", ex_en: "Don't touch the fire", ar_ex: "لا تلمس النار" },
  { id: 355, en: "grass", ar: "عشب", pronounce: "غراس", ex_en: "Sit on the grass", ar_ex: "اجلس على العشب" },
  { id: 356, en: "sign", ar: "إشارة", pronounce: "ساين", ex_en: "Look at the sign", ar_ex: "انظر للإشارة" },
  { id: 357, en: "stone", ar: "حجر", pronounce: "ستون", ex_en: "Throw the small stone", ar_ex: "ارمِ الحجر الصغير" },
  { id: 358, en: "bottom", ar: "قاع", pronounce: "بوتَم", ex_en: "Look at the bottom", ar_ex: "انظر للقاع" },
  { id: 359, en: "north", ar: "شمال", pronounce: "نورث", ex_en: "Go to the north", ar_ex: "اذهب للشمال" },
  { id: 360, en: "top", ar: "قمة", pronounce: "توب", ex_en: "Reach the top now", ar_ex: "صل للقمة الآن" }
];