const levelCLASS8_Words = [
  { "id": 1, "en": "adult", "ar": "بالغ", "pronounce": "أَدَلْت", "ex_en": "He is an adult now.", "ar_ex": "إنه شخص بالغ الآن." },
  { "id": 2, "en": "age", "ar": "عمر", "pronounce": "إيج", "ex_en": "What is your age?", "ar_ex": "كم عمرك؟" },
  { "id": 3, "en": "alone", "ar": "وحيد", "pronounce": "أَلون", "ex_en": "He lives alone here.", "ar_ex": "هو يعيش وحيداً هنا." },
  { "id": 4, "en": "Arab", "ar": "عربي", "pronounce": "آرَب", "ex_en": "They are Arab people.", "ar_ex": "هم أشخاص عرب." },
  { "id": 5, "en": "at first", "ar": "في البداية", "pronounce": "آت فِرست", "ex_en": "At first, I was shy.", "ar_ex": "في البداية، كنت خجولاً." },
  { "id": 6, "en": "at the moment", "ar": "في الوقت الحالي", "pronounce": "آت ذَ مومِنت", "ex_en": "I am busy now.", "ar_ex": "أنا مشغول في الوقت الحالي." },
  { "id": 7, "en": "Australia", "ar": "أستراليا", "pronounce": "أُسترَيْليا", "ex_en": "I want to visit Australia.", "ar_ex": "أريد زيارة أستراليا." },
  { "id": 8, "en": "awake", "ar": "مستيقظ", "pronounce": "أويك", "ex_en": "Are you still awake?", "ar_ex": "هل ما زلت مستيقظاً؟" },
  { "id": 9, "en": "Brazilian", "ar": "برازيلي", "pronounce": "برازيلْيَن", "ex_en": "My friend is Brazilian.", "ar_ex": "صديقي برازيلي." },
  { "id": 10, "en": "campsite", "ar": "موقع تخييم", "pronounce": "كامبسايت", "ex_en": "The campsite is clean.", "ar_ex": "موقع التخييم نظيف." },
  { "id": 11, "en": "classical", "ar": "كلاسيكي", "pronounce": "كْلاسِكَل", "ex_en": "I love classical music.", "ar_ex": "أحب الموسيقى الكلاسيكية." },
  { "id": 12, "en": "club", "ar": "نادٍ", "pronounce": "كلَب", "ex_en": "He goes to the club.", "ar_ex": "هو يذهب إلى النادي." },
  { "id": 13, "en": "coach", "ar": "مدرب", "pronounce": "كوتش", "ex_en": "The coach is very kind.", "ar_ex": "المدرب لطيف جداً." },
  { "id": 14, "en": "coat", "ar": "معطف", "pronounce": "كوت", "ex_en": "Wear your warm coat.", "ar_ex": "ارتدِ معطفك الدافئ." },
  { "id": 15, "en": "compete", "ar": "ينافس", "pronounce": "كُمْپِيت", "ex_en": "They will compete today.", "ar_ex": "سوف يتنافسون اليوم." },
  { "id": 16, "en": "completely", "ar": "تمامًا", "pronounce": "كُمْپْليتلي", "ex_en": "I am completely ready.", "ar_ex": "أنا جاهز تماماً." },
  { "id": 17, "en": "culture", "ar": "ثقافة", "pronounce": "كَلْتشر", "ex_en": "I like Arab culture.", "ar_ex": "أحب الثقافة العربية." },
  { "id": 18, "en": "cut down", "ar": "يقطع", "pronounce": "كَت داون", "ex_en": "Do not cut down trees.", "ar_ex": "لا تقطع الأشجار." },
  { "id": 19, "en": "damage", "ar": "ضرر", "pronounce": "دامِج", "ex_en": "It caused much damage.", "ar_ex": "لقد تسبب بضرر كبير." },
  { "id": 20, "en": "danger", "ar": "خطر", "pronounce": "دينجَر", "ex_en": "You are in danger.", "ar_ex": "أنت في خطر." },
  { "id": 21, "en": "develop", "ar": "يطوّر", "pronounce": "دِڤِلُپ", "ex_en": "We must develop skills.", "ar_ex": "يجب أن نطور مهاراتنا." },
  { "id": 22, "en": "dislike", "ar": "يكره", "pronounce": "دِسلايك", "ex_en": "I dislike hot weather.", "ar_ex": "أنا أكره الطقس الحار." },
  { "id": 23, "en": "documentary", "ar": "فيلم وثائقي", "pronounce": "دُكْيُومِنْتَري", "ex_en": "I watched a documentary.", "ar_ex": "شاهدت فيلماً وثائقياً." },
  { "id": 24, "en": "dollar", "ar": "دولار", "pronounce": "دُولَر", "ex_en": "It costs one dollar.", "ar_ex": "إنه يكلف دولاراً واحداً." },
  { "id": 25, "en": "each", "ar": "كلّ", "pronounce": "إيتش", "ex_en": "Each student has books.", "ar_ex": "كل طالب لديه كتب." },
  { "id": 26, "en": "either", "ar": "أيضًا / أيّهما", "pronounce": "إيذَر", "ex_en": "Either way is fine.", "ar_ex": "أي منهما جيد." },
  { "id": 27, "en": "embarrassed", "ar": "محرج", "pronounce": "إمبارَسْت", "ex_en": "I felt very embarrassed.", "ar_ex": "شعرت بالحرج الشديد." },
  { "id": 28, "en": "entrance", "ar": "مدخل", "pronounce": "إِنترَنس", "ex_en": "Meet at the entrance.", "ar_ex": "قابلني عند المدخل." },
  { "id": 29, "en": "thing", "ar": "شيء", "pronounce": "ثِنغ", "ex_en": "That is a good thing.", "ar_ex": "هذا شيء جيد." },
  { "id": 30, "en": "everything", "ar": "كل شيء", "pronounce": "إيفريثِنغ", "ex_en": "Everything is ready now.", "ar_ex": "كل شيء جاهز الآن." },
  { "id": 31, "en": "everywhere", "ar": "في كل مكان", "pronounce": "إيفري وِير", "ex_en": "Flowers are everywhere here.", "ar_ex": "الزهور في كل مكان." },
  { "id": 32, "en": "exercise", "ar": "تمرين", "pronounce": "إكْسِرسايز", "ex_en": "Do your daily exercise.", "ar_ex": "قم بتمرينك اليومي." },
  { "id": 33, "en": "family", "ar": "عائلة", "pronounce": "فامِلي", "ex_en": "I love my family.", "ar_ex": "أنا أحب عائلتي." },
  { "id": 34, "en": "far", "ar": "بعيد", "pronounce": "فار", "ex_en": "It is not too far.", "ar_ex": "إنه ليس بعيداً جداً." },
  { "id": 35, "en": "feel like", "ar": "يشعر بـ", "pronounce": "فيل لايك", "ex_en": "I feel like eating.", "ar_ex": "أشعر برغبة في الأكل." },
  { "id": 36, "en": "feeling", "ar": "شعور", "pronounce": "فيلِنغ", "ex_en": "It is a happy feeling.", "ar_ex": "إنه شعور سعيد." },
  { "id": 37, "en": "fit", "ar": "مناسب", "pronounce": "فِت", "ex_en": "The shoes fit well.", "ar_ex": "الحذاء مناسب تماماً." },
  { "id": 38, "en": "folk song", "ar": "أغنية شعبية", "pronounce": "فوك سونغ", "ex_en": "I like this folk song.", "ar_ex": "أحب هذه الأغنية الشعبية." },
  { "id": 39, "en": "for example", "ar": "على سبيل المثال", "pronounce": "فور إكزامپُل", "ex_en": "Read, for example, books.", "ar_ex": "اقرأ، على سبيل المثال، كتباً." },
  { "id": 40, "en": "forecast", "ar": "توقعات", "pronounce": "فوركاست", "ex_en": "Check the weather forecast.", "ar_ex": "تحقق من توقعات الطقس." },
  { "id": 41, "en": "go camping", "ar": "يذهب للتخييم", "pronounce": "غو كامپِنغ", "ex_en": "Let us go camping.", "ar_ex": "هيا نذهب للتخييم." },
  { "id": 42, "en": "go fishing", "ar": "يذهب للصيد", "pronounce": "غو فِشِنغ", "ex_en": "We go fishing weekly.", "ar_ex": "نذهب للصيد أسبوعياً." },
  { "id": 43, "en": "go hiking", "ar": "يذهب للتنزه", "pronounce": "غو هايكِنغ", "ex_en": "They like to go hiking.", "ar_ex": "هم يحبون الذهاب للتنزه." },
  { "id": 44, "en": "however", "ar": "لكن / مع ذلك", "pronounce": "هاوإڤَر", "ex_en": "It is late, however.", "ar_ex": "الوقت متأخر، مع ذلك." },
  { "id": 45, "en": "go online", "ar": "يتصل بالإنترنت", "pronounce": "غو أونلاين", "ex_en": "I must go online.", "ar_ex": "يجب أن أتصل بالإنترنت." },
  { "id": 46, "en": "secret", "ar": "سر", "pronounce": "سيكرت", "ex_en": "Keep my small secret.", "ar_ex": "احتفظ بسري الصغير." },
  { "id": 47, "en": "seem", "ar": "يبدو", "pronounce": "سيم", "ex_en": "You seem very happy.", "ar_ex": "أنت تبدو سعيداً جداً." },
  { "id": 48, "en": "serious", "ar": "جدي", "pronounce": "سِيرْيَس", "ex_en": "He is a serious man.", "ar_ex": "إنه رجل جدي." },
  { "id": 49, "en": "singer", "ar": "مغنٍ", "pronounce": "سِنغَر", "ex_en": "She is a good singer.", "ar_ex": "هي مغنية جيدة." },
  { "id": 50, "en": "situation", "ar": "موقف", "pronounce": "سِتْشُوَيْشَن", "ex_en": "This is a bad situation.", "ar_ex": "هذا موقف سيء." },
  { "id": 51, "en": "soccer", "ar": "كرة القدم", "pronounce": "سوكَر", "ex_en": "I love playing soccer.", "ar_ex": "أحب لعب كرة القدم." },
  { "id": 52, "en": "something", "ar": "شيء ما", "pronounce": "سَمْثِنغ", "ex_en": "I need something here.", "ar_ex": "أحتاج لشيء ما هنا." },
  { "id": 53, "en": "somewhere", "ar": "مكان ما", "pronounce": "سَمْوِير", "ex_en": "Go somewhere quiet now.", "ar_ex": "اذهب لمكان هادئ الآن." },
  { "id": 54, "en": "song", "ar": "أغنية", "pronounce": "سونغ", "ex_en": "Listen to this song.", "ar_ex": "استمع لهذه الأغنية." },
  { "id": 55, "en": "sound", "ar": "يبدو", "pronounce": "ساوند", "ex_en": "That sounds very good.", "ar_ex": "هذا يبدو جيداً جداً." },
  { "id": 56, "en": "speed", "ar": "سرعة", "pronounce": "سبيد", "ex_en": "He drives with speed.", "ar_ex": "هو يقود بسرعة." },
  { "id": 57, "en": "sports bag", "ar": "حقيبة رياضية", "pronounce": "سبورتس باغ", "ex_en": "Put items in bag.", "ar_ex": "ضع الأغراض في الحقيبة." },
  { "id": 58, "en": "study", "ar": "يدرس", "pronounce": "سْتَدي", "ex_en": "I study for exams.", "ar_ex": "أنا أدرس للامتحانات." },
  { "id": 59, "en": "support", "ar": "يدعم", "pronounce": "سَبّورت", "ex_en": "Please support my work.", "ar_ex": "من فضلك ادعم عملي." },
  { "id": 60, "en": "taste", "ar": "يتذوق", "pronounce": "تيست", "ex_en": "I want to taste it.", "ar_ex": "أريد أن أتذوقه." },
  { "id": 61, "en": "test", "ar": "اختبار", "pronounce": "تيست", "ex_en": "Study for the test.", "ar_ex": "ادرس للاختبار." },
  { "id": 62, "en": "the heart of", "ar": "قلب", "pronounce": "ذَ هارت أُف", "ex_en": "In the heart of city.", "ar_ex": "في قلب المدينة." },
  { "id": 63, "en": "training", "ar": "تدريب", "pronounce": "ترينِنغ", "ex_en": "I need more training.", "ar_ex": "أحتاج للمزيد من التدريب." },
  { "id": 64, "en": "trip", "ar": "رحلة", "pronounce": "تْرِپ", "ex_en": "The trip was amazing.", "ar_ex": "الرحلة كانت مذهلة." },
  { "id": 65, "en": "trust", "ar": "يثق", "pronounce": "تْرَست", "ex_en": "I trust my friends.", "ar_ex": "أنا أثق بأصدقائي." },
  { "id": 66, "en": "try (experiment)", "ar": "يجرّب", "pronounce": "تراي", "ex_en": "Try this new food.", "ar_ex": "جرب هذا الطعام الجديد." },
  { "id": 67, "en": "tub", "ar": "حوض", "pronounce": "تَب", "ex_en": "The tub is full.", "ar_ex": "الحوض ممتلئ." },
  { "id": 68, "en": "unhealthy", "ar": "غير صحي", "pronounce": "أَنْهِلثي", "ex_en": "Do not eat unhealthy food.", "ar_ex": "لا تأكل طعاماً غير صحي." },
  { "id": 69, "en": "used to", "ar": "اعتاد على", "pronounce": "يُوز تو", "ex_en": "I used to run.", "ar_ex": "أنا اعتدت على الجري." },
  { "id": 70, "en": "volunteer", "ar": "متطوع", "pronounce": "ڤولَنتير", "ex_en": "He is a great volunteer.", "ar_ex": "إنه متطوع رائع." },
  { "id": 71, "en": "wake up", "ar": "يستيقظ", "pronounce": "ويك أپ", "ex_en": "I wake up early.", "ar_ex": "أنا أستيقظ باكراً." },
  { "id": 72, "en": "waterfall", "ar": "شلال", "pronounce": "وُوترفول", "ex_en": "The waterfall is tall.", "ar_ex": "الشلال طويل." },
  { "id": 73, "en": "weight", "ar": "وزن", "pronounce": "ويت", "ex_en": "Watch your body weight.", "ar_ex": "راقب وزن جسمك." },
  { "id": 74, "en": "wildlife", "ar": "الحياة البرية", "pronounce": "وايلدلايف", "ex_en": "Protect the local wildlife.", "ar_ex": "احمِ الحياة البرية المحلية." },
  { "id": 75, "en": "worried", "ar": "قلق", "pronounce": "وُرِيد", "ex_en": "Why are you worried?", "ar_ex": "لماذا أنت قلق؟" },
  { "id": 76, "en": "gap", "ar": "فجوة", "pronounce": "گاب", "ex_en": "Fill in the gap.", "ar_ex": "املأ الفجوة." },
  { "id": 77, "en": "paragraph", "ar": "فقرة", "pronounce": "پاراغراف", "ex_en": "Read this long paragraph.", "ar_ex": "اقرأ هذه الفقرة الطويلة." },
  { "id": 78, "en": "topic", "ar": "موضوع", "pronounce": "توبيك", "ex_en": "Choose a new topic.", "ar_ex": "اختر موضوعاً جديداً." },
  { "id": 79, "en": "place", "ar": "مكان", "pronounce": "پْلايس", "ex_en": "This is a quiet place.", "ar_ex": "هذا مكان هادئ." },
  { "id": 80, "en": "ancestor", "ar": "سَلَف", "pronounce": "آنسِستَر", "ex_en": "He is my noble ancestor.", "ar_ex": "إنه سلفي النبيل." },
  { "id": 81, "en": "architecture", "ar": "عمارة", "pronounce": "آركِتِكْتشَر", "ex_en": "The architecture is beautiful.", "ar_ex": "العمارة جميلة." },
  { "id": 82, "en": "area", "ar": "منطقة", "pronounce": "إيريا", "ex_en": "This is a large area.", "ar_ex": "هذه منطقة كبيرة." },
  { "id": 83, "en": "assistant", "ar": "مساعد", "pronounce": "أَسِسْتَنت", "ex_en": "He is my personal assistant.", "ar_ex": "إنه مساعدي الشخصي." },
  { "id": 84, "en": "backpack", "ar": "حقيبة ظهر", "pronounce": "باكباك", "ex_en": "Where is my blue backpack?", "ar_ex": "أين حقيبة ظهري الزرقاء؟" },
  { "id": 85, "en": "beard", "ar": "لحية", "pronounce": "بيرد", "ex_en": "He has a long beard.", "ar_ex": "هو لديه لحية طويلة." },
  { "id": 86, "en": "begin", "ar": "يبدأ", "pronounce": "بِگِن", "ex_en": "The class will begin now.", "ar_ex": "الصف سيبدأ الآن." },
  { "id": 87, "en": "bride", "ar": "عروس", "pronounce": "برايد", "ex_en": "The bride looks lovely.", "ar_ex": "العروس تبدو جميلة." },
  { "id": 88, "en": "carton", "ar": "كرتون", "pronounce": "كارتُن", "ex_en": "Open the milk carton.", "ar_ex": "افتح كرتونة الحليب." },
  { "id": 89, "en": "celebrate", "ar": "يحتفل", "pronounce": "سِلِبرِيت", "ex_en": "We celebrate our success.", "ar_ex": "نحن نحتفل بنجاحنا." },
  { "id": 90, "en": "centimetre", "ar": "سنتيمتر", "pronounce": "سِنْتِمِيتر", "ex_en": "It is one centimetre long.", "ar_ex": "طوله سنتيمتر واحد." },
  { "id": 91, "en": "Islamic", "ar": "إسلامي", "pronounce": "إسلامِك", "ex_en": "I study Islamic history.", "ar_ex": "أنا أدرس التاريخ الإسلامي." },
  { "id": 92, "en": "Italian", "ar": "إيطالي", "pronounce": "إِتاليَن", "ex_en": "He is an Italian man.", "ar_ex": "هو رجل إيطالي." },
  { "id": 93, "en": "Japan", "ar": "اليابان", "pronounce": "جَپان", "ex_en": "I want to visit Japan.", "ar_ex": "أريد زيارة اليابان." },
  { "id": 94, "en": "jar", "ar": "مرطبان", "pronounce": "جار", "ex_en": "Fill the glass jar.", "ar_ex": "املأ المرطبان الزجاجي." },
  { "id": 95, "en": "just", "ar": "تمامًا", "pronounce": "جَست", "ex_en": "It is just perfect.", "ar_ex": "إنه مثالي تماماً." },
  { "id": 96, "en": "land", "ar": "أرض", "pronounce": "لاند", "ex_en": "The land is very dry.", "ar_ex": "الأرض جافة جداً." },
  { "id": 97, "en": "uniform", "ar": "زيّ", "pronounce": "يُونيفورم", "ex_en": "Wear the school uniform.", "ar_ex": "ارتدِ الزي المدرسي." },
  { "id": 98, "en": "list", "ar": "قائمة", "pronounce": "لِست", "ex_en": "Write a shopping list.", "ar_ex": "اكتب قائمة تسوق." },
  { "id": 99, "en": "litre", "ar": "لتر", "pronounce": "ليتَر", "ex_en": "Need one litre water.", "ar_ex": "أحتاج لتراً من الماء." },
  { "id": 100, "en": "long ago", "ar": "منذ زمن", "pronounce": "لونغ أگو", "ex_en": "It happened long ago.", "ar_ex": "حدث ذلك منذ زمن." },
  { "id": 101, "en": "look up", "ar": "يبحث", "pronounce": "لوك أپ", "ex_en": "Look up this new word.", "ar_ex": "ابحث عن هذه الكلمة." },
  { "id": 102, "en": "lovely", "ar": "جميل", "pronounce": "لَڤلي", "ex_en": "You look lovely today.", "ar_ex": "تبدين جميلة اليوم." },
  { "id": 103, "en": "medical", "ar": "طبي", "pronounce": "مِدِكَل", "ex_en": "He needs medical help.", "ar_ex": "هو يحتاج مساعدة طبية." },
  { "id": 104, "en": "moustache", "ar": "شارب", "pronounce": "مُسْتاش", "ex_en": "He has a thick moustache.", "ar_ex": "لديه شارب سميك." },
  { "id": 105, "en": "of course", "ar": "طبعًا", "pronounce": "أُف كورس", "ex_en": "Yes, of course.", "ar_ex": "نعم، طبعاً." },
  { "id": 106, "en": "once", "ar": "مرة واحدة", "pronounce": "وُنس", "ex_en": "I go once daily.", "ar_ex": "أذهب مرة واحدة يومياً." },
  { "id": 107, "en": "operation", "ar": "عملية", "pronounce": "أوبِرَيْشَن", "ex_en": "The operation was successful.", "ar_ex": "العملية كانت ناجحة." },
  { "id": 108, "en": "personal details", "ar": "تفاصيل شخصية", "pronounce": "پِرسُنَل ديتيلز", "ex_en": "Write your personal details.", "ar_ex": "اكتب تفاصيلك الشخصية." },
  { "id": 109, "en": "pick up", "ar": "يلتقط", "pronounce": "پِك أپ", "ex_en": "Pick up your pen.", "ar_ex": "التقط قلمك." },
  { "id": 110, "en": "probably", "ar": "غالبًا", "pronounce": "پرُوبَبْلي", "ex_en": "I will probably go.", "ar_ex": "غالبًا سأذهب." },
  { "id": 111, "en": "produce", "ar": "ينتج", "pronounce": "پروديوس", "ex_en": "Farms produce good food.", "ar_ex": "المزارع تنتج طعاماً جيداً." },
  { "id": 112, "en": "purpose", "ar": "هدف", "pronounce": "پِرپَس", "ex_en": "What is your purpose?", "ar_ex": "ما هو هدفك؟" },
  { "id": 113, "en": "Scotland", "ar": "اسكتلندا", "pronounce": "سْكوتلَند", "ex_en": "I live in Scotland.", "ar_ex": "أنا أعيش في اسكتلندا." },
  { "id": 114, "en": "set up", "ar": "يؤسّس", "pronounce": "سِت أپ", "ex_en": "He will set up business.", "ar_ex": "هو سيؤسس عملاً تجارياً." },
  { "id": 115, "en": "shoe shop", "ar": "محل أحذية", "pronounce": "شو شوب", "ex_en": "Go to the shoe shop.", "ar_ex": "اذهب لمحل الأحذية." },
  { "id": 116, "en": "side", "ar": "جانب", "pronounce": "سايد", "ex_en": "Sit on my side.", "ar_ex": "اجلس بجانبي." },
  { "id": 117, "en": "size", "ar": "مقاس", "pronounce": "سايز", "ex_en": "What is your shoe size?", "ar_ex": "ما هو مقاس حذائك؟" },
  { "id": 118, "en": "smart", "ar": "أنيق", "pronounce": "سْمارْت", "ex_en": "You look smart today.", "ar_ex": "تبدو أنيقاً اليوم." },
  { "id": 119, "en": "son", "ar": "ابن", "pronounce": "سَن", "ex_en": "He is my only son.", "ar_ex": "إنه ابني الوحيد." },
  { "id": 120, "en": "spirit", "ar": "روح", "pronounce": "سْپيرِت", "ex_en": "She has good spirit.", "ar_ex": "لديها روح طيبة." },
  { "id": 121, "en": "sports shop", "ar": "محل رياضة", "pronounce": "سبورتس شوب", "ex_en": "Visit the sports shop.", "ar_ex": "زُر محل الرياضة." },
  { "id": 122, "en": "straight", "ar": "مستقيم", "pronounce": "سْتريت", "ex_en": "The road is straight.", "ar_ex": "الطريق مستقيم." },
  { "id": 123, "en": "student", "ar": "طالب", "pronounce": "سْتيودَنت", "ex_en": "I am a new student.", "ar_ex": "أنا طالب جديد." },
  { "id": 124, "en": "text message", "ar": "رسالة نصية", "pronounce": "تِكست", "ex_en": "Send a text message.", "ar_ex": "أرسل رسالة نصية." },
  { "id": 125, "en": "thick", "ar": "سميك", "pronounce": "ثِك", "ex_en": "The wall is thick.", "ar_ex": "الجدار سميك." },
  { "id": 126, "en": "tomato paste", "ar": "رب بندورة", "pronounce": "تُماتو پِست", "ex_en": "Add some tomato paste.", "ar_ex": "أضف بعض رب البندورة." },
  { "id": 127, "en": "tourism", "ar": "سياحة", "pronounce": "تُورِزم", "ex_en": "Tourism is very important.", "ar_ex": "السياحة مهمة جداً." },
  { "id": 128, "en": "tower", "ar": "برج", "pronounce": "تاوَر", "ex_en": "The tower is huge.", "ar_ex": "البرج ضخم." },
  { "id": 129, "en": "various", "ar": "متنوع", "pronounce": "ڤارِيَس", "ex_en": "We have various items.", "ar_ex": "لدينا أغراض متنوعة." },
  { "id": 130, "en": "wife", "ar": "زوجة", "pronounce": "وايف", "ex_en": "She is my wife.", "ar_ex": "هي زوجتي." },
  { "id": 131, "en": "writer", "ar": "كاتب", "pronounce": "رايتَر", "ex_en": "He is a famous writer.", "ar_ex": "إنه كاتب مشهور." },
  { "id": 132, "en": "tourist", "ar": "سائح", "pronounce": "تُورِست", "ex_en": "The tourist visited here.", "ar_ex": "السائح زار هذا المكان." },
  { "id": 133, "en": "come back", "ar": "يعود", "pronounce": "كَم باك", "ex_en": "Please come back soon.", "ar_ex": "من فضلك عُد قريباً." },
  { "id": 134, "en": "consider", "ar": "يعتبر", "pronounce": "كَنزِدَر", "ex_en": "I consider him friend.", "ar_ex": "أنا أعتبره صديقاً." },
  { "id": 135, "en": "decide", "ar": "يقرر", "pronounce": "دِسايد", "ex_en": "You must decide now.", "ar_ex": "يجب أن تقرر الآن." },
  { "id": 136, "en": "find out", "ar": "يكتشف", "pronounce": "فايند آوت", "ex_en": "I will find out.", "ar_ex": "سوف أكتشف الأمر." },
  { "id": 137, "en": "forget", "ar": "ينسى", "pronounce": "فُرغِت", "ex_en": "Do not forget me.", "ar_ex": "لا تنسني." },
  { "id": 138, "en": "hang", "ar": "يعلّق", "pronounce": "هانغ", "ex_en": "Hang the coat there.", "ar_ex": "علق المعطف هناك." },
  { "id": 139, "en": "intend", "ar": "ينوي", "pronounce": "إنتِند", "ex_en": "I intend to travel.", "ar_ex": "أنا أنوي السفر." },
  { "id": 140, "en": "introduce", "ar": "يقدّم", "pronounce": "إنترديوس", "ex_en": "Let me introduce you.", "ar_ex": "دعني أقدمك." },
  { "id": 141, "en": "keep", "ar": "يحتفظ", "pronounce": "كيب", "ex_en": "Keep it safe please.", "ar_ex": "احتفظ به آمناً من فضلك." },
  { "id": 142, "en": "make up", "ar": "يختلق", "pronounce": "ميك أپ", "ex_en": "Do not make up stories.", "ar_ex": "لا تختلق القصص." },
  { "id": 143, "en": "offer", "ar": "يعرض", "pronounce": "أوفَر", "ex_en": "They offer good help.", "ar_ex": "هم يعرضون مساعدة جيدة." },
  { "id": 144, "en": "order", "ar": "يطلب", "pronounce": "أوردر", "ex_en": "Order the food now.", "ar_ex": "اطلب الطعام الآن." },
  { "id": 145, "en": "pass on", "ar": "يمرّر", "pronounce": "پاس أون", "ex_en": "Pass on the ball.", "ar_ex": "مرر الكرة." },
  { "id": 146, "en": "protect", "ar": "يحمي", "pronounce": "پروتِكت", "ex_en": "We must protect earth.", "ar_ex": "يجب أن نحمي الأرض." },
  { "id": 147, "en": "raise", "ar": "يرفع", "pronounce": "ريز", "ex_en": "Raise your hand now.", "ar_ex": "ارفع يدك الآن." },
  { "id": 148, "en": "receive", "ar": "يستقبل", "pronounce": "رِسيف", "ex_en": "Did you receive mail?", "ar_ex": "هل استقبلت البريد؟" },
  { "id": 149, "en": "remain", "ar": "يبقى", "pronounce": "رِمِين", "ex_en": "Remain here for now.", "ar_ex": "ابقَ هنا حالياً." },
  { "id": 150, "en": "sell", "ar": "يبيع", "pronounce": "سِل", "ex_en": "They sell fresh bread.", "ar_ex": "هم يبيعون خبزاً طازجاً." },
  { "id": 151, "en": "spend", "ar": "ينفق", "pronounce": "سْپِند", "ex_en": "Do not spend money.", "ar_ex": "لا تنفق المال." },
  { "id": 152, "en": "start (up)", "ar": "يبدأ", "pronounce": "ستارت", "ex_en": "Let us start now.", "ar_ex": "هيا نبدأ الآن." },
  { "id": 153, "en": "stop", "ar": "يتوقف", "pronounce": "ستوب", "ex_en": "Please stop doing that.", "ar_ex": "من فضلك توقف عن ذلك." },
  { "id": 154, "en": "strengthen", "ar": "يقوّي", "pronounce": "سْترينغثِن", "ex_en": "Exercise will strengthen you.", "ar_ex": "التمرين سيقويك." },
  { "id": 155, "en": "think back", "ar": "يتذكر", "pronounce": "ثِنك باك", "ex_en": "Think back to then.", "ar_ex": "تذكر ذلك الوقت." },
  { "id": 156, "en": "turn", "ar": "ينعطف", "pronounce": "تِرن", "ex_en": "Turn left at road.", "ar_ex": "انعطف يساراً عند الطريق." },
  { "id": 157, "en": "wait", "ar": "ينتظر", "pronounce": "وِيت", "ex_en": "Please wait for me.", "ar_ex": "من فضلك انتظرني." },
  { "id": 158, "en": "worry", "ar": "يقلق", "pronounce": "وُري", "ex_en": "Do not worry please.", "ar_ex": "لا تقلق من فضلك." },
  { "id": 159, "en": "acceptable", "ar": "مقبول", "pronounce": "أَكْسِبتَبُل", "ex_en": "This is acceptable now.", "ar_ex": "هذا مقبول الآن." },
  { "id": 160, "en": "ancient", "ar": "قديم", "pronounce": "إينشَنت", "ex_en": "This is ancient art.", "ar_ex": "هذا فن قديم." },
  { "id": 161, "en": "delicious", "ar": "لذيذ", "pronounce": "دِلِشَس", "ex_en": "The food is delicious.", "ar_ex": "الطعام لذيذ." },
  { "id": 162, "en": "empty", "ar": "فارغ", "pronounce": "إمبتي", "ex_en": "The cup is empty.", "ar_ex": "الكوب فارغ." },
  { "id": 163, "en": "huge", "ar": "ضخم", "pronounce": "هيوج", "ex_en": "The whale is huge.", "ar_ex": "الحوت ضخم." },
  { "id": 164, "en": "large", "ar": "كبير", "pronounce": "لارج", "ex_en": "He has large eyes.", "ar_ex": "هو لديه عينان كبيرتان." },
  { "id": 165, "en": "modern", "ar": "حديث", "pronounce": "مودَرن", "ex_en": "I like modern house.", "ar_ex": "أحب المنزل الحديث." },
  { "id": 166, "en": "narrow", "ar": "ضيق", "pronounce": "نارُو", "ex_en": "The street is narrow.", "ar_ex": "الشارع ضيق." },
  { "id": 167, "en": "normal", "ar": "عادي", "pronounce": "نورمَل", "ex_en": "This is normal day.", "ar_ex": "هذا يوم عادي." },
  { "id": 168, "en": "polite / impolite", "ar": "مؤدب / غير مؤدب", "pronounce": "پولايت", "ex_en": "Always be polite.", "ar_ex": "كن مؤدباً دائماً." },
  { "id": 169, "en": "pregnant", "ar": "حامل", "pronounce": "پْرِغنَنت", "ex_en": "She is pregnant now.", "ar_ex": "هي حامل الآن." },
  { "id": 170, "en": "soft", "ar": "ناعم", "pronounce": "سوفت", "ex_en": "The pillow is soft.", "ar_ex": "الوسادة ناعمة." },
  { "id": 171, "en": "tasty", "ar": "شهي", "pronounce": "تايستي", "ex_en": "The cake is tasty.", "ar_ex": "الكعكة شهية." },
  { "id": 172, "en": "tidy", "ar": "مرتب", "pronounce": "تايدي", "ex_en": "Keep your room tidy.", "ar_ex": "حافظ على غرفتك مرتبة." },
  { "id": 173, "en": "untidy", "ar": "غير مرتب", "pronounce": "أَنْتايدي", "ex_en": "Your desk is untidy.", "ar_ex": "مكتبك غير مرتب." },
  { "id": 174, "en": "ugly", "ar": "قبيح", "pronounce": "أَغلي", "ex_en": "Do not be ugly.", "ar_ex": "لا تكن قبيحاً." },
  { "id": 175, "en": "wonderful", "ar": "رائع", "pronounce": "وَندرفُل", "ex_en": "You are a wonderful friend.", "ar_ex": "أنت صديق رائع." },
  { "id": 176, "en": "although", "ar": "بالرغم من", "pronounce": "أولذو", "ex_en": "Although, I am tired.", "ar_ex": "بالرغم من أني متعب." },
  { "id": 177, "en": "finally", "ar": "أخيرًا", "pronounce": "فاينَلي", "ex_en": "Finally, I am home.", "ar_ex": "أخيراً، أنا في المنزل." },
  { "id": 178, "en": "white water rafting", "ar": "تجديف الأنهار", "pronounce": "وايت وُوتر رافتِنغ", "ex_en": "I love river rafting.", "ar_ex": "أحب تجديف الأنهار." },
  { "id": 179, "en": "guitar", "ar": "غيتار", "pronounce": "غِتار", "ex_en": "He plays the guitar.", "ar_ex": "هو يعزف على الغيتار." },
  { "id": 180, "en": "had better", "ar": "من الأفضل", "pronounce": "هاد بِتَر", "ex_en": "You had better go.", "ar_ex": "من الأفضل أن تذهب." },
  { "id": 181, "en": "hear", "ar": "يسمع", "pronounce": "هير", "ex_en": "Can you hear me?", "ar_ex": "هل تستطيع سماعي؟" },
  { "id": 182, "en": "distant", "ar": "بعيد", "pronounce": "دِسْتَنت", "ex_en": "It is a distant land.", "ar_ex": "إنها أرض بعيدة." },
  { "id": 183, "en": "horrible", "ar": "فظيع", "pronounce": "هُورِبُل", "ex_en": "What a horrible day.", "ar_ex": "يا له من يوم فظيع." },
  { "id": 184, "en": "hurricane", "ar": "إعصار", "pronounce": "هَرِيكين", "ex_en": "The hurricane was strong.", "ar_ex": "الإعصار كان قوياً." },
  { "id": 185, "en": "immediately", "ar": "فورًا", "pronounce": "إِمِيدْيَتْلي", "ex_en": "Come here immediately.", "ar_ex": "تعال هنا فوراً." },
  { "id": 186, "en": "in fact", "ar": "في الحقيقة", "pronounce": "إن فاكت", "ex_en": "In fact, I know.", "ar_ex": "في الحقيقة، أنا أعرف." },
  { "id": 187, "en": "in the end", "ar": "في النهاية", "pronounce": "إن ذَ إِند", "ex_en": "In the end, we win.", "ar_ex": "في النهاية، نحن نفوز." },
  { "id": 188, "en": "information", "ar": "معلومات", "pronounce": "إنفورميشن", "ex_en": "I need some information.", "ar_ex": "أحتاج لبعض المعلومات." },
  { "id": 189, "en": "instead", "ar": "بدلًا من", "pronounce": "إنستِد", "ex_en": "Go instead of him.", "ar_ex": "اذهب بدلاً منه." },
  { "id": 190, "en": "instrument", "ar": "أداة", "pronounce": "إنسترومِنت", "ex_en": "That is a musical instrument.", "ar_ex": "تلك أداة موسيقية." },
  { "id": 191, "en": "invent", "ar": "يخترع", "pronounce": "إنڤِنت", "ex_en": "Who did invent this?", "ar_ex": "من اخترع هذا؟" },
  { "id": 192, "en": "join", "ar": "ينضم", "pronounce": "جوين", "ex_en": "Will you join us?", "ar_ex": "هل ستنضم إلينا؟" },
  { "id": 193, "en": "junk food", "ar": "طعام غير صحي", "pronounce": "جانك فود", "ex_en": "Avoid eating junk food.", "ar_ex": "تجنب تناول الطعام السريع." },
  { "id": 194, "en": "just", "ar": "فقط", "pronounce": "جَست", "ex_en": "I need just one.", "ar_ex": "أحتاج واحدة فقط." },
  { "id": 195, "en": "kick", "ar": "يركل", "pronounce": "كِك", "ex_en": "Kick the ball hard.", "ar_ex": "اركل الكرة بقوة." },
  { "id": 196, "en": "kind", "ar": "نوع / لطيف", "pronounce": "كايند", "ex_en": "You are very kind.", "ar_ex": "أنت لطيف جداً." },
  { "id": 197, "en": "landline", "ar": "هاتف أرضي", "pronounce": "لاندلاين", "ex_en": "Call on the landline.", "ar_ex": "اتصل عبر الهاتف الأرضي." },
  { "id": 198, "en": "let’s", "ar": "هيا", "pronounce": "لِتس", "ex_en": "Let us study now.", "ar_ex": "هيا ندرس الآن." },
  { "id": 199, "en": "like (such as)", "ar": "مثل", "pronounce": "لايك", "ex_en": "Fruits like apple, pear.", "ar_ex": "فواكه مثل التفاح والكمثرى." },
  { "id": 200, "en": "Morocco", "ar": "المغرب", "pronounce": "مورُوكو", "ex_en": "I live in Morocco.", "ar_ex": "أنا أعيش في المغرب." },
  { "id": 201, "en": "musical", "ar": "موسيقي", "pronounce": "ميوزِكَل", "ex_en": "I have musical talent.", "ar_ex": "أنا لدي موهبة موسيقية." },
  { "id": 202, "en": "musician", "ar": "موسيقي", "pronounce": "ميوزِشَن", "ex_en": "He is a great musician.", "ar_ex": "إنه موسيقي عظيم." },
  { "id": 203, "en": "national", "ar": "وطني", "pronounce": "ناشنَل", "ex_en": "This is our national day.", "ar_ex": "هذا يومنا الوطني." },
  { "id": 204, "en": "nationality", "ar": "جنسية", "pronounce": "ناشنَالِتي", "ex_en": "What is your nationality?", "ar_ex": "ما هي جنسيتك؟" },
  { "id": 205, "en": "natural", "ar": "طبيعي", "pronounce": "ناتشْرَل", "ex_en": "This is a natural place.", "ar_ex": "هذا مكان طبيعي." },
  { "id": 206, "en": "on the phone", "ar": "على الهاتف", "pronounce": "أون ذَ فون", "ex_en": "Talk on the phone.", "ar_ex": "تحدث على الهاتف." },
  { "id": 207, "en": "online", "ar": "متصل بالإنترنت", "pronounce": "أونلاين", "ex_en": "Are you online now?", "ar_ex": "هل أنت متصل حالياً؟" },
  { "id": 208, "en": "pass (a football)", "ar": "يمرّر", "pronounce": "پاس", "ex_en": "Pass the ball now.", "ar_ex": "مرر الكرة الآن." },
  { "id": 209, "en": "pass (a place)", "ar": "يتجاوز", "pronounce": "پاس", "ex_en": "Pass the park slowly.", "ar_ex": "تجاوز الحديقة ببطء." },
  { "id": 210, "en": "pizza", "ar": "بيتزا", "pronounce": "پِيتسا", "ex_en": "I love eating pizza.", "ar_ex": "أحب أكل البيتزا." },
  { "id": 211, "en": "player", "ar": "لاعب", "pronounce": "بلايَر", "ex_en": "He is a good player.", "ar_ex": "إنه لاعب جيد." },
  { "id": 212, "en": "poem", "ar": "قصيدة", "pronounce": "پُوِم", "ex_en": "Read this nice poem.", "ar_ex": "اقرأ هذه القصيدة اللطيفة." },
  { "id": 213, "en": "practise", "ar": "يتدرّب", "pronounce": "پراكتِس", "ex_en": "Practise daily to win.", "ar_ex": "تدرب يومياً لتفوز." },
  { "id": 214, "en": "project", "ar": "مشروع", "pronounce": "پْروجِكت", "ex_en": "Finish your school project.", "ar_ex": "أنهِ مشروعك المدرسي." },
  { "id": 215, "en": "proud", "ar": "فخور", "pronounce": "پراود", "ex_en": "I am proud of you.", "ar_ex": "أنا فخور بك." },
  { "id": 216, "en": "quite", "ar": "جدًا", "pronounce": "كْوايت", "ex_en": "It is quite cold today.", "ar_ex": "إنه بارد جداً اليوم." },
  { "id": 217, "en": "real", "ar": "حقيقي", "pronounce": "رِيَل", "ex_en": "This is a real story.", "ar_ex": "هذه قصة حقيقية." },
  { "id": 218, "en": "really", "ar": "حقًا", "pronounce": "رِيلي", "ex_en": "I am really tired.", "ar_ex": "أنا حقاً متعب." },
  { "id": 219, "en": "recently", "ar": "مؤخرًا", "pronounce": "رِيسَنتلي", "ex_en": "I saw him recently.", "ar_ex": "رأيته مؤخراً." },
  { "id": 220, "en": "rock music", "ar": "موسيقى الروك", "pronounce": "روك ميوزك", "ex_en": "Do you like rock music?", "ar_ex": "هل تحب موسيقى الروك؟" },
  { "id": 221, "en": "rule", "ar": "قاعدة", "pronounce": "رول", "ex_en": "Follow the school rule.", "ar_ex": "اتبع القاعدة المدرسية." },
  { "id": 222, "en": "scared", "ar": "خائف", "pronounce": "سْكيرد", "ex_en": "Why are you scared?", "ar_ex": "لماذا أنت خائف؟" },
  { "id": 223, "en": "centre", "ar": "مركز", "pronounce": "سِنتر", "ex_en": "Meet at the city centre.", "ar_ex": "قابلني في مركز المدينة." },
  { "id": 224, "en": "check", "ar": "يفحص", "pronounce": "تشِك", "ex_en": "Check your answers again.", "ar_ex": "افحص إجاباتك مجدداً." },
  { "id": 225, "en": "climate", "ar": "مناخ", "pronounce": "كْلايمِت", "ex_en": "The climate is warm.", "ar_ex": "المناخ دافئ." },
  { "id": 226, "en": "clothes", "ar": "ملابس", "pronounce": "كْلوثز", "ex_en": "Buy new warm clothes.", "ar_ex": "اشترِ ملابس دافئة جديدة." },
  { "id": 227, "en": "coffee shop", "ar": "مقهى", "pronounce": "كوفي شوب", "ex_en": "Let us go to shop.", "ar_ex": "هيا نذهب للمقهى." },
  { "id": 228, "en": "comfortably", "ar": "براحة", "pronounce": "كَمفُرتَبْلي", "ex_en": "Sit down comfortably now.", "ar_ex": "اجلس براحة الآن." },
  { "id": 229, "en": "congratulations", "ar": "تهانينا", "pronounce": "كونغراتيوليشنز", "ex_en": "Congratulations on your success.", "ar_ex": "تهانينا على نجاحك." },
  { "id": 230, "en": "construct", "ar": "يبني", "pronounce": "كَنستْرَكت", "ex_en": "They construct new houses.", "ar_ex": "هم يبنون منازل جديدة." },
  { "id": 231, "en": "counsellor", "ar": "مرشد", "pronounce": "كاونسلَر", "ex_en": "Talk to your counsellor.", "ar_ex": "تحدث لمرشدك." },
  { "id": 232, "en": "crazy about", "ar": "مهووس بـ", "pronounce": "كْريزي أباوت", "ex_en": "I am crazy about music.", "ar_ex": "أنا مهووس بالموسيقى." },
  { "id": 233, "en": "crop", "ar": "محصول", "pronounce": "كْروب", "ex_en": "The crop is good.", "ar_ex": "المحصول جيد." },
  { "id": 234, "en": "curly", "ar": "مجعّد", "pronounce": "كيرلي", "ex_en": "She has curly hair.", "ar_ex": "هي لديها شعر مجعد." },
  { "id": 235, "en": "custom", "ar": "عادة", "pronounce": "كَسْتَم", "ex_en": "It is a local custom.", "ar_ex": "إنها عادة محلية." },
  { "id": 236, "en": "date of birth", "ar": "تاريخ الميلاد", "pronounce": "ديت أُف بِرث", "ex_en": "Write your date of birth.", "ar_ex": "اكتب تاريخ ميلادك." },
  { "id": 237, "en": "daughter", "ar": "ابنة", "pronounce": "دُوتر", "ex_en": "She is my daughter.", "ar_ex": "هي ابنتي." },
  { "id": 238, "en": "deep", "ar": "عميق", "pronounce": "ديپ", "ex_en": "The sea is deep.", "ar_ex": "البحر عميق." },
  { "id": 239, "en": "discuss", "ar": "يناقش", "pronounce": "دِسكَس", "ex_en": "Let us discuss it.", "ar_ex": "هيا نناقش الأمر." },
  { "id": 240, "en": "disease", "ar": "مرض", "pronounce": "دِزيز", "ex_en": "Avoid any serious disease.", "ar_ex": "تجنب أي مرض خطير." },
  { "id": 241, "en": "dough", "ar": "عجين", "pronounce": "دو", "ex_en": "Mix the bread dough.", "ar_ex": "اخلط عجين الخبز." },
  { "id": 242, "en": "during", "ar": "خلال", "pronounce": "دْيُورِنغ", "ex_en": "Study during the day.", "ar_ex": "ادرس خلال النهار." },
  { "id": 243, "en": "export", "ar": "يصدّر", "pronounce": "إكْسْپورت", "ex_en": "We export many goods.", "ar_ex": "نحن نصدر بضائع كثيرة." },
  { "id": 244, "en": "farming", "ar": "زراعة", "pronounce": "فارمِنغ", "ex_en": "He loves farming work.", "ar_ex": "هو يحب أعمال الزراعة." },
  { "id": 245, "en": "follow", "ar": "يتبع", "pronounce": "فولو", "ex_en": "Follow the teacher now.", "ar_ex": "اتبع المعلم الآن." },
  { "id": 246, "en": "full", "ar": "ممتلئ", "pronounce": "فول", "ex_en": "The box is full.", "ar_ex": "الصندوق ممتلئ." },
  { "id": 247, "en": "import", "ar": "يستورد", "pronounce": "إِمپورْت", "ex_en": "They import new cars.", "ar_ex": "هم يستوردون سيارات جديدة." },
  { "id": 248, "en": "given name", "ar": "الاسم الأول", "pronounce": "گِڤِن نِيم", "ex_en": "Write your given name.", "ar_ex": "اكتب اسمك الأول." },
  { "id": 249, "en": "glasses", "ar": "نظارات", "pronounce": "غْلاسِز", "ex_en": "Where are my glasses?", "ar_ex": "أين نظاراتي؟" },
  { "id": 250, "en": "gloves", "ar": "قفازات", "pronounce": "غْلَفز", "ex_en": "Wear your warm gloves.", "ar_ex": "ارتدِ قفازاتك الدافئة." },
  { "id": 251, "en": "grade", "ar": "صف / علامة", "pronounce": "گْريد", "ex_en": "I got high grade.", "ar_ex": "حصلت على علامة عالية." },
  { "id": 252, "en": "groom", "ar": "عريس", "pronounce": "گروم", "ex_en": "The groom looks happy.", "ar_ex": "العريس يبدو سعيداً." },
  { "id": 253, "en": "ground meat", "ar": "لحم مفروم", "pronounce": "غْراوند مِيت", "ex_en": "Buy fresh ground meat.", "ar_ex": "اشترِ لحماً مفروماً طازجاً." },
  { "id": 254, "en": "guest", "ar": "ضيف", "pronounce": "گِست", "ex_en": "We have a guest.", "ar_ex": "لدينا ضيف." },
  { "id": 255, "en": "half", "ar": "نصف", "pronounce": "هاف", "ex_en": "Eat half the cake.", "ar_ex": "كل نصف الكعكة." },
  { "id": 256, "en": "hold", "ar": "يمسك", "pronounce": "هولد", "ex_en": "Hold my hand please.", "ar_ex": "امسك يدي من فضلك." },
  { "id": 257, "en": "hotel", "ar": "فندق", "pronounce": "هوتِل", "ex_en": "This is a big hotel.", "ar_ex": "هذا فندق كبير." },
  { "id": 258, "en": "housework", "ar": "أعمال منزلية", "pronounce": "هاوسوِرك", "ex_en": "Do your daily housework.", "ar_ex": "قم بأعمالك المنزلية." },
  { "id": 259, "en": "human being", "ar": "إنسان", "pronounce": "هيومن بينغ", "ex_en": "Every human being matters.", "ar_ex": "كل إنسان مهم." },
  { "id": 260, "en": "hurry up", "ar": "أسرع", "pronounce": "هَري أپ", "ex_en": "Please hurry up now.", "ar_ex": "من فضلك أسرع الآن." },
  { "id": 261, "en": "husband", "ar": "زوج", "pronounce": "هَزبَند", "ex_en": "He is my husband.", "ar_ex": "إنه زوجي." },
  { "id": 262, "en": "including", "ar": "بما في ذلك", "pronounce": "إنكلودِنغ", "ex_en": "Read all, including notes.", "ar_ex": "اقرأ الكل بما فيها الملاحظات." }
];