const levelCLASS9_Words = [
  { "id": 1, "en": "a few", "ar": "بضعة / قليل", "pronounce": "أ فْيُو", "ex_en": "I have a few books", "ar_ex": "لدي بضعة كتب" },
  { "id": 2, "en": "across", "ar": "عبر", "pronounce": "أكْروس", "ex_en": "Walk across the street", "ar_ex": "امشِ عبر الشارع" },
  { "id": 3, "en": "advantage", "ar": "فائدة / ميزة", "pronounce": "أدْڤانْتِدْج", "ex_en": "This has a big advantage", "ar_ex": "هذا له ميزة كبيرة" },
  { "id": 4, "en": "airport", "ar": "مطار", "pronounce": "إيرْپُورْت", "ex_en": "We arrived at the airport", "ar_ex": "وصلنا إلى المطار" },
  { "id": 5, "en": "anyway", "ar": "على أي حال", "pronounce": "إِني وِي", "ex_en": "I will go anyway", "ar_ex": "سأذهب على أي حال" },
  { "id": 6, "en": "as well as", "ar": "بالإضافة إلى", "pronounce": "أز وِل أز", "ex_en": "He speaks Arabic as well as English", "ar_ex": "يتحدث العربية بالإضافة للإنجليزية" },
  { "id": 7, "en": "attendant", "ar": "مضيف / مرافق", "pronounce": "أتِنْدَنْت", "ex_en": "The flight attendant smiled", "ar_ex": "ابتسم مضيف الطيران" },
  { "id": 8, "en": "away", "ar": "بعيداً", "pronounce": "أوِي", "ex_en": "He walked away", "ar_ex": "مشى بعيداً" },
  { "id": 9, "en": "battle", "ar": "معركة", "pronounce": "باتِل", "ex_en": "They won the battle", "ar_ex": "ربحوا المعركة" },
  { "id": 10, "en": "beat", "ar": "يهزم / يضرب", "pronounce": "بِيت", "ex_en": "We can beat them", "ar_ex": "يمكننا أن نهزمهم" },
  { "id": 11, "en": "behave", "ar": "يتصرف", "pronounce": "بِهِيف", "ex_en": "Behave yourself in school", "ar_ex": "تصرف بأدب في المدرسة" },
  { "id": 12, "en": "believe", "ar": "يصدق / يعتقد", "pronounce": "بِلِيڤ", "ex_en": "I believe you", "ar_ex": "أنا أصدقك" },
  { "id": 13, "en": "thermal blanket", "ar": "بطانية حرارية", "pronounce": "ثيرْمَل بْلانْكِت", "ex_en": "Use the thermal blanket", "ar_ex": "استخدم البطانية الحرارية" },
  { "id": 14, "en": "by", "ar": "بواسطة / بجانب", "pronounce": "باي", "ex_en": "I go by bus", "ar_ex": "أذهب بواسطة الحافلة" },
  { "id": 15, "en": "by hand", "ar": "يدوياً / باليد", "pronounce": "باي هانْد", "ex_en": "It is made by hand", "ar_ex": "صُنِع يدوياً" },
  { "id": 16, "en": "calm down", "ar": "يهدأ", "pronounce": "كام داون", "ex_en": "Please calm down", "ar_ex": "من فضلك اهدأ" },
  { "id": 17, "en": "captain", "ar": "قبطان / قائد", "pronounce": "كابْتِن", "ex_en": "He is the team captain", "ar_ex": "هو قائد الفريق" },
  { "id": 18, "en": "carpet", "ar": "سجادة", "pronounce": "كارْپِت", "ex_en": "The carpet is soft", "ar_ex": "السجادة ناعمة" },
  { "id": 19, "en": "certainly", "ar": "بالتأكيد", "pronounce": "سِيرْتِنْلي", "ex_en": "I will certainly help", "ar_ex": "سأساعد بالتأكيد" },
  { "id": 20, "en": "chart", "ar": "رسم بياني / جدول", "pronounce": "تشارت", "ex_en": "Look at this chart", "ar_ex": "انظر إلى هذا الرسم البياني" },
  { "id": 21, "en": "coin", "ar": "عملة معدنية", "pronounce": "كويْن", "ex_en": "I found a gold coin", "ar_ex": "وجدت عملة ذهبية" },
  { "id": 22, "en": "collapse", "ar": "ينهار", "pronounce": "كُولاپْس", "ex_en": "The old wall might collapse", "ar_ex": "الجدار القديم قد ينهار" },
  { "id": 23, "en": "community", "ar": "مجتمع", "pronounce": "كُميُونِتي", "ex_en": "We live in a good community", "ar_ex": "نعيش في مجتمع جيد" },
  { "id": 24, "en": "complete", "ar": "يكمل / كامل", "pronounce": "كُمْپْلِيت", "ex_en": "Complete your homework", "ar_ex": "أكمل واجبك المنزلي" },
  { "id": 25, "en": "continent", "ar": "قارة", "pronounce": "كونْتِنِنت", "ex_en": "Asia is a large continent", "ar_ex": "آسيا قارة كبيرة" },
  { "id": 26, "en": "continue", "ar": "يستمر", "pronounce": "كُنتِنْيُو", "ex_en": "Let us continue the game", "ar_ex": "دعونا نستمر في اللعب" },
  { "id": 27, "en": "cover", "ar": "يغطي / غطاء", "pronounce": "كَڤَر", "ex_en": "Cover your food", "ar_ex": "غطِّ طعامك" },
  { "id": 28, "en": "crossroads", "ar": "مفترق طرق", "pronounce": "كْروسْ رُودْز", "ex_en": "Turn left at the crossroads", "ar_ex": "انعطف يساراً عند مفترق الطرق" },
  { "id": 29, "en": "crusade", "ar": "حملة (صليبية / للتغيير)", "pronounce": "كْرُوسِيد", "ex_en": "A crusade against pollution", "ar_ex": "حملة ضد التلوث" },
  { "id": 30, "en": "curtain", "ar": "ستارة", "pronounce": "كِيرْتِن", "ex_en": "Open the curtain", "ar_ex": "افتح الستارة" },
  { "id": 31, "en": "customer", "ar": "زبون", "pronounce": "كَسْتُمَر", "ex_en": "The customer is always right", "ar_ex": "الزبون دائماً على حق" },
  { "id": 32, "en": "defeat", "ar": "يهزم / هزيمة", "pronounce": "دِفِيت", "ex_en": "We will defeat them", "ar_ex": "سوف نهزمهم" },
  { "id": 33, "en": "die", "ar": "يموت", "pronounce": "داي", "ex_en": "Plants die without water", "ar_ex": "النباتات تموت بدون ماء" },
  { "id": 34, "en": "dining room", "ar": "غرفة الطعام", "pronounce": "داينِنْغ رُوم", "ex_en": "We eat in the dining room", "ar_ex": "نحن نأكل في غرفة الطعام" },
  { "id": 35, "en": "dry", "ar": "جاف / يجفف", "pronounce": "دْراي", "ex_en": "The clothes are dry", "ar_ex": "الملابس جافة" },
  { "id": 36, "en": "efficient", "ar": "فعال / كفء", "pronounce": "إفِشِنْت", "ex_en": "He is an efficient worker", "ar_ex": "إنه عامل كفء" },
  { "id": 37, "en": "empire", "ar": "إمبراطورية", "pronounce": "إمْپايَر", "ex_en": "The Roman Empire was huge", "ar_ex": "الإمبراطورية الرومانية كانت ضخمة" },
  { "id": 38, "en": "enemy", "ar": "عدو", "pronounce": "إنِمي", "ex_en": "He is my enemy", "ar_ex": "إنه عدوي" },
  { "id": 39, "en": "expert", "ar": "خبير", "pronounce": "إكْسْپِيرْت", "ex_en": "She is an expert in math", "ar_ex": "هي خبيرة في الرياضيات" },
  { "id": 40, "en": "factory", "ar": "مصنع", "pronounce": "فاكْتُري", "ex_en": "He works in a factory", "ar_ex": "يعمل في مصنع" },
  { "id": 41, "en": "fair", "ar": "عادل", "pronounce": "فِير", "ex_en": "That is not fair", "ar_ex": "هذا ليس عادلاً" },
  { "id": 42, "en": "fascinating", "ar": "ساحر / مذهل", "pronounce": "فاسِنِيتِنْغ", "ex_en": "The story is fascinating", "ar_ex": "القصة مذهلة" },
  { "id": 43, "en": "first aid kit", "ar": "حقيبة إسعافات أولية", "pronounce": "فِيرْسْت إيد كِت", "ex_en": "Bring the first aid kit", "ar_ex": "أحضر حقيبة الإسعافات الأولية" },
  { "id": 44, "en": "free", "ar": "مجاني / حر", "pronounce": "فْري", "ex_en": "The tickets are free", "ar_ex": "التذاكر مجانية" },
  { "id": 45, "en": "gate", "ar": "بوابة", "pronounce": "گِيت", "ex_en": "Close the gate", "ar_ex": "أغلق البوابة" },
  { "id": 46, "en": "gentle", "ar": "لطيف / رقيق", "pronounce": "جِنْتِل", "ex_en": "Be gentle with the baby", "ar_ex": "كن لطيفاً مع الطفل" },
  { "id": 47, "en": "geography", "ar": "جغرافيا", "pronounce": "جِيُوگْرافي", "ex_en": "I study geography", "ar_ex": "أنا أدرس الجغرافيا" },
  { "id": 48, "en": "get on", "ar": "يركب (حافلة/قطار)", "pronounce": "گِت أُون", "ex_en": "Get on the bus quickly", "ar_ex": "اركب الحافلة بسرعة" },
  { "id": 49, "en": "God", "ar": "الله / إله", "pronounce": "گود", "ex_en": "God is great", "ar_ex": "الله عظيم" },
  { "id": 50, "en": "government", "ar": "حكومة", "pronounce": "گَڤَرْنْمِنت", "ex_en": "The government built new schools", "ar_ex": "الحكومة بنت مدارس جديدة" },
  { "id": 51, "en": "ground", "ar": "أرض", "pronounce": "گْراونْد", "ex_en": "Sit on the ground", "ar_ex": "اجلس على الأرض" },
  { "id": 52, "en": "guide", "ar": "مرشد / دليل", "pronounce": "گايْد", "ex_en": "The tour guide is friendly", "ar_ex": "المرشد السياحي ودود" },
  { "id": 53, "en": "hall", "ar": "قاعة / ممر", "pronounce": "هُول", "ex_en": "Wait in the hall", "ar_ex": "انتظر في القاعة" },
  { "id": 54, "en": "heart", "ar": "قلب", "pronounce": "هارْت", "ex_en": "My heart is beating fast", "ar_ex": "قلبي ينبض بسرعة" },
  { "id": 55, "en": "identity", "ar": "هوية", "pronounce": "آيْدِنْتِتي", "ex_en": "Keep your identity safe", "ar_ex": "حافظ على هويتك آمنة" },
  { "id": 56, "en": "in time", "ar": "في الوقت المناسب", "pronounce": "إن تايْم", "ex_en": "We arrived in time", "ar_ex": "وصلنا في الوقت المناسب" },
  { "id": 57, "en": "independent", "ar": "مستقل", "pronounce": "إنْدِپِنْدِنْت", "ex_en": "She is an independent woman", "ar_ex": "هي امرأة مستقلة" },
  { "id": 58, "en": "industry", "ar": "صناعة", "pronounce": "إنْدَسْتْري", "ex_en": "The car industry is huge", "ar_ex": "صناعة السيارات ضخمة" },
  { "id": 59, "en": "injury", "ar": "إصابة", "pronounce": "إنْجُري", "ex_en": "He has a knee injury", "ar_ex": "لديه إصابة في الركبة" },
  { "id": 60, "en": "jewellery", "ar": "مجوهرات", "pronounce": "جُولِري", "ex_en": "She wears expensive jewellery", "ar_ex": "ترتدي مجوهرات باهظة" },
  { "id": 61, "en": "keep out", "ar": "يمنع الدخول / يبقى بالخارج", "pronounce": "كِيب آوت", "ex_en": "Keep out of the danger", "ar_ex": "ابقَ بعيداً عن الخطر" },
  { "id": 62, "en": "land", "ar": "أرض / يهبط", "pronounce": "لانْد", "ex_en": "The plane will land soon", "ar_ex": "الطائرة ستهبط قريباً" },
  { "id": 63, "en": "landing card", "ar": "بطاقة الهبوط", "pronounce": "لانْدِنْغ كارد", "ex_en": "Fill in the landing card", "ar_ex": "املأ بطاقة الهبوط" },
  { "id": 64, "en": "leader", "ar": "قائد", "pronounce": "لِيدَر", "ex_en": "He is a great leader", "ar_ex": "إنه قائد عظيم" },
  { "id": 65, "en": "lie", "ar": "يكذب / كذبة", "pronounce": "لاي", "ex_en": "Never tell a lie", "ar_ex": "لا تقل كذبة أبداً" },
  { "id": 66, "en": "lira", "ar": "ليرة", "pronounce": "لِيرا", "ex_en": "It costs fifty lira", "ar_ex": "تكلف خمسين ليرة" },
  { "id": 67, "en": "local", "ar": "محلي", "pronounce": "لُوكَل", "ex_en": "Eat local food", "ar_ex": "تناول طعاماً محلياً" },
  { "id": 68, "en": "marble", "ar": "رخام", "pronounce": "مارْبِل", "ex_en": "The floor is made of marble", "ar_ex": "الأرضية مصنوعة من الرخام" },
  { "id": 69, "en": "mini bus", "ar": "حافلة صغيرة", "pronounce": "مِني بَس", "ex_en": "We rented a mini bus", "ar_ex": "استأجرنا حافلة صغيرة" },
  { "id": 70, "en": "museum", "ar": "متحف", "pronounce": "مْيُوزِيَم", "ex_en": "We visit the museum", "ar_ex": "نحن نزور المتحف" },
  { "id": 71, "en": "out of breath", "ar": "مقطوع الأنفاس", "pronounce": "آوت أُوف بْرِيث", "ex_en": "I am out of breath", "ar_ex": "أنا مقطوع الأنفاس" },
  { "id": 72, "en": "over", "ar": "فوق / أكثر من", "pronounce": "أُوڤَر", "ex_en": "It is over there", "ar_ex": "إنه هناك" },
  { "id": 73, "en": "passport", "ar": "جواز سفر", "pronounce": "پاسْپُورْت", "ex_en": "Show your passport please", "ar_ex": "أرني جواز سفرك من فضلك" },
  { "id": 74, "en": "pay", "ar": "يدفع", "pronounce": "پِي", "ex_en": "I will pay the bill", "ar_ex": "سأدفع الفاتورة" },
  { "id": 75, "en": "peace", "ar": "سلام", "pronounce": "پِيس", "ex_en": "We all want peace", "ar_ex": "كلنا نريد السلام" },
  { "id": 76, "en": "per cent", "ar": "بالمئة", "pronounce": "پِير سِنْت", "ex_en": "Ten per cent discount", "ar_ex": "خصم عشرة بالمئة" },
  { "id": 77, "en": "point", "ar": "نقطة / يشير", "pronounce": "پُويْنْت", "ex_en": "Point to the picture", "ar_ex": "أشر إلى الصورة" },
  { "id": 78, "en": "powerful", "ar": "قوي", "pronounce": "پاوَرْفُل", "ex_en": "The storm was powerful", "ar_ex": "العاصفة كانت قوية" },
  { "id": 79, "en": "prophet", "ar": "نبي", "pronounce": "پْرُوفِت", "ex_en": "Muhammad is a prophet", "ar_ex": "محمد هو نبي" },
  { "id": 80, "en": "provide", "ar": "يوفر / يزود", "pronounce": "پْرُوڤايْد", "ex_en": "They provide free food", "ar_ex": "هم يوفرون طعاماً مجانياً" },
  { "id": 81, "en": "pulse", "ar": "نبض", "pronounce": "پَلْس", "ex_en": "The doctor felt his pulse", "ar_ex": "فحص الطبيب نبضه" },
  { "id": 82, "en": "purse", "ar": "محفظة نسائية", "pronounce": "پِيرْس", "ex_en": "She lost her purse", "ar_ex": "لقد أضاعت محفظتها" },
  { "id": 83, "en": "put up", "ar": "يرفع / ينصب", "pronounce": "پُت أپ", "ex_en": "Put up your hand", "ar_ex": "ارفع يدك" },
  { "id": 84, "en": "quarry", "ar": "محجر / مقلع حجارة", "pronounce": "كْواري", "ex_en": "They work in a stone quarry", "ar_ex": "هم يعملون في محجر حجارة" },
  { "id": 85, "en": "rate", "ar": "معدل / نسبة", "pronounce": "رِيت", "ex_en": "A high success rate", "ar_ex": "معدل نجاح عالٍ" },
  { "id": 86, "en": "reach", "ar": "يصل إلى", "pronounce": "رِيتْش", "ex_en": "I will reach home soon", "ar_ex": "سأصل للمنزل قريباً" },
  { "id": 87, "en": "relax", "ar": "يسترخي", "pronounce": "رِلاكْس", "ex_en": "Sit down and relax", "ar_ex": "اجلس واسترخِ" },
  { "id": 88, "en": "remind", "ar": "يذكر", "pronounce": "رِمايْنْد", "ex_en": "Remind me to call him", "ar_ex": "ذكرني أن أتصل به" },
  { "id": 89, "en": "respect", "ar": "يحترم / احترام", "pronounce": "رِسْپِكْت", "ex_en": "Respect your teachers", "ar_ex": "احترم معلميك" },
  { "id": 90, "en": "right", "ar": "حق / يمين / صحيح", "pronounce": "رايْت", "ex_en": "You are right", "ar_ex": "أنت على حق" },
  { "id": 91, "en": "right now", "ar": "الآن فوراً", "pronounce": "رايْت ناو", "ex_en": "Do it right now", "ar_ex": "افعلها الآن فوراً" },
  { "id": 92, "en": "ruler", "ar": "حاكم / مسطرة", "pronounce": "رُولَر", "ex_en": "He is a fair ruler", "ar_ex": "إنه حاكم عادل" },
  { "id": 93, "en": "schedule", "ar": "جدول زمني", "pronounce": "سْكِدْيُول", "ex_en": "My schedule is busy", "ar_ex": "جدولي الزمني مزدحم" },
  { "id": 94, "en": "sensible", "ar": "عاقل / حكيم", "pronounce": "سِنْسِبِل", "ex_en": "That is a sensible idea", "ar_ex": "تلك فكرة حكيمة" },
  { "id": 95, "en": "site", "ar": "موقع", "pronounce": "سايْت", "ex_en": "This is a building site", "ar_ex": "هذا موقع بناء" },
  { "id": 96, "en": "special", "ar": "خاص / مميز", "pronounce": "سْپِشَل", "ex_en": "Today is a special day", "ar_ex": "اليوم يوم مميز" },
  { "id": 97, "en": "sultan", "ar": "سلطان", "pronounce": "سُلْطان", "ex_en": "The sultan built a mosque", "ar_ex": "السلطان بنى مسجداً" },
  { "id": 98, "en": "sweat", "ar": "يعرق / عرق", "pronounce": "سْوِت", "ex_en": "Running makes you sweat", "ar_ex": "الركض يجعلك تعرق" },
  { "id": 99, "en": "take off", "ar": "يقلع / يخلع", "pronounce": "تِيك أُوف", "ex_en": "Take off your shoes", "ar_ex": "اخلع حذاءك" },
  { "id": 100, "en": "take out", "ar": "يُخرج", "pronounce": "تِيك آوت", "ex_en": "Take out your books", "ar_ex": "أخرجوا كتبكم" },
  { "id": 101, "en": "through", "ar": "خلال", "pronounce": "ثْرُو", "ex_en": "Walk through the door", "ar_ex": "امشِ خلال الباب" },
  { "id": 102, "en": "title", "ar": "عنوان (كتاب/مقال)", "pronounce": "تايْتِل", "ex_en": "What is the book title?", "ar_ex": "ما هو عنوان الكتاب؟" },
  { "id": 103, "en": "towards", "ar": "باتجاه", "pronounce": "تُووَرْدْز", "ex_en": "Walk towards the light", "ar_ex": "امشِ باتجاه الضوء" },
  { "id": 104, "en": "trade", "ar": "تجارة", "pronounce": "تْرِيد", "ex_en": "Trade is important", "ar_ex": "التجارة مهمة" },
  { "id": 105, "en": "village", "ar": "قرية", "pronounce": "ڤِلِدْج", "ex_en": "He lives in a small village", "ar_ex": "يعيش في قرية صغيرة" },
  { "id": 106, "en": "wall", "ar": "جدار", "pronounce": "وُول", "ex_en": "The wall is painted blue", "ar_ex": "الجدار مطلي بالأزرق" },
  { "id": 107, "en": "wardrobe", "ar": "خزانة ملابس", "pronounce": "وُورْدْرُوب", "ex_en": "Put clothes in the wardrobe", "ar_ex": "ضع الملابس في الخزانة" },
  { "id": 108, "en": "warm up", "ar": "يسخن / يحمّي", "pronounce": "وُورْم أپ", "ex_en": "Warm up before running", "ar_ex": "قم بالإحماء قبل الركض" },
  { "id": 109, "en": "wet", "ar": "مبلل", "pronounce": "وِت", "ex_en": "The floor is wet", "ar_ex": "الأرضية مبللة" },
  { "id": 110, "en": "whole", "ar": "كامل", "pronounce": "هُول", "ex_en": "I ate the whole pizza", "ar_ex": "أكلت البيتزا كاملة" },
  { "id": 111, "en": "be able to", "ar": "قادر على", "pronounce": "بي إيْبِل تُو", "ex_en": "I will be able to come", "ar_ex": "سأكون قادراً على المجيء" },
  { "id": 112, "en": "a bit", "ar": "قليلاً", "pronounce": "أ بـِت", "ex_en": "I am a bit tired", "ar_ex": "أنا متعب قليلاً" },
  { "id": 113, "en": "accidentally", "ar": "بالصدفة / بالخطأ", "pronounce": "أكْسِدِنْتَلي", "ex_en": "I dropped it accidentally", "ar_ex": "أسقطته عن طريق الخطأ" },
  { "id": 114, "en": "action", "ar": "حركة / فعل", "pronounce": "أكْشِن", "ex_en": "It is an action movie", "ar_ex": "إنه فيلم حركة" },
  { "id": 115, "en": "aim", "ar": "يهدف / هدف", "pronounce": "إيْم", "ex_en": "Aim high in life", "ar_ex": "استهدف عالياً في الحياة" },
  { "id": 116, "en": "a.m.", "ar": "صباحاً", "pronounce": "إي إم", "ex_en": "I wake up at 7 a.m.", "ar_ex": "أستيقظ السابعة صباحاً" },
  { "id": 117, "en": "amazed", "ar": "مندهش", "pronounce": "أمِيزْد", "ex_en": "I am amazed by the view", "ar_ex": "أنا مندهش من المنظر" },
  { "id": 118, "en": "around", "ar": "حول / في الأرجاء", "pronounce": "أراونْد", "ex_en": "Look around you", "ar_ex": "انظر حولك" },
  { "id": 119, "en": "artificial", "ar": "صناعي", "pronounce": "آرْتِفِشَل", "ex_en": "This is artificial intelligence", "ar_ex": "هذا ذكاء اصطناعي" },
  { "id": 120, "en": "ashamed", "ar": "خجلان", "pronounce": "أشِيْمْد", "ex_en": "Do not feel ashamed", "ar_ex": "لا تشعر بالخجل" },
  { "id": 121, "en": "athlete", "ar": "رياضي", "pronounce": "أثْلِيت", "ex_en": "He is a famous athlete", "ar_ex": "إنه رياضي مشهور" },
  { "id": 122, "en": "attention", "ar": "انتباه", "pronounce": "أتِنْشِن", "ex_en": "Pay attention in class", "ar_ex": "انتبه في الصف" },
  { "id": 123, "en": "be down", "ar": "مكتئب / محبط", "pronounce": "بي داون", "ex_en": "He seems to be down today", "ar_ex": "يبدو محبطاً اليوم" },
  { "id": 124, "en": "belong", "ar": "يخص / ينتمي", "pronounce": "بِلُونْغ", "ex_en": "This book belongs to me", "ar_ex": "هذا الكتاب يخصني" },
  { "id": 125, "en": "be born", "ar": "يولد", "pronounce": "بي بُورْن", "ex_en": "I was born in May", "ar_ex": "ولدت في مايو" },
  { "id": 126, "en": "broken", "ar": "مكسور", "pronounce": "بْرُوكِن", "ex_en": "The glass is broken", "ar_ex": "الزجاج مكسور" },
  { "id": 127, "en": "burn", "ar": "يحرق / يحترق", "pronounce": "بِيرْن", "ex_en": "Do not burn the wood here", "ar_ex": "لا تحرق الخشب هنا" },
  { "id": 128, "en": "by time", "ar": "بحلول الوقت", "pronounce": "باي تايْم", "ex_en": "I will finish by 5 PM", "ar_ex": "سأنتهي بحلول الخامسة مساءً" },
  { "id": 129, "en": "carpenter", "ar": "نجار", "pronounce": "كارْپِنْتَر", "ex_en": "The carpenter makes chairs", "ar_ex": "النجار يصنع الكراسي" },
  { "id": 130, "en": "cause", "ar": "يسبب / سبب", "pronounce": "كُوز", "ex_en": "What is the cause of this?", "ar_ex": "ما هو سبب هذا؟" },
  { "id": 131, "en": "chance", "ar": "فرصة", "pronounce": "تشانْس", "ex_en": "Give me another chance", "ar_ex": "أعطني فرصة أخرى" },
  { "id": 132, "en": "cheer up", "ar": "يبتهج / يسعد", "pronounce": "تشِير أپ", "ex_en": "Cheer up, friend!", "ar_ex": "ابتهج يا صديقي!" },
  { "id": 133, "en": "cheerful", "ar": "مبتهج / بشوش", "pronounce": "تشِيرْفُل", "ex_en": "She is a cheerful girl", "ar_ex": "إنها فتاة مبتهجة" },
  { "id": 134, "en": "chemical", "ar": "مادة كيميائية", "pronounce": "كِيمِيكَل", "ex_en": "This is a bad chemical", "ar_ex": "هذه مادة كيميائية سيئة" },
  { "id": 135, "en": "clean up", "ar": "ينظف", "pronounce": "كْلِين أپ", "ex_en": "Clean up your room", "ar_ex": "نظف غرفتك" },
  { "id": 136, "en": "cleaner", "ar": "منظف / عامل نظافة", "pronounce": "كْلِينَر", "ex_en": "Use the glass cleaner", "ar_ex": "استخدم منظف الزجاج" },
  { "id": 137, "en": "close", "ar": "قريب / يغلق", "pronounce": "كْلُوز", "ex_en": "My house is close", "ar_ex": "منزلي قريب" },
  { "id": 138, "en": "coast", "ar": "ساحل", "pronounce": "كُوسْت", "ex_en": "We live on the coast", "ar_ex": "نعيش على الساحل" },
  { "id": 139, "en": "come down", "ar": "ينزل", "pronounce": "كَم داون", "ex_en": "Come down from the tree", "ar_ex": "انزل من الشجرة" },
  { "id": 140, "en": "comment", "ar": "تعليق / يعلق", "pronounce": "كُومِنْت", "ex_en": "Leave a comment below", "ar_ex": "اترك تعليقاً بالأسفل" },
  { "id": 141, "en": "committee", "ar": "لجنة", "pronounce": "كُمِيتي", "ex_en": "The committee had a meeting", "ar_ex": "اللجنة عقدت اجتماعاً" },
  { "id": 142, "en": "cooker", "ar": "موقد / طباخ", "pronounce": "كُوكَر", "ex_en": "Put the pan on the cooker", "ar_ex": "ضع المقلاة على الموقد" },
  { "id": 143, "en": "create", "ar": "يبتكر / يخلق", "pronounce": "كْرِيِيْت", "ex_en": "We can create a new game", "ar_ex": "يمكننا ابتكار لعبة جديدة" },
  { "id": 144, "en": "death", "ar": "موت", "pronounce": "دِث", "ex_en": "His death was sad", "ar_ex": "كان موته حزيناً" },
  { "id": 145, "en": "definitely", "ar": "بالتأكيد", "pronounce": "دِفِنِتْلي", "ex_en": "I will definitely go", "ar_ex": "سأذهب بالتأكيد" },
  { "id": 146, "en": "depressed", "ar": "مكتئب", "pronounce": "دِپْرِسْد", "ex_en": "He felt very depressed", "ar_ex": "شعر بالاكتئاب الشديد" },
  { "id": 147, "en": "destroy", "ar": "يدمر", "pronounce": "دِسْتْرُوي", "ex_en": "Do not destroy the toys", "ar_ex": "لا تدمر الألعاب" },
  { "id": 148, "en": "disability", "ar": "إعاقة", "pronounce": "دِسْأبِلِتي", "ex_en": "He lives with a disability", "ar_ex": "يعيش مع إعاقة" },
  { "id": 149, "en": "disabled", "ar": "من ذوي الإعاقة", "pronounce": "دِسْإيْبِلْد", "ex_en": "He is a disabled athlete", "ar_ex": "إنه رياضي من ذوي الإعاقة" },
  { "id": 150, "en": "disappear", "ar": "يختفي", "pronounce": "دِسْأپِير", "ex_en": "The sun will disappear", "ar_ex": "الشمس سوف تختفي" },
  { "id": 151, "en": "disaster", "ar": "كارثة", "pronounce": "دِزاسْتَر", "ex_en": "The flood was a disaster", "ar_ex": "كان الفيضان كارثة" },
  { "id": 152, "en": "discover", "ar": "يكتشف", "pronounce": "دِسْكَڤَر", "ex_en": "Scientists discover new things", "ar_ex": "العلماء يكتشفون أشياء جديدة" },
  { "id": 153, "en": "discussion", "ar": "نقاش", "pronounce": "دِسْكَشِن", "ex_en": "We had a good discussion", "ar_ex": "حظينا بنقاش جيد" },
  { "id": 154, "en": "do well", "ar": "يُبلي حسناً", "pronounce": "دُو وِل", "ex_en": "You will do well in the test", "ar_ex": "ستبلي حسناً في الاختبار" },
  { "id": 155, "en": "dramatic", "ar": "درامي / مثير", "pronounce": "دْراماتِك", "ex_en": "It was a dramatic change", "ar_ex": "كان تغييراً درامياً" },
  { "id": 156, "en": "duty", "ar": "واجب", "pronounce": "دْيُوتي", "ex_en": "It is my duty to help", "ar_ex": "من واجبي المساعدة" },
  { "id": 157, "en": "earthquake", "ar": "زلزال", "pronounce": "إيرْث كْوِيك", "ex_en": "The earthquake shook the city", "ar_ex": "هز الزلزال المدينة" },
  { "id": 158, "en": "energy", "ar": "طاقة", "pronounce": "إنِرْجي", "ex_en": "I have no energy today", "ar_ex": "ليس لدي طاقة اليوم" },
  { "id": 159, "en": "equipment", "ar": "معدات", "pronounce": "إكْوِيپْمِنْت", "ex_en": "We need sports equipment", "ar_ex": "نحتاج معدات رياضية" },
  { "id": 160, "en": "expect", "ar": "يتوقع", "pronounce": "إكْسْپِكْت", "ex_en": "I expect him to win", "ar_ex": "أتوقع منه الفوز" },
  { "id": 161, "en": "experience", "ar": "تجربة / خبرة", "pronounce": "إكْسْپِيرْيَنْس", "ex_en": "It was a great experience", "ar_ex": "كانت تجربة رائعة" },
  { "id": 162, "en": "explain", "ar": "يشرح", "pronounce": "إكْسْپْلِين", "ex_en": "Can you explain this rule?", "ar_ex": "هل يمكنك شرح هذه القاعدة؟" },
  { "id": 163, "en": "explode", "ar": "ينفجر", "pronounce": "إكْسْپْلُود", "ex_en": "The bomb might explode", "ar_ex": "القنبلة قد تنفجر" },
  { "id": 164, "en": "extra", "ar": "إضافي", "pronounce": "إكْسْتْرا", "ex_en": "I need extra time", "ar_ex": "أحتاج وقتاً إضافياً" },
  { "id": 165, "en": "favour", "ar": "معروف / فضل", "pronounce": "فِيڤَر", "ex_en": "Can you do me a favour?", "ar_ex": "هل يمكنك إسداء معروف لي؟" },
  { "id": 166, "en": "fence", "ar": "سياج / سور", "pronounce": "فِنْس", "ex_en": "The dog jumped the fence", "ar_ex": "الكلب قفز فوق السياج" },
  { "id": 167, "en": "fetch", "ar": "يجلب", "pronounce": "فِتْش", "ex_en": "Please fetch my bag", "ar_ex": "الرجاء جلب حقيبتي" },
  { "id": 168, "en": "flood", "ar": "فيضان", "pronounce": "فْلَد", "ex_en": "The rain caused a flood", "ar_ex": "المطر تسبب في فيضان" },
  { "id": 169, "en": "fridge", "ar": "ثلاجة", "pronounce": "فْرِدْج", "ex_en": "Put the milk in the fridge", "ar_ex": "ضع الحليب في الثلاجة" },
  { "id": 170, "en": "gardener", "ar": "بستاني", "pronounce": "گارْدِنَر", "ex_en": "The gardener waters the plants", "ar_ex": "البستاني يسقي النباتات" },
  { "id": 171, "en": "get rid of", "ar": "يتخلص من", "pronounce": "گِت رِد أُوف", "ex_en": "Get rid of the rubbish", "ar_ex": "تخلص من القمامة" },
  { "id": 172, "en": "get to know", "ar": "يتعرف على", "pronounce": "گِت تُو نُو", "ex_en": "I want to get to know you", "ar_ex": "أريد أن أتعرف عليك" },
  { "id": 173, "en": "go up", "ar": "يصعد / يرتفع", "pronounce": "گُو أپ", "ex_en": "Prices go up fast", "ar_ex": "الأسعار ترتفع بسرعة" },
  { "id": 174, "en": "grow up", "ar": "يكبر / ينمو", "pronounce": "گْرُو أپ", "ex_en": "Children grow up fast", "ar_ex": "الأطفال يكبرون بسرعة" },
  { "id": 175, "en": "how come", "ar": "كيف ذلك / لمَ", "pronounce": "هاو كَم", "ex_en": "How come you are here?", "ar_ex": "كيف يعقل أنك هنا؟" },
  { "id": 176, "en": "ignore", "ar": "يتجاهل", "pronounce": "إگْنُور", "ex_en": "Do not ignore my message", "ar_ex": "لا تتجاهل رسالتي" },
  { "id": 177, "en": "imagine", "ar": "يتخيل", "pronounce": "إماجِن", "ex_en": "Imagine flying in the sky", "ar_ex": "تخيل الطيران في السماء" },
  { "id": 178, "en": "international", "ar": "دولي / عالمي", "pronounce": "إنْتِرْناشُونَل", "ex_en": "It is an international school", "ar_ex": "إنها مدرسة دولية" },
  { "id": 179, "en": "joke", "ar": "مزحة / يمزح", "pronounce": "جُوك", "ex_en": "He told a funny joke", "ar_ex": "لقد ألقى مزحة مضحكة" },
  { "id": 180, "en": "just", "ar": "فقط / للتو", "pronounce": "جَسْت", "ex_en": "I just arrived", "ar_ex": "لقد وصلت للتو" },
  { "id": 181, "en": "keep", "ar": "يحتفظ / يستمر", "pronounce": "كِيب", "ex_en": "Keep going straight", "ar_ex": "استمر بالذهاب للأمام" },
  { "id": 182, "en": "knock", "ar": "يطرق", "pronounce": "نُوك", "ex_en": "Knock on the door", "ar_ex": "اطرق الباب" },
  { "id": 183, "en": "lead", "ar": "يقود", "pronounce": "لِيد", "ex_en": "He will lead the team", "ar_ex": "هو سيقود الفريق" },
  { "id": 184, "en": "look after", "ar": "يعتني بـ", "pronounce": "لُوك آفْتَر", "ex_en": "Look after your little brother", "ar_ex": "اعتنِ بأخيك الصغير" },
  { "id": 185, "en": "look forward to", "ar": "يتطلع إلى", "pronounce": "لُوك فُورْوَرْد تُو", "ex_en": "I look forward to meeting you", "ar_ex": "أتطلع لرؤيتك" },
  { "id": 186, "en": "lovely", "ar": "جميل / رائع", "pronounce": "لَڤْلي", "ex_en": "What a lovely dress!", "ar_ex": "يا له من فستان جميل!" },
  { "id": 187, "en": "luckily", "ar": "لحسن الحظ", "pronounce": "لَكِلي", "ex_en": "Luckily we found it", "ar_ex": "لحسن الحظ وجدناه" },
  { "id": 188, "en": "manage to", "ar": "يتمكن من", "pronounce": "مانِدْج تُو", "ex_en": "I managed to finish", "ar_ex": "تمكنت من الإنهاء" },
  { "id": 189, "en": "man-made", "ar": "من صنع الإنسان", "pronounce": "مان مِيْد", "ex_en": "This lake is man-made", "ar_ex": "هذه البحيرة من صنع الإنسان" },
  { "id": 190, "en": "material", "ar": "مادة / قماش", "pronounce": "ماتِيرْيَل", "ex_en": "This is a soft material", "ar_ex": "هذه مادة ناعمة" },
  { "id": 191, "en": "middle", "ar": "منتصف", "pronounce": "مِدِل", "ex_en": "Stand in the middle", "ar_ex": "قف في المنتصف" },
  { "id": 192, "en": "meeting", "ar": "اجتماع", "pronounce": "مِيتِنْغ", "ex_en": "We have a meeting now", "ar_ex": "لدينا اجتماع الآن" },
  { "id": 193, "en": "midday", "ar": "منتصف النهار", "pronounce": "مِد دِي", "ex_en": "The sun is hot at midday", "ar_ex": "الشمس حارة منتصف النهار" },
  { "id": 194, "en": "mood", "ar": "مزاج", "pronounce": "مُود", "ex_en": "I am in a good mood", "ar_ex": "أنا في مزاج جيد" },
  { "id": 195, "en": "necessary", "ar": "ضروري", "pronounce": "نِسِيسَري", "ex_en": "Water is necessary for life", "ar_ex": "الماء ضروري للحياة" },
  { "id": 196, "en": "negative", "ar": "سلبي", "pronounce": "نِگاتِڤ", "ex_en": "Do not be so negative", "ar_ex": "لا تكن سلبياً جداً" },
  { "id": 197, "en": "nervous", "ar": "متوتر", "pronounce": "نِيرْڤَس", "ex_en": "He feels nervous today", "ar_ex": "هو يشعر بالتوتر اليوم" },
  { "id": 198, "en": "net", "ar": "شبكة", "pronounce": "نِت", "ex_en": "The ball hit the net", "ar_ex": "ضربت الكرة الشبكة" },
  { "id": 199, "en": "no one", "ar": "لا أحد", "pronounce": "نُو وَن", "ex_en": "No one is in the room", "ar_ex": "لا أحد في الغرفة" },
  { "id": 200, "en": "notice", "ar": "يلاحظ / ملاحظة", "pronounce": "نُوتِس", "ex_en": "Did you notice the sign?", "ar_ex": "هل لاحظت اللافتة؟" },
  { "id": 201, "en": "organization", "ar": "منظمة / مؤسسة", "pronounce": "أُرْگانَيْزِيْشِن", "ex_en": "She works for an organization", "ar_ex": "تعمل لصالح مؤسسة" },
  { "id": 202, "en": "ordinary", "ar": "عادي", "pronounce": "أُورْدِنَري", "ex_en": "It is an ordinary day", "ar_ex": "إنه يوم عادي" },
  { "id": 203, "en": "scream", "ar": "يصرخ", "pronounce": "سْكْرِيم", "ex_en": "Do not scream loudly", "ar_ex": "لا تصرخ بصوت عالٍ" },
  { "id": 204, "en": "pan", "ar": "مقلاة", "pronounce": "پان", "ex_en": "Fry eggs in the pan", "ar_ex": "اقلِ البيض في المقلاة" },
  { "id": 205, "en": "past", "ar": "ماضي", "pronounce": "پاسْت", "ex_en": "Do not live in the past", "ar_ex": "لا تعش في الماضي" },
  { "id": 206, "en": "patient", "ar": "مريض / صبور", "pronounce": "پِيْشِنْت", "ex_en": "Be patient with him", "ar_ex": "كن صبوراً معه" },
  { "id": 207, "en": "piece", "ar": "قطعة", "pronounce": "پِيس", "ex_en": "I want a piece of cake", "ar_ex": "أريد قطعة من الكعك" },
  { "id": 208, "en": "pity", "ar": "شفقة / من المؤسف", "pronounce": "پِتي", "ex_en": "What a pity!", "ar_ex": "يا للأسف!" },
  { "id": 209, "en": "secretary", "ar": "سكرتير", "pronounce": "سِكْرِتِري", "ex_en": "The secretary is busy", "ar_ex": "السكرتير مشغول" },
  { "id": 210, "en": "section", "ar": "قسم", "pronounce": "سِكْشِن", "ex_en": "Read the next section", "ar_ex": "اقرأ القسم التالي" },
  { "id": 211, "en": "selfish", "ar": "أناني", "pronounce": "سِلْفِش", "ex_en": "He is a selfish boy", "ar_ex": "إنه ولد أناني" },
  { "id": 212, "en": "simple", "ar": "بسيط", "pronounce": "سِمْپِل", "ex_en": "This is a simple rule", "ar_ex": "هذه قاعدة بسيطة" },
  { "id": 213, "en": "species", "ar": "فصيلة / أنواع", "pronounce": "سْپِيشِيز", "ex_en": "A rare species of bird", "ar_ex": "فصيلة نادرة من الطيور" },
  { "id": 214, "en": "p.m.", "ar": "مساءً", "pronounce": "پي إم", "ex_en": "We meet at 5 p.m.", "ar_ex": "نلتقي الخامسة مساءً" },
  { "id": 215, "en": "stain", "ar": "بقعة", "pronounce": "سْتِين", "ex_en": "There is a stain on the shirt", "ar_ex": "هناك بقعة على القميص" },
  { "id": 216, "en": "population", "ar": "سكان", "pronounce": "پُوپْيُولِيْشِن", "ex_en": "The population is growing", "ar_ex": "عدد السكان ينمو" },
  { "id": 217, "en": "successful", "ar": "ناجح", "pronounce": "سَكْسِسْفُل", "ex_en": "She is a successful doctor", "ar_ex": "هي طبيبة ناجحة" },
  { "id": 218, "en": "possible", "ar": "ممكن", "pronounce": "پُوسِبِل", "ex_en": "Is it possible to come?", "ar_ex": "هل من الممكن المجيء؟" },
  { "id": 219, "en": "suddenly", "ar": "فجأة", "pronounce": "سَدِنْلي", "ex_en": "The lights went out suddenly", "ar_ex": "انطفأت الأنوار فجأة" },
  { "id": 220, "en": "positive", "ar": "إيجابي", "pronounce": "پُوزِتِڤ", "ex_en": "Stay positive always", "ar_ex": "ابقَ إيجابياً دائماً" },
  { "id": 221, "en": "suggest", "ar": "يقترح", "pronounce": "سَجِسْت", "ex_en": "What do you suggest?", "ar_ex": "ماذا تقترح؟" },
  { "id": 222, "en": "pound", "ar": "باوند / جنيه", "pronounce": "پاونْد", "ex_en": "It costs one pound", "ar_ex": "يكلف باونداً واحداً" },
  { "id": 223, "en": "pour", "ar": "يسكب / يصب", "pronounce": "پُور", "ex_en": "Please pour the tea", "ar_ex": "الرجاء سكب الشاي" },
  { "id": 224, "en": "price", "ar": "سعر", "pronounce": "پْرايْس", "ex_en": "What is the price?", "ar_ex": "ما هو السعر؟" },
  { "id": 225, "en": "realize", "ar": "يدرك", "pronounce": "رِيَلايْز", "ex_en": "I realize my mistake", "ar_ex": "أدرك خطئي" },
  { "id": 226, "en": "rely on", "ar": "يعتمد على", "pronounce": "رِلاي أُون", "ex_en": "You can rely on me", "ar_ex": "يمكنك الاعتماد علي" },
  { "id": 227, "en": "repair", "ar": "يصلح", "pronounce": "رِپِير", "ex_en": "He will repair the car", "ar_ex": "هو سيصلح السيارة" },
  { "id": 228, "en": "request", "ar": "يطلب / طلب", "pronounce": "رِكْوِسْت", "ex_en": "I request your help", "ar_ex": "أطلب مساعدتك" },
  { "id": 229, "en": "require", "ar": "يتطلب", "pronounce": "رِكْوايَر", "ex_en": "Plants require sunlight", "ar_ex": "النباتات تتطلب ضوء الشمس" },
  { "id": 230, "en": "result", "ar": "نتيجة", "pronounce": "رِزَلْت", "ex_en": "The result is very good", "ar_ex": "النتيجة جيدة جداً" },
  { "id": 231, "en": "risk", "ar": "خطر / يخاطر", "pronounce": "رِسْك", "ex_en": "Do not risk your life", "ar_ex": "لا تخاطر بحياتك" },
  { "id": 232, "en": "rubbish", "ar": "قمامة", "pronounce": "رَبِش", "ex_en": "Throw the rubbish here", "ar_ex": "ارمِ القمامة هنا" },
  { "id": 233, "en": "supermarket", "ar": "سوبر ماركت", "pronounce": "سُوپرْمارْكِت", "ex_en": "Go to the supermarket", "ar_ex": "اذهب للسوبر ماركت" },
  { "id": 234, "en": "tonight", "ar": "الليلة", "pronounce": "تُونايْت", "ex_en": "We will study tonight", "ar_ex": "سندرس الليلة" },
  { "id": 235, "en": "tray", "ar": "صينية", "pronounce": "تْرِي", "ex_en": "Carry the cups on the tray", "ar_ex": "احمل الأكواب في الصينية" },
  { "id": 236, "en": "in trouble", "ar": "في ورطة", "pronounce": "إن تْرَبِل", "ex_en": "He is in big trouble", "ar_ex": "إنه في ورطة كبيرة" },
  { "id": 237, "en": "tuna", "ar": "تونة", "pronounce": "تُونا", "ex_en": "I like tuna sandwiches", "ar_ex": "أحب شطائر التونة" },
  { "id": 238, "en": "upset", "ar": "منزعج", "pronounce": "أپْسِت", "ex_en": "Why are you upset?", "ar_ex": "لماذا أنت منزعج؟" },
  { "id": 239, "en": "urgent", "ar": "عاجل", "pronounce": "أُرْجِنْت", "ex_en": "It is an urgent message", "ar_ex": "إنها رسالة عاجلة" },
  { "id": 240, "en": "victim", "ar": "ضحية", "pronounce": "ڤِكْتِم", "ex_en": "Help the poor victim", "ar_ex": "ساعد الضحية المسكين" },
  { "id": 241, "en": "voluntary", "ar": "تطوعي", "pronounce": "ڤُولُنْتَري", "ex_en": "It is voluntary work", "ar_ex": "إنه عمل تطوعي" },
  { "id": 242, "en": "waste", "ar": "يضيع / يهدر", "pronounce": "وِيْسْت", "ex_en": "Do not waste water", "ar_ex": "لا تهدر الماء" },
  { "id": 243, "en": "without", "ar": "بدون", "pronounce": "وِذاوْت", "ex_en": "I cannot live without air", "ar_ex": "لا أستطيع العيش بدون هواء" }
];
