const levelCLASS3_Words = [
  { "id": 1, "en": "make", "ar": "يصنع", "pronounce": "مَيْك", "ex_en": "I make a nice paper kite", "ar_ex": "أنا أصنع طائرة ورقية جميلة" },
  { "id": 2, "en": "photo", "ar": "صورة", "pronounce": "فُوتو", "ex_en": "Take a photo of the tree", "ar_ex": "التقط صورة للشجرة" },
  { "id": 3, "en": "remember", "ar": "يتذكر", "pronounce": "رِمِمبر", "ex_en": "Remember to do your homework today", "ar_ex": "تذكر أن تحل وظيفتك اليوم" },
  { "id": 4, "en": "sandwich", "ar": "شطيرة", "pronounce": "ساندوِتش", "ex_en": "I eat a cheese sandwich now", "ar_ex": "آكل شطيرة جبن الآن" },
  { "id": 5, "en": "scientist", "ar": "عالم", "pronounce": "سايَنْتِست", "ex_en": "The scientist works in the lab", "ar_ex": "العالم يعمل في المختبر" },
  { "id": 6, "en": "thirsty", "ar": "عطشان", "pronounce": "ثِرْسْتي", "ex_en": "I am thirsty, give me water", "ar_ex": "أنا عطشان، أعطني ماءً" },
  { "id": 7, "en": "timetable", "ar": "جدول", "pronounce": "تايم تَيْبُل", "ex_en": "Look at the school timetable now", "ar_ex": "انظر إلى الجدول المدرسي الآن" },
  { "id": 8, "en": "policeman", "ar": "شرطي", "pronounce": "بُوليسمَن", "ex_en": "The policeman helps all people", "ar_ex": "الشرطي يساعد كل الناس" },
  { "id": 9, "en": "job", "ar": "عمل", "pronounce": "جوب", "ex_en": "What is your dad’s job?", "ar_ex": "ما هو عمل والدك؟" },
  { "id": 10, "en": "I would like", "ar": "أود", "pronounce": "آي وُد لايك", "ex_en": "I would like an apple juice", "ar_ex": "أود الحصول على عصير تفاح" },
  { "id": 11, "en": "onion", "ar": "بصل", "pronounce": "أَنْيَن", "ex_en": "Put some onion in the salad", "ar_ex": "ضع بعض البصل في السلطة" },
  { "id": 12, "en": "beach", "ar": "شاطئ", "pronounce": "بيتش", "ex_en": "We play on the beach happily", "ar_ex": "نحن نلعب على الشاطئ بسعادة" },
  { "id": 13, "en": "pool", "ar": "بركة سباحة", "pronounce": "بول", "ex_en": "The pool water is very cold", "ar_ex": "ماء البركة بارد جدًا" },
  { "id": 14, "en": "sand", "ar": "رمل", "pronounce": "ساند", "ex_en": "Children love playing with sand", "ar_ex": "الأطفال يحبون اللعب بالرمل" },
  { "id": 15, "en": "garden", "ar": "حديقة", "pronounce": "غاردِن", "ex_en": "Our garden has beautiful flowers", "ar_ex": "حديقتنا فيها زهور جميلة" },
  { "id": 16, "en": "monkey", "ar": "قرد", "pronounce": "مانكي", "ex_en": "The monkey eats a sweet banana", "ar_ex": "القرد يأكل موزة حلوة" },
  { "id": 17, "en": "giraffe", "ar": "زرافة", "pronounce": "جِراف", "ex_en": "The giraffe is a tall animal", "ar_ex": "الزرافة حيوان طويل" },
  { "id": 18, "en": "zoo", "ar": "حديقة حيوان", "pronounce": "زو", "ex_en": "Let us visit the zoo tomorrow", "ar_ex": "لنقم بزيارة حديقة الحيوان غدًا" },
  { "id": 19, "en": "elephant", "ar": "فيل", "pronounce": "إِلِفَنت", "ex_en": "The grey elephant is very big", "ar_ex": "الفيل الرمادي كبير جدًا" },
  { "id": 20, "en": "see", "ar": "يرى", "pronounce": "سي", "ex_en": "I see a blue bird outside", "ar_ex": "أنا أرى طائرًا أزرق بالخارج" },
  { "id": 21, "en": "very", "ar": "جدًا", "pronounce": "فِري", "ex_en": "The weather is very hot today", "ar_ex": "الطقس حار جدًا اليوم" },
  { "id": 22, "en": "fox", "ar": "ثعلب", "pronounce": "فوكس", "ex_en": "The wild fox runs fast now", "ar_ex": "الثعلب البري يركض سريعًا الآن" },
  { "id": 23, "en": "tiger", "ar": "نمر", "pronounce": "تايغر", "ex_en": "The tiger has black stripes always", "ar_ex": "النمر يملك خطوطًا سوداء دائمًا" },
  { "id": 24, "en": "snake", "ar": "أفعى", "pronounce": "سْنيك", "ex_en": "The green snake is long, dangerous", "ar_ex": "الأفعى الخضراء طويلة وخطيرة" },
  { "id": 25, "en": "turn", "ar": "ينعطف", "pronounce": "تِرن", "ex_en": "Turn right at the next corner", "ar_ex": "انعطف يمينًا عند الزاوية القادمة" },
  { "id": 26, "en": "can", "ar": "يستطيع", "pronounce": "كان", "ex_en": "I can ride a small bike", "ar_ex": "أستطيع ركوب دراجة صغيرة" },
  { "id": 27, "en": "usually", "ar": "عادةً", "pronounce": "يُوجُولي", "ex_en": "I usually get up early morning", "ar_ex": "أنا عادةً أستيقظ في الصباح الباكر" },
  { "id": 28, "en": "fast", "ar": "سريع", "pronounce": "فاست", "ex_en": "The blue train moves very fast", "ar_ex": "القطار الأزرق يتحرك سريعًا جدًا" },
  { "id": 29, "en": "slow", "ar": "بطيء", "pronounce": "سْلو", "ex_en": "The old turtle is very slow", "ar_ex": "السلحفاة القديمة بطيئة جدًا" },
  { "id": 30, "en": "wash", "ar": "يغسل", "pronounce": "ووش", "ex_en": "Wash your hands before eating food", "ar_ex": "اغسل يديك قبل تناول الطعام" },
  { "id": 31, "en": "how", "ar": "كيف", "pronounce": "هاو", "ex_en": "How can I open this box?", "ar_ex": "كيف يمكنني فتح هذا الصندوق؟" },
  { "id": 32, "en": "where", "ar": "أين", "pronounce": "وِير", "ex_en": "Where is my English book, mum?", "ar_ex": "أين كتاب الإنجليزي الخاص بي يا أمي؟" },
  { "id": 33, "en": "what", "ar": "ماذا", "pronounce": "وُت", "ex_en": "What do you like to eat?", "ar_ex": "ماذا تحب أن تأكل؟" },
  { "id": 34, "en": "who", "ar": "من", "pronounce": "هو", "ex_en": "Who is that tall teacher over there?", "ar_ex": "من ذلك المعلم الطويل هناك؟" },
  { "id": 35, "en": "here you are", "ar": "تفضل", "pronounce": "هِير يو آر", "ex_en": "Here you are, your cold water", "ar_ex": "تفضل، ماؤك البارد" },
  { "id": 36, "en": "listen to music", "ar": "يستمع للموسيقى", "pronounce": "لِسِن تو ميوزِك", "ex_en": "I like to listen to music", "ar_ex": "أحب الاستماع للموسيقى" },
  { "id": 37, "en": "playing football", "ar": "يلعب كرة قدم", "pronounce": "بلايِنغ فُتبول", "ex_en": "He is playing football in playground", "ar_ex": "هو يلعب كرة القدم في الملعب" },
  { "id": 38, "en": "playing the drums", "ar": "يعزف الطبل", "pronounce": "بلايِنغ ذَ دْرَمْز", "ex_en": "The happy boy is playing drums", "ar_ex": "الولد السعيد يعزف على الطبول" },
  { "id": 39, "en": "playing with friends", "ar": "يلعب مع الأصدقاء", "pronounce": "بلايِنغ وِذ فْرِندز", "ex_en": "I enjoy playing with friends daily", "ar_ex": "أستمتع باللعب مع الأصدقاء يوميًا" },
  { "id": 40, "en": "read", "ar": "يقرأ", "pronounce": "ريد", "ex_en": "Read this beautiful story book now", "ar_ex": "اقرأ كتاب القصة الجميلة هذا الآن" },
  { "id": 41, "en": "run", "ar": "يركض", "pronounce": "رَن", "ex_en": "Run fast in the green park", "ar_ex": "اركض سريعًا في المنتزه الأخضر" },
  { "id": 42, "en": "sing", "ar": "يغني", "pronounce": "سِنغ", "ex_en": "The cute girls sing a song", "ar_ex": "الفتيات اللطيفات يغنين أغنية" },
  { "id": 43, "en": "swim", "ar": "يسبح", "pronounce": "سْوِم", "ex_en": "I can swim in the pool", "ar_ex": "أستطيع السباحة في البركة" },
  { "id": 44, "en": "watch cartoon", "ar": "يشاهد كرتون", "pronounce": "وُوتش كارتون", "ex_en": "Children love to watch cartoon weekly", "ar_ex": "الأطفال يحبون مشاهدة الكرتون أسبوعيًا" },
  { "id": 45, "en": "lunch", "ar": "الغداء", "pronounce": "لَنْتش", "ex_en": "Let us eat our delicious lunch", "ar_ex": "لنأكل غداءنا اللذيذ" },
  { "id": 46, "en": "dinner", "ar": "العشاء", "pronounce": "دِنَر", "ex_en": "We have light dinner at night", "ar_ex": "نتناول عشاءً خفيفًا في الليل" },
  { "id": 47, "en": "climbing frame", "ar": "إطار تسلق", "pronounce": "كْلايمِنغ فْريم", "ex_en": "Play safely on the climbing frame", "ar_ex": "العب بأمان على إطار التسلق" },
  { "id": 48, "en": "sand pit", "ar": "حفرة رمل", "pronounce": "ساند بِت", "ex_en": "The children sit in sand pit", "ar_ex": "الأطفال يجلسون في حفرة الرمل" },
  { "id": 49, "en": "seesaw", "ar": "أرجوحة", "pronounce": "سي سو", "ex_en": "We ride the seesaw with friends", "ar_ex": "نركب الأرجوحة (سي سو) مع الأصدقاء" },
  { "id": 50, "en": "slide", "ar": "زحليقة", "pronounce": "سْلايد", "ex_en": "Go down the long slide safely", "ar_ex": "انزل من على الزحليقة الطويلة بأمان" },
  { "id": 51, "en": "swing", "ar": "أرجوحة", "pronounce": "سْوِنغ", "ex_en": "I love the swing very much", "ar_ex": "أحب الأرجوحة كثيرًا" },
  { "id": 52, "en": "over", "ar": "فوق", "pronounce": "أوڤَر", "ex_en": "The bird flies over the tree", "ar_ex": "الطائر يطير فوق الشجرة" },
  { "id": 53, "en": "around", "ar": "حول", "pronounce": "أراوند", "ex_en": "Run around the big green playground", "ar_ex": "اركض حول الملعب الأخضر الكبير" },
  { "id": 54, "en": "up", "ar": "أعلى", "pronounce": "أَب", "ex_en": "Look up at the blue sky", "ar_ex": "انظر لأعلى نحو السماء الزرقاء" },
  { "id": 55, "en": "dancing dabka", "ar": "يرقص الدبكة", "pronounce": "دانسِنغ دَبْكا", "ex_en": "They are dancing dabka at party", "ar_ex": "هم يرقصون الدبكة في الحفلة" },
  { "id": 56, "en": "draw a picture", "ar": "يرسم صورة", "pronounce": "دْرو أ بكتشر", "ex_en": "Draw a picture of your family", "ar_ex": "ارسم صورة لعائلتك" },
  { "id": 57, "en": "paint", "ar": "يلوّن", "pronounce": "پِينت", "ex_en": "Paint the small room with white", "ar_ex": "لوّن الغرفة الصغيرة بالأبيض" },
  { "id": 58, "en": "play music", "ar": "يعزف موسيقى", "pronounce": "بلاي ميوزِك", "ex_en": "They play music in the class", "ar_ex": "هم يعزفون الموسيقى في الصف" },
  { "id": 59, "en": "show", "ar": "يُظهر", "pronounce": "شو", "ex_en": "Show me your new school bag", "ar_ex": "أرني حقيبتك المدرسية الجديدة" },
  { "id": 60, "en": "outdoor", "ar": "في الهواء الطلق", "pronounce": "آوتدور", "ex_en": "We like outdoor games very much", "ar_ex": "نحب الألعاب في الهواء الطلق كثيرًا" },
  { "id": 61, "en": "school", "ar": "مدرسة", "pronounce": "سْكول", "ex_en": "Go to school every morning early", "ar_ex": "اذهب للمدرسة كل صباح باكراً" },
  { "id": 62, "en": "swimming pool", "ar": "بركة سباحة", "pronounce": "سْوِمِنغ بول", "ex_en": "The swimming pool is very large", "ar_ex": "بركة السباحة كبيرة جداً" },
  { "id": 63, "en": "scarf", "ar": "وشاح", "pronounce": "سكارف", "ex_en": "Wear a warm wool scarf today", "ar_ex": "ارتدِ وشاحًا صوفيًا دافئًا اليوم" },
  { "id": 64, "en": "slippers", "ar": "شبشب", "pronounce": "سْلِبَرْز", "ex_en": "Put on your soft slippers now", "ar_ex": "ارتدِ شبشبك الناعم الآن" },
  { "id": 65, "en": "Australia", "ar": "أستراليا", "pronounce": "أُسْتريليا", "ex_en": "Australia is a very big country", "ar_ex": "أستراليا بلد كبير جدًا" },
  { "id": 66, "en": "trainers", "ar": "حذاء رياضي", "pronounce": "تْرِينَرْز", "ex_en": "Wear trainers for the running race", "ar_ex": "ارتدِ حذاءً رياضيًا لسباق الركض" },
  { "id": 67, "en": "I do not feel well", "ar": "لا أشعر أنني بخير", "pronounce": "آي دو نوت فيل وِل", "ex_en": "I do not feel well today", "ar_ex": "لا أشعر أنني بخير اليوم" },
  { "id": 68, "en": "stomach", "ar": "معدة", "pronounce": "سْتَمَك", "ex_en": "My stomach is full of food", "ar_ex": "معدتي مليئة بالطعام" },
  { "id": 69, "en": "hurt", "ar": "يؤلم", "pronounce": "هِرت", "ex_en": "Does your leg hurt you now?", "ar_ex": "هل ساقك تؤلمك الآن؟" },
  { "id": 70, "en": "rest", "ar": "راحة", "pronounce": "رِست", "ex_en": "Take a rest on the bed", "ar_ex": "خذ قسطًا من الراحة على التخت" },
  { "id": 71, "en": "medicine", "ar": "دواء", "pronounce": "مِدِسِن", "ex_en": "Take this useful medicine every evening", "ar_ex": "تناول هذا الدواء المفيد كل مساء" },
  { "id": 72, "en": "watch", "ar": "يشاهد / ساعة", "pronounce": "وُوتش", "ex_en": "I have a new gold watch", "ar_ex": "لدي ساعة ذهبية جديدة" },
  { "id": 73, "en": "do", "ar": "يفعل", "pronounce": "دو", "ex_en": "Do your school tasks carefully now", "ar_ex": "قم بمهامك المدرسية بعناية الآن" },
  { "id": 74, "en": "play", "ar": "يلعب", "pronounce": "بلاي", "ex_en": "Let us play table tennis together", "ar_ex": "لنلعب تنس الطاولة معًا" },
  { "id": 75, "en": "weather", "ar": "الطقس", "pronounce": "وِذَر", "ex_en": "The weather is fine thanks today", "ar_ex": "الطقس جيد اليوم شكرًا" },
  { "id": 76, "en": "rainy", "ar": "ممطر", "pronounce": "رَيْني", "ex_en": "The winter weather is always rainy", "ar_ex": "طقس الشتاء ممطر دائمًا" },
  { "id": 77, "en": "windy", "ar": "عاصف", "pronounce": "وِنْدي", "ex_en": "It is cold and windy today", "ar_ex": "الطقس بارد وعاصف اليوم" },
  { "id": 78, "en": "cloudy", "ar": "غائم", "pronounce": "كْلاودي", "ex_en": "The sky is very cloudy now", "ar_ex": "السماء غائمة جدًا الآن" },
  { "id": 79, "en": "cold", "ar": "بارد", "pronounce": "كولد", "ex_en": "Drink hot tea when it's cold", "ar_ex": "اشرب الشاي الساخن عندما يكون باردًا" },
  { "id": 80, "en": "sunny", "ar": "مشمس", "pronounce": "سَنّي", "ex_en": "Summer days are always very sunny", "ar_ex": "أيام الصيف مشمسة جدًا دائمًا" },
  { "id": 81, "en": "hot", "ar": "حار", "pronounce": "هوت", "ex_en": "Drink fresh juice when it's hot", "ar_ex": "اشرب عصيرًا طازجًا عندما يكون حارًا" },
  { "id": 82, "en": "snowy", "ar": "مثلج", "pronounce": "سْنُوي", "ex_en": "The high mountain is snowy today", "ar_ex": "الجبل المرتفع مثلج اليوم" },
  { "id": 83, "en": "Saturday", "ar": "السبت", "pronounce": "ساتَردَي", "ex_en": "I play football on Saturday morning", "ar_ex": "ألعَب كرة القدم صباح السبت" },
  { "id": 84, "en": "Sunday", "ar": "الأحد", "pronounce": "سَنْدي", "ex_en": "Sunday is a school day here", "ar_ex": "الأحد هو يوم مدرسة هنا" },
  { "id": 85, "en": "Monday", "ar": "الاثنين", "pronounce": "مَنْدي", "ex_en": "We study English every Monday morning", "ar_ex": "ندرس الإنجليزية كل صباح اثنين" },
  { "id": 86, "en": "Tuesday", "ar": "الثلاثاء", "pronounce": "تُوزدي", "ex_en": "I visit my grandfather on Tuesday", "ar_ex": "أزور جدي يوم الثلاثاء" },
  { "id": 87, "en": "Wednesday", "ar": "الأربعاء", "pronounce": "وِنزدي", "ex_en": "We play music every Wednesday afternoon", "ar_ex": "نعزف الموسيقى كل بعد ظهر أربعاء" },
  { "id": 88, "en": "Thursday", "ar": "الخميس", "pronounce": "ثِرْزدي", "ex_en": "Thursday is a lovely happy day", "ar_ex": "الخميس يوم جميل وسعيد" },
  { "id": 89, "en": "Friday", "ar": "الجمعة", "pronounce": "فْرايدي", "ex_en": "Friday is a happy family holiday", "ar_ex": "الجمعة عطلة عائلية سعيدة" },
  { "id": 90, "en": "one", "ar": "واحد", "pronounce": "وان", "ex_en": "I have one small red ball", "ar_ex": "لدي كرة حمراء صغيرة واحدة" },
  { "id": 91, "en": "two", "ar": "اثنان", "pronounce": "تو", "ex_en": "Count the two big green apples", "ar_ex": "عد التفاحتين الخضراوين الكبيرتين" },
  { "id": 92, "en": "three", "ar": "ثلاثة", "pronounce": "ثري", "ex_en": "There are three books on desk", "ar_ex": "يوجد ثلاثة كتب على المكتب" },
  { "id": 93, "en": "four", "ar": "أربعة", "pronounce": "فور", "ex_en": "Draw four small blue circles now", "ar_ex": "ارسم أربع دوائر زرقاء صغيرة الآن" },
  { "id": 94, "en": "five", "ar": "خمسة", "pronounce": "فايف", "ex_en": "I have five fingers on hand", "ar_ex": "لدي خمسة أصابع في اليد" },
  { "id": 95, "en": "six", "ar": "ستة", "pronounce": "سِكس", "ex_en": "There are six cats in box", "ar_ex": "يوجد ستة قطط في الصندوق" },
  { "id": 96, "en": "seven", "ar": "سبعة", "pronounce": "سِفِن", "ex_en": "I am seven years old now", "ar_ex": "عمري سبع سنوات الآن" },
  { "id": 97, "en": "eight", "ar": "ثمانية", "pronounce": "إيت", "ex_en": "Count eight white eggs, please look", "ar_ex": "عد ثماني بيضات بيضاء من فضلك" },
  { "id": 98, "en": "nine", "ar": "تسعة", "pronounce": "ناين", "ex_en": "Buy nine sweet oranges from shop", "ar_ex": "اشترِ تسع برتقالات حلوة من الدكان" },
  { "id": 99, "en": "ten", "ar": "عشرة", "pronounce": "تِن", "ex_en": "I have ten colorful pencils here", "ar_ex": "لدي عشرة أقلام رصاص ملونة هنا" },
  { "id": 100, "en": "eleven", "ar": "أحد عشر", "pronounce": "إِلِفِن", "ex_en": "There are eleven children in class", "ar_ex": "هناك أحد عشر طفلاً في الصف" },
  { "id": 101, "en": "twelve", "ar": "اثنا عشر", "pronounce": "توِلف", "ex_en": "Look at the twelve bright candles", "ar_ex": "انظر إلى الاثني عشر شمعة مضيئة" },
  { "id": 102, "en": "capital", "ar": "عاصمة", "pronounce": "كابِتَل", "ex_en": "What is the capital city here?", "ar_ex": "ما هي العاصمة هنا؟" },
  { "id": 103, "en": "Amman", "ar": "عمّان", "pronounce": "أَمّان", "ex_en": "Amman is a beautiful big city", "ar_ex": "عمان مدينة كبيرة وجميلة" },
  { "id": 104, "en": "Cairo", "ar": "القاهرة", "pronounce": "كايرو", "ex_en": "Cairo is the capital of Egypt", "ar_ex": "القاهرة هي عاصمة مصر" },
  { "id": 105, "en": "Bagdad", "ar": "بغداد", "pronounce": "باغداد", "ex_en": "Bagdad is an ancient great city", "ar_ex": "بغداد مدينة عظيمة قديمة" },
  { "id": 106, "en": "London", "ar": "لندن", "pronounce": "لَنْدَن", "ex_en": "London is a very rainy city", "ar_ex": "لندن مدينة ممطرة جدًا" },
  { "id": 107, "en": "Washington", "ar": "واشنطن", "pronounce": "واشِنغتَن", "ex_en": "Washington is a famous beautiful city", "ar_ex": "واشنطن مدينة جميلة مشهورة" },
  { "id": 108, "en": "beautiful", "ar": "جميل", "pronounce": "بْيُوتِفُل", "ex_en": "Palestine is a very beautiful country", "ar_ex": "فلسطين بلد جميل جداً" },
  { "id": 109, "en": "table tennis", "ar": "تنس الطاولة", "pronounce": "تايبل تِنِس", "ex_en": "We play table tennis at school", "ar_ex": "نحن نلعب تنس الطاولة في المدرسة" },
  { "id": 110, "en": "breakfast", "ar": "الفطور", "pronounce": "بْرِكفَست", "ex_en": "Eat healthy breakfast every morning early", "ar_ex": "تناول فطورًا صحيًا كل صباح باكرًا" },
  { "id": 111, "en": "volleyball", "ar": "كرة طائرة", "pronounce": "ڤولي بول", "ex_en": "They play volleyball in the playground", "ar_ex": "هم يلعبون الكرة الطائرة في الملعب" },
  { "id": 112, "en": "English", "ar": "إنجليزي", "pronounce": "إِنغْلِش", "ex_en": "I love my English lesson today", "ar_ex": "أنا أحب درس الإنجليزي اليوم" },
  { "id": 113, "en": "fun", "ar": "متعة", "pronounce": "فَن", "ex_en": "Playing with friends is great fun", "ar_ex": "اللعب مع الأصدقاء متعة كبيرة" },
  { "id": 114, "en": "boring", "ar": "ممل", "pronounce": "بورِنغ", "ex_en": "This long game is very boring", "ar_ex": "هذه اللعبة الطويلة مملة جدًا" },
  { "id": 115, "en": "easy", "ar": "سهل", "pronounce": "إيزي", "ex_en": "The math exam is very easy", "ar_ex": "امتحان الرياضيات سهل جدًا" },
  { "id": 116, "en": "difficult", "ar": "صعب", "pronounce": "دِفِكَلْت", "ex_en": "This puzzle is difficult to solve", "ar_ex": "هذه الأحجية صعبة الحل" },
  { "id": 117, "en": "great", "ar": "عظيم", "pronounce": "غْريت", "ex_en": "You did a great job today", "ar_ex": "لقد قمت بعمل عظيم اليوم" },
  { "id": 118, "en": "my favorite", "ar": "المفضل لدي", "pronounce": "ماي فَيْفَرِت", "ex_en": "Red is my favorite bright color", "ar_ex": "الأحمر هو لوني المشرق المفضل" },
  { "id": 119, "en": "I", "ar": "أنا", "pronounce": "آي", "ex_en": "I am a smart school student", "ar_ex": "أنا طالب مدرسي ذكي" },
  { "id": 120, "en": "you", "ar": "أنت", "pronounce": "يو", "ex_en": "You are my best kind friend", "ar_ex": "أنت صديقي الطيب المفضل" },
  { "id": 121, "en": "we", "ar": "نحن", "pronounce": "وي", "ex_en": "We love our school very much", "ar_ex": "نحن نحب مدرستنا كثيرًا" },
  { "id": 122, "en": "they", "ar": "هم", "pronounce": "ذَي", "ex_en": "They play football in playground daily", "ar_ex": "هم يلعبون كرة القدم في الملعب يوميًا" },
  { "id": 123, "en": "he", "ar": "هو", "pronounce": "هي", "ex_en": "He is a good clever boy", "ar_ex": "هو ولد ذكي وصالح" },
  { "id": 124, "en": "she", "ar": "هي", "pronounce": "شي", "ex_en": "She draws a nice picture today", "ar_ex": "هي ترسم صورة جميلة اليوم" },
  { "id": 125, "en": "my", "ar": "لي", "pronounce": "ماي", "ex_en": "This is my new blue pen", "ar_ex": "هذا قلمي الأزرق الجديد" },
  { "id": 126, "en": "your", "ar": "لك", "pronounce": "يُور", "ex_en": "Where is your school bag, boy?", "ar_ex": "أين حقيبتك المدرسية يا ولد؟" },
  { "id": 127, "en": "his", "ar": "له", "pronounce": "هِز", "ex_en": "His dad is a kind teacher", "ar_ex": "والده معلم طيب" },
  { "id": 128, "en": "her", "ar": "لها", "pronounce": "هِر", "ex_en": "Her dress is very beautiful pink", "ar_ex": "فستانها وردي جميل جدًا" },
  { "id": 129, "en": "our", "ar": "لنا", "pronounce": "آوَر", "ex_en": "Our classroom is nice and clean", "ar_ex": "صفنا جميل ونظيف" },
  { "id": 130, "en": "their", "ar": "لهم", "pronounce": "ذِير", "ex_en": "Their house is near the mosque", "ar_ex": "منزلهم قريب من المسجد" },
  { "id": 131, "en": "Britain", "ar": "بريطانيا", "pronounce": "بِرِتِن", "ex_en": "He comes from Britain city now", "ar_ex": "هو يأتي من بريطانيا الآن" },
  { "id": 132, "en": "United States", "ar": "الولايات المتحدة", "pronounce": "يُونايتِد سْتيتس", "ex_en": "The United States is very big", "ar_ex": "الولايات المتحدة كبيرة جدًا" }
];