const levelCLASS6_Words = [
  { "id": 1, "en": "awful", "ar": "مريع", "pronounce": "أُوفُل", "ex_en": "The weather is awful today", "ar_ex": "الطقس مريع اليوم" },
  { "id": 2, "en": "a little", "ar": "قليل", "pronounce": "أ لِتِل", "ex_en": "I need a little water", "ar_ex": "أحتاج قليلاً من الماء" },
  { "id": 3, "en": "fizzy drink", "ar": "مشروب غازي", "pronounce": "فِزي دْرِنك", "ex_en": "I like a fizzy drink", "ar_ex": "أحب المشروب الغازي" },
  { "id": 4, "en": "funny", "ar": "مضحك", "pronounce": "فَني", "ex_en": "He tells a funny story", "ar_ex": "هو يروي قصة مضحكة" },
  { "id": 5, "en": "hungry", "ar": "جائع", "pronounce": "هَنگري", "ex_en": "I am very hungry now", "ar_ex": "أنا جائع جداً الآن" },
  { "id": 6, "en": "noise", "ar": "ضجيج", "pronounce": "نويز", "ex_en": "Don't make any noise", "ar_ex": "لا تصدر أي ضجيج" },
  { "id": 7, "en": "other", "ar": "آخر", "pronounce": "أَذَر", "ex_en": "Give me the other book", "ar_ex": "أعطني الكتاب الآخر" },
  { "id": 8, "en": "safe", "ar": "آمن", "pronounce": "سيف", "ex_en": "It is safe here", "ar_ex": "إنه آمن هنا" },
  { "id": 9, "en": "million", "ar": "مليون", "pronounce": "مِلْيَن", "ex_en": "I have a million ideas", "ar_ex": "لدي مليون فكرة" },
  { "id": 10, "en": "still (remain)", "ar": "ما زال / يبقى", "pronounce": "سْتِل", "ex_en": "He is still here", "ar_ex": "هو ما زال هنا" },
  { "id": 11, "en": "sweet", "ar": "حلو", "pronounce": "سْوِيت", "ex_en": "The cake is sweet", "ar_ex": "الكعكة حلوة المذاق" },
  { "id": 12, "en": "useful", "ar": "مفيد", "pronounce": "يُوسْفُل", "ex_en": "This app is useful", "ar_ex": "هذا التطبيق مفيد" },
  { "id": 13, "en": "wise", "ar": "حكيم", "pronounce": "وايز", "ex_en": "The old man is wise", "ar_ex": "الرجل العجوز حكيم" },
  { "id": 14, "en": "because", "ar": "لأن", "pronounce": "بِكوز", "ex_en": "I run because I'm late", "ar_ex": "أركض لأنني متأخر" },
  { "id": 15, "en": "but", "ar": "لكن", "pronounce": "بَت", "ex_en": "I want but I can't", "ar_ex": "أريد لكن لا أستطيع" },
  { "id": 16, "en": "when", "ar": "عندما", "pronounce": "وِن", "ex_en": "Call me when you arrive", "ar_ex": "اتصل بي عندما تصل" },
  { "id": 17, "en": "while", "ar": "بينما", "pronounce": "وايل", "ex_en": "Study while you are young", "ar_ex": "ادرس بينما أنت صغير" },
  { "id": 18, "en": "agree", "ar": "يوافق", "pronounce": "أگري", "ex_en": "I agree with you", "ar_ex": "أنا أوافقك الرأي" },
  { "id": 19, "en": "become", "ar": "يصبح", "pronounce": "بِكَم", "ex_en": "He will become a doctor", "ar_ex": "سيصبح طبيباً" },
  { "id": 20, "en": "change", "ar": "يغيّر", "pronounce": "تشينج", "ex_en": "Please change your clothes", "ar_ex": "من فضلك غير ملابسك" },
  { "id": 21, "en": "explore", "ar": "يستكشف", "pronounce": "إكْسْپلور", "ex_en": "We explore the desert", "ar_ex": "نحن نستكشف الصحراء" },
  { "id": 22, "en": "(in a) hurry", "ar": "على عجلة", "pronounce": "هَري", "ex_en": "Don't be in a hurry", "ar_ex": "لا تكن على عجلة" },
  { "id": 23, "en": "rise", "ar": "يرتفع", "pronounce": "رايز", "ex_en": "The sun will rise soon", "ar_ex": "الشمس ستشرق قريباً" },
  { "id": 24, "en": "sail", "ar": "يبحر", "pronounce": "سَيْل", "ex_en": "They sail across the sea", "ar_ex": "هم يبحرون عبر البحر" },
  { "id": 25, "en": "good actions", "ar": "تصرفات جيدة", "pronounce": "غود آكشنز", "ex_en": "Help others with good actions", "ar_ex": "ساعد الآخرين بتصرفات جيدة" },
  { "id": 26, "en": "brave", "ar": "شجاع", "pronounce": "بْريف", "ex_en": "The soldier is very brave", "ar_ex": "الجندي شجاع جداً" },
  { "id": 27, "en": "hope", "ar": "يأمل", "pronounce": "هوب", "ex_en": "I hope you are fine", "ar_ex": "آمل أن تكون بخير" },
  { "id": 28, "en": "notice", "ar": "يلاحظ", "pronounce": "نوتِس", "ex_en": "Did you notice the bird?", "ar_ex": "هل لاحظت الطائر؟" },
  { "id": 29, "en": "promise", "ar": "يعد", "pronounce": "پْرومِس", "ex_en": "I promise to study hard", "ar_ex": "أعد بالدراسة بجد" },
  { "id": 30, "en": "sore throat", "ar": "التهاب الحلق", "pronounce": "سور ثْرُوت", "ex_en": "I have a sore throat", "ar_ex": "لدي التهاب في الحلق" },
  { "id": 31, "en": "stomachache", "ar": "ألم المعدة", "pronounce": "سْتَمَك إيك", "ex_en": "He has a bad stomachache", "ar_ex": "لديه ألم معدة شديد" },
  { "id": 32, "en": "thirsty", "ar": "عطشان", "pronounce": "ثِرْسْتي", "ex_en": "I am very thirsty now", "ar_ex": "أنا عطشان جداً الآن" },
  { "id": 33, "en": "compass", "ar": "بوصلة", "pronounce": "كُمْپَس", "ex_en": "Use the compass to find", "ar_ex": "استخدم البوصلة لتجد الطريق" },
  { "id": 34, "en": "queue", "ar": "طابور", "pronounce": "كْيُو", "ex_en": "Stand in the queue please", "ar_ex": "قف في الطابور من فضلك" },
  { "id": 35, "en": "skin", "ar": "جلد", "pronounce": "سْكِن", "ex_en": "Protect your skin from sun", "ar_ex": "احمِ جلدك من الشمس" },
  { "id": 36, "en": "explorer", "ar": "مستكشف", "pronounce": "إكْسْپلورَر", "ex_en": "He is a great explorer", "ar_ex": "هو مستكشف عظيم" },
  { "id": 37, "en": "librarian", "ar": "أمين مكتبة", "pronounce": "لايبْرِيرْيَن", "ex_en": "The librarian helped me today", "ar_ex": "أمين المكتبة ساعدني اليوم" },
  { "id": 38, "en": "man", "ar": "رجل", "pronounce": "مان", "ex_en": "That man is my uncle", "ar_ex": "ذلك الرجل هو عمي" },
  { "id": 39, "en": "neighbor", "ar": "جار", "pronounce": "نَيْبَر", "ex_en": "My neighbor is very kind", "ar_ex": "جاري لطيف جداً" },
  { "id": 40, "en": "woman", "ar": "امرأة", "pronounce": "وُمَن", "ex_en": "The woman is reading books", "ar_ex": "المرأة تقرأ كتباً" },
  { "id": 41, "en": "cave", "ar": "كهف", "pronounce": "كَيْف", "ex_en": "There is a dark cave", "ar_ex": "هناك كهف مظلم" },
  { "id": 42, "en": "earth", "ar": "الأرض", "pronounce": "إيرث", "ex_en": "We live on the earth", "ar_ex": "نحن نعيش على الأرض" },
  { "id": 43, "en": "east", "ar": "الشرق", "pronounce": "إيست", "ex_en": "The sun rises in east", "ar_ex": "الشمس تشرق من الشرق" },
  { "id": 44, "en": "library", "ar": "مكتبة", "pronounce": "لايبرَري", "ex_en": "I go to the library", "ar_ex": "أنا أذهب إلى المكتبة" },
  { "id": 45, "en": "ocean", "ar": "محيط", "pronounce": "أُوشِن", "ex_en": "The ocean is very big", "ar_ex": "المحيط كبير جداً" },
  { "id": 46, "en": "south", "ar": "الجنوب", "pronounce": "ساوث", "ex_en": "Travel to the south now", "ar_ex": "سافر إلى الجنوب الآن" },
  { "id": 47, "en": "west", "ar": "الغرب", "pronounce": "وِست", "ex_en": "He lives in the west", "ar_ex": "هو يعيش في الغرب" },
  { "id": 48, "en": "above", "ar": "فوق", "pronounce": "أَبَڤ", "ex_en": "The bird is above us", "ar_ex": "الطائر فوقنا" },
  { "id": 49, "en": "anywhere", "ar": "أي مكان", "pronounce": "إيني وِير", "ex_en": "I can go anywhere today", "ar_ex": "أستطيع الذهاب لأي مكان" },
  { "id": 50, "en": "into", "ar": "إلى داخل", "pronounce": "إنتو", "ex_en": "Go into the room now", "ar_ex": "ادخل إلى الغرفة الآن" },
  { "id": 51, "en": "adventure", "ar": "مغامرة", "pronounce": "أَدڤِنْتْشَر", "ex_en": "It is a great adventure", "ar_ex": "إنها مغامرة عظيمة" },
  { "id": 52, "en": "exploring", "ar": "استكشاف", "pronounce": "إكْسْپلورِنغ", "ex_en": "I like exploring new places", "ar_ex": "أحب استكشاف أماكن جديدة" },
  { "id": 53, "en": "coral", "ar": "مرجان", "pronounce": "كُورَل", "ex_en": "The coral is very colorful", "ar_ex": "المرجان ملون جداً" },
  { "id": 54, "en": "flippers", "ar": "زعانف", "pronounce": "فْلِپَرْز", "ex_en": "Wear your flippers for swimming", "ar_ex": "ارتدِ زعانفك للسباحة" },
  { "id": 55, "en": "goggles", "ar": "نظارات سباحة", "pronounce": "غوغِلز", "ex_en": "Use goggles in the pool", "ar_ex": "استخدم النظارات في المسبح" },
  { "id": 56, "en": "sunrise", "ar": "شروق الشمس", "pronounce": "سَنْرايز", "ex_en": "I love the sunrise time", "ar_ex": "أحب وقت شروق الشمس" },
  { "id": 57, "en": "sunset", "ar": "غروب الشمس", "pronounce": "سَنْسِت", "ex_en": "The sunset is beautiful today", "ar_ex": "غروب الشمس جميل اليوم" },
  { "id": 58, "en": "ever", "ar": "في أي وقت", "pronounce": "إِڤَر", "ex_en": "Have you ever been there?", "ar_ex": "هل سبق لك الذهاب هناك؟" },
  { "id": 59, "en": "for", "ar": "لمدة / لـ", "pronounce": "فور", "ex_en": "I waited for one hour", "ar_ex": "انتظرت لمدة ساعة واحدة" },
  { "id": 60, "en": "never", "ar": "أبدًا", "pronounce": "نِڤَر", "ex_en": "I will never lie again", "ar_ex": "لن أكذب أبداً مجدداً" },
  { "id": 61, "en": "since", "ar": "منذ", "pronounce": "سِنْس", "ex_en": "I have been here since", "ar_ex": "أنا هنا منذ الصباح" },
  { "id": 62, "en": "until", "ar": "حتى", "pronounce": "أَنْتِل", "ex_en": "Wait until I come back", "ar_ex": "انتظر حتى أعود" },
  { "id": 63, "en": "(water) cycle", "ar": "دورة الماء", "pronounce": "ووتر سايكل", "ex_en": "The water cycle is important", "ar_ex": "دورة الماء مهمة" },
  { "id": 64, "en": "air", "ar": "هواء", "pronounce": "إير", "ex_en": "The air is very clean", "ar_ex": "الهواء نظيف جداً" },
  { "id": 65, "en": "rain", "ar": "مطر", "pronounce": "رين", "ex_en": "I like the heavy rain", "ar_ex": "أحب المطر الغزير" },
  { "id": 66, "en": "sun", "ar": "شمس", "pronounce": "سَن", "ex_en": "The sun is very hot", "ar_ex": "الشمس حارة جداً" },
  { "id": 67, "en": "vapor", "ar": "بخار", "pronounce": "ڤَيْپَر", "ex_en": "Water turns into steam vapor", "ar_ex": "الماء يتحول إلى بخار" },
  { "id": 68, "en": "correct", "ar": "صحيح", "pronounce": "كُرِكت", "ex_en": "That is the correct answer", "ar_ex": "تلك هي الإجابة الصحيحة" },
  { "id": 69, "en": "bug", "ar": "جرثومة", "pronounce": "بَغ", "ex_en": "Wash hands to avoid bugs", "ar_ex": "اغسل يديك لتجنب الجراثيم" },
  { "id": 70, "en": "cold", "ar": "زكام", "pronounce": "كولد", "ex_en": "I have a bad cold", "ar_ex": "لدي زكام شديد" },
  { "id": 71, "en": "cough", "ar": "سعال", "pronounce": "كوف", "ex_en": "He has a loud cough", "ar_ex": "هو لديه سعال عالٍ" },
  { "id": 72, "en": "earache", "ar": "ألم الأذن", "pronounce": "إير إيك", "ex_en": "She has a bad earache", "ar_ex": "هي لديها ألم أذن" },
  { "id": 73, "en": "fever", "ar": "حمى", "pronounce": "فيڤَر", "ex_en": "He has a high fever", "ar_ex": "هو لديه حمى مرتفعة" },
  { "id": 74, "en": "flu", "ar": "إنفلونزا", "pronounce": "فْلو", "ex_en": "The flu is very common", "ar_ex": "الإنفلونزا شائعة جداً" },
  { "id": 75, "en": "sick", "ar": "مريض", "pronounce": "سِك", "ex_en": "He is too sick today", "ar_ex": "هو مريض جداً اليوم" },
  { "id": 76, "en": "sneeze", "ar": "يعطس", "pronounce": "سْنِيز", "ex_en": "Cover your mouth when sneeze", "ar_ex": "غطِّ فمك عند العطس" },
  { "id": 77, "en": "summer camp", "ar": "مخيم صيفي", "pronounce": "سَمَر كامب", "ex_en": "I go to summer camp", "ar_ex": "أنا أذهب للمخيم الصيفي" },
  { "id": 78, "en": "stairs", "ar": "درج", "pronounce": "ستيرز", "ex_en": "Do not run on stairs", "ar_ex": "لا تركض على الدرج" },
  { "id": 79, "en": "accident", "ar": "حادث", "pronounce": "أَكْسِدِنت", "ex_en": "Be careful to avoid accidents", "ar_ex": "كن حذراً لتجنب الحوادث" },
  { "id": 80, "en": "anyone", "ar": "أي شخص", "pronounce": "أَني وُن", "ex_en": "Can anyone help me now?", "ar_ex": "هل يستطيع أحد مساعدتي؟" },
  { "id": 81, "en": "someone", "ar": "شخص ما", "pronounce": "سَم وُن", "ex_en": "Someone is knocking the door", "ar_ex": "شخص ما يطرق الباب" },
  { "id": 82, "en": "together", "ar": "معًا", "pronounce": "تُگِذَر", "ex_en": "We study together every day", "ar_ex": "نحن ندرس معاً كل يوم" },
  { "id": 83, "en": "hundred", "ar": "مئة", "pronounce": "هَندْرِد", "ex_en": "I have a hundred pens", "ar_ex": "لدي مئة قلم" },
  { "id": 84, "en": "thousand", "ar": "ألف", "pronounce": "ثاوزَند", "ex_en": "It costs a thousand dollars", "ar_ex": "تكلفته ألف دولار" },
  { "id": 85, "en": "argue", "ar": "يجادل", "pronounce": "آرغْيُو", "ex_en": "Do not argue with me", "ar_ex": "لا تجادل معي" },
  { "id": 86, "en": "attack", "ar": "يهاجم", "pronounce": "أتاك", "ex_en": "The dog might attack you", "ar_ex": "الكلب قد يهاجمك" },
  { "id": 87, "en": "back (return)", "ar": "يعود", "pronounce": "باك", "ex_en": "I will be back soon", "ar_ex": "سأعود قريباً" },
  { "id": 88, "en": "bang (into something)", "ar": "يصطدم", "pronounce": "بانغ", "ex_en": "Don't bang into the wall", "ar_ex": "لا تصطدم بالحائط" },
  { "id": 89, "en": "be tired", "ar": "يكون متعبًا", "pronounce": "بي تايِرد", "ex_en": "You seem to be tired", "ar_ex": "تبدو متعباً" },
  { "id": 90, "en": "boil (water)", "ar": "يغلي", "pronounce": "بويل", "ex_en": "Please boil the water now", "ar_ex": "من فضلك اغلي الماء الآن" },
  { "id": 91, "en": "burst (something)", "ar": "ينفجر", "pronounce": "بَرْست", "ex_en": "The balloon might burst now", "ar_ex": "البالون قد ينفجر الآن" },
  { "id": 92, "en": "call", "ar": "ينادي", "pronounce": "كول", "ex_en": "Please call your friend now", "ar_ex": "من فضلك نادِ صديقك" },
  { "id": 93, "en": "chase", "ar": "يطارد", "pronounce": "تشيس", "ex_en": "The cat will chase mice", "ar_ex": "القط سيطارد الفئران" },
  { "id": 94, "en": "could (polite request)", "ar": "هل يمكن", "pronounce": "كُد", "ex_en": "Could you help me please?", "ar_ex": "هل يمكنك مساعدتي من فضلك؟" },
  { "id": 95, "en": "crash (into something)", "ar": "يصطدم", "pronounce": "كراش", "ex_en": "Cars might crash if fast", "ar_ex": "السيارات قد تصطدم إذا أسرعت" },
  { "id": 96, "en": "cry", "ar": "يبكي", "pronounce": "كراي", "ex_en": "Do not cry my friend", "ar_ex": "لا تبكِ يا صديقي" },
  { "id": 97, "en": "fall (down)", "ar": "يسقط", "pronounce": "فول", "ex_en": "Be careful not to fall", "ar_ex": "احذر أن تسقط" },
  { "id": 98, "en": "fight", "ar": "يقاتل", "pronounce": "فايت", "ex_en": "We should not fight ever", "ar_ex": "يجب ألا نقاتل أبداً" },
  { "id": 99, "en": "fry", "ar": "يقلي", "pronounce": "فراي", "ex_en": "I will fry the fish", "ar_ex": "سأقلي السمك" },
  { "id": 100, "en": "give back", "ar": "يعيد", "pronounce": "غِف باك", "ex_en": "Please give back my pen", "ar_ex": "أعد لي قلمي من فضلك" },
  { "id": 101, "en": "happen", "ar": "يحدث", "pronounce": "هابِن", "ex_en": "What did happen today?", "ar_ex": "ماذا حدث اليوم؟" },
  { "id": 102, "en": "harvest", "ar": "يحصد", "pronounce": "هارڤِست", "ex_en": "Farmers harvest the crops now", "ar_ex": "المزارعون يحصدون المحاصيل الآن" },
  { "id": 103, "en": "invite", "ar": "يدعو", "pronounce": "إنڤايت", "ex_en": "I will invite my friends", "ar_ex": "سأدعو أصدقائي" },
  { "id": 104, "en": "lend (≠ borrow)", "ar": "يُقرض", "pronounce": "لِند", "ex_en": "Can you lend me money?", "ar_ex": "هل يمكنك إقراضي المال؟" },
  { "id": 105, "en": "take turns", "ar": "يتناوب", "pronounce": "تيك تِرنز", "ex_en": "We must take turns now", "ar_ex": "يجب أن نتناوب الآن" },
  { "id": 106, "en": "bad actions", "ar": "تصرفات سيئة", "pronounce": "باد آكشنز", "ex_en": "Stop doing those bad actions", "ar_ex": "توقف عن تلك التصرفات السيئة" },
  { "id": 107, "en": "complain", "ar": "يشتكي", "pronounce": "كُمْپْلين", "ex_en": "Do not complain about everything", "ar_ex": "لا تشتكِ من كل شيء" },
  { "id": 108, "en": "hate", "ar": "يكره", "pronounce": "هيت", "ex_en": "I do not hate anyone", "ar_ex": "أنا لا أكره أحداً" },
  { "id": 109, "en": "interrupt", "ar": "يقاطع", "pronounce": "إِنترَبْت", "ex_en": "Do not interrupt the speaker", "ar_ex": "لا تقاطع المتحدث" },
  { "id": 110, "en": "lie", "ar": "يكذب", "pronounce": "لاي", "ex_en": "It is wrong to lie", "ar_ex": "من الخطأ أن تكذب" },
  { "id": 111, "en": "push (in)", "ar": "يدفع", "pronounce": "پُش", "ex_en": "Do not push your friends", "ar_ex": "لا تدفع أصدقاءك" },
  { "id": 112, "en": "shout", "ar": "يصرخ", "pronounce": "شاوْت", "ex_en": "It is rude to shout", "ar_ex": "من الوقاحة أن تصرخ" },
  { "id": 113, "en": "bat", "ar": "خفاش", "pronounce": "بات", "ex_en": "The bat flies at night", "ar_ex": "الخفاش يطير ليلاً" },
  { "id": 114, "en": "desert animals", "ar": "حيوانات الصحراء", "pronounce": "دِزِرت آنِمَلز", "ex_en": "I like desert animals much", "ar_ex": "أحب حيوانات الصحراء كثيراً" },
  { "id": 115, "en": "gazelle", "ar": "غزال", "pronounce": "گَزِل", "ex_en": "The gazelle runs very fast", "ar_ex": "الغزال يجري بسرعة كبيرة" },
  { "id": 116, "en": "hedgehog", "ar": "قنفذ", "pronounce": "هدجْهُوغ", "ex_en": "The hedgehog has many spines", "ar_ex": "القنفذ لديه أشواك كثيرة" },
  { "id": 117, "en": "jerboa", "ar": "يربوع", "pronounce": "جِربوا", "ex_en": "The jerboa lives in desert", "ar_ex": "اليربوع يعيش في الصحراء" },
  { "id": 118, "en": "oasis", "ar": "واحة", "pronounce": "أُوَيْسِس", "ex_en": "We found a beautiful oasis", "ar_ex": "وجدنا واحة جميلة" },
  { "id": 119, "en": "palm tree", "ar": "نخلة", "pronounce": "پام تري", "ex_en": "The palm tree is tall", "ar_ex": "النخلة طويلة" },
  { "id": 120, "en": "rock", "ar": "صخرة", "pronounce": "روك", "ex_en": "Sit on that big rock", "ar_ex": "اجلس على تلك الصخرة" },
  { "id": 121, "en": "spring", "ar": "نبع", "pronounce": "سْبرِنغ", "ex_en": "Water comes from the spring", "ar_ex": "الماء يأتي من النبع" },
  { "id": 122, "en": "star", "ar": "نجمة", "pronounce": "ستار", "ex_en": "I see a bright star", "ar_ex": "أرى نجمة ساطعة" },
  { "id": 123, "en": "wild cat", "ar": "قط بري", "pronounce": "وايلد كات", "ex_en": "The wild cat is dangerous", "ar_ex": "القط البري خطير" },
  { "id": 124, "en": "below sea level", "ar": "تحت مستوى البحر", "pronounce": "بِلُو سي لِڤِل", "ex_en": "It is below sea level", "ar_ex": "إنها تحت مستوى البحر" },
  { "id": 125, "en": "mud", "ar": "طين", "pronounce": "مَد", "ex_en": "Don't walk on the mud", "ar_ex": "لا تمشِ على الطين" },
  { "id": 126, "en": "salty", "ar": "مالح", "pronounce": "سُولتي", "ex_en": "The sea water is salty", "ar_ex": "ماء البحر مالح" },
  { "id": 127, "en": "friendly", "ar": "ودود", "pronounce": "فْرِندلي", "ex_en": "My cat is very friendly", "ar_ex": "قطتي ودودة جداً" },
  { "id": 128, "en": "generous", "ar": "كريم", "pronounce": "جِنِرَس", "ex_en": "He is a generous man", "ar_ex": "هو رجل كريم" },
  { "id": 129, "en": "helpful", "ar": "مفيد", "pronounce": "هِلْپْفُل", "ex_en": "You are a helpful person", "ar_ex": "أنت شخص مفيد" },
  { "id": 130, "en": "honest", "ar": "أمين", "pronounce": "أُونِسْت", "ex_en": "Always be an honest person", "ar_ex": "كن دائماً شخصاً أميناً" },
  { "id": 131, "en": "kind", "ar": "لطيف", "pronounce": "كايند", "ex_en": "Be kind to your friends", "ar_ex": "كن لطيفاً مع أصدقائك" },
  { "id": 132, "en": "polite", "ar": "مؤدب", "pronounce": "پولايت", "ex_en": "Always act in polite way", "ar_ex": "تصرف دائماً بطريقة مؤدبة" },
  { "id": 133, "en": "carefully", "ar": "بحذر", "pronounce": "كِيرفُلي", "ex_en": "Drive the car very carefully", "ar_ex": "قد السيارة بحذر شديد" },
  { "id": 134, "en": "clearly", "ar": "بوضوح", "pronounce": "كْلِيرلي", "ex_en": "Speak clearly to the people", "ar_ex": "تحدث بوضوح مع الناس" },
  { "id": 135, "en": "correctly", "ar": "بشكل صحيح", "pronounce": "كُرِكتلي", "ex_en": "Answer all questions correctly now", "ar_ex": "أجب على الأسئلة بشكل صحيح" },
  { "id": 136, "en": "loudly", "ar": "بصوت عالٍ", "pronounce": "لاودلي", "ex_en": "Don't speak so loudly please", "ar_ex": "لا تتحدث بصوت عالٍ من فضلك" },
  { "id": 137, "en": "noisily", "ar": "بضوضاء", "pronounce": "نويزِلي", "ex_en": "They play very noisily here", "ar_ex": "هم يلعبون بضوضاء هنا" },
  { "id": 138, "en": "politely", "ar": "بأدب", "pronounce": "پولايتلي", "ex_en": "Talk to your teacher politely", "ar_ex": "تحدث مع معلمك بأدب" },
  { "id": 139, "en": "quickly", "ar": "بسرعة", "pronounce": "كْوِكْلي", "ex_en": "Run quickly to the class", "ar_ex": "اركض بسرعة إلى الصف" },
  { "id": 140, "en": "quietly", "ar": "بهدوء", "pronounce": "كْوايِتلي", "ex_en": "Read the books very quietly", "ar_ex": "اقرأ الكتب بهدوء تام" },
  { "id": 141, "en": "rudely", "ar": "بوقاحة", "pronounce": "رودلي", "ex_en": "Do not act so rudely", "ar_ex": "لا تتصرف بوقاحة" },
  { "id": 142, "en": "safely", "ar": "بأمان", "pronounce": "سَيْفلي", "ex_en": "Travel home safely my friend", "ar_ex": "سافر للبيت بأمان يا صديقي" },
  { "id": 143, "en": "backache", "ar": "ألم الظهر", "pronounce": "باك إيك", "ex_en": "I have a bad backache", "ar_ex": "لدي ألم ظهر شديد" }
];