// words.js
const levelA1_Words = [
    { id: 1, en: "a/an", ar: "أداة نكرة", pronounce: "ا / أن", ex_en: "I am a student", ar_ex: "أنا طالب" },
    { id: 2, en: "about", ar: "عن", pronounce: "أباوت", ex_en: "I talk about you", ar_ex: "أنا أتحدث عنك" },
    { id: 3, en: "above", ar: "فوق", pronounce: "أبف", ex_en: "The plane is above us", ar_ex: "الطائرة فوقنا" },
    { id: 4, en: "across", ar: "عبر", pronounce: "أكروس", ex_en: "I walked across the street", ar_ex: "مشيت عبر الشارع" },
    { id: 5, en: "action", ar: "حركة", pronounce: "أكشن", ex_en: "This is an action movie", ar_ex: "هذا فيلم مليء بالحركة" },
    { id: 6, en: "activity", ar: "نشاط", pronounce: "أكتفتي", ex_en: "The activity is fun", ar_ex: "النشاط ممتع" },
    { id: 7, en: "actor", ar: "ممثل", pronounce: "أكتر", ex_en: "He is an actor", ar_ex: "هو ممثل مشهور" },
    { id: 8, en: "actress", ar: "ممثلة", pronounce: "أكترس", ex_en: "She is an actress", ar_ex: "هي ممثلة" },
    { id: 9, en: "add", ar: "يضيف", pronounce: "أد", ex_en: "I add sugar", ar_ex: "أضيف السكر" },
    { id: 10, en: "address", ar: "عنوان", pronounce: "آدرس", ex_en: "This is my address", ar_ex: "هذا هو عنواني" },
    { id: 11, en: "adult", ar: "بالغ", pronounce: "أدلت", ex_en: "He is an adult", ar_ex: "هو شخص بالغ" },
    { id: 12, en: "afraid", ar: "خائف", pronounce: "أفريد", ex_en: "I am afraid", ar_ex: "أنا خائف" },
    { id: 13, en: "after", ar: "بعد", pronounce: "أفتر", ex_en: "After school", ar_ex: "بعد المدرسة" },
    { id: 14, en: "afternoon", ar: "بعد الظهر", pronounce: "أفترنون", ex_en: "We meet in the afternoon", ar_ex: "نلتقي بعد الظهر" },
    { id: 15, en: "again", ar: "مرة أخرى", pronounce: "أجين", ex_en: "Try again", ar_ex: "حاول مرة أخرى" },
    { id: 16, en: "age", ar: "عمر", pronounce: "إيج", ex_en: "My age is 20", ar_ex: "عمري 20 سنة" },
    { id: 17, en: "ago", ar: "منذ", pronounce: "أغو", ex_en: "A long time ago", ar_ex: "منذ زمن طويل" },
    { id: 18, en: "air", ar: "هواء", pronounce: "إير", ex_en: "The air is clean", ar_ex: "الهواء نقي" },
    { id: 19, en: "airport", ar: "مطار", pronounce: "إيربورت", ex_en: "I am at the airport", ar_ex: "أنا في المطار" },
    { id: 20, en: "all", ar: "كل", pronounce: "أول", ex_en: "All students are here", ar_ex: "كل الطلاب هنا" },
    { id: 21, en: "all right", ar: "بخير", pronounce: "أول رايت", ex_en: "Everything is all right", ar_ex: "كل شيء على ما يرام" },
    { id: 22, en: "also", ar: "أيضاً", pronounce: "أولسو", ex_en: "I also like coffee", ar_ex: "أنا أيضاً أحب القهوة" },
    { id: 23, en: "always", ar: "دائماً", pronounce: "أولويز", ex_en: "I always wake up early", ar_ex: "أنا دائماً أستيقظ مبكراً" },
    { id: 24, en: "amazing", ar: "مذهل", pronounce: "أَميزنغ", ex_en: "This is amazing", ar_ex: "هذا رائع جداً" },
    { id: 25, en: "and", ar: "و", pronounce: "أند", ex_en: "You and I are friends", ar_ex: "أنا وأنت أصدقاء" },
	{ id: 26, en: "angry", ar: "غاضب", pronounce: "أنغري", ex_en: "He is angry today", ar_ex: "هو غاضب اليوم" },
    { id: 27, en: "animal", ar: "حيوان", pronounce: "أنيمَل", ex_en: "I have an animal", ar_ex: "لدي حيوان أليف" },
    { id: 28, en: "another", ar: "آخر", pronounce: "أنذر", ex_en: "I want another cup", ar_ex: "أريد كوباً آخر" },
    { id: 29, en: "answer (v)", ar: "يجيب", pronounce: "آنسر", ex_en: "I answer the question", ar_ex: "أجيب على السؤال" },
    { id: 30, en: "answer (n)", ar: "جواب", pronounce: "آنسر", ex_en: "This is the answer", ar_ex: "هذا هو الجواب" },
    { id: 31, en: "any", ar: "أي", pronounce: "إني", ex_en: "Do you have any question?", ar_ex: "هل لديك أي سؤال؟" },
    { id: 32, en: "anyone", ar: "أي شخص", pronounce: "إني ون", ex_en: "Is anyone here?", ar_ex: "هل هناك أي شخص؟" },
    { id: 33, en: "anything", ar: "أي شيء", pronounce: "إني ثنغ", ex_en: "Do you want anything?", ar_ex: "هل تريد أي شيء؟" },
    { id: 34, en: "apartment", ar: "شقة", pronounce: "أبارتمنت", ex_en: "I live in an apartment", ar_ex: "أعيش في شقة" },
    { id: 35, en: "apple", ar: "تفاح", pronounce: "أبل", ex_en: "I eat an apple", ar_ex: "أكل تفاحة" },
    { id: 36, en: "April", ar: "أبريل", pronounce: "إيبرل", ex_en: "We meet in April", ar_ex: "نلتقي في أبريل" },
    { id: 37, en: "area", ar: "منطقة", pronounce: "إيريا", ex_en: "This is a nice area", ar_ex: "هذه منطقة جميلة" },
    { id: 38, en: "arm", ar: "ذراع", pronounce: "آرم", ex_en: "My arm hurts", ar_ex: "ذراعي يؤلمني" },
    { id: 39, en: "around", ar: "حول", pronounce: "أراوند", ex_en: "I walk around the house", ar_ex: "أمشي حول البيت" },
    { id: 40, en: "arrive", ar: "يصل", pronounce: "أرايف", ex_en: "I arrive early", ar_ex: "أصل مبكراً" },
	{ id: 41, en: "art", ar: "فن", pronounce: "آرت", ex_en: "I like art", ar_ex: "أحب الفن" },
    { id: 42, en: "article", ar: "مقال", pronounce: "آرتكل", ex_en: "I read an article", ar_ex: "أقرأ مقالاً" },
    { id: 43, en: "artist", ar: "فنان", pronounce: "آرتست", ex_en: "He is an artist", ar_ex: "هو فنان" },
    { id: 44, en: "as", ar: "كـ / مثل", pronounce: "آز", ex_en: "He works as a teacher", ar_ex: "هو يعمل كمعلم" },
    { id: 45, en: "ask", ar: "يسأل", pronounce: "آسك", ex_en: "I ask a question", ar_ex: "أسأل سؤالاً" },
    { id: 46, en: "at", ar: "في", pronounce: "آت", ex_en: "I am at school", ar_ex: "أنا في المدرسة" },
    { id: 47, en: "August", ar: "أغسطس", pronounce: "أوغست", ex_en: "I travel in August", ar_ex: "أسافر في أغسطس" },
    { id: 48, en: "aunt", ar: "عمة / خالة", pronounce: "آنت", ex_en: "This is my aunt", ar_ex: "هذه عمتي" },
    { id: 49, en: "autumn", ar: "خريف", pronounce: "أوتم", ex_en: "I like autumn", ar_ex: "أحب الخريف" },
    { id: 50, en: "away", ar: "بعيد", pronounce: "أوي", ex_en: "He is away", ar_ex: "هو بعيد" },
    { id: 51, en: "baby", ar: "طفل رضيع", pronounce: "بيبي", ex_en: "The baby sleeps", ar_ex: "الطفل ينام" },
    { id: 52, en: "back", ar: "إلى الخلف / ظهر", pronounce: "باك", ex_en: "Go back", ar_ex: "عد إلى الخلف" },
    { id: 53, en: "bad", ar: "سيئ", pronounce: "باد", ex_en: "This is bad", ar_ex: "هذا سيئ" },
    { id: 54, en: "bag", ar: "حقيبة", pronounce: "باغ", ex_en: "I have a bag", ar_ex: "لدي حقيبة" },
    { id: 55, en: "ball", ar: "كرة", pronounce: "بول", ex_en: "I play with a ball", ar_ex: "ألعب بالكرة" },
    { id: 56, en: "banana", ar: "موز", pronounce: "بنانا", ex_en: "I eat a banana", ar_ex: "أكل موزة" },
    { id: 57, en: "band", ar: "فرقة", pronounce: "باند", ex_en: "I have a band", ar_ex: "لدي فرقة موسيقية" },
    { id: 58, en: "bank", ar: "بنك", pronounce: "بانك", ex_en: "I go to the bank", ar_ex: "أذهب إلى البنك" },
    { id: 59, en: "bar", ar: "حانة / لوح", pronounce: "بار", ex_en: "We sit in a bar", ar_ex: "نجلس في الحانة" },
    { id: 60, en: "bath", ar: "حمام", pronounce: "باث", ex_en: "I take a bath", ar_ex: "آخذ حماماً" },
    { id: 61, en: "bathroom", ar: "غرفة الحمام", pronounce: "باثروم", ex_en: "This is the bathroom", ar_ex: "هذا هو الحمام" },
    { id: 62, en: "be", ar: "يكون", pronounce: "بي", ex_en: "I am happy", ar_ex: "أنا سعيد" },
    { id: 63, en: "beach", ar: "شاطئ", pronounce: "بيتش", ex_en: "I go to the beach", ar_ex: "أذهب إلى الشاطئ" },
    { id: 64, en: "beautiful", ar: "جميل", pronounce: "بيوتفل", ex_en: "She is beautiful", ar_ex: "هي جميلة" },
    { id: 65, en: "because", ar: "لأن", pronounce: "بكوز", ex_en: "Because I am tired", ar_ex: "لأنني تعبت" },
    { id: 66, en: "become", ar: "يصبح", pronounce: "بكم", ex_en: "I become a doctor", ar_ex: "أصبح طبيباً" },
    { id: 67, en: "bed", ar: "سرير", pronounce: "بد", ex_en: "I go to bed", ar_ex: "أذهب إلى السرير" },
    { id: 68, en: "bedroom", ar: "غرفة نوم", pronounce: "بدروم", ex_en: "This is my bedroom", ar_ex: "هذه غرفة نومي" },
    { id: 69, en: "beer", ar: "بيرة", pronounce: "بير", ex_en: "I drink beer", ar_ex: "أشرب بيرة" },
    { id: 70, en: "before", ar: "قبل", pronounce: "بفور", ex_en: "Before work", ar_ex: "قبل العمل" },
    { id: 71, en: "begin", ar: "يبدأ", pronounce: "بغن", ex_en: "I begin now", ar_ex: "أبدأ الآن" },
    { id: 72, en: "beginning", ar: "بداية", pronounce: "بغننغ", ex_en: "This is the beginning", ar_ex: "هذه البداية" },
    { id: 73, en: "behind", ar: "خلف", pronounce: "بهايند", ex_en: "Behind the house", ar_ex: "خلف المنزل" },
    { id: 74, en: "believe", ar: "يؤمن / يصدق", pronounce: "بليف", ex_en: "I believe you", ar_ex: "أؤمن بك" },
    { id: 75, en: "below", ar: "أسفل / تحت", pronounce: "بلو", ex_en: "Below the table", ar_ex: "أسفل الطاولة" },
    { id: 76, en: "best", ar: "الأفضل", pronounce: "بست", ex_en: "This is the best", ar_ex: "هذا هو الأفضل" },
    { id: 77, en: "better", ar: "أفضل", pronounce: "بتر", ex_en: "This is better", ar_ex: "هذا أفضل" },
    { id: 78, en: "between", ar: "بين", pronounce: "بتوين", ex_en: "Between us", ar_ex: "بيننا" },
    { id: 79, en: "bicycle", ar: "دراجة هوائية", pronounce: "بايسكل", ex_en: "I have a bicycle", ar_ex: "لدي دراجة" },
    { id: 80, en: "big", ar: "كبير", pronounce: "بغ", ex_en: "This is big", ar_ex: "هذا كبير" },
    { id: 81, en: "bike", ar: "دراجة", pronounce: "بايك", ex_en: "I ride a bike", ar_ex: "أركب دراجة" },
    { id: 82, en: "bill", ar: "فاتورة", pronounce: "بل", ex_en: "I pay the bill", ar_ex: "أدفع الفاتورة" },
    { id: 83, en: "bird", ar: "طائر", pronounce: "برد", ex_en: "I see a bird", ar_ex: "أرى طائراً" },
    { id: 84, en: "birthday", ar: "عيد ميلاد", pronounce: "بيرثدي", ex_en: "Today is my birthday", ar_ex: "عيد ميلادي اليوم" },
    { id: 85, en: "black", ar: "أسود", pronounce: "بلاك", ex_en: "This is black", ar_ex: "هذا أسود" },
    { id: 86, en: "blog", ar: "مدونة", pronounce: "بلوغ", ex_en: "I have a blog", ar_ex: "لدي مدونة" },
    { id: 87, en: "blonde", ar: "أشقر", pronounce: "بلوند", ex_en: "Her hair is blonde", ar_ex: "شعرها أشقر" },
    { id: 88, en: "blue", ar: "أزرق", pronounce: "بلو", ex_en: "The sky is blue", ar_ex: "السماء زرقاء" },
    { id: 89, en: "boat", ar: "قارب", pronounce: "بوت", ex_en: "I ride a boat", ar_ex: "أركب قارباً" },
    { id: 90, en: "body", ar: "جسم", pronounce: "بودي", ex_en: "This is my body", ar_ex: "هذا جسمي" },
    { id: 91, en: "book", ar: "كتاب", pronounce: "بوك", ex_en: "I read a book", ar_ex: "أقرأ كتاباً" },
    { id: 92, en: "boot", ar: "حذاء طويل", pronounce: "بوت", ex_en: "I wear a boot", ar_ex: "أرتدي حذاءً طويلاً" },
    { id: 93, en: "bored", ar: "يشعر بالملل", pronounce: "بورد", ex_en: "I am bored", ar_ex: "أنا أشعر بالملل" },
    { id: 94, en: "boring", ar: "ممل", pronounce: "بورنغ", ex_en: "This is boring", ar_ex: "هذا ممل" },
    { id: 95, en: "born", ar: "ولد", pronounce: "بورن", ex_en: "I was born here", ar_ex: "ولدت هنا" },
    { id: 96, en: "both", ar: "كلاهما", pronounce: "بوث", ex_en: "Both are here", ar_ex: "كلاهما هنا" },
    { id: 97, en: "bottle", ar: "زجاجة", pronounce: "بوتل", ex_en: "I drink from a bottle", ar_ex: "أشرب من زجاجة" },
    { id: 98, en: "bottom", ar: "أسفل / قاع", pronounce: "بوتم", ex_en: "At the bottom", ar_ex: "في الأسفل" },
    { id: 99, en: "box", ar: "صندوق", pronounce: "بوكس", ex_en: "Put it in the box", ar_ex: "ضعها في الصندوق" },
    { id: 100, en: "boy", ar: "ولد", pronounce: "بوي", ex_en: "This is a boy", ar_ex: "هذا ولد" },
    { id: 101, en: "boyfriend", ar: "صديق (حبيب)", pronounce: "بوي فريند", ex_en: "He is my boyfriend", ar_ex: "هذا صديقي" },
    { id: 102, en: "bread", ar: "خبز", pronounce: "برد", ex_en: "I eat bread", ar_ex: "أكل خبزاً" },
    { id: 103, en: "break", ar: "يكسر / استراحة", pronounce: "بريك", ex_en: "I break the glass", ar_ex: "أكسر الزجاج" },
    { id: 104, en: "breakfast", ar: "فطور", pronounce: "بركفاست", ex_en: "I eat breakfast", ar_ex: "أتناول الإفطار" },
    { id: 105, en: "bring", ar: "يحضر", pronounce: "برنغ", ex_en: "I bring the book", ar_ex: "أحضر الكتاب" },
    { id: 106, en: "brother", ar: "أخ", pronounce: "برذر", ex_en: "He is my brother", ar_ex: "هذا أخي" },
    { id: 107, en: "brown", ar: "بني", pronounce: "براون", ex_en: "This is brown", ar_ex: "هذا بني" },
    { id: 108, en: "build", ar: "يبني", pronounce: "بلد", ex_en: "I build a house", ar_ex: "أبني بيتاً" },
    { id: 109, en: "building", ar: "مبنى", pronounce: "بلدنغ", ex_en: "This is a building", ar_ex: "هذا مبنى" },
    { id: 110, en: "bus", ar: "حافلة", pronounce: "بس", ex_en: "I take the bus", ar_ex: "أركب الحافلة" },
    { id: 111, en: "business", ar: "عمل / تجارة", pronounce: "بزنس", ex_en: "I have a business", ar_ex: "لدي عمل" },
    { id: 112, en: "busy", ar: "مشغول", pronounce: "بزي", ex_en: "I am busy", ar_ex: "أنا مشغول" },
    { id: 113, en: "but", ar: "لكن", pronounce: "بت", ex_en: "I want to go but I am tired", ar_ex: "أريد الذهاب لكنني متعب" },
    { id: 114, en: "butter", ar: "زبدة", pronounce: "بتر", ex_en: "I put butter", ar_ex: "أضع الزبدة" },
    { id: 115, en: "buy", ar: "يشتري", pronounce: "باي", ex_en: "I buy food", ar_ex: "أشتري طعاماً" },
    { id: 116, en: "by", ar: "بواسطة", pronounce: "باي", ex_en: "I go by car", ar_ex: "أذهب بالسيارة" },
    { id: 117, en: "bye", ar: "وداعاً", pronounce: "باي", ex_en: "Bye!", ar_ex: "وداعاً!" },
    { id: 118, en: "cafe", ar: "مقهى", pronounce: "كافيه", ex_en: "We sit in a cafe", ar_ex: "نجلس في مقهى" },
    { id: 119, en: "cake", ar: "كعكة", pronounce: "كيك", ex_en: "I eat cake", ar_ex: "أكل كعكة" },
    { id: 120, en: "call", ar: "يتصل / ينادي", pronounce: "كول", ex_en: "I call you", ar_ex: "أتصل بك" },
    { id: 121, en: "camera", ar: "كاميرا", pronounce: "كاميرا", ex_en: "I have a camera", ar_ex: "لدي كاميرا" },
    { id: 122, en: "can", ar: "يستطيع", pronounce: "كان", ex_en: "I can swim", ar_ex: "أستطيع السباحة" },
    { id: 123, en: "cannot", ar: "لا يستطيع", pronounce: "كانوت", ex_en: "I cannot go", ar_ex: "لا أستطيع الذهاب" },
    { id: 124, en: "capital", ar: "عاصمة / حرف كبير", pronounce: "كابتل", ex_en: "This is the capital", ar_ex: "هذه العاصمة" },
    { id: 125, en: "car", ar: "سيارة", pronounce: "كار", ex_en: "I have a car", ar_ex: "أملك سيارة" },
    { id: 126, en: "card", ar: "بطاقة", pronounce: "كارد", ex_en: "I have a card", ar_ex: "لدي بطاقة" },
    { id: 127, en: "carrot", ar: "جزر", pronounce: "كاروت", ex_en: "I eat a carrot", ar_ex: "أكل جزرة" },
    { id: 128, en: "carry", ar: "يحمل", pronounce: "كاري", ex_en: "I carry the bag", ar_ex: "أحمل الحقيبة" },
    { id: 129, en: "cat", ar: "قطة", pronounce: "كات", ex_en: "I have a cat", ar_ex: "لدي قطة" },
    { id: 130, en: "CD", ar: "قرص مدمج", pronounce: "سي دي", ex_en: "I listen to a CD", ar_ex: "أستمع إلى قرص مدمج" },
    { id: 131, en: "cent", ar: "سنت", pronounce: "سنت", ex_en: "This is a cent", ar_ex: "هذا سنت" },
    { id: 132, en: "centre", ar: "مركز", pronounce: "سنتر", ex_en: "I am in the centre", ar_ex: "أنا في المركز" },
    { id: 133, en: "chair", ar: "كرسي", pronounce: "تشير", ex_en: "I sit on a chair", ar_ex: "أجلس على الكرسي" },
    { id: 134, en: "change", ar: "يغير / تغيير", pronounce: "تشينج", ex_en: "I change the plan", ar_ex: "أغير الخطة" },
    { id: 135, en: "chart", ar: "مخطط", pronounce: "تشارت", ex_en: "I see a chart", ar_ex: "أرى مخططاً" },
    { id: 136, en: "cheap", ar: "رخيص", pronounce: "تشيب", ex_en: "This is cheap", ar_ex: "هذا رخيص" },
    { id: 137, en: "check", ar: "يتحقق / يفحص", pronounce: "تشك", ex_en: "I check the work", ar_ex: "أتحقق من العمل" },
    { id: 138, en: "cheese", ar: "جبن", pronounce: "تشيز", ex_en: "I like cheese", ar_ex: "أحب الجبن" },
    { id: 139, en: "chicken", ar: "دجاج", pronounce: "تشكن", ex_en: "I eat chicken", ar_ex: "آكل دجاجاً" },
    { id: 140, en: "child", ar: "طفل", pronounce: "تشايلد", ex_en: "The child plays", ar_ex: "الطفل يلعب" },
    { id: 141, en: "chocolate", ar: "شوكولاتة", pronounce: "تشوكلت", ex_en: "I like chocolate", ar_ex: "أحب الشوكولاتة" },
    { id: 142, en: "choose", ar: "يختار", pronounce: "تشوز", ex_en: "I choose this", ar_ex: "أختار هذا" },
    { id: 143, en: "cinema", ar: "سينما", pronounce: "سنما", ex_en: "I go to the cinema", ar_ex: "أذهب إلى السينما" },
    { id: 144, en: "city", ar: "مدينة", pronounce: "ستي", ex_en: "This is a big city", ar_ex: "هذه مدينة كبيرة" },
    { id: 145, en: "class", ar: "صف / فصل", pronounce: "كلاس", ex_en: "This is a class", ar_ex: "هذا صف" },
    { id: 146, en: "classroom", ar: "غرفة الصف", pronounce: "كلاسروم", ex_en: "This is a classroom", ar_ex: "هذا فصل دراسي" },
    { id: 147, en: "clean (v)", ar: "ينظف", pronounce: "كلين", ex_en: "I clean the room", ar_ex: "أنظف الغرفة" },
    { id: 148, en: "clean (adj)", ar: "نظيف", pronounce: "كلين", ex_en: "This is clean", ar_ex: "هذا نظيف" },
    { id: 149, en: "climb", ar: "يتسلق", pronounce: "كلايمب", ex_en: "I climb the mountain", ar_ex: "أتسلق الجبل" },
    { id: 150, en: "clock", ar: "ساعة حائط", pronounce: "كلوك", ex_en: "The clock is on the wall", ar_ex: "الساعة على الحائط" },
    { id: 151, en: "close", ar: "يغلق / قريب", pronounce: "كلوز", ex_en: "I close the door", ar_ex: "أغلق الباب" },
    { id: 152, en: "clothes", ar: "ملابس", pronounce: "كلوذز", ex_en: "These are my clothes", ar_ex: "هذه ملابسي" },
    { id: 153, en: "club", ar: "نادي", pronounce: "كلب", ex_en: "I am in a club", ar_ex: "أنا في النادي" },
    { id: 154, en: "coat", ar: "معطف", pronounce: "كوت", ex_en: "I wear a coat", ar_ex: "أرتدي معطفاً" },
    { id: 155, en: "coffee", ar: "قهوة", pronounce: "كوفي", ex_en: "I drink coffee", ar_ex: "أشرب قهوة" },
    { id: 156, en: "cold", ar: "بارد", pronounce: "كولد", ex_en: "It is cold", ar_ex: "الجو بارد" },
    { id: 157, en: "college", ar: "كلية", pronounce: "كولج", ex_en: "I study in college", ar_ex: "أدرس في الكلية" },
    { id: 158, en: "colour", ar: "لون", pronounce: "كلر", ex_en: "This colour is nice", ar_ex: "هذا اللون جميل" },
    { id: 159, en: "come", ar: "يأتي", pronounce: "كم", ex_en: "Come here", ar_ex: "تعال هنا" },
    { id: 160, en: "company", ar: "شركة", pronounce: "كمبني", ex_en: "This is a company", ar_ex: "هذه شركة" },
    { id: 161, en: "complete", ar: "يكمل / كامل", pronounce: "كمبليت", ex_en: "I complete the work", ar_ex: "أكمل العمل" },
    { id: 162, en: "computer", ar: "حاسوب", pronounce: "كمبيوتر", ex_en: "I use a computer", ar_ex: "أستخدم الحاسوب" },
    { id: 163, en: "concert", ar: "حفلة موسيقية", pronounce: "كونسرت", ex_en: "I attend a concert", ar_ex: "أحضر حفلة موسيقية" },
    { id: 164, en: "cook", ar: "يطبخ / طباخ", pronounce: "كوك", ex_en: "I cook food", ar_ex: "أطبخ الطعام" },
    { id: 165, en: "cooking", ar: "الطبخ", pronounce: "كوكنغ", ex_en: "I like cooking", ar_ex: "أحب الطبخ" },
    { id: 166, en: "cool", ar: "رائع / معتدل البرودة", pronounce: "كول", ex_en: "This is cool", ar_ex: "هذا رائع" },
    { id: 167, en: "correct", ar: "صحيح / يصحح", pronounce: "كوركت", ex_en: "This is correct", ar_ex: "هذا صحيح" },
    { id: 168, en: "cost", ar: "يكلف / تكلفة", pronounce: "كوست", ex_en: "It costs a lot", ar_ex: "يكلف كثيراً" },
    { id: 169, en: "could", ar: "استطاع / يمكن", pronounce: "كود", ex_en: "I could help", ar_ex: "يمكنني المساعدة" },
    { id: 170, en: "country", ar: "بلد", pronounce: "كنتري", ex_en: "This is a country", ar_ex: "هذا بلد جميل" },
    { id: 171, en: "course", ar: "دورة تعليمية", pronounce: "كورس", ex_en: "This is a course", ar_ex: "هذا درس مهم" },
    { id: 172, en: "cousin", ar: "ابن عم / خالة", pronounce: "كزن", ex_en: "He is my cousin", ar_ex: "هذا ابن عمي" },
    { id: 173, en: "cow", ar: "بقرة", pronounce: "كاو", ex_en: "I see a cow", ar_ex: "أرى بقرة" },
    { id: 174, en: "cream", ar: "كريم / قشطة", pronounce: "كريم", ex_en: "I use cream", ar_ex: "أضع كريماً" },
    { id: 175, en: "cup", ar: "كوب / فنجان", pronounce: "كب", ex_en: "I drink from a cup", ar_ex: "أشرب من كوب" },
    { id: 176, en: "customer", ar: "زبون", pronounce: "كستمر", ex_en: "This is a customer", ar_ex: "هذا زبون" },
    { id: 177, en: "cut", ar: "يقطع / قص", pronounce: "كت", ex_en: "I cut the paper", ar_ex: "أقطع الورق" },
    { id: 178, en: "dad", ar: "أب", pronounce: "داد", ex_en: "This is my dad", ar_ex: "هذا أبي" },
    { id: 179, en: "daily", ar: "يومي", pronounce: "ديلي", ex_en: "This is a daily task", ar_ex: "هذا عمل يومي" },
    { id: 180, en: "dance", ar: "يرقص / رقص", pronounce: "دانس", ex_en: "I dance now", ar_ex: "أرقص الآن" },
    { id: 181, en: "dancer", ar: "راقص", pronounce: "دانسر", ex_en: "She is a dancer", ar_ex: "هي راقصة" },
    { id: 182, en: "dancing", ar: "الرقص", pronounce: "دانسنغ", ex_en: "I like dancing", ar_ex: "أحب الرقص" },
    { id: 183, en: "dangerous", ar: "خطير", pronounce: "دينجرس", ex_en: "This is dangerous", ar_ex: "هذا خطير" },
    { id: 184, en: "dark", ar: "مظلم / داكن", pronounce: "دارك", ex_en: "The room is dark", ar_ex: "الغرفة مظلمة" },
    { id: 185, en: "date", ar: "تاريخ / موعد", pronounce: "ديت", ex_en: "What is the date?", ar_ex: "ما هو التاريخ؟" },
    { id: 186, en: "daughter", ar: "ابنة", pronounce: "دوتر", ex_en: "This is my daughter", ar_ex: "هذه ابنتي" },
    { id: 187, en: "day", ar: "يوم", pronounce: "دي", ex_en: "Today is nice", ar_ex: "اليوم جميل" },
    { id: 188, en: "dear", ar: "عزيزي", pronounce: "دير", ex_en: "Dear friend", ar_ex: "عزيزي صديقي" },
    { id: 189, en: "December", ar: "ديسمبر", pronounce: "ديسمبر", ex_en: "December is cold", ar_ex: "ديسمبر بارد" },
    { id: 190, en: "decide", ar: "يقرر", pronounce: "دسايد", ex_en: "I decide now", ar_ex: "أقرر الآن" },
    { id: 191, en: "delicious", ar: "لذيذ", pronounce: "دلشس", ex_en: "This is delicious", ar_ex: "هذا لذيذ" },
    { id: 192, en: "desk", ar: "مكتب", pronounce: "دسك", ex_en: "This is my desk", ar_ex: "هذا مكتبي" },
    { id: 193, en: "detail", ar: "تفصيل", pronounce: "ديتيل", ex_en: "This is an important detail", ar_ex: "هذا تفصيل مهم" },
    { id: 194, en: "dialogue", ar: "حوار", pronounce: "دايلوغ", ex_en: "I read a dialogue", ar_ex: "أقرأ حواراً" },
    { id: 195, en: "dictionary", ar: "قاموس", pronounce: "دكشنري", ex_en: "I use a dictionary", ar_ex: "أستخدم قاموساً" },
    { id: 196, en: "die", ar: "يموت", pronounce: "داي", ex_en: "The plant dies", ar_ex: "يموت النبات" },
    { id: 197, en: "diet", ar: "حمية غذائية", pronounce: "دايت", ex_en: "I follow a diet", ar_ex: "أتبع حمية" },
    { id: 198, en: "different", ar: "مختلف", pronounce: "دفرنت", ex_en: "This is different", ar_ex: "هذا مختلف" },
    { id: 199, en: "difficult", ar: "صعب", pronounce: "ديفكلت", ex_en: "This is difficult", ar_ex: "هذا صعب" },
    { id: 200, en: "dinner", ar: "عشاء", pronounce: "دنر", ex_en: "I eat dinner", ar_ex: "أتناول العشاء" },
    { id: 201, en: "dish", ar: "طبق", pronounce: "دش", ex_en: "I wash the dish", ar_ex: "أغسل الصحون" },
    { id: 202, en: "do", ar: "يفعل", pronounce: "دو", ex_en: "I do my homework", ar_ex: "أقوم بواجبي" },
    { id: 203, en: "doctor", ar: "طبيب", pronounce: "دوكتر", ex_en: "He is a doctor", ar_ex: "هذا طبيب" },
    { id: 204, en: "dog", ar: "كلب", pronounce: "دوغ", ex_en: "I have a dog", ar_ex: "لدي كلب" },
    { id: 205, en: "dollar", ar: "دولار", pronounce: "دولر", ex_en: "I pay in dollars", ar_ex: "أدفع بالدولار" },
    { id: 206, en: "door", ar: "باب", pronounce: "دور", ex_en: "I close the door", ar_ex: "أغلق الباب" },
    { id: 207, en: "down", ar: "إلى الأسفل", pronounce: "داون", ex_en: "Go down", ar_ex: "انزل للأسفل" },
    { id: 208, en: "downstairs", ar: "في الطابق السفلي", pronounce: "داونستيرز", ex_en: "I go downstairs", ar_ex: "أذهب للأسفل" },
    { id: 209, en: "draw", ar: "يرسم", pronounce: "درو", ex_en: "I draw a picture", ar_ex: "أرسم صورة" },
    { id: 210, en: "dress", ar: "فستان", pronounce: "درس", ex_en: "I wear a dress", ar_ex: "أرتدي فستاناً" },
    { id: 211, en: "drink", ar: "يشرب / مشروب", pronounce: "درنك", ex_en: "I drink water", ar_ex: "أشرب ماءً" },
    { id: 212, en: "drive", ar: "يقود", pronounce: "درايف", ex_en: "I drive a car", ar_ex: "أقود السيارة" },
    { id: 213, en: "driver", ar: "سائق", pronounce: "درايفر", ex_en: "He is a driver", ar_ex: "هو سائق" },
    { id: 214, en: "driving", ar: "القيادة", pronounce: "درايفنغ", ex_en: "I like driving", ar_ex: "أحب القيادة" },
    { id: 215, en: "dry", ar: "جاف / يجفف", pronounce: "دراي", ex_en: "It is dry", ar_ex: "الجو جاف" },
    { id: 216, en: "during", ar: "خلال / أثناء", pronounce: "ديورينغ", ex_en: "During the lesson", ar_ex: "أثناء الدرس" },
    { id: 217, en: "DVD", ar: "قرص دي في دي", pronounce: "دي في دي", ex_en: "I watch a DVD", ar_ex: "أشاهد قرص دي في دي" },
    { id: 218, en: "each", ar: "كل (واحد)", pronounce: "إيتش", ex_en: "Each student is here", ar_ex: "كل طالب هنا" },
    { id: 219, en: "ear", ar: "أذن", pronounce: "إير", ex_en: "My ear hurts", ar_ex: "أذني تؤلمني" },
    { id: 220, en: "early", ar: "مبكراً", pronounce: "إيرلي", ex_en: "I wake up early", ar_ex: "أستيقظ مبكراً" },
    { id: 221, en: "east", ar: "شرق", pronounce: "إيست", ex_en: "The east is beautiful", ar_ex: "الشرق جميل" },
    { id: 222, en: "easy", ar: "سهل", pronounce: "إيزي", ex_en: "This is easy", ar_ex: "هذا سهل" },
    { id: 223, en: "egg", ar: "بيضة", pronounce: "إيغ", ex_en: "I eat an egg", ar_ex: "آكل بيضة" },
    { id: 224, en: "eight", ar: "ثمانية", pronounce: "إيت", ex_en: "I have eight books", ar_ex: "لدي ثمانية كتب" },
    { id: 225, en: "eighteen", ar: "ثمانية عشر", pronounce: "إيتين", ex_en: "I am eighteen", ar_ex: "عمري ثمانية عشر" },
    { id: 226, en: "eighty", ar: "ثمانون", pronounce: "إيتي", ex_en: "Eighty students", ar_ex: "ثمانون طالباً" },
    { id: 227, en: "elephant", ar: "فيل", pronounce: "إليفنت", ex_en: "The elephant is big", ar_ex: "الفيل كبير" },
    { id: 228, en: "eleven", ar: "أحد عشر", pronounce: "إليفن", ex_en: "I have eleven pens", ar_ex: "لدي أحد عشر قلماً" },
    { id: 229, en: "else", ar: "آخر / غير ذلك", pronounce: "إلس", ex_en: "What else?", ar_ex: "ماذا أيضاً؟" },
    { id: 230, en: "email", ar: "بريد إلكتروني", pronounce: "إيميل", ex_en: "I send an email", ar_ex: "أرسل بريداً إلكترونياً" },
    { id: 231, en: "end", ar: "نهاية / ينهي", pronounce: "إند", ex_en: "This is the end", ar_ex: "هذه هي النهاية" },
    { id: 232, en: "enjoy", ar: "يستمتع", pronounce: "إنجوي", ex_en: "I enjoy the time", ar_ex: "أستمتع بالوقت" },
    { id: 233, en: "enough", ar: "كافٍ / يكفي", pronounce: "إناف", ex_en: "This is enough", ar_ex: "هذا يكفي" },
    { id: 234, en: "euro", ar: "يورو", pronounce: "يورو", ex_en: "This is a euro", ar_ex: "هذا يورو" },
    { id: 235, en: "even", ar: "حتى / زوجي", pronounce: "إيفن", ex_en: "Even now", ar_ex: "حتى الآن" },
    { id: 236, en: "evening", ar: "مساء", pronounce: "إيفننغ", ex_en: "The evening is nice", ar_ex: "المساء جميل" },
    { id: 237, en: "ever", ar: "أبداً / في أي وقت", pronounce: "إيفر", ex_en: "Have you ever?", ar_ex: "هل سبق لك؟" },
    { id: 238, en: "every", ar: "كل", pronounce: "إيفري", ex_en: "Every day", ar_ex: "كل يوم" },
    { id: 239, en: "everybody", ar: "الجميع", pronounce: "إيفري بودي", ex_en: "Everybody is here", ar_ex: "الجميع هنا" },
    { id: 240, en: "everyone", ar: "كل شخص", pronounce: "إيفري ون", ex_en: "Everyone is happy", ar_ex: "الجميع سعيد" },
    { id: 241, en: "everything", ar: "كل شيء", pronounce: "إيفري ثنغ", ex_en: "Everything is good", ar_ex: "كل شيء جيد" },
    { id: 242, en: "exam", ar: "امتحان", pronounce: "إغزام", ex_en: "I have an exam", ar_ex: "لدي امتحان" },
    { id: 243, en: "example", ar: "مثال", pronounce: "إغزامبل", ex_en: "This is an example", ar_ex: "هذا مثال" },
    { id: 244, en: "excited", ar: "متحمس", pronounce: "إكسايتد", ex_en: "I am excited", ar_ex: "أنا متحمس" },
    { id: 245, en: "exciting", ar: "مثير / ممتع", pronounce: "إكسايتنغ", ex_en: "This is exciting", ar_ex: "هذا ممتع" },
    { id: 246, en: "exercise", ar: "تمرين", pronounce: "إكسرسايز", ex_en: "I do exercise", ar_ex: "أمارس الرياضة" },
    { id: 247, en: "expensive", ar: "غالي الثمن", pronounce: "إكسبنسف", ex_en: "This is expensive", ar_ex: "هذا غالي" },
    { id: 248, en: "explain", ar: "يشرح", pronounce: "إكسابلين", ex_en: "I explain the lesson", ar_ex: "أشرح الدرس" },
    { id: 249, en: "extra", ar: "إضافي", pronounce: "إكسترا", ex_en: "This is extra", ar_ex: "هذا إضافي" },
    { id: 250, en: "eye", ar: "عين", pronounce: "آي", ex_en: "My eye hurts", ar_ex: "عيني تؤلمني" },
    { id: 251, en: "face", ar: "وجه", pronounce: "فيس", ex_en: "This is my face", ar_ex: "هذا وجهي" },
    { id: 252, en: "fall", ar: "يسقط / خريف", pronounce: "فول", ex_en: "I fall down", ar_ex: "أسقط على الأرض" },
    { id: 253, en: "false", ar: "خاطئ", pronounce: "فولس", ex_en: "This is false", ar_ex: "هذا خطأ" },
    { id: 254, en: "family", ar: "عائلة", pronounce: "فاميلي", ex_en: "This is my family", ar_ex: "هذه عائلتي" },
    { id: 255, en: "famous", ar: "مشهور", pronounce: "فيمس", ex_en: "He is famous", ar_ex: "هو مشهور" },
    { id: 256, en: "fantastic", ar: "رائع جداً", pronounce: "فانتاستك", ex_en: "This is fantastic", ar_ex: "هذا رائع جداً" },
    { id: 257, en: "far", ar: "بعيد", pronounce: "فار", ex_en: "It is far", ar_ex: "هو بعيد" },
    { id: 258, en: "farm", ar: "مزرعة", pronounce: "فارم", ex_en: "I live on a farm", ar_ex: "أعيش في مزرعة" },
    { id: 259, en: "farmer", ar: "مزارع", pronounce: "فارمر", ex_en: "He is a farmer", ar_ex: "هو مزارع" },
    { id: 260, en: "fast", ar: "سريع", pronounce: "فاست", ex_en: "This is fast", ar_ex: "هذا سريع" },
    { id: 261, en: "fat", ar: "سمين / دهون", pronounce: "فات", ex_en: "This is fat", ar_ex: "هذا سمين" },
    { id: 262, en: "father", ar: "أب", pronounce: "فاذر", ex_en: "He is my father", ar_ex: "هذا أبي" },
    { id: 263, en: "favourite", ar: "مفضل", pronounce: "فيفورت", ex_en: "This is my favourite", ar_ex: "هذا المفضل لدي" },
    { id: 264, en: "February", ar: "فبراير", pronounce: "فبرواري", ex_en: "February is cold", ar_ex: "فبراير بارد" },
    { id: 265, en: "feel", ar: "يشعر", pronounce: "فيل", ex_en: "I feel happy", ar_ex: "أشعر بالسعادة" },
    { id: 266, en: "festival", ar: "مهرجان", pronounce: "فستفل", ex_en: "This is a festival", ar_ex: "هذا مهرجان" },
    { id: 267, en: "few", ar: "قليل", pronounce: "فيو", ex_en: "I have a few minutes", ar_ex: "لدي القليل من الوقت" },
    { id: 268, en: "fifteen", ar: "خمسة عشر", pronounce: "ففتين", ex_en: "I have fifteen books", ar_ex: "لدي خمسة عشر كتاباً" },
    { id: 269, en: "fifth", ar: "الخامس", pronounce: "ففث", ex_en: "This is the fifth", ar_ex: "هذا الخامس" },
    { id: 270, en: "fifty", ar: "خمسون", pronounce: "ففتي", ex_en: "Fifty students", ar_ex: "خمسون طالباً" },
    { id: 271, en: "fill", ar: "يملأ", pronounce: "فل", ex_en: "I fill the cup", ar_ex: "أملأ الكوب" },
    { id: 272, en: "film", ar: "فيلم", pronounce: "فيلم", ex_en: "I watch a film", ar_ex: "أشاهد فيلماً" },
    { id: 273, en: "final", ar: "نهائي", pronounce: "فاينل", ex_en: "This is final", ar_ex: "هذا النهائي" },
    { id: 274, en: "find", ar: "يجد", pronounce: "فايند", ex_en: "I find the answer", ar_ex: "أجد الحل" },
    { id: 275, en: "fine", ar: "بخير / غرامة", pronounce: "فاين", ex_en: "I am fine", ar_ex: "أنا بخير" },
    { id: 276, en: "finish", ar: "ينهي", pronounce: "فنش", ex_en: "I finish the work", ar_ex: "أنهي العمل" },
    { id: 277, en: "fire", ar: "نار / حريق", pronounce: "فاير", ex_en: "There is a fire", ar_ex: "هناك نار" },
    { id: 278, en: "first", ar: "الأول", pronounce: "فيرست", ex_en: "I am first", ar_ex: "أنا الأول" },
    { id: 279, en: "fish", ar: "سمك", pronounce: "فش", ex_en: "I eat fish", ar_ex: "آكل السمك" },
    { id: 280, en: "five", ar: "خمسة", pronounce: "فايف", ex_en: "I have five books", ar_ex: "لدي خمسة كتب" },
    { id: 281, en: "fix", ar: "يصلح", pronounce: "فكس", ex_en: "I fix the phone", ar_ex: "أصلح الهاتف" },
    { id: 282, en: "flat", ar: "شقة / مسطح", pronounce: "فلات", ex_en: "I live in a flat", ar_ex: "أعيش في شقة" },
    { id: 283, en: "flight", ar: "رحلة طيران", pronounce: "فلايت", ex_en: "I have a flight", ar_ex: "لدي رحلة طيران" },
    { id: 284, en: "floor", ar: "طابق / أرضية", pronounce: "فلور", ex_en: "This is the first floor", ar_ex: "هذا الطابق الأول" },
    { id: 285, en: "flower", ar: "زهرة", pronounce: "فلاور", ex_en: "This is a flower", ar_ex: "هذه زهرة" },
    { id: 286, en: "fly", ar: "يطير / ذبابة", pronounce: "فلاي", ex_en: "I fly in the sky", ar_ex: "أطير في السماء" },
    { id: 287, en: "follow", ar: "يتبع", pronounce: "فولو", ex_en: "I follow instructions", ar_ex: "أتبع التعليمات" },
    { id: 288, en: "food", ar: "طعام", pronounce: "فود", ex_en: "The food is good", ar_ex: "الطعام لذيذ" },
    { id: 289, en: "foot", ar: "قدم", pronounce: "فوت", ex_en: "This is my foot", ar_ex: "هذه قدمي" },
    { id: 290, en: "football", ar: "كرة القدم", pronounce: "فوتبول", ex_en: "I play football", ar_ex: "ألعب كرة القدم" },
    { id: 291, en: "for", ar: "لـ / من أجل", pronounce: "فور", ex_en: "This is for you", ar_ex: "هذا لك" },
    { id: 292, en: "forget", ar: "ينسى", pronounce: "فورغت", ex_en: "I sometimes forget", ar_ex: "أحياناً أنسى" },
    { id: 293, en: "form", ar: "نموذج / يشكل", pronounce: "فورم", ex_en: "I fill the form", ar_ex: "أملأ النموذج" },
    { id: 294, en: "forty", ar: "أربعون", pronounce: "فورتي", ex_en: "Forty students", ar_ex: "أربعون طالباً" },
    { id: 295, en: "four", ar: "أربعة", pronounce: "فور", ex_en: "I have four books", ar_ex: "لدي أربعة كتب" },
    { id: 296, en: "fourteen", ar: "أربعة عشر", pronounce: "فورتين", ex_en: "I have fourteen pens", ar_ex: "لدي أربعة عشر قلماً" },
    { id: 297, en: "fourth", ar: "الرابع", pronounce: "فورث", ex_en: "This is the fourth", ar_ex: "هذا الرابع" },
    { id: 298, en: "free", ar: "مجاني / حر", pronounce: "فري", ex_en: "I am free today", ar_ex: "أنا حر اليوم" },
    { id: 299, en: "Friday", ar: "الجمعة", pronounce: "فرايدي", ex_en: "Today is Friday", ar_ex: "اليوم الجمعة" },
    { id: 300, en: "friend", ar: "صديق", pronounce: "فريند", ex_en: "He is my friend", ar_ex: "هذا صديقي" },
    { id: 301, en: "friendly", ar: "ودود", pronounce: "فريندلي", ex_en: "He is friendly", ar_ex: "هو ودود" },
    { id: 302, en: "from", ar: "من", pronounce: "فروم", ex_en: "I am from Palestine", ar_ex: "أنا من فلسطين" },
    { id: 303, en: "front", ar: "أمام / مقدمة", pronounce: "فرونت", ex_en: "The door is in the front", ar_ex: "الباب في الأمام" },
    { id: 304, en: "fruit", ar: "فاكهة", pronounce: "فروت", ex_en: "I eat fruit", ar_ex: "آكل فاكهة" },
    { id: 305, en: "full", ar: "ممتلئ", pronounce: "فل", ex_en: "The glass is full", ar_ex: "الكأس ممتلئ" },
    { id: 306, en: "fun", ar: "متعة / مرح", pronounce: "فن", ex_en: "This is fun", ar_ex: "هذا ممتع" },
    { id: 307, en: "funny", ar: "مضحك", pronounce: "فني", ex_en: "This is funny", ar_ex: "هذا مضحك" },
    { id: 308, en: "future", ar: "مستقبل", pronounce: "فيوتشر", ex_en: "The future is important", ar_ex: "المستقبل مهم" },
    { id: 309, en: "game", ar: "لعبة", pronounce: "غيم", ex_en: "I play a game", ar_ex: "ألعب لعبة" },
    { id: 310, en: "garden", ar: "حديقة", pronounce: "غاردن", ex_en: "I have a garden", ar_ex: "لدي حديقة" },
    { id: 311, en: "geography", ar: "جغرافيا", pronounce: "جيوغرافي", ex_en: "I study geography", ar_ex: "أدرس الجغرافيا" },
    { id: 312, en: "gift", ar: "هدية", pronounce: "غفت", ex_en: "I get a gift", ar_ex: "أحصل على هدية" },
    { id: 313, en: "girl", ar: "فتاة", pronounce: "غيرل", ex_en: "This is a girl", ar_ex: "هذه فتاة" },
    { id: 314, en: "girlfriend", ar: "صديقة (حبيبة)", pronounce: "غيرل فريند", ex_en: "She is my girlfriend", ar_ex: "هذه صديقتي" },
    { id: 315, en: "give", ar: "يعطي", pronounce: "غف", ex_en: "I give you the book", ar_ex: "أعطيك الكتاب" },
    { id: 316, en: "glass", ar: "زجاج / كأس", pronounce: "غلاس", ex_en: "I drink from a glass", ar_ex: "أشرب من كأس زجاجي" },
    { id: 317, en: "go", ar: "يذهب", pronounce: "غو", ex_en: "I go to school", ar_ex: "أذهب إلى المدرسة" },
    { id: 318, en: "good", ar: "جيد", pronounce: "غود", ex_en: "This is good", ar_ex: "هذا جيد" },
    { id: 319, en: "goodbye", ar: "وداعاً", pronounce: "غودباي", ex_en: "Goodbye!", ar_ex: "وداعاً!" },
    { id: 320, en: "grandfather", ar: "جد", pronounce: "غراند فاذر", ex_en: "He is my grandfather", ar_ex: "هذا جدي" },
    { id: 321, en: "grandmother", ar: "جدة", pronounce: "غراند ماذر", ex_en: "She is my grandmother", ar_ex: "هذه جدتي" },
    { id: 322, en: "grandparent", ar: "جد أو جدة", pronounce: "غراند بيرنت", ex_en: "He is a grandparent", ar_ex: "هذا أحد الأجداد" },
    { id: 323, en: "great", ar: "رائع / عظيم", pronounce: "غريت", ex_en: "This is great", ar_ex: "هذا رائع" },
    { id: 324, en: "green", ar: "أخضر", pronounce: "غرين", ex_en: "The grass is green", ar_ex: "العشب أخضر" },
    { id: 325, en: "grey", ar: "رمادي", pronounce: "غراي", ex_en: "This is grey", ar_ex: "هذا رمادي" },
    { id: 326, en: "group", ar: "مجموعة", pronounce: "غروب", ex_en: "We are a group", ar_ex: "نحن مجموعة" },
    { id: 327, en: "grow", ar: "ينمو / يزرع", pronounce: "غرو", ex_en: "The plant grows", ar_ex: "ينمو النبات" },
    { id: 328, en: "guess", ar: "يخمن", pronounce: "غس", ex_en: "I guess the answer", ar_ex: "أخمن الجواب" },
    { id: 329, en: "guitar", ar: "غيتار", pronounce: "غيتار", ex_en: "I play the guitar", ar_ex: "أعزف على الغيتار" },
    { id: 330, en: "gym", ar: "نادي رياضي", pronounce: "جيم", ex_en: "I go to the gym", ar_ex: "أذهب إلى النادي الرياضي" },
    { id: 331, en: "hair", ar: "شعر", pronounce: "هير", ex_en: "My hair is long", ar_ex: "شعري طويل" },
    { id: 332, en: "half", ar: "نصف", pronounce: "هاف", ex_en: "Half the cake", ar_ex: "نصف الكعكة" },
    { id: 333, en: "hand", ar: "يد", pronounce: "هاند", ex_en: "This is my hand", ar_ex: "هذه يدي" },
    { id: 334, en: "happen", ar: "يحدث", pronounce: "هابن", ex_en: "What happened?", ar_ex: "ماذا حدث؟" },
    { id: 335, en: "happy", ar: "سعيد", pronounce: "هابي", ex_en: "I am happy", ar_ex: "أنا سعيد" },
    { id: 336, en: "hard", ar: "صعب / صلب", pronounce: "هارد", ex_en: "This is hard", ar_ex: "هذا صعب" },
    { id: 337, en: "hat", ar: "قبعة", pronounce: "هات", ex_en: "I wear a hat", ar_ex: "أرتدي قبعة" },
    { id: 338, en: "hate", ar: "يكره", pronounce: "هيت", ex_en: "I hate lies", ar_ex: "أكره الكذب" },
    { id: 339, en: "have", ar: "يملك / يتناول", pronounce: "هاف", ex_en: "I have a car", ar_ex: "لدي سيارة" },
    { id: 340, en: "to have", ar: "يجب أن", pronounce: "تو هاف", ex_en: "I have to go", ar_ex: "يجب أن أذهب" },
    { id: 341, en: "he", ar: "هو", pronounce: "هي", ex_en: "He is here", ar_ex: "هو هنا" },
    { id: 342, en: "head", ar: "رأس", pronounce: "هيد", ex_en: "This is my head", ar_ex: "هذا رأسي" },
    { id: 343, en: "health", ar: "صحة", pronounce: "هلث", ex_en: "Health is important", ar_ex: "الصحة مهمة" },
    { id: 344, en: "healthy", ar: "صحي", pronounce: "هلثي", ex_en: "I am healthy", ar_ex: "أنا بصحة جيدة" },
    { id: 345, en: "hear", ar: "يسمع", pronounce: "هير", ex_en: "I hear a sound", ar_ex: "أسمع صوتاً" },
    { id: 346, en: "hello", ar: "مرحباً", pronounce: "هلو", ex_en: "Hello!", ar_ex: "مرحباً!" },
    { id: 347, en: "help", ar: "يساعد / مساعدة", pronounce: "هلب", ex_en: "I help you", ar_ex: "أساعدك" },
    { id: 348, en: "her", ar: "لها", pronounce: "هير", ex_en: "Her book is here", ar_ex: "كتابها هنا" },
    { id: 349, en: "here", ar: "هنا", pronounce: "هير", ex_en: "I am here", ar_ex: "أنا هنا" },
    { id: 350, en: "hey", ar: "مهلاً / مرحباً", pronounce: "هاي", ex_en: "Hey!", ar_ex: "مرحباً!" },
    { id: 351, en: "hi", ar: "مرحباً", pronounce: "هاي", ex_en: "Hi!", ar_ex: "مرحباً!" },
    { id: 352, en: "high", ar: "عالٍ / مرتفع", pronounce: "هاي", ex_en: "The mountain is high", ar_ex: "الجبل عالٍ" },
    { id: 353, en: "him", ar: "إياه (للمفعول به)", pronounce: "هم", ex_en: "I see him", ar_ex: "أراه" },
    { id: 354, en: "his", ar: "له", pronounce: "هز", ex_en: "This is his book", ar_ex: "هذا كتابه" },
    { id: 355, en: "history", ar: "تاريخ", pronounce: "هستري", ex_en: "I like history", ar_ex: "أحب التاريخ" },
    { id: 356, en: "hobby", ar: "هواية", pronounce: "هوبي", ex_en: "I have a hobby", ar_ex: "لدي هواية" },
    { id: 357, en: "holiday", ar: "عطلة", pronounce: "هوليدي", ex_en: "I go on holiday", ar_ex: "أذهب في عطلة" },
    { id: 358, en: "home", ar: "منزل / وطن", pronounce: "هوم", ex_en: "I am at home", ar_ex: "أنا في المنزل" },
    { id: 359, en: "homework", ar: "واجب منزلي", pronounce: "هوم وورك", ex_en: "I have homework", ar_ex: "لدي واجب منزلي" },
    { id: 360, en: "hope", ar: "يأمل / أمل", pronounce: "هوب", ex_en: "I hope so", ar_ex: "آمل ذلك" },
    { id: 361, en: "horse", ar: "حصان", pronounce: "هورس", ex_en: "I see a horse", ar_ex: "أرى حصاناً" },
    { id: 362, en: "hospital", ar: "مستشفى", pronounce: "هوسبتل", ex_en: "I go to the hospital", ar_ex: "أذهب إلى المستشفى" },
    { id: 363, en: "hot", ar: "حار / ساخن", pronounce: "هوت", ex_en: "It is hot", ar_ex: "الجو حار" },
    { id: 364, en: "hotel", ar: "فندق", pronounce: "هوتل", ex_en: "This is a hotel", ar_ex: "هذا فندق" },
    { id: 365, en: "hour", ar: "ساعة (زمن)", pronounce: "أوَر", ex_en: "One hour", ar_ex: "ساعة واحدة" },
    { id: 366, en: "house", ar: "بيت / منزل", pronounce: "هاوس", ex_en: "This is my house", ar_ex: "هذا منزلي" },
    { id: 367, en: "how", ar: "كيف", pronounce: "هاو", ex_en: "How are you?", ar_ex: "كيف حالك؟" },
    { id: 368, en: "hundred", ar: "مئة", pronounce: "هندريد", ex_en: "One hundred students", ar_ex: "مئة طالب" },
    { id: 369, en: "hungry", ar: "جائع", pronounce: "هنغري", ex_en: "I am hungry", ar_ex: "أنا جائع" },
    { id: 370, en: "husband", ar: "زوج", pronounce: "هزبند", ex_en: "He is my husband", ar_ex: "هذا زوجي" },
    { id: 371, en: "I", ar: "أنا", pronounce: "آي", ex_en: "I am a student", ar_ex: "أنا طالب" },
    { id: 372, en: "ice", ar: "ثلج", pronounce: "آيس", ex_en: "This is ice", ar_ex: "هذا ثلج" },
    { id: 373, en: "ice cream", ar: "مثلجات", pronounce: "آيس كريم", ex_en: "I eat ice cream", ar_ex: "آكل مثلجات" },
    { id: 374, en: "idea", ar: "فكرة", pronounce: "آيديا", ex_en: "I have an idea", ar_ex: "لدي فكرة" },
    { id: 375, en: "if", ar: "إذا / لو", pronounce: "إف", ex_en: "If you study, you succeed", ar_ex: "إذا درست تنجح" },
    { id: 376, en: "important", ar: "مهم", pronounce: "إمبورتنت", ex_en: "This is important", ar_ex: "هذا مهم" },
    { id: 377, en: "in", ar: "في / بداخل", pronounce: "إن", ex_en: "I am in the house", ar_ex: "أنا في البيت" },
    { id: 378, en: "include", ar: "يشمل / يتضمن", pronounce: "إنكلود", ex_en: "It includes everyone", ar_ex: "يشمل الجميع" },
    { id: 379, en: "information", ar: "معلومات", pronounce: "إنفورميشن", ex_en: "This is information", ar_ex: "هذه معلومات" },
    { id: 380, en: "interest", ar: "اهتمام / فائدة", pronounce: "إنترست", ex_en: "I have interest", ar_ex: "لدي اهتمام" },
    { id: 381, en: "interested", ar: "مهتم", pronounce: "إنترستد", ex_en: "I am interested", ar_ex: "أنا مهتم" },
    { id: 382, en: "interesting", ar: "ممتع / مثير للاهتمام", pronounce: "إنترستنغ", ex_en: "This is interesting", ar_ex: "هذا ممتع" },
    { id: 383, en: "internet", ar: "إنترنت", pronounce: "إنترنت", ex_en: "I use the internet", ar_ex: "أستخدم الإنترنت" },
    { id: 384, en: "interview", ar: "مقابلة", pronounce: "إنترفيو", ex_en: "I have an interview", ar_ex: "لدي مقابلة" },
    { id: 385, en: "into", ar: "إلى الداخل", pronounce: "إنتو", ex_en: "I go into the room", ar_ex: "أدخل إلى الغرفة" },
    { id: 386, en: "introduce", ar: "يقدم / يعرّف", pronounce: "إنتروديوس", ex_en: "I introduce myself", ar_ex: "أقدم نفسي" },
    { id: 387, en: "island", ar: "جزيرة", pronounce: "آيلاند", ex_en: "This is an island", ar_ex: "هذه جزيرة" },
    { id: 388, en: "it", ar: "هو/هي لغير العاقل", pronounce: "إت", ex_en: "It is nice", ar_ex: "إنه جميل" },
    { id: 389, en: "its", ar: "له/لها (لغير العاقل)", pronounce: "إتس", ex_en: "This is its cover", ar_ex: "هذا غلافه" },
    { id: 390, en: "jacket", ar: "سترة / جاكيت", pronounce: "جاكيت", ex_en: "I wear a jacket", ar_ex: "أرتدي سترة" },
    { id: 391, en: "January", ar: "يناير", pronounce: "جانيواري", ex_en: "January is cold", ar_ex: "يناير بارد" },
    { id: 392, en: "jeans", ar: "بنطال جينز", pronounce: "جينز", ex_en: "I wear jeans", ar_ex: "أرتدي جينز" },
    { id: 393, en: "job", ar: "وظيفة / عمل", pronounce: "جوب", ex_en: "I have a job", ar_ex: "لدي وظيفة" },
    { id: 394, en: "join", ar: "ينضم", pronounce: "جوين", ex_en: "I join the team", ar_ex: "أنضم للفريق" },
    { id: 395, en: "journey", ar: "رحلة", pronounce: "جورني", ex_en: "This is a journey", ar_ex: "هذه رحلة" },
    { id: 396, en: "juice", ar: "عصير", pronounce: "جوس", ex_en: "I drink juice", ar_ex: "أشرب عصيراً" },
    { id: 397, en: "July", ar: "يوليو", pronounce: "جولاي", ex_en: "July is hot", ar_ex: "يوليو حار" },
    { id: 398, en: "June", ar: "يونيو", pronounce: "جون", ex_en: "June is nice", ar_ex: "يونيو جميل" },
    { id: 399, en: "just", ar: "فقط / للتو", pronounce: "جست", ex_en: "I just learn", ar_ex: "أنا فقط أتعلم" },
    { id: 400, en: "keep", ar: "يحتفظ", pronounce: "كيب", ex_en: "I keep the key", ar_ex: "أحتفظ بالمفتاح" },
    { id: 401, en: "key", ar: "مفتاح", pronounce: "كي", ex_en: "This is my key", ar_ex: "هذا مفتاحي" },
    { id: 402, en: "kilometre", ar: "كيلومتر", pronounce: "كيلومتر", ex_en: "A kilometre is long", ar_ex: "الكيلومتر طويل" },
    { id: 403, en: "kind", ar: "نوع / لطيف", pronounce: "كايند", ex_en: "This is a kind type", ar_ex: "هذا نوع جيد" },
    { id: 404, en: "kitchen", ar: "مطبخ", pronounce: "كتشن", ex_en: "This is my kitchen", ar_ex: "هذا مطبخي" },
    { id: 405, en: "know", ar: "يعرف", pronounce: "نو", ex_en: "I know the answer", ar_ex: "أعرف الجواب" },
    { id: 406, en: "land", ar: "أرض", pronounce: "لاند", ex_en: "This is nice land", ar_ex: "هذه أرض جميلة" },
    { id: 407, en: "language", ar: "لغة", pronounce: "لانغوج", ex_en: "I learn a language", ar_ex: "أتعلم لغة" },
    { id: 408, en: "large", ar: "كبير / واسع", pronounce: "لارج", ex_en: "This is large", ar_ex: "هذا كبير" },
    { id: 409, en: "last", ar: "أخير / ماضي", pronounce: "لاست", ex_en: "This is the last day", ar_ex: "هذا آخر يوم" },
    { id: 410, en: "late", ar: "متأخر", pronounce: "ليت", ex_en: "I am late", ar_ex: "أنا متأخر" },
    { id: 411, en: "later", ar: "لاحقاً", pronounce: "ليتر", ex_en: "See you later", ar_ex: "أراك لاحقاً" },
    { id: 412, en: "laugh", ar: "يضحك", pronounce: "لاف", ex_en: "I laugh a lot", ar_ex: "أضحك كثيراً" },
    { id: 413, en: "learn", ar: "يتعلم", pronounce: "ليرن", ex_en: "I learn English", ar_ex: "أتعلم الإنجليزية" },
    { id: 414, en: "leave", ar: "يغادر / يترك", pronounce: "ليف", ex_en: "I leave now", ar_ex: "أغادر الآن" },
    { id: 415, en: "left", ar: "يسار", pronounce: "لفت", ex_en: "Turn left", ar_ex: "انعطف يساراً" },
    { id: 416, en: "leg", ar: "ساق", pronounce: "لغ", ex_en: "This is my leg", ar_ex: "هذه ساقي" },
    { id: 417, en: "lesson", ar: "درس", pronounce: "لسن", ex_en: "I have a lesson", ar_ex: "لدي درس" },
    { id: 418, en: "let", ar: "يسمح / دع", pronounce: "لت", ex_en: "Let me see", ar_ex: "دعني أرى" },
    { id: 419, en: "letter", ar: "رسالة / حرف", pronounce: "لتر", ex_en: "I write a letter", ar_ex: "أكتب رسالة" },
    { id: 420, en: "library", ar: "مكتبة", pronounce: "لايبرري", ex_en: "I go to the library", ar_ex: "أذهب إلى المكتبة" },
    { id: 421, en: "lie", ar: "يكذب / يستلقي", pronounce: "لاي", ex_en: "I sometimes lie", ar_ex: "أحياناً أكذب" },
    { id: 422, en: "life", ar: "حياة", pronounce: "لايف", ex_en: "Life is beautiful", ar_ex: "الحياة جميلة" },
    { id: 423, en: "light", ar: "ضوء / خفيف", pronounce: "لايت", ex_en: "The light is strong", ar_ex: "الضوء قوي" },
    { id: 424, en: "like (prep)", ar: "مثل", pronounce: "لايك", ex_en: "This is like you", ar_ex: "هذا مثلك" },
    { id: 425, en: "like (v)", ar: "يحب / يعجبه", pronounce: "لايك", ex_en: "I like coffee", ar_ex: "أحب القهوة" },
    { id: 426, en: "line", ar: "خط / طابور", pronounce: "لاين", ex_en: "This is a long line", ar_ex: "هذا خط طويل" },
    { id: 427, en: "lion", ar: "أسد", pronounce: "لايون", ex_en: "The lion is strong", ar_ex: "الأسد قوي" },
    { id: 428, en: "list", ar: "قائمة", pronounce: "لست", ex_en: "I have a list", ar_ex: "لدي قائمة" },
    { id: 429, en: "listen", ar: "يستمع", pronounce: "لسن", ex_en: "I listen to music", ar_ex: "أستمع للموسيقى" },
    { id: 430, en: "little", ar: "صغير / قليل", pronounce: "لتل", ex_en: "This is little", ar_ex: "هذا صغير" },
    { id: 431, en: "live", ar: "يعيش / يسكن", pronounce: "ليف", ex_en: "I live here", ar_ex: "أعيش هنا" },
    { id: 432, en: "long", ar: "طويل", pronounce: "لونغ", ex_en: "This is long", ar_ex: "هذا طويل" },
    { id: 433, en: "look", ar: "ينظر", pronounce: "لوك", ex_en: "I look at you", ar_ex: "أنظر إليك" },
    { id: 434, en: "lose", ar: "يخسر / يفقد", pronounce: "لوز", ex_en: "I lose money", ar_ex: "أخسر المال" },
    { id: 435, en: "lot", ar: "كثير", pronounce: "لوت", ex_en: "I have a lot", ar_ex: "لدي الكثير" },
    { id: 436, en: "love", ar: "يحب / حب", pronounce: "لف", ex_en: "I love my family", ar_ex: "أحب عائلتي" },
    { id: 437, en: "lunch", ar: "غداء", pronounce: "لنش", ex_en: "I eat lunch", ar_ex: "أتناول الغداء" },
    { id: 438, en: "machine", ar: "آلة", pronounce: "ماشين", ex_en: "This is a machine", ar_ex: "هذه آلة" },
    { id: 439, en: "magazine", ar: "مجلة", pronounce: "ماغازين", ex_en: "I read a magazine", ar_ex: "أقرأ مجلة" },
    { id: 440, en: "main", ar: "رئيسي / أساسي", pronounce: "مين", ex_en: "This is main", ar_ex: "هذا رئيسي" },
    { id: 441, en: "make", ar: "يصنع / يجعل", pronounce: "ميك", ex_en: "I make food", ar_ex: "أصنع طعاماً" },
    { id: 442, en: "man", ar: "رجل", pronounce: "مان", ex_en: "This is a man", ar_ex: "هذا رجل" },
    { id: 443, en: "many", ar: "كثير (للعدد)", pronounce: "مني", ex_en: "I have many books", ar_ex: "لدي كتب كثيرة" }
    { id: 444, en: "map", ar: "خريطة", pronounce: "ماب", ex_en: "I look at the map", ar_ex: "أنظر إلى الخريطة" },
    
 
];