// words.js
const levelA1_Words = [
    { id: 1, en: "a/an", ar: "أداة نكرة", pronounce: "ا / أن", ex_en: "I am a student", ar_ex: "أنا طالب" },
    { id: 2, en: "about", ar: "عن", pronounce: "أباوت", ex_en: "I talk about you", ar_ex: "أنا أتحدث عنك" },
    { id: 3, en: "above", ar: "فوق", pronounce: "أبف", ex_en: "The plane is above us", ar_ex: "الطائرة فوقنا" },
    { id: 4, en: "across", ar: "عبر", pronounce: "أكروس", ex_en: "I walked across the street", ar_ex: "مشيت عبر الشارع" },
    { id: 5, en: "action", ar: "حركة", pronounce: "أكشن", ex_en: "This is an action movie", ar_ex: "هذا فيلم مليء بالحركة" },
    { id: 6, en: "activity", ar: "نشاط", pronounce: "أكتفتي", ex_en: "The activity is fun", ar_ex: "النشاط ممتع" },
    { id: 7, en: "actor", ar: "ممثل", pronounce: "أكتر", ex_en: "He is an actor", ar_ex: "هو ممثل مشهور" },
    { id: 8, en: "actress", ar: "ممثلة", pronounce: "أكترس", ex_en: "She is an actress", ar_ex: "هي ممثلة" },
    { id: 9, en: "add", ar: "يضيف", pronounce: "أد", ex_en: "I add sugar", ar_ex: "أضيف السكر" },
    { id: 10, en: "address", ar: "عنوان", pronounce: "آدرس", ex_en: "This is my address", ar_ex: "هذا هو عنواني" },
    { id: 11, en: "adult", ar: "بالغ", pronounce: "أدلت", ex_en: "He is an adult", ar_ex: "هو شخص بالغ" },
    { id: 12, en: "afraid", ar: "خائف", pronounce: "أفريد", ex_en: "I am afraid", ar_ex: "أنا خائف" },
    { id: 13, en: "after", ar: "بعد", pronounce: "أفتر", ex_en: "After school", ar_ex: "بعد المدرسة" },
    { id: 14, en: "afternoon", ar: "بعد الظهر", pronounce: "أفترنون", ex_en: "We meet in the afternoon", ar_ex: "نلتقي بعد الظهر" },
    { id: 15, en: "again", ar: "مرة أخرى", pronounce: "أجين", ex_en: "Try again", ar_ex: "حاول مرة أخرى" },
    { id: 16, en: "age", ar: "عمر", pronounce: "إيج", ex_en: "My age is 20", ar_ex: "عمري 20 سنة" },
    { id: 17, en: "ago", ar: "منذ", pronounce: "أغو", ex_en: "A long time ago", ar_ex: "منذ زمن طويل" },
    { id: 18, en: "air", ar: "هواء", pronounce: "إير", ex_en: "The air is clean", ar_ex: "الهواء نقي" },
    { id: 19, en: "airport", ar: "مطار", pronounce: "إيربورت", ex_en: "I am at the airport", ar_ex: "أنا في المطار" },
    { id: 20, en: "all", ar: "كل", pronounce: "أول", ex_en: "All students are here", ar_ex: "كل الطلاب هنا" },
    { id: 21, en: "all right", ar: "بخير", pronounce: "أول رايت", ex_en: "Everything is all right", ar_ex: "كل شيء على ما يرام" },
    { id: 22, en: "also", ar: "أيضاً", pronounce: "أولسو", ex_en: "I also like coffee", ar_ex: "أنا أيضاً أحب القهوة" },
    { id: 23, en: "always", ar: "دائماً", pronounce: "أولويز", ex_en: "I always wake up early", ar_ex: "أنا دائماً أستيقظ مبكراً" },
    { id: 24, en: "amazing", ar: "مذهل", pronounce: "أَميزنغ", ex_en: "This is amazing", ar_ex: "هذا رائع جداً" },
    { id: 25, en: "and", ar: "و", pronounce: "أند", ex_en: "You and I are friends", ar_ex: "أنا وأنت أصدقاء" },
    { id: 26, en: "angry", ar: "غاضب", pronounce: "أنغري", ex_en: "He is angry today", ar_ex: "هو غاضب اليوم" },
    { id: 27, en: "animal", ar: "حيوان", pronounce: "أنيمَل", ex_en: "I have an animal", ar_ex: "لدي حيوان أليف" },
    { id: 28, en: "another", ar: "آخر", pronounce: "أنذر", ex_en: "I want another cup", ar_ex: "أريد كوباً آخر" },
    { id: 29, en: "answer (v)", ar: "يجيب", pronounce: "آنسر", ex_en: "I answer the question", ar_ex: "أجيب على السؤال" },
    { id: 30, en: "answer (n)", ar: "جواب", pronounce: "آنسر", ex_en: "This is the answer", ar_ex: "هذا هو الجواب" },
    { id: 31, en: "any", ar: "أي", pronounce: "إني", ex_en: "Do you have any question?", ar_ex: "هل لديك أي سؤال؟" },
    { id: 32, en: "anyone", ar: "أي شخص", pronounce: "إني ون", ex_en: "Is anyone here?", ar_ex: "هل هناك أي شخص؟" },
    { id: 33, en: "anything", ar: "أي شيء", pronounce: "إني ثنغ", ex_en: "Do you want anything?", ar_ex: "هل تريد أي شيء؟" },
    { id: 34, en: "apartment", ar: "شقة", pronounce: "أبارتمنت", ex_en: "I live in an apartment", ar_ex: "أعيش في شقة" },
    { id: 35, en: "apple", ar: "تفاح", pronounce: "أبل", ex_en: "I eat an apple", ar_ex: "أكل تفاحة" },
    { id: 36, en: "April", ar: "أبريل", pronounce: "إيبرل", ex_en: "We meet in April", ar_ex: "نلتقي في أبريل" },
    { id: 37, en: "area", ar: "منطقة", pronounce: "إيريا", ex_en: "This is a nice area", ar_ex: "هذه منطقة جميلة" },
    { id: 38, en: "arm", ar: "ذراع", pronounce: "آرم", ex_en: "My arm hurts", ar_ex: "ذراعي يؤلمني" },
    { id: 39, en: "around", ar: "حول", pronounce: "أراوند", ex_en: "I walk around the house", ar_ex: "أمشي حول البيت" },
    { id: 40, en: "arrive", ar: "يصل", pronounce: "أرايف", ex_en: "I arrive early", ar_ex: "أصل مبكراً" },
    { id: 41, en: "art", ar: "فن", pronounce: "آرت", ex_en: "I like art", ar_ex: "أحب الفن" },
    { id: 42, en: "article", ar: "مقال", pronounce: "آرتكل", ex_en: "I read an article", ar_ex: "أقرأ مقالاً" },
    { id: 43, en: "artist", ar: "فنان", pronounce: "آرتست", ex_en: "He is an artist", ar_ex: "هو فنان" },
    { id: 44, en: "as", ar: "كـ / مثل", pronounce: "آز", ex_en: "He works as a teacher", ar_ex: "هو يعمل كمعلم" },
    { id: 45, en: "ask", ar: "يسأل", pronounce: "آسك", ex_en: "I ask a question", ar_ex: "أسأل سؤالاً" },
    { id: 46, en: "at", ar: "في", pronounce: "آت", ex_en: "I am at school", ar_ex: "أنا في المدرسة" },
    { id: 47, en: "August", ar: "أغسطس", pronounce: "أوغست", ex_en: "I travel in August", ar_ex: "أسافر في أغسطس" },
    { id: 48, en: "aunt", ar: "عمة / خالة", pronounce: "آنت", ex_en: "This is my aunt", ar_ex: "هذه عمتي" },
    { id: 49, en: "autumn", ar: "خريف", pronounce: "أوتم", ex_en: "I like autumn", ar_ex: "أحب الخريف" },
    { id: 50, en: "away", ar: "بعيد", pronounce: "أوي", ex_en: "He is away", ar_ex: "هو بعيد" },
    { id: 51, en: "baby", ar: "طفل رضيع", pronounce: "بيبي", ex_en: "The baby sleeps", ar_ex: "الطفل ينام" },
    { id: 52, en: "back", ar: "إلى الخلف / ظهر", pronounce: "باك", ex_en: "Go back", ar_ex: "عد إلى الخلف" },
    { id: 53, en: "bad", ar: "سيئ", pronounce: "باد", ex_en: "This is bad", ar_ex: "هذا سيئ" },
    { id: 54, en: "bag", ar: "حقيبة", pronounce: "باغ", ex_en: "I have a bag", ar_ex: "لدي حقيبة" },
    { id: 55, en: "ball", ar: "كرة", pronounce: "بول", ex_en: "I play with a ball", ar_ex: "ألعب بالكرة" },
    { id: 56, en: "banana", ar: "موز", pronounce: "بنانا", ex_en: "I eat a banana", ar_ex: "أكل موزة" },
    { id: 57, en: "band", ar: "فرقة", pronounce: "باند", ex_en: "I have a band", ar_ex: "لدي فرقة موسيقية" },
    { id: 58, en: "bank", ar: "بنك", pronounce: "بانك", ex_en: "I go to the bank", ar_ex: "أذهب إلى البنك" },
    { id: 59, en: "bar", ar: "حانة / لوح", pronounce: "بار", ex_en: "We sit in a bar", ar_ex: "نجلس في الحانة" },
    { id: 60, en: "bath", ar: "حمام", pronounce: "باث", ex_en: "I take a bath", ar_ex: "آخذ حماماً" },
    
];