// words.js
const levelA1_Words = [
   
    { id: 1, en: "a/an", ar: "أداة نكرة", pronounce: "ا / أن", ex_en: "I am a student", ar_ex: "أنا طالب" },
    { id: 2, en: "about", ar: "عن", pronounce: "أباوت", ex_en: "I talk about you", ar_ex: "أنا أتحدث عنك" },
    { id: 3, en: "above", ar: "فوق", pronounce: "أبف", ex_en: "The plane is above us", ar_ex: "الطائرة فوقنا" },
    { id: 4, en: "across", ar: "عبر", pronounce: "أكروس", ex_en: "I walked across the street", ar_ex: "مشيت عبر الشارع" },
    { id: 5, en: "action", ar: "حركة", pronounce: "أكشن", ex_en: "This is an action movie", ar_ex: "هذا فيلم مليء بالحركة" },
    { id: 6, en: "activity", ar: "نشاط", pronounce: "أكتفتي", ex_en: "The activity is fun", ar_ex: "النشاط ممتع" },
    { id: 7, en: "actor", ar: "ممثل", pronounce: "أكتر", ex_en: "He is an actor", ar_ex: "هو ممثل مشهور" },
    { id: 8, en: "actress", ar: "ممثلة", pronounce: "أكترس", ex_en: "She is an actress", ar_ex: "هي ممثلة" },
    { id: 9, en: "add", ar: "يضيف", pronounce: "أد", ex_en: "I add sugar", ar_ex: "أضيف السكر" },
    { id: 10, en: "address", ar: "عنوان", pronounce: "آدرس", ex_en: "This is my address", ar_ex: "هذا هو عنواني" },
    { id: 11, en: "adult", ar: "بالغ", pronounce: "أدلت", ex_en: "He is an adult", ar_ex: "هو شخص بالغ" },
    { id: 12, en: "afraid", ar: "خائف", pronounce: "أفريد", ex_en: "I am afraid", ar_ex: "أنا خائف" },
    { id: 13, en: "after", ar: "بعد", pronounce: "أفتر", ex_en: "After school", ar_ex: "بعد المدرسة" },
    { id: 14, en: "afternoon", ar: "بعد الظهر", pronounce: "أفترنون", ex_en: "We meet in the afternoon", ar_ex: "نلتقي بعد الظهر" },
    { id: 15, en: "again", ar: "مرة أخرى", pronounce: "أجين", ex_en: "Try again", ar_ex: "حاول مرة أخرى" },
    { id: 16, en: "age", ar: "عمر", pronounce: "إيج", ex_en: "My age is 20", ar_ex: "عمري 20 سنة" },
    { id: 17, en: "ago", ar: "منذ", pronounce: "أغو", ex_en: "A long time ago", ar_ex: "منذ زمن طويل" },
    { id: 18, en: "air", ar: "هواء", pronounce: "إير", ex_en: "The air is clean", ar_ex: "الهواء نقي" },
    { id: 19, en: "airport", ar: "مطار", pronounce: "إيربورت", ex_en: "I am at the airport", ar_ex: "أنا في المطار" },
    { id: 20, en: "all", ar: "كل", pronounce: "أول", ex_en: "All students are here", ar_ex: "كل الطلاب هنا" },
    { id: 21, en: "all right", ar: "بخير", pronounce: "أول رايت", ex_en: "Everything is all right", ar_ex: "كل شيء على ما يرام" },
    { id: 22, en: "also", ar: "أيضاً", pronounce: "أولسو", ex_en: "I also like coffee", ar_ex: "أنا أيضاً أحب القهوة" },
    { id: 23, en: "always", ar: "دائماً", pronounce: "أولويز", ex_en: "I always wake up early", ar_ex: "أنا دائماً أستيقظ مبكراً" },
    { id: 24, en: "amazing", ar: "مذهل", pronounce: "أَميزنغ", ex_en: "This is amazing", ar_ex: "هذا رائع جداً" },
    { id: 25, en: "and", ar: "و", pronounce: "أند", ex_en: "You and I are friends", ar_ex: "أنا وأنت أصدقاء" },
    { id: 26, en: "angry", ar: "غاضب", pronounce: "أنغري", ex_en: "He is angry today", ar_ex: "هو غاضب اليوم" },
    { id: 27, en: "animal", ar: "حيوان", pronounce: "أنيمَل", ex_en: "I have an animal", ar_ex: "لدي حيوان أليف" },
    { id: 28, en: "another", ar: "آخر", pronounce: "أنذر", ex_en: "I want another cup", ar_ex: "أريد كوباً آخر" },
    { id: 29, en: "answer (v)", ar: "يجيب", pronounce: "آنسر", ex_en: "I answer the question", ar_ex: "أجيب على السؤال" },
    { id: 30, en: "answer (n)", ar: "جواب", pronounce: "آنسر", ex_en: "This is the answer", ar_ex: "هذا هو الجواب" },
    { id: 31, en: "any", ar: "أي", pronounce: "إني", ex_en: "Do you have any question?", ar_ex: "هل لديك أي سؤال؟" },
    { id: 32, en: "anyone", ar: "أي شخص", pronounce: "إني ون", ex_en: "Is anyone here?", ar_ex: "هل هناك أي شخص؟" },
    { id: 33, en: "anything", ar: "أي شيء", pronounce: "إني ثنغ", ex_en: "Do you want anything?", ar_ex: "هل تريد أي شيء؟" },
    { id: 34, en: "apartment", ar: "شقة", pronounce: "أبارتمنت", ex_en: "I live in an apartment", ar_ex: "أعيش في شقة" },
    { id: 35, en: "apple", ar: "تفاح", pronounce: "أبل", ex_en: "I eat an apple", ar_ex: "أكل تفاحة" },
    { id: 36, en: "April", ar: "أبريل", pronounce: "إيبرل", ex_en: "We meet in April", ar_ex: "نلتقي في أبريل" },
    { id: 37, en: "area", ar: "منطقة", pronounce: "إيريا", ex_en: "This is a nice area", ar_ex: "هذه منطقة جميلة" },
    { id: 38, en: "arm", ar: "ذراع", pronounce: "آرم", ex_en: "My arm hurts", ar_ex: "ذراعي يؤلمني" },
    { id: 39, en: "around", ar: "حول", pronounce: "أراوند", ex_en: "I walk around the house", ar_ex: "أمشي حول البيت" },
    { id: 40, en: "arrive", ar: "يصل", pronounce: "أرايف", ex_en: "I arrive early", ar_ex: "أصل مبكراً" },
    { id: 41, en: "art", ar: "فن", pronounce: "آرت", ex_en: "I like art", ar_ex: "أحب الفن" },
    { id: 42, en: "article", ar: "مقال", pronounce: "آرتكل", ex_en: "I read an article", ar_ex: "أقرأ مقالاً" },
    { id: 43, en: "artist", ar: "فنان", pronounce: "آرتست", ex_en: "He is an artist", ar_ex: "هو فنان" },
    { id: 44, en: "as", ar: "كـ / مثل", pronounce: "آز", ex_en: "He works as a teacher", ar_ex: "هو يعمل كمعلم" },
    { id: 45, en: "ask", ar: "يسأل", pronounce: "آسك", ex_en: "I ask a question", ar_ex: "أسأل سؤالاً" },
    { id: 46, en: "at", ar: "في", pronounce: "آت", ex_en: "I am at school", ar_ex: "أنا في المدرسة" },
    { id: 47, en: "August", ar: "أغسطس", pronounce: "أوغست", ex_en: "I travel in August", ar_ex: "أسافر في أغسطس" },
    { id: 48, en: "aunt", ar: "عمة / خالة", pronounce: "آنت", ex_en: "This is my aunt", ar_ex: "هذه عمتي" },
    { id: 49, en: "autumn", ar: "خريف", pronounce: "أوتم", ex_en: "I like autumn", ar_ex: "أحب الخريف" },
    { id: 50, en: "away", ar: "بعيد", pronounce: "أوي", ex_en: "He is away", ar_ex: "هو بعيد" },
    { id: 51, en: "baby", ar: "طفل رضيع", pronounce: "بيبي", ex_en: "The baby sleeps", ar_ex: "الطفل ينام" },
    { id: 52, en: "back", ar: "إلى الخلف / ظهر", pronounce: "باك", ex_en: "Go back", ar_ex: "عد إلى الخلف" },
    { id: 53, en: "bad", ar: "سيئ", pronounce: "باد", ex_en: "This is bad", ar_ex: "هذا سيئ" },
    { id: 54, en: "bag", ar: "حقيبة", pronounce: "باغ", ex_en: "I have a bag", ar_ex: "لدي حقيبة" },
    { id: 55, en: "ball", ar: "كرة", pronounce: "بول", ex_en: "I play with a ball", ar_ex: "ألعب بالكرة" },
    { id: 56, en: "banana", ar: "موز", pronounce: "بنانا", ex_en: "I eat a banana", ar_ex: "أكل موزة" },
    { id: 57, en: "band", ar: "فرقة", pronounce: "باند", ex_en: "I have a band", ar_ex: "لدي فرقة موسيقية" },
    { id: 58, en: "bank", ar: "بنك", pronounce: "بانك", ex_en: "I go to the bank", ar_ex: "أذهب إلى البنك" },
    { id: 59, en: "bar", ar: "حانة / لوح", pronounce: "بار", ex_en: "We sit in a bar", ar_ex: "نجلس في الحانة" },
    { id: 60, en: "bath", ar: "حمام", pronounce: "باث", ex_en: "I take a bath", ar_ex: "آخذ حماماً" },
    { id: 61, en: "bathroom", ar: "غرفة الحمام", pronounce: "باثروم", ex_en: "This is the bathroom", ar_ex: "هذا هو الحمام" },
    { id: 62, en: "be", ar: "يكون", pronounce: "بي", ex_en: "I am happy", ar_ex: "أنا سعيد" },
    { id: 63, en: "beach", ar: "شاطئ", pronounce: "بيتش", ex_en: "I go to the beach", ar_ex: "أذهب إلى الشاطئ" },
    { id: 64, en: "beautiful", ar: "جميل", pronounce: "بيوتفل", ex_en: "She is beautiful", ar_ex: "هي جميلة" },
    { id: 65, en: "because", ar: "لأن", pronounce: "بكوز", ex_en: "Because I am tired", ar_ex: "لأنني تعبت" },
    { id: 66, en: "become", ar: "يصبح", pronounce: "بكم", ex_en: "I become a doctor", ar_ex: "أصبح طبيباً" },
    { id: 67, en: "bed", ar: "سرير", pronounce: "بد", ex_en: "I go to bed", ar_ex: "أذهب إلى السرير" },
    { id: 68, en: "bedroom", ar: "غرفة نوم", pronounce: "بدروم", ex_en: "This is my bedroom", ar_ex: "هذه غرفة نومي" },
    { id: 69, en: "beer", ar: "بيرة", pronounce: "بير", ex_en: "I drink beer", ar_ex: "أشرب بيرة" },
    { id: 70, en: "before", ar: "قبل", pronounce: "بفور", ex_en: "Before work", ar_ex: "قبل العمل" },
    { id: 71, en: "begin", ar: "يبدأ", pronounce: "بغن", ex_en: "I begin now", ar_ex: "أبدأ الآن" },
    { id: 72, en: "beginning", ar: "بداية", pronounce: "بغننغ", ex_en: "This is the beginning", ar_ex: "هذه البداية" },
    { id: 73, en: "behind", ar: "خلف", pronounce: "بهايند", ex_en: "Behind the house", ar_ex: "خلف المنزل" },
    { id: 74, en: "believe", ar: "يؤمن / يصدق", pronounce: "بليف", ex_en: "I believe you", ar_ex: "أؤمن بك" },
    { id: 75, en: "below", ar: "أسفل / تحت", pronounce: "بلو", ex_en: "Below the table", ar_ex: "أسفل الطاولة" },
    { id: 76, en: "best", ar: "الأفضل", pronounce: "بست", ex_en: "This is the best", ar_ex: "هذا هو الأفضل" },
    { id: 77, en: "better", ar: "أفضل", pronounce: "بتر", ex_en: "This is better", ar_ex: "هذا أفضل" },
    { id: 78, en: "between", ar: "بين", pronounce: "بتوين", ex_en: "Between us", ar_ex: "بيننا" },
    { id: 79, en: "bicycle", ar: "دراجة هوائية", pronounce: "بايسكل", ex_en: "I have a bicycle", ar_ex: "لدي دراجة" },
    { id: 80, en: "big", ar: "كبير", pronounce: "بغ", ex_en: "This is big", ar_ex: "هذا كبير" },
    { id: 81, en: "bike", ar: "دراجة", pronounce: "بايك", ex_en: "I ride a bike", ar_ex: "أركب دراجة" },
    { id: 82, en: "bill", ar: "فاتورة", pronounce: "بل", ex_en: "I pay the bill", ar_ex: "أدفع الفاتورة" },
    { id: 83, en: "bird", ar: "طائر", pronounce: "برد", ex_en: "I see a bird", ar_ex: "أرى طائراً" },
    { id: 84, en: "birthday", ar: "عيد ميلاد", pronounce: "بيرثدي", ex_en: "Today is my birthday", ar_ex: "عيد ميلادي اليوم" },
    { id: 85, en: "black", ar: "أسود", pronounce: "بلاك", ex_en: "This is black", ar_ex: "هذا أسود" },
    { id: 86, en: "blog", ar: "مدونة", pronounce: "بلوغ", ex_en: "I have a blog", ar_ex: "لدي مدونة" },
    { id: 87, en: "blonde", ar: "أشقر", pronounce: "بلوند", ex_en: "Her hair is blonde", ar_ex: "شعرها أشقر" },
    { id: 88, en: "blue", ar: "أزرق", pronounce: "بلو", ex_en: "The sky is blue", ar_ex: "السماء زرقاء" },
    { id: 89, en: "boat", ar: "قارب", pronounce: "بوت", ex_en: "I ride a boat", ar_ex: "أركب قارباً" },
    { id: 90, en: "body", ar: "جسم", pronounce: "بودي", ex_en: "This is my body", ar_ex: "هذا جسمي" },
    { id: 91, en: "book", ar: "كتاب", pronounce: "بوك", ex_en: "I read a book", ar_ex: "أقرأ كتاباً" },
    { id: 92, en: "boot", ar: "حذاء طويل", pronounce: "بوت", ex_en: "I wear a boot", ar_ex: "أرتدي حذاءً طويلاً" },
    { id: 93, en: "bored", ar: "يشعر بالملل", pronounce: "بورد", ex_en: "I am bored", ar_ex: "أنا أشعر بالملل" },
    { id: 94, en: "boring", ar: "ممل", pronounce: "بورنغ", ex_en: "This is boring", ar_ex: "هذا ممل" },
    { id: 95, en: "born", ar: "ولد", pronounce: "بورن", ex_en: "I was born here", ar_ex: "ولدت هنا" },
    { id: 96, en: "both", ar: "كلاهما", pronounce: "بوث", ex_en: "Both are here", ar_ex: "كلاهما هنا" },
    { id: 97, en: "bottle", ar: "زجاجة", pronounce: "بوتل", ex_en: "I drink from a bottle", ar_ex: "أشرب من زجاجة" },
    { id: 98, en: "bottom", ar: "أسفل / قاع", pronounce: "بوتم", ex_en: "At the bottom", ar_ex: "في الأسفل" },
    { id: 99, en: "box", ar: "صندوق", pronounce: "بوكس", ex_en: "Put it in the box", ar_ex: "ضعها في الصندوق" },
    { id: 100, en: "boy", ar: "ولد", pronounce: "بوي", ex_en: "This is a boy", ar_ex: "هذا ولد" },
    { id: 101, en: "boyfriend", ar: "صديق (حبيب)", pronounce: "بوي فريند", ex_en: "He is my boyfriend", ar_ex: "هذا صديقي" },
    { id: 102, en: "bread", ar: "خبز", pronounce: "برد", ex_en: "I eat bread", ar_ex: "أكل خبزاً" },
    { id: 103, en: "break", ar: "يكسر / استراحة", pronounce: "بريك", ex_en: "I break the glass", ar_ex: "أكسر الزجاج" },
    { id: 104, en: "breakfast", ar: "فطور", pronounce: "بركفاست", ex_en: "I eat breakfast", ar_ex: "أتناول الإفطار" },
    { id: 105, en: "bring", ar: "يحضر", pronounce: "برنغ", ex_en: "I bring the book", ar_ex: "أحضر الكتاب" },
    { id: 106, en: "brother", ar: "أخ", pronounce: "برذر", ex_en: "He is my brother", ar_ex: "هذا أخي" },
    { id: 107, en: "brown", ar: "بني", pronounce: "براون", ex_en: "This is brown", ar_ex: "هذا بني" },
    { id: 108, en: "build", ar: "يبني", pronounce: "بلد", ex_en: "I build a house", ar_ex: "أبني بيتاً" },
    { id: 109, en: "building", ar: "مبنى", pronounce: "بلدنغ", ex_en: "This is a building", ar_ex: "هذا مبنى" },
    { id: 110, en: "bus", ar: "حافلة", pronounce: "بس", ex_en: "I take the bus", ar_ex: "أركب الحافلة" },
    { id: 111, en: "business", ar: "عمل / تجارة", pronounce: "بزنس", ex_en: "I have a business", ar_ex: "لدي عمل" },
    { id: 112, en: "busy", ar: "مشغول", pronounce: "بزي", ex_en: "I am busy", ar_ex: "أنا مشغول" },
    { id: 113, en: "but", ar: "لكن", pronounce: "بت", ex_en: "I want to go but I am tired", ar_ex: "أريد الذهاب لكنني متعب" },
    { id: 114, en: "butter", ar: "زبدة", pronounce: "بتر", ex_en: "I put butter", ar_ex: "أضع الزبدة" },
    { id: 115, en: "buy", ar: "يشتري", pronounce: "باي", ex_en: "I buy food", ar_ex: "أشتري طعاماً" },
    { id: 116, en: "by", ar: "بواسطة", pronounce: "باي", ex_en: "I go by car", ar_ex: "أذهب بالسيارة" },
    { id: 117, en: "bye", ar: "وداعاً", pronounce: "باي", ex_en: "Bye!", ar_ex: "وداعاً!" },
    { id: 118, en: "cafe", ar: "مقهى", pronounce: "كافيه", ex_en: "We sit in a cafe", ar_ex: "نجلس في مقهى" },
    { id: 119, en: "cake", ar: "كعكة", pronounce: "كيك", ex_en: "I eat cake", ar_ex: "أكل كعكة" },
    { id: 120, en: "call", ar: "يتصل / ينادي", pronounce: "كول", ex_en: "I call you", ar_ex: "أتصل بك" },
    { id: 121, en: "camera", ar: "كاميرا", pronounce: "كاميرا", ex_en: "I have a camera", ar_ex: "لدي كاميرا" },
    { id: 122, en: "can", ar: "يستطيع", pronounce: "كان", ex_en: "I can swim", ar_ex: "أستطيع السباحة" },
    { id: 123, en: "cannot", ar: "لا يستطيع", pronounce: "كانوت", ex_en: "I cannot go", ar_ex: "لا أستطيع الذهاب" },
    { id: 124, en: "capital", ar: "عاصمة / حرف كبير", pronounce: "كابتل", ex_en: "This is the capital", ar_ex: "هذه العاصمة" },
    { id: 125, en: "car", ar: "سيارة", pronounce: "كار", ex_en: "I have a car", ar_ex: "أملك سيارة" },
    { id: 126, en: "card", ar: "بطاقة", pronounce: "كارد", ex_en: "I have a card", ar_ex: "لدي بطاقة" },
    { id: 127, en: "carrot", ar: "جزر", pronounce: "كاروت", ex_en: "I eat a carrot", ar_ex: "أكل جزرة" },
    { id: 128, en: "carry", ar: "يحمل", pronounce: "كاري", ex_en: "I carry the bag", ar_ex: "أحمل الحقيبة" },
    { id: 129, en: "cat", ar: "قطة", pronounce: "كات", ex_en: "I have a cat", ar_ex: "لدي قطة" },
    { id: 130, en: "CD", ar: "قرص مدمج", pronounce: "سي دي", ex_en: "I listen to a CD", ar_ex: "أستمع إلى قرص مدمج" },
    { id: 131, en: "cent", ar: "سنت", pronounce: "سنت", ex_en: "This is a cent", ar_ex: "هذا سنت" },
    { id: 132, en: "centre", ar: "مركز", pronounce: "سنتر", ex_en: "I am in the centre", ar_ex: "أنا في المركز" },
    { id: 133, en: "chair", ar: "كرسي", pronounce: "تشير", ex_en: "I sit on a chair", ar_ex: "أجلس على الكرسي" },
    { id: 134, en: "change", ar: "يغير / تغيير", pronounce: "تشينج", ex_en: "I change the plan", ar_ex: "أغير الخطة" },
    { id: 135, en: "chart", ar: "مخطط", pronounce: "تشارت", ex_en: "I see a chart", ar_ex: "أرى مخططاً" },
    { id: 136, en: "cheap", ar: "رخيص", pronounce: "تشيب", ex_en: "This is cheap", ar_ex: "هذا رخيص" },
    { id: 137, en: "check", ar: "يتحقق / يفحص", pronounce: "تشك", ex_en: "I check the work", ar_ex: "أتحقق من العمل" },
    { id: 138, en: "cheese", ar: "جبن", pronounce: "تشيز", ex_en: "I like cheese", ar_ex: "أحب الجبن" },
    { id: 139, en: "chicken", ar: "دجاج", pronounce: "تشكن", ex_en: "I eat chicken", ar_ex: "آكل دجاجاً" },
    { id: 140, en: "child", ar: "طفل", pronounce: "تشايلد", ex_en: "The child plays", ar_ex: "الطفل يلعب" },
    { id: 141, en: "chocolate", ar: "شوكولاتة", pronounce: "تشوكلت", ex_en: "I like chocolate", ar_ex: "أحب الشوكولاتة" },
    { id: 142, en: "choose", ar: "يختار", pronounce: "تشوز", ex_en: "I choose this", ar_ex: "أختار هذا" },
    { id: 143, en: "cinema", ar: "سينما", pronounce: "سنما", ex_en: "I go to the cinema", ar_ex: "أذهب إلى السينما" },
    { id: 144, en: "city", ar: "مدينة", pronounce: "ستي", ex_en: "This is a big city", ar_ex: "هذه مدينة كبيرة" },
    { id: 145, en: "class", ar: "صف / فصل", pronounce: "كلاس", ex_en: "This is a class", ar_ex: "هذا صف" },
    { id: 146, en: "classroom", ar: "غرفة الصف", pronounce: "كلاسروم", ex_en: "This is a classroom", ar_ex: "هذا فصل دراسي" },
    { id: 147, en: "clean (v)", ar: "ينظف", pronounce: "كلين", ex_en: "I clean the room", ar_ex: "أنظف الغرفة" },
    { id: 148, en: "clean (adj)", ar: "نظيف", pronounce: "كلين", ex_en: "This is clean", ar_ex: "هذا نظيف" },
    { id: 149, en: "climb", ar: "يتسلق", pronounce: "كلايمب", ex_en: "I climb the mountain", ar_ex: "أتسلق الجبل" },
    { id: 150, en: "clock", ar: "ساعة حائط", pronounce: "كلوك", ex_en: "The clock is on the wall", ar_ex: "الساعة على الحائط" },
    { id: 151, en: "close", ar: "يغلق / قريب", pronounce: "كلوز", ex_en: "I close the door", ar_ex: "أغلق الباب" },
    { id: 152, en: "clothes", ar: "ملابس", pronounce: "كلوذز", ex_en: "These are my clothes", ar_ex: "هذه ملابسي" },
    { id: 153, en: "club", ar: "نادي", pronounce: "كلب", ex_en: "I am in a club", ar_ex: "أنا في النادي" },
    { id: 154, en: "coat", ar: "معطف", pronounce: "كوت", ex_en: "I wear a coat", ar_ex: "أرتدي معطفاً" },
    { id: 155, en: "coffee", ar: "قهوة", pronounce: "كوفي", ex_en: "I drink coffee", ar_ex: "أشرب قهوة" },
    { id: 156, en: "cold", ar: "بارد", pronounce: "كولد", ex_en: "It is cold", ar_ex: "الجو بارد" },
    { id: 157, en: "college", ar: "كلية", pronounce: "كولج", ex_en: "I study in college", ar_ex: "أدرس في الكلية" },
    { id: 158, en: "colour", ar: "لون", pronounce: "كلر", ex_en: "This colour is nice", ar_ex: "هذا اللون جميل" },
    { id: 159, en: "come", ar: "يأتي", pronounce: "كم", ex_en: "Come here", ar_ex: "تعال هنا" },
    { id: 160, en: "company", ar: "شركة", pronounce: "كمبني", ex_en: "This is a company", ar_ex: "هذه شركة" },
    { id: 161, en: "complete", ar: "يكمل / كامل", pronounce: "كمبليت", ex_en: "I complete the work", ar_ex: "أكمل العمل" },
    { id: 162, en: "computer", ar: "حاسوب", pronounce: "كمبيوتر", ex_en: "I use a computer", ar_ex: "أستخدم الحاسوب" },
    { id: 163, en: "concert", ar: "حفلة موسيقية", pronounce: "كونسرت", ex_en: "I attend a concert", ar_ex: "أحضر حفلة موسيقية" },
    { id: 164, en: "cook", ar: "يطبخ / طباخ", pronounce: "كوك", ex_en: "I cook food", ar_ex: "أطبخ الطعام" },
    { id: 165, en: "cooking", ar: "الطبخ", pronounce: "كوكنغ", ex_en: "I like cooking", ar_ex: "أحب الطبخ" },
    { id: 166, en: "cool", ar: "رائع / معتدل البرودة", pronounce: "كول", ex_en: "This is cool", ar_ex: "هذا رائع" },
    { id: 167, en: "correct", ar: "صحيح / يصحح", pronounce: "كوركت", ex_en: "This is correct", ar_ex: "هذا صحيح" },
    { id: 168, en: "cost", ar: "يكلف / تكلفة", pronounce: "كوست", ex_en: "It costs a lot", ar_ex: "يكلف كثيراً" },
    { id: 169, en: "could", ar: "استطاع / يمكن", pronounce: "كود", ex_en: "I could help", ar_ex: "يمكنني المساعدة" },
    { id: 170, en: "country", ar: "بلد", pronounce: "كنتري", ex_en: "This is a country", ar_ex: "هذا بلد جميل" },
    { id: 171, en: "course", ar: "دورة تعليمية", pronounce: "كورس", ex_en: "This is a course", ar_ex: "هذا درس مهم" },
    { id: 172, en: "cousin", ar: "ابن عم / خالة", pronounce: "كزن", ex_en: "He is my cousin", ar_ex: "هذا ابن عمي" },
    { id: 173, en: "cow", ar: "بقرة", pronounce: "كاو", ex_en: "I see a cow", ar_ex: "أرى بقرة" },
    { id: 174, en: "cream", ar: "كريم / قشطة", pronounce: "كريم", ex_en: "I use cream", ar_ex: "أضع كريماً" },
    { id: 175, en: "cup", ar: "كوب / فنجان", pronounce: "كب", ex_en: "I drink from a cup", ar_ex: "أشرب من كوب" },
    { id: 176, en: "customer", ar: "زبون", pronounce: "كستمر", ex_en: "This is a customer", ar_ex: "هذا زبون" },
    { id: 177, en: "cut", ar: "يقطع / قص", pronounce: "كت", ex_en: "I cut the paper", ar_ex: "أقطع الورق" },
    { id: 178, en: "dad", ar: "أب", pronounce: "داد", ex_en: "This is my dad", ar_ex: "هذا أبي" },
    { id: 179, en: "daily", ar: "يومي", pronounce: "ديلي", ex_en: "This is a daily task", ar_ex: "هذا عمل يومي" },
    { id: 180, en: "dance", ar: "يرقص / رقص", pronounce: "دانس", ex_en: "I dance now", ar_ex: "أرقص الآن" },
    { id: 181, en: "dancer", ar: "راقص", pronounce: "دانسر", ex_en: "She is a dancer", ar_ex: "هي راقصة" },
    { id: 182, en: "dancing", ar: "الرقص", pronounce: "دانسنغ", ex_en: "I like dancing", ar_ex: "أحب الرقص" },
    { id: 183, en: "dangerous", ar: "خطير", pronounce: "دينجرس", ex_en: "This is dangerous", ar_ex: "هذا خطير" },
    { id: 184, en: "dark", ar: "مظلم / داكن", pronounce: "دارك", ex_en: "The room is dark", ar_ex: "الغرفة مظلمة" },
    { id: 185, en: "date", ar: "تاريخ / موعد", pronounce: "ديت", ex_en: "What is the date?", ar_ex: "ما هو التاريخ؟" },
    { id: 186, en: "daughter", ar: "ابنة", pronounce: "دوتر", ex_en: "This is my daughter", ar_ex: "هذه ابنتي" },
    { id: 187, en: "day", ar: "يوم", pronounce: "دي", ex_en: "Today is nice", ar_ex: "اليوم جميل" },
    { id: 188, en: "dear", ar: "عزيزي", pronounce: "دير", ex_en: "Dear friend", ar_ex: "عزيزي صديقي" },
    { id: 189, en: "December", ar: "ديسمبر", pronounce: "ديسمبر", ex_en: "December is cold", ar_ex: "ديسمبر بارد" },
    { id: 190, en: "decide", ar: "يقرر", pronounce: "دسايد", ex_en: "I decide now", ar_ex: "أقرر الآن" },
    { id: 191, en: "delicious", ar: "لذيذ", pronounce: "دلشس", ex_en: "This is delicious", ar_ex: "هذا لذيذ" },
    { id: 192, en: "desk", ar: "مكتب", pronounce: "دسك", ex_en: "This is my desk", ar_ex: "هذا مكتبي" },
    { id: 193, en: "detail", ar: "تفصيل", pronounce: "ديتيل", ex_en: "This is an important detail", ar_ex: "هذا تفصيل مهم" },
    { id: 194, en: "dialogue", ar: "حوار", pronounce: "دايلوغ", ex_en: "I read a dialogue", ar_ex: "أقرأ حواراً" },
    { id: 195, en: "dictionary", ar: "قاموس", pronounce: "دكشنري", ex_en: "I use a dictionary", ar_ex: "أستخدم قاموساً" },
    { id: 196, en: "die", ar: "يموت", pronounce: "داي", ex_en: "The plant dies", ar_ex: "يموت النبات" },
    { id: 197, en: "diet", ar: "حمية غذائية", pronounce: "دايت", ex_en: "I follow a diet", ar_ex: "أتبع حمية" },
    { id: 198, en: "different", ar: "مختلف", pronounce: "دفرنت", ex_en: "This is different", ar_ex: "هذا مختلف" },
    { id: 199, en: "difficult", ar: "صعب", pronounce: "ديفكلت", ex_en: "This is difficult", ar_ex: "هذا صعب" },
    { id: 200, en: "dinner", ar: "عشاء", pronounce: "دنر", ex_en: "I eat dinner", ar_ex: "أتناول العشاء" },
   

];