const levelCLASS1_Words = [
  { "id": 1, "en": "hello", "ar": "مرحبًا", "pronounce": "هَلّو", "ex_en": "Hello, my name is Tala", "ar_ex": "مرحبًا، اسمي تالا" },
  { "id": 2, "en": "hi", "ar": "مرحبًا", "pronounce": "هاي", "ex_en": "Hi, how are you?", "ar_ex": "مرحبًا، كيف حالك؟" },
  { "id": 3, "en": "good bye", "ar": "مع السلامة", "pronounce": "غُد باي", "ex_en": "Good bye, see you tomorrow", "ar_ex": "مع السلامة، أراك غدًا" },
  { "id": 4, "en": "bye", "ar": "مع السلامة", "pronounce": "باي", "ex_en": "Bye, have a nice day", "ar_ex": "وداعًا، يومك سعيد" },
  { "id": 5, "en": "good morning", "ar": "صباح الخير", "pronounce": "غُد مورنِنغ", "ex_en": "Good morning, my dear teacher", "ar_ex": "صباح الخير معلمتي العزيزة" },
  { "id": 6, "en": "good afternoon", "ar": "مساء الخير", "pronounce": "غُد آفترنون", "ex_en": "Good afternoon, let us study", "ar_ex": "مساء الخير، لنبدأ الدراسة" },
  { "id": 7, "en": "What’s your name?", "ar": "ما اسمك؟", "pronounce": "وُتس يُور نِيم", "ex_en": "What is your name, please?", "ar_ex": "ما اسمك من فضلك؟" },
  { "id": 8, "en": "My name’s Tala", "ar": "اسمي تالا", "pronounce": "ماي نِيمز تالا", "ex_en": "My name is Tala", "ar_ex": "اسمي هو تالا" },
  { "id": 9, "en": "nut", "ar": "فستق", "pronounce": "نَت", "ex_en": "I like to eat a nut", "ar_ex": "أحب تناول الفستق" },
  { "id": 10, "en": "melon", "ar": "شمّام", "pronounce": "مِلَن", "ex_en": "The melon is very sweet", "ar_ex": "الشمّام لذيذ جدًا" },
  { "id": 11, "en": "olive", "ar": "زيتون", "pronounce": "أُولِف", "ex_en": "I put olive on bread", "ar_ex": "أضع الزيتون على الخبز" },
  { "id": 12, "en": "date", "ar": "تمر", "pronounce": "دَيْت", "ex_en": "Eat a date every day", "ar_ex": "تناول تمرة كل يوم" },
  { "id": 13, "en": "egg", "ar": "بيضة", "pronounce": "إِغ", "ex_en": "I eat an egg daily", "ar_ex": "أنا آكل بيضة يوميًا" },
  { "id": 14, "en": "bread", "ar": "خبز", "pronounce": "بِرِد", "ex_en": "The bread is fresh", "ar_ex": "الخبز طازج" },
  { "id": 15, "en": "cheese", "ar": "جبن", "pronounce": "تشيز", "ex_en": "I love eating white cheese", "ar_ex": "أحب أكل الجبن الأبيض" },
  { "id": 16, "en": "goat", "ar": "ماعز", "pronounce": "غَوت", "ex_en": "The goat is on the farm", "ar_ex": "الماعز في المزرعة" },
  { "id": 17, "en": "rabbit", "ar": "أرنب", "pronounce": "رَابِت", "ex_en": "The rabbit can jump", "ar_ex": "الأرنب يستطيع القفز" },
  { "id": 18, "en": "insect", "ar": "حشرة", "pronounce": "إِنْسِكت", "ex_en": "The insect is small", "ar_ex": "الحشرة صغيرة جدًا" },
  { "id": 19, "en": "zebra", "ar": "حمار وحشي", "pronounce": "زِيبرا", "ex_en": "The zebra is black and white", "ar_ex": "الحمار الوحشي أسود وأبيض" },
  { "id": 20, "en": "lion", "ar": "أسد", "pronounce": "لايَن", "ex_en": "The lion is a big animal", "ar_ex": "الأسد حيوان كبير" },
  { "id": 21, "en": "cat", "ar": "قط", "pronounce": "كات", "ex_en": "The cat is in the box", "ar_ex": "القط داخل الصندوق" },
  { "id": 22, "en": "dog", "ar": "كلب", "pronounce": "دوغ", "ex_en": "The dog is my friend", "ar_ex": "الكلب هو صديقي" },
  { "id": 23, "en": "shoulder", "ar": "كتف", "pronounce": "شُولْدَر", "ex_en": "Touch your right shoulder", "ar_ex": "المس كتفك الأيمن" },
  { "id": 24, "en": "eye", "ar": "عين", "pronounce": "آي", "ex_en": "I see with my eye", "ar_ex": "أنا أرى بعيني" },
  { "id": 25, "en": "ear", "ar": "أذن", "pronounce": "إِير", "ex_en": "Listen with your ear", "ar_ex": "استمع بأذنك" },
  { "id": 26, "en": "nose", "ar": "أنف", "pronounce": "نَوز", "ex_en": "Touch your small nose", "ar_ex": "المس أنفك الصغير" },
  { "id": 27, "en": "mouth", "ar": "فم", "pronounce": "ماوْث", "ex_en": "Open your mouth now", "ar_ex": "افتح فمك الآن" },
  { "id": 28, "en": "face", "ar": "وجه", "pronounce": "فِيس", "ex_en": "Wash your face every morning", "ar_ex": "اغسل وجهك كل صباح" },
  { "id": 29, "en": "leg", "ar": "ساق", "pronounce": "لِغ", "ex_en": "My leg is strong", "ar_ex": "ساقي قوية" },
  { "id": 30, "en": "finger", "ar": "إصبع", "pronounce": "فِنغَر", "ex_en": "Point with your finger", "ar_ex": "أشر بإصبعك" },
  { "id": 31, "en": "head", "ar": "رأس", "pronounce": "هِد", "ex_en": "I wear a hat on head", "ar_ex": "ألبس قبعة على رأسي" },
  { "id": 32, "en": "hair", "ar": "شعر", "pronounce": "هَيْر", "ex_en": "My hair is clean", "ar_ex": "شعري نظيف" },
  { "id": 33, "en": "bag", "ar": "حقيبة", "pronounce": "باغ", "ex_en": "Put books in your bag", "ar_ex": "ضع الكتب في حقيبتك" },
  { "id": 34, "en": "classroom", "ar": "صف", "pronounce": "كْلاسْروم", "ex_en": "Our classroom is nice", "ar_ex": "صفنا جميل" },
  { "id": 35, "en": "teacher", "ar": "معلم", "pronounce": "تِيتْشَر", "ex_en": "The teacher is kind", "ar_ex": "المعلم طيب" },
  { "id": 36, "en": "pencil", "ar": "قلم رصاص", "pronounce": "بِنسِل", "ex_en": "Use your pencil to write", "ar_ex": "استخدم قلمك للكتابة" },
  { "id": 37, "en": "board", "ar": "لوح", "pronounce": "بُورد", "ex_en": "Look at the board", "ar_ex": "انظر إلى اللوح" },
  { "id": 38, "en": "desk", "ar": "مكتب", "pronounce": "دِسْك", "ex_en": "Keep your desk clean", "ar_ex": "حافظ على نظافة مكتبك" },
  { "id": 39, "en": "book", "ar": "كتاب", "pronounce": "بُك", "ex_en": "Read your book now", "ar_ex": "اقرأ كتابك الآن" },
  { "id": 40, "en": "family", "ar": "عائلة", "pronounce": "فامِلي", "ex_en": "I love my small family", "ar_ex": "أنا أحب عائلتي الصغيرة" },
  { "id": 41, "en": "Who is this?", "ar": "من هذا؟", "pronounce": "هو إِز ذِس؟", "ex_en": "Who is this tall boy?", "ar_ex": "من هذا الولد الطويل؟" },
  { "id": 42, "en": "dad", "ar": "أب", "pronounce": "داد", "ex_en": "My dad is great", "ar_ex": "أبي رائع" },
  { "id": 43, "en": "mum", "ar": "أم", "pronounce": "مَم", "ex_en": "My mum is kind", "ar_ex": "أمي طيبة" },
  { "id": 44, "en": "sister", "ar": "أخت", "pronounce": "سِستَر", "ex_en": "My sister is cute", "ar_ex": "أختي لطيفة" },
  { "id": 45, "en": "brother", "ar": "أخ", "pronounce": "بْرَذَر", "ex_en": "My brother plays with me", "ar_ex": "أخي يلعب معي" },
  { "id": 46, "en": "baby", "ar": "طفل", "pronounce": "بِيبِي", "ex_en": "The baby is sleeping", "ar_ex": "الطفل نائم" },
  { "id": 47, "en": "every", "ar": "كل", "pronounce": "إِفري", "ex_en": "I play every day", "ar_ex": "أنا ألعب كل يوم" },
  { "id": 48, "en": "milk", "ar": "حليب", "pronounce": "مِلك", "ex_en": "Drink your milk, please", "ar_ex": "اشرب حليبك من فضلك" },
  { "id": 49, "en": "tea", "ar": "شاي", "pronounce": "تي", "ex_en": "I drink hot tea", "ar_ex": "أنا أشرب الشاي الساخن" },
  { "id": 50, "en": "coffee", "ar": "قهوة", "pronounce": "كُوفي", "ex_en": "Mum drinks some coffee", "ar_ex": "أمي تشرب القليل من القهوة" },
  { "id": 51, "en": "water", "ar": "ماء", "pronounce": "وُوتر", "ex_en": "Drink water to stay healthy", "ar_ex": "اشرب الماء لتبقى بصحة" },
  { "id": 52, "en": "juice", "ar": "عصير", "pronounce": "جوس", "ex_en": "This juice is delicious", "ar_ex": "هذا العصير لذيذ" },
  { "id": 53, "en": "apple juice", "ar": "عصير تفاح", "pronounce": "أَبُل جوس", "ex_en": "I like apple juice", "ar_ex": "أنا أحب عصير التفاح" },
  { "id": 54, "en": "ball", "ar": "كرة", "pronounce": "بول", "ex_en": "I have a red ball", "ar_ex": "لدي كرة حمراء" },
  { "id": 55, "en": "doll", "ar": "دمية", "pronounce": "دُول", "ex_en": "My doll is very beautiful", "ar_ex": "دميتي جميلة جدًا" },
  { "id": 56, "en": "yo-yo", "ar": "لعبة", "pronounce": "يُو يُو", "ex_en": "Play with the yo-yo", "ar_ex": "العب باليو يو" },
  { "id": 57, "en": "kite", "ar": "طائرة ورقية", "pronounce": "كايت", "ex_en": "The kite is in sky", "ar_ex": "الطائرة في السماء" },
  { "id": 58, "en": "balloon", "ar": "بالون", "pronounce": "بَلون", "ex_en": "Blow up the balloon", "ar_ex": "انفخ البالون" },
  { "id": 59, "en": "skate", "ar": "زلاجة", "pronounce": "سْكِيت", "ex_en": "I can skate well", "ar_ex": "أستطيع التزلج جيدًا" },
  { "id": 60, "en": "tooth", "ar": "سن", "pronounce": "توث", "ex_en": "Brush your tooth daily", "ar_ex": "نظف سنك يوميًا" },
  { "id": 61, "en": "here", "ar": "هنا", "pronounce": "هِير", "ex_en": "Come here, my friend", "ar_ex": "تعال هنا يا صديقي" },
  { "id": 62, "en": "there", "ar": "هناك", "pronounce": "ذِير", "ex_en": "Look over there now", "ar_ex": "انظر إلى هناك الآن" },
  { "id": 63, "en": "car", "ar": "سيارة", "pronounce": "كار", "ex_en": "My car is blue", "ar_ex": "سيارتي زرقاء" },
  { "id": 64, "en": "bus", "ar": "حافلة", "pronounce": "بَس", "ex_en": "The bus is big", "ar_ex": "الحافلة كبيرة" },
  { "id": 65, "en": "bike", "ar": "دراجة", "pronounce": "بايك", "ex_en": "I ride my bike", "ar_ex": "أنا أركب دراجتي" },
  { "id": 66, "en": "van", "ar": "شاحنة", "pronounce": "فان", "ex_en": "The van is moving", "ar_ex": "الشاحنة تتحرك" },
  { "id": 67, "en": "taxi", "ar": "سيارة أجرة", "pronounce": "تاكسي", "ex_en": "Take a taxi home", "ar_ex": "خذ تاكسي للمنزل" },
  { "id": 68, "en": "How many?", "ar": "كم عدد؟", "pronounce": "هاو مِني", "ex_en": "How many books are here?", "ar_ex": "كم كتابًا هنا؟" },
  { "id": 69, "en": "What color?", "ar": "ما اللون؟", "pronounce": "وُت كَلَر", "ex_en": "What color is this?", "ar_ex": "ما لون هذا؟" },
  { "id": 70, "en": "color", "ar": "اللون", "pronounce": "كَلَر", "ex_en": "Red is my favorite color", "ar_ex": "الأحمر هو لوني المفضل" },
  { "id": 71, "en": "flag", "ar": "علم", "pronounce": "فْلاغ", "ex_en": "Raise the flag high", "ar_ex": "ارفع العلم عاليًا" },
  { "id": 72, "en": "stand up", "ar": "قف", "pronounce": "ستاند أَب", "ex_en": "Please, stand up now", "ar_ex": "من فضلك قف الآن" },
  { "id": 73, "en": "sit down", "ar": "اجلس", "pronounce": "سِت داون", "ex_en": "Sit down and listen", "ar_ex": "اجلس واستمع" },
  { "id": 74, "en": "jump", "ar": "اقفز", "pronounce": "جَمب", "ex_en": "Jump up and down", "ar_ex": "اقفز للأعلى وللأسفل" },
  { "id": 75, "en": "point", "ar": "يشير", "pronounce": "بوينت", "ex_en": "Point to the picture", "ar_ex": "أشر إلى الصورة" },
  { "id": 76, "en": "skirt", "ar": "تنّورة", "pronounce": "سْكِرت", "ex_en": "The skirt is new", "ar_ex": "التنورة جديدة" },
  { "id": 77, "en": "t-shirt", "ar": "بلوزة", "pronounce": "تي شِرت", "ex_en": "I like this t-shirt", "ar_ex": "أنا أحب هذه البلوزة" },
  { "id": 78, "en": "dress", "ar": "فستان", "pronounce": "دْرِس", "ex_en": "The dress is pink", "ar_ex": "الفستان لونه وردي" },
  { "id": 79, "en": "shoes", "ar": "حذاء", "pronounce": "شوز", "ex_en": "Wear your brown shoes", "ar_ex": "ارتدِ حذاءك البني" },
  { "id": 80, "en": "shorts", "ar": "شورت", "pronounce": "شورتس", "ex_en": "Put on your shorts", "ar_ex": "ارتدِ الشورت الخاص بك" },
  { "id": 81, "en": "jeans", "ar": "جينز", "pronounce": "جينز", "ex_en": "These jeans are comfortable", "ar_ex": "هذا الجينز مريح" },
  { "id": 82, "en": "bed", "ar": "تخت", "pronounce": "بِد", "ex_en": "The bed is soft", "ar_ex": "التخت مريح" },
  { "id": 83, "en": "table", "ar": "طاولة", "pronounce": "تَيْبِل", "ex_en": "Put food on table", "ar_ex": "ضع الطعام على الطاولة" },
  { "id": 84, "en": "chair", "ar": "كرسي", "pronounce": "تْشِيَر", "ex_en": "Sit on the chair", "ar_ex": "اجلس على الكرسي" },
  { "id": 85, "en": "box", "ar": "صندوق", "pronounce": "بوكس", "ex_en": "The box is small", "ar_ex": "الصندوق صغير" },
  { "id": 86, "en": "window", "ar": "نافذة", "pronounce": "وِندَو", "ex_en": "Open the window please", "ar_ex": "افتح النافذة من فضلك" },
  { "id": 87, "en": "door", "ar": "باب", "pronounce": "دُور", "ex_en": "Close the door now", "ar_ex": "أغلق الباب الآن" },
  { "id": 88, "en": "on", "ar": "على", "pronounce": "أون", "ex_en": "The cat is on bed", "ar_ex": "القط على التخت" },
  { "id": 89, "en": "under", "ar": "تحت", "pronounce": "أَنْدَر", "ex_en": "The ball is under chair", "ar_ex": "الكرة تحت الكرسي" },
  { "id": 90, "en": "in", "ar": "في", "pronounce": "إِن", "ex_en": "Put it in the box", "ar_ex": "ضعها في الصندوق" },
  { "id": 91, "en": "orange", "ar": "برتقالة", "pronounce": "أُورِنْج", "ex_en": "I eat an orange", "ar_ex": "أنا آكل برتقالة" },
  { "id": 92, "en": "lemon", "ar": "ليمون", "pronounce": "لِمَن", "ex_en": "Lemon is very sour", "ar_ex": "الليمون حامض جدًا" },
  { "id": 93, "en": "grapes", "ar": "عنب", "pronounce": "غْرِيبس", "ex_en": "Grapes are very yummy", "ar_ex": "العنب لذيذ جدًا" },
  { "id": 94, "en": "apple", "ar": "تفاحة", "pronounce": "أَبُل", "ex_en": "Eat a red apple", "ar_ex": "تناول تفاحة حمراء" },
  { "id": 95, "en": "banana", "ar": "موز", "pronounce": "بَنَانَا", "ex_en": "I like to eat banana", "ar_ex": "أحب أكل الموز" },
  { "id": 96, "en": "fig", "ar": "تين", "pronounce": "فِغ", "ex_en": "The fig is sweet", "ar_ex": "التين حلو المذاق" },
  { "id": 97, "en": "big", "ar": "كبير", "pronounce": "بِغ", "ex_en": "The elephant is big", "ar_ex": "الفيل كبير" },
  { "id": 98, "en": "small", "ar": "صغير", "pronounce": "سْمُول", "ex_en": "The ant is small", "ar_ex": "النملة صغيرة" },
  { "id": 99, "en": "friend", "ar": "صديق", "pronounce": "فْرِينْد", "ex_en": "He is my best friend", "ar_ex": "هو صديقي المفضل" },
  { "id": 100, "en": "short", "ar": "قصير", "pronounce": "شُورت", "ex_en": "The pencil is short", "ar_ex": "قلم الرصاص قصير" },
  { "id": 101, "en": "tall", "ar": "طويل", "pronounce": "تُول", "ex_en": "The tree is very tall", "ar_ex": "الشجرة طويلة جدًا" },
  { "id": 102, "en": "count", "ar": "يعدّ", "pronounce": "كَاونت", "ex_en": "Count the apples, please", "ar_ex": "عد التفاح من فضلك" },
  { "id": 103, "en": "guess", "ar": "يُخمّن", "pronounce": "غِس", "ex_en": "Guess what I have", "ar_ex": "خمن ماذا لدي" },
  { "id": 104, "en": "skip", "ar": "يقفز", "pronounce": "سْكِب", "ex_en": "Let us skip happily", "ar_ex": "لنقفز بسعادة" },
  { "id": 105, "en": "come", "ar": "يأتي", "pronounce": "كَم", "ex_en": "Come to me now", "ar_ex": "تعال إليّ الآن" },
  { "id": 106, "en": "get", "ar": "يحصل", "pronounce": "غِت", "ex_en": "Get your books now", "ar_ex": "أحضر كتبك الآن" },
  { "id": 107, "en": "tomorrow", "ar": "غدًا", "pronounce": "تُمارُو", "ex_en": "See you tomorrow morning", "ar_ex": "أراك غدًا صباحًا" },
  { "id": 108, "en": "yesterday", "ar": "أمس", "pronounce": "يِستَردَي", "ex_en": "I played yesterday", "ar_ex": "أنا لعبت بالأمس" },
  { "id": 109, "en": "tracksuit", "ar": "بدلة رياضة", "pronounce": "تْراكْسوت", "ex_en": "Wear your clean tracksuit", "ar_ex": "ارتدِ بدلتك الرياضية" },
  { "id": 110, "en": "tractor", "ar": "جرّار", "pronounce": "تْراكْتَر", "ex_en": "The tractor is red", "ar_ex": "الجرار لونه أحمر" },
  { "id": 111, "en": "trainer", "ar": "مدرّب", "pronounce": "تْرِينَر", "ex_en": "The trainer is nice", "ar_ex": "المدرّب لطيف" },
  { "id": 112, "en": "triangle", "ar": "مثلث", "pronounce": "ترايَانغِل", "ex_en": "Draw a small triangle", "ar_ex": "ارسم مثلثًا صغيرًا" },
  { "id": 113, "en": "walk", "ar": "يمشي", "pronounce": "وُوك", "ex_en": "Let us walk outside", "ar_ex": "لنتمشى في الخارج" },
  { "id": 114, "en": "wall", "ar": "حائط", "pronounce": "وُول", "ex_en": "Paint the wall white", "ar_ex": "اطله الحائط بالأبيض" },
  { "id": 115, "en": "watch", "ar": "يشاهد", "pronounce": "وُوتش", "ex_en": "Watch TV with me", "ar_ex": "شاهد التلفاز معي" },
  { "id": 116, "en": "write", "ar": "يكتب", "pronounce": "رايت", "ex_en": "Write your name clearly", "ar_ex": "اكتب اسمك بوضوح" },
  { "id": 117, "en": "arm", "ar": "ذراع", "pronounce": "آرم", "ex_en": "Move your arm slowly", "ar_ex": "حرك ذراعك ببطء" },
  { "id": 118, "en": "brush", "ar": "فرشاة", "pronounce": "بْرَش", "ex_en": "Use your hair brush", "ar_ex": "استخدم فرشاة شعرك" },
  { "id": 119, "en": "city", "ar": "مدينة", "pronounce": "سِتي", "ex_en": "Nablus is a city", "ar_ex": "نابلس مدينة" },
  { "id": 120, "en": "delicious", "ar": "لذيذ", "pronounce": "دِلِشَس", "ex_en": "The food is delicious", "ar_ex": "الطعام لذيذ" },
  { "id": 121, "en": "eat", "ar": "يأكل", "pronounce": "إيت", "ex_en": "Eat healthy food always", "ar_ex": "كل طعامًا صحيًا دائمًا" },
  { "id": 122, "en": "red", "ar": "أحمر", "pronounce": "رِد", "ex_en": "I love the color red", "ar_ex": "أنا أحب اللون الأحمر" },
  { "id": 123, "en": "black", "ar": "أسود", "pronounce": "بْلاك", "ex_en": "The cat is black", "ar_ex": "القط أسود" },
  { "id": 124, "en": "white", "ar": "أبيض", "pronounce": "وايت", "ex_en": "The snow is white", "ar_ex": "الثلج أبيض" },
  { "id": 125, "en": "green", "ar": "أخضر", "pronounce": "غرين", "ex_en": "The grass is green", "ar_ex": "العشب أخضر" },
  { "id": 126, "en": "blue", "ar": "أزرق", "pronounce": "بلو", "ex_en": "The sky is blue", "ar_ex": "السماء زرقاء" },
  { "id": 127, "en": "yellow", "ar": "أصفر", "pronounce": "يِلّو", "ex_en": "The sun is yellow", "ar_ex": "الشمس صفراء" },
  { "id": 128, "en": "umbrella", "ar": "مظلة", "pronounce": "أَمبْرِلّا", "ex_en": "Take your umbrella now", "ar_ex": "خذ مظلتك الآن" },
  { "id": 129, "en": "air", "ar": "هواء", "pronounce": "إير", "ex_en": "The air is fresh", "ar_ex": "الهواء نقي" },
  { "id": 130, "en": "bedtime", "ar": "وقت النوم", "pronounce": "بِدتايم", "ex_en": "It is now bedtime", "ar_ex": "إنه الآن وقت النوم" },
  { "id": 131, "en": "blouse", "ar": "بلوزة", "pronounce": "بْلاوس", "ex_en": "The blouse is clean", "ar_ex": "البلوزة نظيفة" },
  { "id": 132, "en": "bus station", "ar": "محطة باص", "pronounce": "بَس ستيشن", "ex_en": "Go to bus station", "ar_ex": "اذهب لمحطة الباص" },
  { "id": 133, "en": "calculator", "ar": "آلة حاسبة", "pronounce": "كالكيوليتر", "ex_en": "Use the calculator now", "ar_ex": "استخدم الآلة الحاسبة" },
  { "id": 134, "en": "careful", "ar": "حذر", "pronounce": "كِيرفُل", "ex_en": "Please, be careful now", "ar_ex": "من فضلك كن حذرًا" },
  { "id": 135, "en": "chalk", "ar": "طباشير", "pronounce": "تشوك", "ex_en": "Use the white chalk", "ar_ex": "استخدم الطباشير البيضاء" },
  { "id": 136, "en": "child", "ar": "طفل", "pronounce": "تشايلد", "ex_en": "The child is happy", "ar_ex": "الطفل سعيد" },
  { "id": 137, "en": "circle", "ar": "دائرة", "pronounce": "سِركِل", "ex_en": "Draw a big circle", "ar_ex": "ارسم دائرة كبيرة" },
  { "id": 138, "en": "farm", "ar": "مزرعة", "pronounce": "فارم", "ex_en": "I go to farm", "ar_ex": "أنا أذهب للمزرعة" },
  { "id": 139, "en": "feather", "ar": "ريشة", "pronounce": "فِذَر", "ex_en": "The feather is soft", "ar_ex": "الريشة ناعمة" },
  { "id": 140, "en": "flat", "ar": "شقة", "pronounce": "فلات", "ex_en": "Our flat is nice", "ar_ex": "شقتنا جميلة" },
  { "id": 141, "en": "France", "ar": "فرنسا", "pronounce": "فْرانس", "ex_en": "France is a country", "ar_ex": "فرنسا بلد" },
  { "id": 142, "en": "give", "ar": "يعطي", "pronounce": "غِف", "ex_en": "Give me a book", "ar_ex": "أعطني كتابًا" },
  { "id": 143, "en": "gloves", "ar": "قفازات", "pronounce": "غْلَفز", "ex_en": "Wear your warm gloves", "ar_ex": "ارتدِ قفازاتك الدافئة" },
  { "id": 144, "en": "go", "ar": "يذهب", "pronounce": "غو", "ex_en": "Let us go now", "ar_ex": "لنذهب الآن" },
  { "id": 145, "en": "homework", "ar": "وظيفة", "pronounce": "هومورك", "ex_en": "Do your homework today", "ar_ex": "قم بحل وظيفتك اليوم" },
  { "id": 146, "en": "key", "ar": "مفتاح", "pronounce": "كي", "ex_en": "I have the key", "ar_ex": "أنا أملك المفتاح" },
  { "id": 147, "en": "letter", "ar": "رسالة", "pronounce": "لِتَر", "ex_en": "Write a nice letter", "ar_ex": "اكتب رسالة جميلة" },
  { "id": 148, "en": "light", "ar": "ضوء", "pronounce": "لايت", "ex_en": "Turn on the light", "ar_ex": "شغل الضوء" }
];


