const levelCLASS4_Words = [
  { "id": 1, "en": "welcome", "ar": "أهلًا وسهلًا", "pronounce": "وِلْكَم", "ex_en": "Welcome to our beautiful school", "ar_ex": "أهلاً وسهلاً بكم في مدرستنا الجميلة" },
  { "id": 2, "en": "pupil", "ar": "تلميذ", "pronounce": "بْيُوبِل", "ex_en": "He is a clever pupil", "ar_ex": "هو تلميذ ذكي" },
  { "id": 3, "en": "driver", "ar": "سائق", "pronounce": "دْرايفَر", "ex_en": "The bus driver drives carefully", "ar_ex": "سائق الحافلة يقود بحذر" },
  { "id": 4, "en": "engineer", "ar": "مهندس", "pronounce": "إِنْجِنِير", "ex_en": "My dad is an engineer", "ar_ex": "أبي مهندس" },
  { "id": 5, "en": "housewife", "ar": "ربة منزل", "pronounce": "هاوس وايف", "ex_en": "The housewife cleans the room", "ar_ex": "ربة المنزل تنظف الغرفة" },
  { "id": 6, "en": "doctor", "ar": "طبيب", "pronounce": "دُكْتَر", "ex_en": "Go to the doctor today", "ar_ex": "اذهب إلى الطبيب اليوم" },
  { "id": 7, "en": "nurse", "ar": "ممرض/ة", "pronounce": "نِرس", "ex_en": "The kind nurse helps patients", "ar_ex": "الممرضة الطيبة تساعد المرضى" },
  { "id": 8, "en": "dentist", "ar": "طبيب أسنان", "pronounce": "دِنْتِست", "ex_en": "I visit the dentist weekly", "ar_ex": "أنا أزور طبيب الأسنان أسبوعيًا" },
  { "id": 9, "en": "farmer", "ar": "مزارع", "pronounce": "فارْمَر", "ex_en": "The farmer works hard daily", "ar_ex": "المزارع يعمل بجد يوميًا" },
  { "id": 10, "en": "spoon", "ar": "ملعقة", "pronounce": "سْبون", "ex_en": "Eat soup with a spoon", "ar_ex": "كل الحساء بالملعقة" },
  { "id": 11, "en": "dry", "ar": "جاف", "pronounce": "دراي", "ex_en": "The desert ground is dry", "ar_ex": "أرض الصحراء جافة" },
  { "id": 12, "en": "ride", "ar": "يركب", "pronounce": "رايد", "ex_en": "I ride my new bicycle", "ar_ex": "أنا أركب دراجتي الجديدة" },
  { "id": 13, "en": "pick", "ar": "يلتقط", "pronounce": "بِك", "ex_en": "Pick up the yellow flowers", "ar_ex": "التقط الزهور الصفراء" },
  { "id": 14, "en": "hobby", "ar": "هواية", "pronounce": "هُوبي", "ex_en": "Drawing is my favorite hobby", "ar_ex": "الرسم هو هوايتي المفضلة" },
  { "id": 15, "en": "spell", "ar": "يتهجّى", "pronounce": "سْبِل", "ex_en": "Can you spell your name?", "ar_ex": "هل يمكنك تهجئة اسمك؟" },
  { "id": 16, "en": "kitchen", "ar": "مطبخ", "pronounce": "كِتْشِن", "ex_en": "Mum cooks in the kitchen", "ar_ex": "أمي تطبخ في المطبخ" },
  { "id": 17, "en": "bedroom", "ar": "غرفة نوم", "pronounce": "بِدروم", "ex_en": "Sleep in your clean bedroom", "ar_ex": "نم في غرفة نومك النظيفة" },
  { "id": 18, "en": "living room", "ar": "غرفة الجلوس", "pronounce": "لِفِنغ روم", "ex_en": "We watch TV in living room", "ar_ex": "نحن نشاهد التلفاز في غرفة الجلوس" },
  { "id": 19, "en": "bathroom", "ar": "حمام", "pronounce": "باثْروم", "ex_en": "Wash hands in the bathroom", "ar_ex": "اغسل يديك في الحمام" },
  { "id": 20, "en": "reading book", "ar": "قراءة كتاب", "pronounce": "ريدِنغ بُك", "ex_en": "I like reading book daily", "ar_ex": "أحب قراءة كتاب يوميًا" },
  { "id": 21, "en": "watching TV", "ar": "مشاهدة التلفاز", "pronounce": "وُوتشِنغ تي في", "ex_en": "He prefers watching TV now", "ar_ex": "هو يفضل مشاهدة التلفاز الآن" },
  { "id": 22, "en": "sleeping", "ar": "النوم", "pronounce": "سْليبِنغ", "ex_en": "Sleeping early is very good", "ar_ex": "النوم مبكرًا مفيد جدًا" },
  { "id": 23, "en": "newspaper", "ar": "جريدة", "pronounce": "نيوزبيپَر", "ex_en": "My grandfather reads the newspaper", "ar_ex": "جدي يقرأ الجريدة" },
  { "id": 24, "en": "season", "ar": "فصل", "pronounce": "سيزَن", "ex_en": "Spring is a beautiful season", "ar_ex": "الربيع فصل جميل" },
  { "id": 25, "en": "today", "ar": "اليوم", "pronounce": "تُداي", "ex_en": "Today is a happy holiday", "ar_ex": "اليوم عطلة سعيدة" },
  { "id": 26, "en": "lost", "ar": "مفقود", "pronounce": "لوست", "ex_en": "I found my lost pen", "ar_ex": "وجدت قلمي المفقود" },
  { "id": 27, "en": "cupboard", "ar": "خزانة", "pronounce": "كَبُورد", "ex_en": "Put clothes in the cupboard", "ar_ex": "ضع الملابس في الخزانة" },
  { "id": 28, "en": "bin", "ar": "سلة", "pronounce": "بِن", "ex_en": "Throw trash in the bin", "ar_ex": "ارمِ القمامة في السلة" },
  { "id": 29, "en": "drawer", "ar": "درج", "pronounce": "دْرَوَر", "ex_en": "Open the desk drawer carefully", "ar_ex": "افتح درج المكتب بحذر" },
  { "id": 30, "en": "shelf", "ar": "رف", "pronounce": "شِلف", "ex_en": "Put books on the shelf", "ar_ex": "ضع الكتب على الرف" },
  { "id": 31, "en": "lamp", "ar": "مصباح", "pronounce": "لامب", "ex_en": "Turn on the small lamp", "ar_ex": "أشعل المصباح الصغير" },
  { "id": 32, "en": "bottle", "ar": "قنينة", "pronounce": "بُوتِل", "ex_en": "Fill the water bottle now", "ar_ex": "املأ قنينة الماء الآن" },
  { "id": 33, "en": "mess", "ar": "فوضى", "pronounce": "مِس", "ex_en": "Do not make a mess", "ar_ex": "لا تحدث فوضى" },
  { "id": 34, "en": "dinar", "ar": "دينار", "pronounce": "دينار", "ex_en": "I have one Jordanian dinar", "ar_ex": "لدي دينار أردني واحد" },
  { "id": 35, "en": "shopkeeper", "ar": "بائع", "pronounce": "شوب كِيپَر", "ex_en": "The shopkeeper sells fresh fruits", "ar_ex": "البائع يبيع فواكه طازجة" },
  { "id": 36, "en": "customer", "ar": "زبون", "pronounce": "كَسْتُمَر", "ex_en": "The customer buys hot bread", "ar_ex": "الزبون يشتري خبزًا ساخنًا" },
  { "id": 37, "en": "shopping", "ar": "تسوّق", "pronounce": "شوبِنغ", "ex_en": "We go shopping every week", "ar_ex": "نحن نذهب للتسوق كل أسبوع" },
  { "id": 38, "en": "need", "ar": "يحتاج", "pronounce": "نيد", "ex_en": "I need a new pencil", "ar_ex": "أنا أحتاج قلم رصاص جديد" },
  { "id": 39, "en": "holiday", "ar": "عطلة", "pronounce": "هولِداي", "ex_en": "We travel during the holiday", "ar_ex": "نحن نسافر خلال العطلة" },
  { "id": 40, "en": "stay", "ar": "يبقى", "pronounce": "سْتاي", "ex_en": "Stay at home tonight, please", "ar_ex": "ابقَ في المنزل الليلة من فضلك" },
  { "id": 41, "en": "indoors", "ar": "داخل", "pronounce": "إِنْدُورز", "ex_en": "We play chess indoors always", "ar_ex": "نحن نلعب الشطرنج في الداخل دائمًا" },
  { "id": 42, "en": "fly", "ar": "يطير", "pronounce": "فلاي", "ex_en": "Birds can fly very high", "ar_ex": "الطيور تستطيع الطيران عاليًا جدًا" },
  { "id": 43, "en": "build", "ar": "يبني", "pronounce": "بِلد", "ex_en": "Let us build a snowman", "ar_ex": "لنقم ببناء رجل ثلج" },
  { "id": 44, "en": "snowman", "ar": "رجل ثلج", "pronounce": "سْنوومان", "ex_en": "The white snowman is huge", "ar_ex": "رجل الثلج الأبيض ضخم" },
  { "id": 45, "en": "above", "ar": "فوق", "pronounce": "أبَڤ", "ex_en": "The plane flies above clouds", "ar_ex": "الطائرة تحلق فوق الغيوم" },
  { "id": 46, "en": "at", "ar": "في", "pronounce": "آت", "ex_en": "Meet me at the park", "ar_ex": "قابلني في المنتزه" },
  { "id": 47, "en": "behind", "ar": "خلف", "pronounce": "بِهايند", "ex_en": "The cat hides behind sofa", "ar_ex": "القطة تختبئ خلف الكنبة" },
  { "id": 48, "en": "in front of", "ar": "أمام", "pronounce": "إن فرَنت أُف", "ex_en": "Stand in front of board", "ar_ex": "قف أمام اللوح" },
  { "id": 49, "en": "down", "ar": "أسفل", "pronounce": "داون", "ex_en": "Sit down on the chair", "ar_ex": "اجلس أسفل على الكرسي" },
  { "id": 50, "en": "in", "ar": "في", "pronounce": "إِن", "ex_en": "The milk is in bottle", "ar_ex": "الحليب في القنينة" },
  { "id": 51, "en": "opposite", "ar": "مقابل", "pronounce": "أُوبُزِت", "ex_en": "The school is opposite mosque", "ar_ex": "المدرسة مقابل المسجد" },
  { "id": 52, "en": "Haifa", "ar": "حيفا", "pronounce": "هايْفا", "ex_en": "Haifa is a beautiful city", "ar_ex": "حيفا مدينة جميلة" },
  { "id": 53, "en": "Akka", "ar": "عكّا", "pronounce": "أَكّا", "ex_en": "Akka has an old wall", "ar_ex": "عكا تملك سورًا قديمًا" },
  { "id": 54, "en": "Al-Ibrahimi Mosque", "ar": "المسجد الإبراهيمي", "pronounce": "أل إبراهيمي موسك", "ex_en": "We pray in Al-Ibrahimi Mosque", "ar_ex": "نحن نصلي في المسجد الإبراهيمي" },
  { "id": 55, "en": "Mount Carmel", "ar": "جبل الكرمل", "pronounce": "ماونت كارمِل", "ex_en": "Mount Carmel is in Haifa", "ar_ex": "جبل الكرمل يقع في حيفا" },
  { "id": 56, "en": "Church of the Nativity", "ar": "كنيسة المهد", "pronounce": "تشيرتش أُف ذَ ناتِڤِتي", "ex_en": "Visit the Church of Nativity", "ar_ex": "زر كنيسة المهد" },
  { "id": 57, "en": "Al-Jazzar Mosque", "ar": "مسجد الجزار", "pronounce": "أل جزار موسك", "ex_en": "Al-Jazzar Mosque is in Akka", "ar_ex": "مسجد الجزار يقع في عكا" },
  { "id": 58, "en": "Al-Aqsa Mosque", "ar": "المسجد الأقصى", "pronounce": "أل أقصى موسك", "ex_en": "Al-Aqsa Mosque is in Jerusalem", "ar_ex": "المسجد الأقصى في القدس" },
  { "id": 59, "en": "Dome of the Rock", "ar": "قبة الصخرة", "pronounce": "دوم أُف ذَ روك", "ex_en": "The Dome of Rock is golden", "ar_ex": "قبة الصخرة ذهبية" },
  { "id": 60, "en": "Dead Sea", "ar": "البحر الميت", "pronounce": "دِد سي", "ex_en": "The Dead Sea is low", "ar_ex": "البحر الميت منخفض" },
  { "id": 61, "en": "Mount of Olives", "ar": "جبل الزيتون", "pronounce": "ماونت أُف أُولِڤز", "ex_en": "Look at Mount of Olives", "ar_ex": "انظر إلى جبل الزيتون" },
  { "id": 62, "en": "market", "ar": "سوق", "pronounce": "ماركِت", "ex_en": "The traditional market is crowded", "ar_ex": "السوق التقليدي مزدحم" },
  { "id": 63, "en": "flour", "ar": "طحين", "pronounce": "فلاوَر", "ex_en": "We use flour for bread", "ar_ex": "نستخدم الطحين لصنع الخبز" },
  { "id": 64, "en": "butter", "ar": "زبدة", "pronounce": "بَتَر", "ex_en": "Put butter on the bread", "ar_ex": "ضع زبدة على الخبز" },
  { "id": 65, "en": "sugar", "ar": "سكر", "pronounce": "شوغَر", "ex_en": "Do not add much sugar", "ar_ex": "لا تضف الكثير من السكر" },
  { "id": 66, "en": "bowl", "ar": "وعاء", "pronounce": "بول", "ex_en": "Put soup in the bowl", "ar_ex": "ضع الحساء في الوعاء" },
  { "id": 67, "en": "cup", "ar": "كوب", "pronounce": "كَب", "ex_en": "Drink milk from this cup", "ar_ex": "اشرب الحليب من هذا الكوب" },
  { "id": 68, "en": "oven", "ar": "فرن", "pronounce": "أُوفِن", "ex_en": "Bake the cake in oven", "ar_ex": "اخبز الكعكة في الفرن" },
  { "id": 69, "en": "biscuits", "ar": "بسكويت", "pronounce": "بِسْكِتس", "ex_en": "I love eating chocolate biscuits", "ar_ex": "أحب أكل بسكويت الشوكولاتة" },
  { "id": 70, "en": "carrots", "ar": "جزر", "pronounce": "كارَتس", "ex_en": "Rabbits love eating fresh carrots", "ar_ex": "الأرانب تحب أكل الجزر الطازج" },
  { "id": 71, "en": "tomatoes", "ar": "بندورة", "pronounce": "تُمَيْتوز", "ex_en": "Buy red tomatoes from market", "ar_ex": "اشترِ بندورة حمراء من السوق" },
  { "id": 72, "en": "put", "ar": "يضع", "pronounce": "پُت", "ex_en": "Put the book on table", "ar_ex": "ضع الكتاب على الطاولة" },
  { "id": 73, "en": "add", "ar": "يضيف", "pronounce": "أَد", "ex_en": "Add some salt to salad", "ar_ex": "أضف بعض الملح للسلطة" },
  { "id": 74, "en": "Excuse me!", "ar": "عذرًا", "pronounce": "إكْسْكيوز مي", "ex_en": "Excuse me, where is school?", "ar_ex": "عذرًا، أين تقع المدرسة؟" },
  { "id": 75, "en": "it’s on the right", "ar": "على اليمين", "pronounce": "إِتس أُن ذَ رايت", "ex_en": "The hospital, it’s on right", "ar_ex": "المستشفى، إنه على اليمين" },
  { "id": 76, "en": "twenty", "ar": "عشرون", "pronounce": "توينتي", "ex_en": "I have twenty small toys", "ar_ex": "لدي عشرون لعبة صغيرة" },
  { "id": 77, "en": "twenty-five", "ar": "خمسة وعشرون", "pronounce": "توينتي فايف", "ex_en": "Count twenty-five green apples now", "ar_ex": "عد خمسة وعشرين تفاحة خضراء الآن" },
  { "id": 78, "en": "thirty", "ar": "ثلاثون", "pronounce": "ثيرتي", "ex_en": "There are thirty pupils here", "ar_ex": "يوجد ثلاثون تلميذًا هنا" },
  { "id": 79, "en": "thirty-five", "ar": "خمسة وثلاثون", "pronounce": "ثيرتي فايف", "ex_en": "He bought thirty-five sweet carrots", "ar_ex": "هو اشترى خمسة وثلاثين جزرة حلوة" },
  { "id": 80, "en": "forty", "ar": "أربعون", "pronounce": "فورتي", "ex_en": "My dad is forty years old", "ar_ex": "أبي عمره أربعون سنة" },
  { "id": 81, "en": "forty-five", "ar": "خمسة وأربعون", "pronounce": "فورتي فايف", "ex_en": "The math test lasts forty-five minutes", "ar_ex": "امتحان الرياضيات يستغرق خمسة وأربعين دقيقة" },
  { "id": 82, "en": "fifty", "ar": "خمسون", "pronounce": "فِفتي", "ex_en": "Give me fifty Jordanian dinars", "ar_ex": "أعطني خمسين دينارًا أردنيًا" },
  { "id": 83, "en": "fifty-five", "ar": "خمسة وخمسون", "pronounce": "فِفتي فايف", "ex_en": "The bus holds fifty-five passengers", "ar_ex": "الحافلة تتسع لخمسة وخمسين راكبًا" },
  { "id": 84, "en": "sixty", "ar": "ستون", "pronounce": "سِكستي", "ex_en": "One hour is sixty minutes", "ar_ex": "الساعة الواحدة ستون دقيقة" },
  { "id": 85, "en": "sixty-five", "ar": "خمسة وستون", "pronounce": "سِكستي فايف", "ex_en": "My grandfather is sixty-five today", "ar_ex": "جدي يبلغ خمسة وستين عامًا اليوم" },
  { "id": 86, "en": "seventy", "ar": "سبعون", "pronounce": "سِڤِنتي", "ex_en": "He scored seventy points easily", "ar_ex": "أحرز سبعين نقطة بسهولة" },
  { "id": 87, "en": "seventy-five", "ar": "خمسة وسبعون", "pronounce": "سِڤِنتي فايف", "ex_en": "The beautiful dress costs seventy-five dinars", "ar_ex": "الفستان الجميل سعره خمسة وسبعون دينارًا" },
  { "id": 88, "en": "eighty", "ar": "ثمانون", "pronounce": "إِيتِي", "ex_en": "The old woman is eighty", "ar_ex": "المرأة العجوز عمرها ثمانون عامًا" },
  { "id": 89, "en": "eighty-five", "ar": "خمسة وثمانون", "pronounce": "إِيتِي فايف", "ex_en": "Page eighty-five has beautiful stories", "ar_ex": "الصفحة خمسة وثمانون فيها قصص جميلة" },
  { "id": 90, "en": "ninety", "ar": "تسعون", "pronounce": "ناينتي", "ex_en": "I got ninety in Maths", "ar_ex": "حصلت على تسعين في الرياضيات" },
  { "id": 91, "en": "ninety-five", "ar": "خمسة وتسعون", "pronounce": "ناينتي فايف", "ex_en": "Ninety-five birds flew away together", "ar_ex": "خمسة وتسعون طائرًا طاروا معًا" },
  { "id": 92, "en": "a hundred", "ar": "مئة", "pronounce": "أ هَندْرِد", "ex_en": "This school has a hundred pupils", "ar_ex": "هذه المدرسة تضم مئة تلميذ" },
  { "id": 93, "en": "sports", "ar": "رياضة", "pronounce": "سبورتس", "ex_en": "I play sports every Friday", "ar_ex": "أنا أمارس الرياضة كل جمعة" },
  { "id": 94, "en": "Maths", "ar": "رياضيات", "pronounce": "ماثس", "ex_en": "Maths is a useful subject", "ar_ex": "الرياضيات مادة مفيدة" },
  { "id": 95, "en": "religion", "ar": "دين", "pronounce": "رِلِجَن", "ex_en": "We study religion at school", "ar_ex": "نحن ندرس الدين في المدرسة" },
  { "id": 96, "en": "science", "ar": "علوم", "pronounce": "سايَنس", "ex_en": "Science lessons are very interesting", "ar_ex": "دروس العلوم ممتعة جدًا" },
  { "id": 97, "en": "story", "ar": "قصة", "pronounce": "سْتوري", "ex_en": "Read this short story tonight", "ar_ex": "اقرأ هذه القصة القصيرة الليلة" },
  { "id": 98, "en": "learn", "ar": "يتعلم", "pronounce": "لِرن", "ex_en": "We learn English at school", "ar_ex": "نحن نتعلم الإنجليزية في المدرسة" },
  { "id": 99, "en": "napkin", "ar": "منديل", "pronounce": "نابكِن", "ex_en": "Clean your face with napkin", "ar_ex": "نظف وجهك بالمنديل" },
  { "id": 100, "en": "menu", "ar": "قائمة", "pronounce": "مِنيُو", "ex_en": "Look at the food menu", "ar_ex": "انظر إلى قائمة الطعام" },
  { "id": 101, "en": "fork", "ar": "شوكة", "pronounce": "فورك", "ex_en": "Eat salad with a fork", "ar_ex": "كل السلطة بالشوكة" },
  { "id": 102, "en": "glass", "ar": "كأس", "pronounce": "غلاس", "ex_en": "Give me a glass water", "ar_ex": "أعطني كأس ماء" },
  { "id": 103, "en": "knife", "ar": "سكين", "pronounce": "نايف", "ex_en": "Do not touch the knife", "ar_ex": "لا تلمس السكين" },
  { "id": 104, "en": "January", "ar": "كانون الثاني", "pronounce": "جانيوَري", "ex_en": "January is a cold month", "ar_ex": "كانون الثاني شهر بارد" },
  { "id": 105, "en": "February", "ar": "شباط", "pronounce": "فِبْرُواري", "ex_en": "February is the shortest month", "ar_ex": "شباط هو أقصر شهر" },
  { "id": 106, "en": "April", "ar": "نيسان", "pronounce": "إيبْرِل", "ex_en": "April weather is usually lovely", "ar_ex": "طقس نيسان لطيف عادة" },
  { "id": 107, "en": "May", "ar": "أيار", "pronounce": "ماي", "ex_en": "Flowers bloom beautifully in May", "ar_ex": "الزهور تتفتح بجمال في أيار" },
  { "id": 108, "en": "June", "ar": "حزيران", "pronounce": "جون", "ex_en": "Our summer holiday starts June", "ar_ex": "عطلتنا الصيفية تبدأ في حزيران" },
  { "id": 109, "en": "July", "ar": "تموز", "pronounce": "جولاَي", "ex_en": "July weather is very hot", "ar_ex": "طقس تموز حار جداً" },
  { "id": 110, "en": "August", "ar": "آب", "pronounce": "أُوغَست", "ex_en": "We go beach in August", "ar_ex": "نحن نذهب للشاطئ في آب" },
  { "id": 111, "en": "September", "ar": "أيلول", "pronounce": "سِبْتِمبَر", "ex_en": "School starts early in September", "ar_ex": "المدرسة تبدأ مبكراً في أيلول" },
  { "id": 112, "en": "October", "ar": "تشرين الأول", "pronounce": "أُكْتوبَر", "ex_en": "Autumn leaves fall in October", "ar_ex": "أوراق الخريف تسقط في تشرين الأول" },
  { "id": 113, "en": "November", "ar": "تشرين الثاني", "pronounce": "نُوفِمبَر", "ex_en": "It rains heavily in November", "ar_ex": "تمطر بغزارة في تشرين الثاني" },
  { "id": 114, "en": "December", "ar": "كانون الأول", "pronounce": "دِسِمبَر", "ex_en": "December is the last month", "ar_ex": "كانون الأول هو الشهر الأخير" },
  { "id": 115, "en": "a lot", "ar": "كثير", "pronounce": "أ لوت", "ex_en": "I love my mother a lot", "ar_ex": "أحب أمي كثيراً" },
  { "id": 116, "en": "subject", "ar": "موضوع", "pronounce": "سَبْجِكت", "ex_en": "English is my favorite subject", "ar_ex": "الإنجليزية هي مادتي المفضلة" },
  { "id": 117, "en": "sky", "ar": "سماء", "pronounce": "سْكاي", "ex_en": "The sky is clear blue", "ar_ex": "السماء زرقاء صافية" },
  { "id": 118, "en": "year", "ar": "سنة", "pronounce": "يير", "ex_en": "A year has twelve months", "ar_ex": "السنة فيها اثنا عشر شهراً" },
  { "id": 119, "en": "day", "ar": "يوم", "pronounce": "داي", "ex_en": "Today is a beautiful day", "ar_ex": "اليوم يوم جميل" },
  { "id": 120, "en": "month", "ar": "شهر", "pronounce": "مَنْث", "ex_en": "January is the first month", "ar_ex": "كانون الثاني هو الشهر الأول" },
  { "id": 121, "en": "week", "ar": "أسبوع", "pronounce": "ويك", "ex_en": "A week has seven days", "ar_ex": "الأسبوع فيه سبعة أيام" },
  { "id": 122, "en": "hour", "ar": "ساعة", "pronounce": "آور", "ex_en": "Wait for one hour, please", "ar_ex": "انتظر لمدة ساعة واحدة من فضلك" },
  { "id": 123, "en": "spring", "ar": "الربيع", "pronounce": "سْبْرِنغ", "ex_en": "I love the spring season", "ar_ex": "أنا أحب فصل الربيع" },
  { "id": 124, "en": "summer", "ar": "الصيف", "pronounce": "سَمَر", "ex_en": "Summer is sunny and hot", "ar_ex": "الصيف مشمس وحار" },
  { "id": 125, "en": "autumn", "ar": "الخريف", "pronounce": "أوتَم", "ex_en": "The weather is cool autumn", "ar_ex": "الطقس بارد في الخريف" },
  { "id": 126, "en": "winter", "ar": "الشتاء", "pronounce": "وِنْتَر", "ex_en": "It always snows in winter", "ar_ex": "إنها تثلج دائمًا في الشتاء" },
  { "id": 127, "en": "cool", "ar": "بارد", "pronounce": "كول", "ex_en": "The autumn breeze is cool", "ar_ex": "نسيم الخريف بارد" },
  { "id": 128, "en": "rain", "ar": "مطر", "pronounce": "رين", "ex_en": "Heavy rain falls from sky", "ar_ex": "المطر الغزير يسقط من السماء" },
  { "id": 129, "en": "wet", "ar": "مبلل", "pronounce": "وِت", "ex_en": "My school clothes are wet", "ar_ex": "ملابسي المدرسية مبللة" },
  { "id": 130, "en": "in the morning", "ar": "في الصباح", "pronounce": "إِن ذَ مورنِنغ", "ex_en": "I go school in morning", "ar_ex": "أذهب إلى المدرسة في الصباح" },
  { "id": 131, "en": "in the afternoon", "ar": "بعد الظهر", "pronounce": "إِن ذَ آفترنون", "ex_en": "We play football in afternoon", "ar_ex": "نحن نلعب كرة القدم بعد الظهر" },
  { "id": 132, "en": "in the evening", "ar": "في المساء", "pronounce": "إِن ذَ إيفنِنغ", "ex_en": "I do homework in evening", "ar_ex": "أحل الواجب في المساء" },
  { "id": 133, "en": "night", "ar": "الليل", "pronounce": "نايت", "ex_en": "The bright stars shine night", "ar_ex": "النجوم اللامعة تضيء في الليل" },
  { "id": 134, "en": "always", "ar": "دائمًا", "pronounce": "أُولويز", "ex_en": "I always brush my teeth", "ar_ex": "أنا دائمًا أفرش أسناني" },
  { "id": 135, "en": "sometimes", "ar": "أحيانًا", "pronounce": "سَمْتايمز", "ex_en": "We sometimes visit the park", "ar_ex": "نحن أحيانًا نزور المنتزه" },
  { "id": 136, "en": "never", "ar": "أبدًا", "pronounce": "نِڤَر", "ex_en": "I never lie to anyone", "ar_ex": "أنا لا أكذب أبدًا على أحد" },
  { "id": 137, "en": "good", "ar": "جيد", "pronounce": "غُد", "ex_en": "You are a good boy", "ar_ex": "أنت ولد صالح" },
  { "id": 138, "en": "bad", "ar": "سيئ", "pronounce": "باد", "ex_en": "Do not form bad habits", "ar_ex": "لا تكتسب عادات سيئة" },
  { "id": 139, "en": "act", "ar": "يمثل", "pronounce": "آكت", "ex_en": "Children love to act plays", "ar_ex": "الأطفال يحبون تمثيل المسرحيات" },
  { "id": 140, "en": "dancing", "ar": "رقص", "pronounce": "دانسِنغ", "ex_en": "Dancing dabka is very fun", "ar_ex": "رقص الدبكة ممتع جدًا" },
  { "id": 141, "en": "driving a car", "ar": "يقود سيارة", "pronounce": "درايفِنغ أ كار", "ex_en": "My brother enjoys driving car", "ar_ex": "أخي يستمتع بقيادة السيارة" },
  { "id": 142, "en": "make cake", "ar": "يصنع كعكة", "pronounce": "ميك كيك", "ex_en": "Mum can make delicious cake", "ar_ex": "أمي تستطيع صنع كعكة لذيذة" },
  { "id": 143, "en": "riding a bicycle", "ar": "يركب دراجة", "pronounce": "رايدِنغ أ بايْسِكِل", "ex_en": "Riding a bicycle is great", "ar_ex": "ركوب الدراجة أمر رائع" },
  { "id": 144, "en": "play basketball", "ar": "يلعب كرة سلة", "pronounce": "بلاي باسكِتبول", "ex_en": "They play basketball together weekly", "ar_ex": "هم يلعبون كرة السلة معًا أسبوعيًا" },
  { "id": 145, "en": "play the piano", "ar": "يعزف البيانو", "pronounce": "بلاي ذَ پيانو", "ex_en": "She can play the piano", "ar_ex": "هي تستطيع العزف على البيانو" },
  { "id": 146, "en": "play tennis", "ar": "يلعب التنس", "pronounce": "بلاي تِنِس", "ex_en": "We play tennis every Saturday", "ar_ex": "نحن نلعب التنس كل سبت" },
  { "id": 147, "en": "play volleyball", "ar": "يلعب كرة طائرة", "pronounce": "بلاي ڤوليبول", "ex_en": "They play volleyball in school", "ar_ex": "هم يلعبون الكرة الطائرة في المدرسة" },
  { "id": 148, "en": "baker", "ar": "خبّاز", "pronounce": "بايكَر", "ex_en": "The baker makes white bread", "ar_ex": "الخباز يصنع الخبز الأبيض" },
  { "id": 149, "en": "book shop", "ar": "محل كتب", "pronounce": "بوك شوب", "ex_en": "Buy books from book shop", "ar_ex": "اشترِ الكتب من محل الكتب" },
  { "id": 150, "en": "grocer", "ar": "بقّال", "pronounce": "غْروسَر", "ex_en": "The grocer sells sugar, butter", "ar_ex": "البقال يبيع السكر والزبدة" },
  { "id": 151, "en": "greengrocer’s", "ar": "بائع خضار", "pronounce": "غرين غْروسَرز", "ex_en": "Buy carrots from the greengrocer’s", "ar_ex": "اشترِ الجزر من عند بائع الخضار" },
  { "id": 152, "en": "music shop", "ar": "محل موسيقى", "pronounce": "ميوزِك شوب", "ex_en": "He visits the music shop", "ar_ex": "هو يزور محل الموسيقى" },
  { "id": 153, "en": "clothes shop", "ar": "محل ملابس", "pronounce": "كْلوثز شوب", "ex_en": "This clothes shop is huge", "ar_ex": "محل الملابس هذا ضخم" },
  { "id": 154, "en": "I went to the baker", "ar": "ذهبت إلى الخباز", "pronounce": "آي وِنت تو ذَ بايكَر", "ex_en": "I went to the baker", "ar_ex": "ذهبت إلى الخباز" },
  { "id": 155, "en": "I bought bread", "ar": "اشتريت خبزًا", "pronounce": "آي بوت برِد", "ex_en": "I bought bread this morning", "ar_ex": "اشتريت خبزًا هذا الصباح" },
  { "id": 156, "en": "What time is it?", "ar": "كم الساعة؟", "pronounce": "وُت تايم إِز إِت", "ex_en": "What time is it, please?", "ar_ex": "كم الساعة من فضلك؟" },
  { "id": 157, "en": "it’s two fifteen", "ar": "الثانية وخمس عشرة", "pronounce": "إِتس تو فِفتين", "ex_en": "Look, it’s two fifteen now", "ar_ex": "انظر، إنها الثانية وخمس عشرة الآن" },
  { "id": 158, "en": "it starts at", "ar": "تبدأ في", "pronounce": "إِت سْتارتس آت", "ex_en": "It starts at three o'clock", "ar_ex": "تبدأ في تمام الساعة الثالثة" },
  { "id": 159, "en": "it finishes at", "ar": "تنتهي في", "pronounce": "إِت فِنِشِز آت", "ex_en": "It finishes at four fifteen", "ar_ex": "تنتهي في الرابعة وخمس عشرة" },
  { "id": 160, "en": "I get up at", "ar": "أستيقظ في", "pronounce": "آي گِت أَب آت", "ex_en": "I get up at six", "ar_ex": "أستيقظ في تمام السادسة" },
  { "id": 161, "en": "I brush my teeth", "ar": "أفرش أسناني", "pronounce": "آي بْرَش ماي تيث", "ex_en": "I brush my teeth daily", "ar_ex": "أفرش أسناني يوميًا" },
  { "id": 162, "en": "I wash my face", "ar": "أغسل وجهي", "pronounce": "آي ووش ماي فيس", "ex_en": "I wash my face early", "ar_ex": "أغسل وجهي مبكرًا" },
  { "id": 163, "en": "I clean my shoes", "ar": "أنظف حذائي", "pronounce": "آي كْلين ماي شوز", "ex_en": "I clean my shoes carefully", "ar_ex": "أنظف حذائي بعناية" },
  { "id": 164, "en": "I do my homework", "ar": "أعمل واجبي", "pronounce": "آي دو ماي هوموورك", "ex_en": "I do my homework now", "ar_ex": "أعمل واجبي الآن" },
  { "id": 165, "en": "Where’s the bookshop?", "ar": "أين مكتبة الكتب؟", "pronounce": "وِيرز ذَ بوكشوب", "ex_en": "Where’s the bookshop, please?", "ar_ex": "أين مكتبة الكتب من فضلك؟" },
  { "id": 166, "en": "it’s on the left", "ar": "على اليسار", "pronounce": "إِتس أُن ذَ لِفت", "ex_en": "The park, it’s on left", "ar_ex": "المنتزه، إنه على اليسار" },
  { "id": 167, "en": "duck", "ar": "بطة", "pronounce": "دَك", "ex_en": "The yellow duck swims nicely", "ar_ex": "البطة الصفراء تسبح بلطف" },
  { "id": 168, "en": "horse", "ar": "حصان", "pronounce": "هورس", "ex_en": "The brown horse runs fast", "ar_ex": "الحصان البني يركض سريعًا" },
  { "id": 169, "en": "cow", "ar": "بقرة", "pronounce": "كاو", "ex_en": "The cow gives fresh milk", "ar_ex": "البقرة تعطي حليبًا طازجًا" },
  { "id": 170, "en": "lamb", "ar": "خروف", "pronounce": "ام", "ex_en": "The small lamb is cute", "ar_ex": "الخروف الصغير لطيف" },
  { "id": 171, "en": "sheep", "ar": "نعجة", "pronounce": "شيپ", "ex_en": "The white sheep eats grass", "ar_ex": "النعجة البيضاء تأكل العشب" },
  { "id": 172, "en": "hen", "ar": "دجاجة", "pronounce": "هِن", "ex_en": "The hen lays white eggs", "ar_ex": "الدجاجة تضع بيضاً أبيض" },
  { "id": 173, "en": "donkey", "ar": "حمار", "pronounce": "دونكي", "ex_en": "The grey donkey walks slowly", "ar_ex": "الحمار الرمادي يمشي ببطء" },
  { "id": 174, "en": "there is a dog", "ar": "يوجد كلب", "pronounce": "ذِير إِز أ دوغ", "ex_en": "There is a dog outside", "ar_ex": "يوجد كلب بالخارج" },
  { "id": 175, "en": "there is not donkey", "ar": "لا يوجد حمار", "pronounce": "ذِير إِز نوت دونكي", "ex_en": "There is not donkey here", "ar_ex": "لا يوجد حمار هنا" },
  { "id": 176, "en": "there are sheep", "ar": "يوجد خراف", "pronounce": "ذِير آر شيپ", "ex_en": "There are sheep on farm", "ar_ex": "يوجد خراف في المزرعة" },
  { "id": 177, "en": "there are not a sheep", "ar": "لا توجد نعجة", "pronounce": "ذِير آر نوت أ شيپ", "ex_en": "There are not sheep here", "ar_ex": "لا توجد خراف هنا" },
  { "id": 178, "en": "my uncle has a farm", "ar": "عمي لديه مزرعة", "pronounce": "ماي أَنْكِل هاز أ فارم", "ex_en": "My uncle has a farm", "ar_ex": "عمي لديه مزرعة" },
  { "id": 179, "en": "I go to the farm", "ar": "أذهب إلى المزرعة", "pronounce": "آي غو تو ذَ فارم", "ex_en": "I go to the farm", "ar_ex": "أذهب إلى المزرعة" },
  { "id": 180, "en": "I help my uncle", "ar": "أساعد عمي", "pronounce": "ماي أَنْكِل", "ex_en": "I help my uncle daily", "ar_ex": "أساعد عمي يوميًا" },
  { "id": 181, "en": "I collect eggs", "ar": "أجمع البيض", "pronounce": "آي كُلِكت إِغز", "ex_en": "I collect eggs every morning", "ar_ex": "أنا أجمع البيض كل صباح" },
  { "id": 182, "en": "I watch the ducks", "ar": "أشاهد البط", "pronounce": "آي ووتش ذَ دَكس", "ex_en": "I watch the ducks swim", "ar_ex": "أنا أشاهد البط يسبح" }
];