const levelCLASS2_Words = [
  { "id": 1, "en": "boy", "ar": "ولد", "pronounce": "بوي", "ex_en": "He is a good boy", "ar_ex": "هو ولد صالح" },
  { "id": 2, "en": "girl", "ar": "بنت", "pronounce": "غِرل", "ex_en": "The girl plays with dolls", "ar_ex": "البنت تلعب بالدمى" },
  { "id": 3, "en": "How old are you?", "ar": "كم عمرك؟", "pronounce": "هاو أُولد آر يو؟", "ex_en": "How old are you, Tala?", "ar_ex": "كم عمرك يا تالا؟" },
  { "id": 4, "en": "I’m …", "ar": "عمري …", "pronounce": "آيم", "ex_en": "I’m seven years old", "ar_ex": "عمري سبع سنوات" },
  { "id": 5, "en": "How are you?", "ar": "كيف حالك؟", "pronounce": "هاو آر يو؟", "ex_en": "How are you today, friend?", "ar_ex": "كيف حالك اليوم يا صديقي؟" },
  { "id": 6, "en": "Fine, thanks.", "ar": "بخير، شكرًا", "pronounce": "فاين ثانكس", "ex_en": "I am fine, thanks", "ar_ex": "أنا بخير، شكرًا" },
  { "id": 7, "en": "What’s this?", "ar": "ما هذا؟", "pronounce": "وُتس ذِس؟", "ex_en": "What’s this in your hand?", "ar_ex": "ما هذا في يدك؟" },
  { "id": 8, "en": "It’s a / an …", "ar": "هذا …", "pronounce": "إتس أ / أن", "ex_en": "It’s a small blue bird", "ar_ex": "هذا طائر أزرق صغير" },
  { "id": 9, "en": "This is a / an …", "ar": "هذا …", "pronounce": "ذِس إِز أ / أن", "ex_en": "This is an apple juice", "ar_ex": "هذا عصير تفاح" },
  { "id": 10, "en": "Is this a / an … ?", "ar": "هل هذا …؟", "pronounce": "إِز ذِس أ / أن؟", "ex_en": "Is this a new book?", "ar_ex": "هل هذا كتاب جديد؟" },
  { "id": 11, "en": "Yes, it is. / No, it isn’t.", "ar": "نعم / لا", "pronounce": "يِس إت إِز / نو إت إِزنت", "ex_en": "Yes, it is a dog", "ar_ex": "نعم، هذا كلب" },
  { "id": 12, "en": "please", "ar": "من فضلك", "pronounce": "بْليز", "ex_en": "Give me water, please", "ar_ex": "أعطني ماءً من فضلك" },
  { "id": 13, "en": "rice", "ar": "أرز", "pronounce": "رايس", "ex_en": "I eat white rice daily", "ar_ex": "أنا آكل الأرز الأبيض يوميًا" },
  { "id": 14, "en": "meat", "ar": "لحم", "pronounce": "ميت", "ex_en": "The meat is very delicious", "ar_ex": "اللحم لذيذ جدًا" },
  { "id": 15, "en": "fish", "ar": "سمك", "pronounce": "فِش", "ex_en": "The fish lives in water", "ar_ex": "السمك يعيش في الماء" },
  { "id": 16, "en": "chicken", "ar": "دجاج", "pronounce": "تْشِكِن", "ex_en": "I love eating fried chicken", "ar_ex": "أحب أكل الدجاج المقلي" },
  { "id": 17, "en": "salad", "ar": "سلطة", "pronounce": "سالَد", "ex_en": "Eat some green salad now", "ar_ex": "تناول بعض السلطة الخضراء الآن" },
  { "id": 18, "en": "ice cream", "ar": "بوظة", "pronounce": "آيس كْريم", "ex_en": "I love strawberry ice cream", "ar_ex": "أحب بوظة الفراولة" },
  { "id": 19, "en": "chocolate", "ar": "شوكولاتة", "pronounce": "تشوكْلِت", "ex_en": "Do not eat much chocolate", "ar_ex": "لا تأكل الكثير من الشوكولاتة" },
  { "id": 20, "en": "like", "ar": "يحب", "pronounce": "لايك", "ex_en": "I like my kind teacher", "ar_ex": "أنا أحب معلمي الطيب" },
  { "id": 21, "en": "food", "ar": "طعام", "pronounce": "فود", "ex_en": "The food is very hot", "ar_ex": "الطعام ساخن جدًا" },
  { "id": 22, "en": "sofa", "ar": "كنبة", "pronounce": "سوفا", "ex_en": "Sit on the brown sofa", "ar_ex": "اجلس على الكنبة البنية" },
  { "id": 23, "en": "telephone", "ar": "هاتف", "pronounce": "تِلِفون", "ex_en": "The telephone is ringing now", "ar_ex": "الهاتف يرن الآن" },
  { "id": 24, "en": "rug", "ar": "سجادة", "pronounce": "رَغ", "ex_en": "The rug is on floor", "ar_ex": "السجادة على الأرض" },
  { "id": 25, "en": "rose", "ar": "وردة", "pronounce": "روز", "ex_en": "This is a beautiful rose", "ar_ex": "هذه وردة جميلة" },
  { "id": 26, "en": "shout", "ar": "يصرخ", "pronounce": "شاوْت", "ex_en": "Do not shout in class", "ar_ex": "لا تصرخ في الصف" },
  { "id": 27, "en": "sitting room", "ar": "غرفة الجلوس", "pronounce": "سِتِنغ روم", "ex_en": "We sit in sitting room", "ar_ex": "نحن نجلس في غرفة الجلوس" },
  { "id": 28, "en": "smile", "ar": "يبتسم", "pronounce": "سْمايل", "ex_en": "Smile for the nice photo", "ar_ex": "ابتسم من أجل الصورة الجميلة" },
  { "id": 29, "en": "sorry", "ar": "آسف", "pronounce": "سُوري", "ex_en": "I am sorry, my friend", "ar_ex": "أنا آسف يا صديقي" },
  { "id": 30, "en": "square", "ar": "مربع", "pronounce": "سْكْوِير", "ex_en": "Draw a small square here", "ar_ex": "ارسم مربعًا صغيرًا هنا" },
  { "id": 31, "en": "stamp", "ar": "طابع", "pronounce": "سْتامب", "ex_en": "Put a stamp on letter", "ar_ex": "ضع طابعًا على الرسالة" },
  { "id": 32, "en": "tail", "ar": "ذيل", "pronounce": "تِيل", "ex_en": "The cat has a tail", "ar_ex": "القط لديه ذيل" },
  { "id": 33, "en": "home", "ar": "بيت", "pronounce": "هوم", "ex_en": "Go back home safely now", "ar_ex": "عد إلى البيت بسلام الآن" },
  { "id": 34, "en": "mosque", "ar": "مسجد", "pronounce": "موسك", "ex_en": "I pray in the mosque", "ar_ex": "أنا أصلي في المسجد" },
  { "id": 35, "en": "church", "ar": "كنيسة", "pronounce": "تْشِرتش", "ex_en": "The church is very old", "ar_ex": "الكنيسة قديمة جدًا" },
  { "id": 36, "en": "shop", "ar": "دكان", "pronounce": "شوب", "ex_en": "Go to the food shop", "ar_ex": "اذهب إلى دكان الطعام" },
  { "id": 37, "en": "park", "ar": "منتزه", "pronounce": "بارك", "ex_en": "We play in the park", "ar_ex": "نحن نلعب في المنتزه" },
  { "id": 38, "en": "playground", "ar": "ملعب", "pronounce": "بلاي غْراوند", "ex_en": "Run in the green playground", "ar_ex": "اركض في الملعب الأخضر" },
  { "id": 39, "en": "house", "ar": "منزل", "pronounce": "هاوس", "ex_en": "My house is big, clean", "ar_ex": "منزلي كبير ونظيف" },
  { "id": 40, "en": "next to", "ar": "بجانب", "pronounce": "نِكست تو", "ex_en": "Sit next to me, please", "ar_ex": "اجلس بجانبي من فضلك" },
  { "id": 41, "en": "between", "ar": "بين", "pronounce": "بِتْوين", "ex_en": "Stand between your friends now", "ar_ex": "قف بين أصدقائك الآن" },
  { "id": 42, "en": "at my house", "ar": "في منزلي", "pronounce": "آت ماي هاوس", "ex_en": "We play at my house", "ar_ex": "نحن نلعب في منزلي" },
  { "id": 43, "en": "and", "ar": "و", "pronounce": "أند", "ex_en": "I like apples and bananas", "ar_ex": "أحب التفاح والموز" },
  { "id": 44, "en": "mountain", "ar": "جبل", "pronounce": "ماونتن", "ex_en": "The mountain is very high", "ar_ex": "الجبل مرتفع جدًا" },
  { "id": 45, "en": "dance", "ar": "رقص", "pronounce": "دانس", "ex_en": "The children love to dance", "ar_ex": "الأطفال يحبون الرقص" },
  { "id": 46, "en": "drawing", "ar": "رسم", "pronounce": "دْرُوينغ", "ex_en": "Drawing is my favorite hobby", "ar_ex": "الرسم هو هوايتي المفضلة" },
  { "id": 47, "en": "swimming", "ar": "سباحة", "pronounce": "سْوِمِنغ", "ex_en": "Swimming is a great sport", "ar_ex": "السباحة رياضة رائعة" },
  { "id": 48, "en": "reading", "ar": "قراءة", "pronounce": "ريدِنغ", "ex_en": "I enjoy reading English books", "ar_ex": "أستمتع بقراءة الكتب الإنجليزية" },
  { "id": 49, "en": "singing", "ar": "غناء", "pronounce": "سِنغِنغ", "ex_en": "She likes singing nice songs", "ar_ex": "هي تحب غناء أغانٍ جميلة" },
  { "id": 50, "en": "ship", "ar": "سفينة", "pronounce": "شِب", "ex_en": "The big ship is sailing", "ar_ex": "السفينة الكبيرة تبحر" },
  { "id": 51, "en": "plane", "ar": "طائرة", "pronounce": "بْلاين", "ex_en": "The plane flies high up", "ar_ex": "الطائرة تحلق عاليًا" },
  { "id": 52, "en": "train", "ar": "قطار", "pronounce": "تْرين", "ex_en": "The train moves fast now", "ar_ex": "القطار يتحرك سريعًا الآن" },
  { "id": 53, "en": "get up", "ar": "يستيقظ", "pronounce": "گِت أَب", "ex_en": "I get up early daily", "ar_ex": "أستيقظ مبكرًا كل يوم" },
  { "id": 54, "en": "help", "ar": "يساعد", "pronounce": "هِلب", "ex_en": "Help your mother at home", "ar_ex": "ساعد والدتك في المنزل" },
  { "id": 55, "en": "hummus", "ar": "حمص", "pronounce": "هُمُس", "ex_en": "I eat hummus with bread", "ar_ex": "آكل الحمص مع الخبز" },
  { "id": 56, "en": "knee", "ar": "ركبة", "pronounce": "ني", "ex_en": "Touch your right knee now", "ar_ex": "المس ركبتك اليمنى الآن" },
  { "id": 57, "en": "bicycle", "ar": "دراجة", "pronounce": "بايْسِكِل", "ex_en": "Ride your blue bicycle safely", "ar_ex": "اركب دراجتك الزرقاء بأمان" },
  { "id": 58, "en": "this plane", "ar": "هذه الطائرة", "pronounce": "ذِس بْلاين", "ex_en": "Look at this plane fly", "ar_ex": "انظر إلى هذه الطائرة تطير" },
  { "id": 59, "en": "this ship", "ar": "هذه السفينة", "pronounce": "ذِس شِب", "ex_en": "This ship is very large", "ar_ex": "هذه السفينة ضخمة جدًا" },
  { "id": 60, "en": "these cars", "ar": "تلك السيارات", "pronounce": "ذِيز كارز", "ex_en": "These cars move very fast", "ar_ex": "تلك السيارات تتحرك بسرعة كبيرة" },
  { "id": 61, "en": "keyboard", "ar": "لوحة مفاتيح", "pronounce": "كِي بُورد", "ex_en": "Clean the computer keyboard now", "ar_ex": "نظف لوحة مفاتيح الحاسوب الآن" },
  { "id": 62, "en": "mouse", "ar": "فأرة", "pronounce": "ماوس", "ex_en": "Move the computer mouse slowly", "ar_ex": "حرك فأرة الحاسوب ببطء" },
  { "id": 63, "en": "ruler", "ar": "مسطرة", "pronounce": "رُولَر", "ex_en": "Use the ruler to draw", "ar_ex": "استخدم المسطرة للرسم" },
  { "id": 64, "en": "eraser", "ar": "ممحاة", "pronounce": "إِريزَر", "ex_en": "I have a white eraser", "ar_ex": "لدي ممحاة بيضاء" },
  { "id": 65, "en": "crayon", "ar": "قلم ألوان", "pronounce": "كْرَيْون", "ex_en": "Color with the red crayon", "ar_ex": "لوّن بقلم الألوان الأحمر" },
  { "id": 66, "en": "cake", "ar": "كعكة", "pronounce": "كَيْك", "ex_en": "This birthday cake tastes delicious", "ar_ex": "كعكة عيد الميلاد هذه لذيذة" },
  { "id": 67, "en": "candle", "ar": "شمعة", "pronounce": "كانْدِل", "ex_en": "Light the small candle, please", "ar_ex": "أشعل الشمعة الصغيرة من فضلك" },
  { "id": 68, "en": "pen", "ar": "قلم حبر", "pronounce": "پِن", "ex_en": "Write with a blue pen", "ar_ex": "اكتب بقلم حبر أزرق" },
  { "id": 69, "en": "bee", "ar": "نحلة", "pronounce": "بي", "ex_en": "The bee makes sweet honey", "ar_ex": "النحلة تصنع العسل اللذيذ" },
  { "id": 70, "en": "butterfly", "ar": "فراشة", "pronounce": "بَتَرفلاي", "ex_en": "The butterfly has nice colors", "ar_ex": "الفراشة لها ألوان جميلة" },
  { "id": 71, "en": "bird", "ar": "طائر", "pronounce": "بِرد", "ex_en": "The small bird can fly", "ar_ex": "الطائر الصغير يستطيع الطيران" },
  { "id": 72, "en": "tree", "ar": "شجرة", "pronounce": "تري", "ex_en": "This olive tree is big", "ar_ex": "شجرة الزيتون هذه كبيرة" },
  { "id": 73, "en": "number", "ar": "رقم", "pronounce": "نَمبَر", "ex_en": "What is your favorite number?", "ar_ex": "ما هو رقمك المفضل؟" },
  { "id": 74, "en": "post office", "ar": "مكتب البريد", "pronounce": "بوست أوفِس", "ex_en": "Where is the post office?", "ar_ex": "أين يقع مكتب البريد؟" },
  { "id": 75, "en": "postman", "ar": "ساعي البريد", "pronounce": "بوستمان", "ex_en": "The postman brings a letter", "ar_ex": "ساعي البريد يحضر رسالة" },
  { "id": 76, "en": "queen", "ar": "ملكة", "pronounce": "كْوين", "ex_en": "The queen wears a crown", "ar_ex": "الملكة ترتدي تاجًا" },
  { "id": 77, "en": "radio", "ar": "راديو", "pronounce": "رَيْديو", "ex_en": "Listen to the radio now", "ar_ex": "استمع إلى الراديو الآن" },
  { "id": 78, "en": "open", "ar": "يفتح", "pronounce": "أوبِن", "ex_en": "Open your school book now", "ar_ex": "افتح كتابك المدرسي الآن" },
  { "id": 79, "en": "close", "ar": "يُغلق", "pronounce": "كْلوز", "ex_en": "Close the classroom door, please", "ar_ex": "أغلق باب الصف من فضلك" },
  { "id": 80, "en": "touch", "ar": "يلمس", "pronounce": "تَتش", "ex_en": "Do not touch the wall", "ar_ex": "لا تلمس الحائط" },
  { "id": 81, "en": "jump", "ar": "يقفز", "pronounce": "جَمب", "ex_en": "Jump high up in air", "ar_ex": "اقفز عاليًا في الهواء" },
  { "id": 82, "en": "hop", "ar": "يقفز على رجل", "pronounce": "هوب", "ex_en": "Can you hop like this?", "ar_ex": "هل يمكنك القفز هكذا؟" },
  { "id": 83, "en": "clap", "ar": "يصفق", "pronounce": "كْلاب", "ex_en": "Clap your hands with joy", "ar_ex": "صفق بيديك بفرح" },
  { "id": 84, "en": "come here", "ar": "تعال إلى هنا", "pronounce": "كَم هِير", "ex_en": "Come here and study now", "ar_ex": "تعال إلى هنا وادرس الآن" },
  { "id": 85, "en": "listen", "ar": "يستمع", "pronounce": "لِسِن", "ex_en": "Listen to your teacher carefully", "ar_ex": "استمع إلى معلمك بعناية" },
  { "id": 86, "en": "look", "ar": "ينظر", "pronounce": "لوك", "ex_en": "Look at the white board", "ar_ex": "انظر إلى اللوح الأبيض" },
  { "id": 87, "en": "go there", "ar": "اذهب هناك", "pronounce": "غو ذِير", "ex_en": "Go there and play softly", "ar_ex": "اذهب هناك والعب بهدوء" },
  { "id": 88, "en": "be quiet", "ar": "كن هادئًا", "pronounce": "بي كْوايِت", "ex_en": "Please, be quiet in class", "ar_ex": "من فضلك كن هادئًا بالصف" },
  { "id": 89, "en": "shirt", "ar": "قميص", "pronounce": "شِرت", "ex_en": "I wear a clean shirt", "ar_ex": "أنا أرتدي قميصًا نظيفًا" },
  { "id": 90, "en": "sweater", "ar": "كنزة", "pronounce": "سْوِتَر", "ex_en": "This wool sweater is warm", "ar_ex": "هذه الكنزة الصوفية دافئة" },
  { "id": 91, "en": "socks", "ar": "جوارب", "pronounce": "سوكس", "ex_en": "Put on your white socks", "ar_ex": "ارتدِ جواربك البيضاء" },
  { "id": 92, "en": "boots", "ar": "حذاء طويل", "pronounce": "بوتس", "ex_en": "Wear boots in the winter", "ar_ex": "ارتدِ الحذاء الطويل في الشتاء" },
  { "id": 93, "en": "pajamas", "ar": "بيجاما", "pronounce": "بَجاماز", "ex_en": "Wear your pajamas before bedtime", "ar_ex": "ارتدِ بيجامتك قبل وقت النوم" },
  { "id": 94, "en": "coat", "ar": "معطف", "pronounce": "كوت", "ex_en": "This heavy coat is black", "ar_ex": "هذا المعطف الثقيل أسود" },
  { "id": 95, "en": "hat", "ar": "قبعة", "pronounce": "هات", "ex_en": "Put a hat on head", "ar_ex": "ضع قبعة على رأسك" },
  { "id": 96, "en": "new", "ar": "جديد", "pronounce": "نيو", "ex_en": "I have a new bag", "ar_ex": "لدي حقيبة جديدة" },
  { "id": 97, "en": "old", "ar": "قديم", "pronounce": "أُولد", "ex_en": "This old car is slow", "ar_ex": "هذه السيارة القديمة بطيئة" },
  { "id": 98, "en": "clothes", "ar": "ملابس", "pronounce": "كْلوز", "ex_en": "Wash your dirty clothes now", "ar_ex": "اغسل ملابسك المتسخة الآن" },
  { "id": 99, "en": "my grandfather", "ar": "جدي", "pronounce": "ماي غْرانْد فاذَر", "ex_en": "I love my grandfather very much", "ar_ex": "أنا أحب جدي كثيرًا" },
  { "id": 100, "en": "my grandmother", "ar": "جدتي", "pronounce": "ماي غْرانْد مَذَر", "ex_en": "My grandmother tells nice stories", "ar_ex": "جدتي تروي قصصًا جميلة" },
  { "id": 101, "en": "falafel", "ar": "فلافل", "pronounce": "فَلافِل", "ex_en": "Falafel is a popular food", "ar_ex": "الفلافل طعام شعبي" },
  { "id": 102, "en": "foggy", "ar": "ضبابي", "pronounce": "فوغي", "ex_en": "The weather is foggy today", "ar_ex": "الطقس ضبابي اليوم" },
  { "id": 103, "en": "player", "ar": "لاعب", "pronounce": "بلايَر", "ex_en": "He is a fast player", "ar_ex": "هو لاعب سريع" },
  { "id": 104, "en": "forget", "ar": "ينسى", "pronounce": "فُرغِت", "ex_en": "Do not forget your homework", "ar_ex": "لا تنسَ وظيفتك" },
  { "id": 105, "en": "cousin", "ar": "ابن عم", "pronounce": "كَزِن", "ex_en": "My cousin plays with me", "ar_ex": "ابن عمي يلعب معي" },
  { "id": 106, "en": "aunt", "ar": "خالة", "pronounce": "آنت", "ex_en": "My aunt is very kind", "ar_ex": "خالتي طيبة جدًا" },
  { "id": 107, "en": "uncle", "ar": "خال", "pronounce": "أَنْكِل", "ex_en": "My uncle lives in town", "ar_ex": "خالي يعيش في البلدة" },
  { "id": 108, "en": "blonde", "ar": "أشقر", "pronounce": "بْلوند", "ex_en": "She has nice blonde hair", "ar_ex": "هي تملك شعرًا أشقر جميلًا" },
  { "id": 109, "en": "brown", "ar": "بني", "pronounce": "براون", "ex_en": "I have a brown table", "ar_ex": "لدي طاولة بنية" },
  { "id": 110, "en": "river", "ar": "نهر", "pronounce": "رِفَر", "ex_en": "The river water is clean", "ar_ex": "ماء النهر نظيف" },
  { "id": 111, "en": "town", "ar": "بلدة", "pronounce": "تاون", "ex_en": "Our town is very beautiful", "ar_ex": "بلدتنا جميلة جدًا" },
  { "id": 112, "en": "flower", "ar": "زهرة", "pronounce": "فلاوَر", "ex_en": "Smell this red flower now", "ar_ex": "شم هذه الزهرة الحمراء الآن" },
  { "id": 113, "en": "the sea", "ar": "البحر", "pronounce": "ذَ سي", "ex_en": "The sea water is blue", "ar_ex": "ماء البحر أزرق" },
  { "id": 114, "en": "Palestine", "ar": "فلسطين", "pronounce": "بالِسْتاين", "ex_en": "Palestine is my beautiful homeland", "ar_ex": "فلسطين هي وطني الجميل" },
  { "id": 115, "en": "Hebron", "ar": "الخليل", "pronounce": "هِبرون", "ex_en": "Hebron is an old city", "ar_ex": "الخليل مدينة قديمة" },
  { "id": 116, "en": "Bethlehem", "ar": "بيت لحم", "pronounce": "بيثْلِهيم", "ex_en": "Bethlehem is a beautiful place", "ar_ex": "بيت لحم مكان جميل" },
  { "id": 117, "en": "Jerusalem", "ar": "القدس", "pronounce": "جِروزَلِم", "ex_en": "Jerusalem is the capital city", "ar_ex": "القدس هي العاصمة" },
  { "id": 118, "en": "Nablus", "ar": "نابلس", "pronounce": "نابْلُس", "ex_en": "I live in Nablus city", "ar_ex": "أنا أعيش في مدينة نابلس" },
  { "id": 119, "en": "Gaza", "ar": "غزة", "pronounce": "غازا", "ex_en": "Gaza is by the sea", "ar_ex": "غزة تقع عند البحر" },
  { "id": 120, "en": "Where are you from?", "ar": "من أي بلد أنت؟", "pronounce": "وِير آر يو فرُم؟", "ex_en": "Where are you from, boy?", "ar_ex": "من أي بلد أنت يا ولد؟" },
  { "id": 121, "en": "I’m from …", "ar": "أنا من…", "pronounce": "آيم فرُم…", "ex_en": "I’m from Palestine", "ar_ex": "أنا من فلسطين" },
  { "id": 122, "en": "birthday", "ar": "عيد ميلاد", "pronounce": "بِرثْداي", "ex_en": "Today is my birthday party", "ar_ex": "اليوم هو حفلة عيد ميلادي" },
  { "id": 123, "en": "party", "ar": "حفلة", "pronounce": "بارتي", "ex_en": "The party is very fun", "ar_ex": "الحفلة ممتعة جدًا" },
  { "id": 124, "en": "present", "ar": "هدية", "pronounce": "بْرِزِنت", "ex_en": "Get a beautiful birthday present", "ar_ex": "احصل على هدية عيد ميلاد جميلة" },
  { "id": 125, "en": "I feel happy", "ar": "أشعر بالسعادة", "pronounce": "آي فيل هابي", "ex_en": "I feel happy with you", "ar_ex": "أشعر بالسعادة معك" },
  { "id": 126, "en": "I feel sad", "ar": "أشعر بالحزن", "pronounce": "آي فيل ساد", "ex_en": "I feel sad today, friend", "ar_ex": "أشعر بالحزن اليوم يا صديقي" },
  { "id": 127, "en": "lovely", "ar": "لطيف", "pronounce": "لَڤلي", "ex_en": "This is a lovely baby", "ar_ex": "هذا طفل لطيف" },
  { "id": 128, "en": "age", "ar": "عمر", "pronounce": "إيج", "ex_en": "What is your age now?", "ar_ex": "ما هو عمرك الآن؟" },
  { "id": 129, "en": "toy", "ar": "لعبة", "pronounce": "توي", "ex_en": "This new toy is nice", "ar_ex": "هذه اللعبة الجديدة جميلة" },
  { "id": 130, "en": "lemonade", "ar": "عصير ليمون", "pronounce": "لِمُنيْد", "ex_en": "I drink cold lemonade juice", "ar_ex": "أنا أشرب عصير الليمون البارد" },
  { "id": 131, "en": "long", "ar": "طويل", "pronounce": "لونغ", "ex_en": "The ruler is very long", "ar_ex": "المسطرة طويلة جدًا" },
  { "id": 132, "en": "must", "ar": "يجب", "pronounce": "مَست", "ex_en": "You must do homework now", "ar_ex": "يجب أن تحل وظيفتك الآن" }
];