const levelCLASS11_Words = [
  { "id": 1, "en": "adapt", "ar": "يتكيف / يتأقلم", "pronounce": "أدَاپْت", "ex_en": "He can adapt easily", "ar_ex": "يمكنه التكيف بسهولة" },
  { "id": 2, "en": "attention", "ar": "انتباه", "pronounce": "أتِنْشِن", "ex_en": "Pay attention to me", "ar_ex": "انتبه لي" },
  { "id": 3, "en": "aural", "ar": "سمعي", "pronounce": "أُورَل", "ex_en": "Aural tests are hard", "ar_ex": "الاختبارات السمعية صعبة" },
  { "id": 4, "en": "detail(s)", "ar": "تفاصيل", "pronounce": "دِيتِيلْز", "ex_en": "Tell me the details", "ar_ex": "أخبرني بالتفاصيل" },
  { "id": 5, "en": "label", "ar": "يصنف / يضع ملصقاً", "pronounce": "لِيْبِل", "ex_en": "Label the boxes", "ar_ex": "ضع ملصقات على الصناديق" },
  { "id": 6, "en": "method", "ar": "طريقة / أسلوب", "pronounce": "مِثُود", "ex_en": "A new teaching method", "ar_ex": "طريقة تدريس جديدة" },
  { "id": 7, "en": "physical", "ar": "بدني / مادي", "pronounce": "فِزِكَل", "ex_en": "Physical exercise is good", "ar_ex": "التمرين البدني جيد" },
  { "id": 8, "en": "retain", "ar": "يحتفظ بـ", "pronounce": "رِتِين", "ex_en": "Retain this information", "ar_ex": "احتفظ بهذه المعلومات" },
  { "id": 9, "en": "social", "ar": "اجتماعي", "pronounce": "سُوشَل", "ex_en": "He is a social person", "ar_ex": "إنه شخص اجتماعي" },
  { "id": 10, "en": "solitary", "ar": "وحيد / منعزل", "pronounce": "سُولِتَري", "ex_en": "A solitary life", "ar_ex": "حياة منعزلة" },
  { "id": 11, "en": "tend to", "ar": "يميل إلى", "pronounce": "تِنْد تُو", "ex_en": "I tend to agree", "ar_ex": "أميل للموافقة" },
  { "id": 12, "en": "tip", "ar": "نصيحة", "pronounce": "تِپ", "ex_en": "A useful tip", "ar_ex": "نصيحة مفيدة" },
  { "id": 13, "en": "visual", "ar": "بصري", "pronounce": "ڤِژْوَل", "ex_en": "Visual arts", "ar_ex": "فنون بصرية" },
  { "id": 14, "en": "apply", "ar": "يطبق / يتقدم بطلب", "pronounce": "أپْلَاي", "ex_en": "Apply the rule", "ar_ex": "طبق القاعدة" },
  { "id": 15, "en": "assumption", "ar": "افتراض", "pronounce": "أسَمْپْشِن", "ex_en": "A false assumption", "ar_ex": "افتراض خاطئ" },
  { "id": 16, "en": "challenge", "ar": "تحدي", "pronounce": "تْشَالِنْج", "ex_en": "A big challenge", "ar_ex": "تحد كبير" },
  { "id": 17, "en": "compulsory", "ar": "إلزامي / إجباري", "pronounce": "كُمْپَلْسَري", "ex_en": "Education is compulsory", "ar_ex": "التعليم إلزامي" },
  { "id": 18, "en": "conclusion", "ar": "خاتمة / استنتاج", "pronounce": "كُنْكْلُوجِن", "ex_en": "The logical conclusion", "ar_ex": "الاستنتاج المنطقي" },
  { "id": 19, "en": "connection", "ar": "اتصال / صلة", "pronounce": "كُنِكْشِن", "ex_en": "A strong connection", "ar_ex": "صلة قوية" },
  { "id": 20, "en": "divide", "ar": "يقسم", "pronounce": "دِڤَايْد", "ex_en": "Divide the cake", "ar_ex": "قسم الكعكة" },
  { "id": 21, "en": "encourage", "ar": "يشجع", "pronounce": "إنْكَرِدْج", "ex_en": "Encourage your friends", "ar_ex": "شجع أصدقاءك" },
  { "id": 22, "en": "evidence", "ar": "دليل / أدلة", "pronounce": "إڤِدِنْس", "ex_en": "Find the evidence", "ar_ex": "جد الدليل" },
  { "id": 23, "en": "face", "ar": "يواجه", "pronounce": "فِيس", "ex_en": "Face your fears", "ar_ex": "واجه مخاوفك" },
  { "id": 24, "en": "invest in", "ar": "يستثمر في", "pronounce": "إنْڤِسْت إن", "ex_en": "Invest in gold", "ar_ex": "استثمر في الذهب" },
  { "id": 25, "en": "solution", "ar": "حل", "pronounce": "سُلُوشِن", "ex_en": "Find a solution", "ar_ex": "جد حلا" },
  { "id": 26, "en": "stress", "ar": "يؤكد / يشدد", "pronounce": "سْتْرِس", "ex_en": "Stress the main point", "ar_ex": "أكد على النقطة الرئيسية" },
  { "id": 27, "en": "survey", "ar": "استطلاع / استبيان", "pronounce": "سِيرْڤِي", "ex_en": "Fill the survey", "ar_ex": "املأ الاستبيان" },
  { "id": 28, "en": "system", "ar": "نظام", "pronounce": "سِسْتِم", "ex_en": "A new system", "ar_ex": "نظام جديد" },
  { "id": 29, "en": "wage", "ar": "أجر / راتب", "pronounce": "وِيْدْج", "ex_en": "A high wage", "ar_ex": "أجر عال" },
  { "id": 30, "en": "ambitious", "ar": "طموح", "pronounce": "أمْبِشَس", "ex_en": "An ambitious boy", "ar_ex": "ولد طموح" },
  { "id": 31, "en": "attitude", "ar": "موقف / توجه", "pronounce": "أتِتْيُود", "ex_en": "A positive attitude", "ar_ex": "موقف إيجابي" },
  { "id": 32, "en": "blunt", "ar": "فظ / صريح جداً", "pronounce": "بْلَنْت", "ex_en": "A blunt answer", "ar_ex": "إجابة فظة" },
  { "id": 33, "en": "extend", "ar": "يمدد / يوسع", "pronounce": "إكْسْتِنْد", "ex_en": "Extend the deadline", "ar_ex": "مدد الموعد النهائي" },
  { "id": 34, "en": "gradual", "ar": "تدريجي", "pronounce": "گْرَادْجْوَل", "ex_en": "A gradual change", "ar_ex": "تغيير تدريجي" },
  { "id": 35, "en": "income", "ar": "دخل", "pronounce": "إنْكَم", "ex_en": "A good income", "ar_ex": "دخل جيد" },
  { "id": 36, "en": "insurance", "ar": "تأمين", "pronounce": "إنْشُورَنْس", "ex_en": "Health insurance", "ar_ex": "تأمين صحي" },
  { "id": 37, "en": "inward / outward", "ar": "للداخل / للخارج", "pronounce": "إنْوَرْد / أوْتْوَرْد", "ex_en": "Look inward", "ar_ex": "انظر للداخل" },
  { "id": 38, "en": "luxury", "ar": "رفاهية / فخامة", "pronounce": "لَكْشَري", "ex_en": "A luxury car", "ar_ex": "سيارة فاخرة" },
  { "id": 39, "en": "pass (laws)", "ar": "يمرر (قوانين)", "pronounce": "پَاس", "ex_en": "Pass a new law", "ar_ex": "يمرر قانونا جديدا" },
  { "id": 40, "en": "portable", "ar": "محمول", "pronounce": "پُورْتَبِل", "ex_en": "A portable device", "ar_ex": "جهاز محمول" },
  { "id": 41, "en": "press", "ar": "الصحافة", "pronounce": "پْرِس", "ex_en": "The local press", "ar_ex": "الصحافة المحلية" },
  { "id": 42, "en": "professional", "ar": "محترف / مهني", "pronounce": "پْرُوفِشِنَل", "ex_en": "A professional player", "ar_ex": "لاعب محترف" },
  { "id": 43, "en": "regulations", "ar": "لوائح / قوانين", "pronounce": "رِگْيُولِيْشِنْز", "ex_en": "Follow the regulations", "ar_ex": "اتبع اللوائح" },
  { "id": 44, "en": "restrict", "ar": "يقيد / يحصر", "pronounce": "رِسْتْرِكْت", "ex_en": "Restrict the access", "ar_ex": "قيد الدخول" },
  { "id": 45, "en": "take responsibility", "ar": "يتحمل المسؤولية", "pronounce": "تِيك رِسْپُونْسِبِلِتي", "ex_en": "Take responsibility now", "ar_ex": "تحمل المسؤولية الآن" },
  { "id": 46, "en": "crew", "ar": "طاقم", "pronounce": "كْرُو", "ex_en": "The ship's crew", "ar_ex": "طاقم السفينة" },
  { "id": 47, "en": "demand", "ar": "طلب / مطلب", "pronounce": "دِمَانْد", "ex_en": "Meet the demand", "ar_ex": "لبِ الطلب" },
  { "id": 48, "en": "demanding", "ar": "متطلب / شاق", "pronounce": "دِمَانْدِنْغ", "ex_en": "A demanding job", "ar_ex": "وظيفة شاقة" },
  { "id": 49, "en": "due to", "ar": "بسبب", "pronounce": "دْيُو تُو", "ex_en": "Due to bad weather", "ar_ex": "بسبب الطقس السيء" },
  { "id": 50, "en": "expenses", "ar": "نفقات / مصاريف", "pronounce": "إكْسْپِنْسِز", "ex_en": "Travel expenses", "ar_ex": "نفقات السفر" },
  { "id": 51, "en": "fare", "ar": "أجرة (السفر)", "pronounce": "فِير", "ex_en": "Pay the taxi fare", "ar_ex": "ادفع أجرة التاكسي" },
  { "id": 52, "en": "harm", "ar": "يؤذي / يضر", "pronounce": "هَارْم", "ex_en": "Do not harm animals", "ar_ex": "لا تؤذ الحيوانات" },
  { "id": 53, "en": "interact", "ar": "يتفاعل", "pronounce": "إنْتَرْأكْت", "ex_en": "Interact with people", "ar_ex": "تفاعل مع الناس" },
  { "id": 54, "en": "impact", "ar": "تأثير / أثر", "pronounce": "إمْپَاكْت", "ex_en": "A big impact", "ar_ex": "تأثير كبير" },
  { "id": 55, "en": "lecture", "ar": "يحاضر", "pronounce": "لِكْتْشَر", "ex_en": "He will lecture today", "ar_ex": "سيحاضر اليوم" },
  { "id": 56, "en": "monument", "ar": "نصب تذكاري / أثر", "pronounce": "مُونْيُمِنْت", "ex_en": "An ancient monument", "ar_ex": "أثر قديم" },
  { "id": 57, "en": "previous", "ar": "سابق", "pronounce": "پْرِيڤْيَس", "ex_en": "The previous day", "ar_ex": "اليوم السابق" },
  { "id": 58, "en": "pick up", "ar": "يتعلم بسرعة (يلتقط)", "pronounce": "پِك أپ", "ex_en": "Pick up a language", "ar_ex": "يتعلم لغة بسرعة" },
  { "id": 59, "en": "records", "ar": "سجلات / أرقام قياسية", "pronounce": "رِكُورْدْز", "ex_en": "Keep the records", "ar_ex": "احتفظ بالسجلات" },
  { "id": 60, "en": "sightseeing", "ar": "مشاهدة المعالم", "pronounce": "سَايْتْسِيِنْغ", "ex_en": "Go sightseeing", "ar_ex": "اذهب لمشاهدة المعالم" },
  { "id": 61, "en": "temporarily", "ar": "مؤقتاً", "pronounce": "تِمْپُورِيرِلي", "ex_en": "Closed temporarily", "ar_ex": "مغلق مؤقتا" },
  { "id": 62, "en": "unique", "ar": "فريد / مميز", "pronounce": "يُونِيك", "ex_en": "A unique design", "ar_ex": "تصميم فريد" },
  { "id": 63, "en": "access", "ar": "وصول / مدخل", "pronounce": "أكْسِس", "ex_en": "Get internet access", "ar_ex": "احصل على وصول للإنترنت" },
  { "id": 64, "en": "achievement", "ar": "إنجاز", "pronounce": "أتْشِيڤْمِنْت", "ex_en": "A great achievement", "ar_ex": "إنجاز عظيم" },
  { "id": 65, "en": "amusing", "ar": "مسلي / مضحك", "pronounce": "أمْيُوزِنْغ", "ex_en": "An amusing story", "ar_ex": "قصة مسلية" },
  { "id": 66, "en": "concrete", "ar": "خرسانة", "pronounce": "كُونْكْرِيت", "ex_en": "A concrete wall", "ar_ex": "جدار خرساني" },
  { "id": 67, "en": "countryside", "ar": "ريف", "pronounce": "كَنْتْرِيْسَايْد", "ex_en": "Live in the countryside", "ar_ex": "يعيش في الريف" },
  { "id": 68, "en": "irreversible", "ar": "لا رجعة فيه", "pronounce": "إرِيڤِيرْسِبِل", "ex_en": "Irreversible damage", "ar_ex": "ضرر لا رجعة فيه" },
  { "id": 69, "en": "occupation", "ar": "مهنة", "pronounce": "أُوكْيُوپِيْشِن", "ex_en": "What is your occupation?", "ar_ex": "ما هي مهنتك؟" },
  { "id": 70, "en": "ownership", "ar": "ملكية", "pronounce": "أُونَرْشِپ", "ex_en": "Prove your ownership", "ar_ex": "أثبت ملكيتك" },
  { "id": 71, "en": "praise", "ar": "يمدح / يثني على", "pronounce": "پْرِيز", "ex_en": "Praise the child", "ar_ex": "امدح الطفل" },
  { "id": 72, "en": "pull up / pull down", "ar": "يتوقف / يهدم", "pronounce": "پُل أپ / پُل دَاوْن", "ex_en": "Pull down the building", "ar_ex": "اهدم المبنى" },
  { "id": 73, "en": "preserve", "ar": "يحافظ على", "pronounce": "پْرِزِيرْڤ", "ex_en": "Preserve the environment", "ar_ex": "حافظ على البيئة" },
  { "id": 74, "en": "review", "ar": "مراجعة / تقييم", "pronounce": "رِڤْيُو", "ex_en": "A book review", "ar_ex": "مراجعة كتاب" },
  { "id": 75, "en": "state", "ar": "يصرح / يذكر", "pronounce": "سْتِيت", "ex_en": "State your name", "ar_ex": "اذكر اسمك" },
  { "id": 76, "en": "take for granted", "ar": "يعتبره أمراً مسلماً به", "pronounce": "تِيك فُور گْرَانْتِد", "ex_en": "Do not take it for granted", "ar_ex": "لا تعتبره من المسلمات" },
  { "id": 77, "en": "take place", "ar": "يحدث / يقع", "pronounce": "تِيك پْلِيس", "ex_en": "The event will take place", "ar_ex": "سيحدث الحدث" },
  { "id": 78, "en": "take up", "ar": "يبدأ (هواية)", "pronounce": "تِيك أپ", "ex_en": "Take up a new hobby", "ar_ex": "ابدأ هواية جديدة" },
  { "id": 79, "en": "touch", "ar": "يؤثر في (المشاعر)", "pronounce": "تَتْش", "ex_en": "It touches my heart", "ar_ex": "إنه يؤثر في قلبي" },
  { "id": 80, "en": "wander", "ar": "يتجول / يهيم", "pronounce": "وَانْدَر", "ex_en": "Wander in the park", "ar_ex": "يتجول في المتنزه" },
  { "id": 81, "en": "additives", "ar": "مواد مضافة", "pronounce": "أدِتِڤْز", "ex_en": "Food additives", "ar_ex": "إضافات غذائية" },
  { "id": 82, "en": "concerns", "ar": "مخاوف / اهتمامات", "pronounce": "كُنْسِيرْنْز", "ex_en": "Health concerns", "ar_ex": "مخاوف صحية" },
  { "id": 83, "en": "disastrous", "ar": "كارثي", "pronounce": "دِزَاسْتْرَس", "ex_en": "A disastrous storm", "ar_ex": "عاصفة كارثية" },
  { "id": 84, "en": "flavours", "ar": "نكهات", "pronounce": "فْلِيْڤَرْز", "ex_en": "Different flavours", "ar_ex": "نكهات مختلفة" },
  { "id": 85, "en": "fresh", "ar": "طازج", "pronounce": "فْرِش", "ex_en": "Fresh fruits", "ar_ex": "فواكه طازجة" },
  { "id": 86, "en": "genes", "ar": "جينات / مورثات", "pronounce": "جِينْز", "ex_en": "Human genes", "ar_ex": "جينات بشرية" },
  { "id": 87, "en": "global", "ar": "عالمي", "pronounce": "گْلُوبَل", "ex_en": "A global issue", "ar_ex": "قضية عالمية" },
  { "id": 88, "en": "homemade", "ar": "مصنوع بالمنزل", "pronounce": "هُومْمِيد", "ex_en": "Homemade bread", "ar_ex": "خبز منزلي" },
  { "id": 89, "en": "ingredients", "ar": "مكونات / مقادير", "pronounce": "إنْگْرِيدْيَنْتْس", "ex_en": "Mix the ingredients", "ar_ex": "اخلط المكونات" },
  { "id": 90, "en": "pests", "ar": "آفات / حشرات ضارة", "pronounce": "پِسْتْس", "ex_en": "Kill the pests", "ar_ex": "اقتل الآفات" },
  { "id": 91, "en": "reaction", "ar": "رد فعل / تفاعل", "pronounce": "رِيْأكْشِن", "ex_en": "A fast reaction", "ar_ex": "رد فعل سريع" },
  { "id": 92, "en": "resist", "ar": "يقاوم", "pronounce": "رِزِسْت", "ex_en": "Resist the temptation", "ar_ex": "قاوم الإغراء" },
  { "id": 93, "en": "seeds", "ar": "بذور", "pronounce": "سِيدْز", "ex_en": "Plant the seeds", "ar_ex": "ازرع البذور" },
  { "id": 94, "en": "standard", "ar": "معياري / قياسي", "pronounce": "سْتَانْدَرْد", "ex_en": "A standard size", "ar_ex": "مقاس قياسي" },
  { "id": 95, "en": "starvation", "ar": "مجاعة / تضور جوعاً", "pronounce": "سْتَارْڤِيْشِن", "ex_en": "Die of starvation", "ar_ex": "يموت من المجاعة" },
  { "id": 96, "en": "according to", "ar": "وفقاً لـ / حسب", "pronounce": "أكُورْدِنْغ تُو", "ex_en": "According to the law", "ar_ex": "وفقا للقانون" },
  { "id": 97, "en": "biologist", "ar": "عالم أحياء", "pronounce": "بَايُولُوجِسْت", "ex_en": "A marine biologist", "ar_ex": "عالم أحياء بحرية" },
  { "id": 98, "en": "complex", "ar": "معقد", "pronounce": "كُمْپْلِكْس", "ex_en": "A complex problem", "ar_ex": "مشكلة معقدة" },
  { "id": 99, "en": "enable", "ar": "يمكّن", "pronounce": "إنِيْبِل", "ex_en": "This will enable you", "ar_ex": "هذا سيمكنك" },
  { "id": 100, "en": "extinction", "ar": "انقراض", "pronounce": "إكْسْتِنْكْشِن", "ex_en": "Animal extinction", "ar_ex": "انقراض الحيوانات" },
  { "id": 101, "en": "giant", "ar": "عملاق", "pronounce": "جَايَنْت", "ex_en": "A giant tree", "ar_ex": "شجرة عملاقة" },
  { "id": 102, "en": "habitat", "ar": "موطن", "pronounce": "هَابِتَات", "ex_en": "Natural habitat", "ar_ex": "موطن طبيعي" },
  { "id": 103, "en": "headline", "ar": "عنوان رئيسي", "pronounce": "هِدْلَايْن", "ex_en": "News headline", "ar_ex": "عنوان الأخبار الرئيسي" },
  { "id": 104, "en": "obviously", "ar": "بوضوح / من الواضح", "pronounce": "أُوبْڤِيَسْلي", "ex_en": "He is obviously tired", "ar_ex": "من الواضح أنه متعب" },
  { "id": 105, "en": "option", "ar": "خيار", "pronounce": "أُوپْشِن", "ex_en": "Another option", "ar_ex": "خيار آخر" },
  { "id": 106, "en": "poll", "ar": "استطلاع رأي", "pronounce": "پُول", "ex_en": "An opinion poll", "ar_ex": "استطلاع رأي" },
  { "id": 107, "en": "pretend", "ar": "يتظاهر / يدّعي", "pronounce": "پْرِتِنْد", "ex_en": "Do not pretend", "ar_ex": "لا تتظاهر" },
  { "id": 108, "en": "publicity", "ar": "دعاية / شهرة", "pronounce": "پَبْلِسِتي", "ex_en": "Good publicity", "ar_ex": "دعاية جيدة" },
  { "id": 109, "en": "random", "ar": "عشوائي", "pronounce": "رَانْدُم", "ex_en": "A random choice", "ar_ex": "اختيار عشوائي" },
  { "id": 110, "en": "struggle", "ar": "يكافح / يصارع", "pronounce": "سْتْرَگِل", "ex_en": "Struggle to survive", "ar_ex": "يكافح للنجاة" },
  { "id": 111, "en": "threat", "ar": "تهديد", "pronounce": "ثْرِت", "ex_en": "A real threat", "ar_ex": "تهديد حقيقي" },
  { "id": 112, "en": "vital", "ar": "حيوي / بالغ الأهمية", "pronounce": "ڤَايْتَل", "ex_en": "Vital signs", "ar_ex": "علامات حيوية" },
  { "id": 113, "en": "character", "ar": "شخصية", "pronounce": "كَارِكْتَر", "ex_en": "A main character", "ar_ex": "شخصية رئيسية" },
  { "id": 114, "en": "couple", "ar": "زوج (اثنان) / زوجان", "pronounce": "كَپِل", "ex_en": "A married couple", "ar_ex": "زوجان متزوجان" },
  { "id": 115, "en": "definition", "ar": "تعريف", "pronounce": "دِفِنِشِن", "ex_en": "Read the definition", "ar_ex": "اقرأ التعريف" },
  { "id": 116, "en": "feature", "ar": "يبرز / يعرض", "pronounce": "فِيتْشَر", "ex_en": "The movie features him", "ar_ex": "الفيلم يعرضه" },
  { "id": 117, "en": "hero", "ar": "بطل", "pronounce": "هِيرُو", "ex_en": "A national hero", "ar_ex": "بطل قومي" },
  { "id": 118, "en": "imaginary", "ar": "خيالي", "pronounce": "إمَاجِنَري", "ex_en": "An imaginary friend", "ar_ex": "صديق خيالي" },
  { "id": 119, "en": "lay", "ar": "يضع / يبيض", "pronounce": "لِي", "ex_en": "Lay the book down", "ar_ex": "ضع الكتاب" },
  { "id": 120, "en": "persuade", "ar": "يقنع", "pronounce": "پِرْسْوِيد", "ex_en": "Persuade your father", "ar_ex": "أقنع أباك" },
  { "id": 121, "en": "refuse", "ar": "يرفض", "pronounce": "رِفْيُوز", "ex_en": "I refuse to go", "ar_ex": "أرفض الذهاب" },
  { "id": 122, "en": "similarity", "ar": "تشابه", "pronounce": "سِمِلَارِتي", "ex_en": "A strong similarity", "ar_ex": "تشابه قوي" },
  { "id": 123, "en": "society", "ar": "مجتمع", "pronounce": "سُوسَايِتي", "ex_en": "Modern society", "ar_ex": "مجتمع حديث" },
  { "id": 124, "en": "summary", "ar": "ملخص", "pronounce": "سَمَري", "ex_en": "Write a summary", "ar_ex": "اكتب ملخصا" },
  { "id": 125, "en": "tale", "ar": "حكاية / قصة", "pronounce": "تِيل", "ex_en": "A folk tale", "ar_ex": "حكاية شعبية" },
  { "id": 126, "en": "tie", "ar": "يربط", "pronounce": "تَاي", "ex_en": "Tie your shoes", "ar_ex": "اربط حذاءك" },
  { "id": 127, "en": "type", "ar": "نوع", "pronounce": "تَايْپ", "ex_en": "What type is it?", "ar_ex": "ما نوعه؟" },
  { "id": 128, "en": "approximately", "ar": "تقريباً / حوالي", "pronounce": "أپْرُوكْسِمِتْلي", "ex_en": "Approximately ten people", "ar_ex": "حوالي عشرة أشخاص" },
  { "id": 129, "en": "candidate", "ar": "مرشح", "pronounce": "كَانْدِدِيت", "ex_en": "A good candidate", "ar_ex": "مرشح جيد" },
  { "id": 130, "en": "crisis", "ar": "أزمة", "pronounce": "كْرَايْسِس", "ex_en": "A financial crisis", "ar_ex": "أزمة مالية" },
  { "id": 131, "en": "election", "ar": "انتخابات", "pronounce": "إلِكْشِن", "ex_en": "Win the election", "ar_ex": "يربح الانتخابات" },
  { "id": 132, "en": "established", "ar": "راسخ / مؤسس", "pronounce": "إسْتَابْلِشْد", "ex_en": "An established company", "ar_ex": "شركة راسخة" },
  { "id": 133, "en": "fiction", "ar": "خيال / قصص خيالية", "pronounce": "فِكْشِن", "ex_en": "Read fiction books", "ar_ex": "اقرأ كتب الخيال" },
  { "id": 134, "en": "financial", "ar": "مالي", "pronounce": "فَايْنَانْشَل", "ex_en": "Financial support", "ar_ex": "دعم مالي" },
  { "id": 135, "en": "fine", "ar": "غرامة", "pronounce": "فَايْن", "ex_en": "Pay a fine", "ar_ex": "ادفع غرامة" },
  { "id": 136, "en": "monarchy", "ar": "ملكية / عاهل", "pronounce": "مُونَارْكي", "ex_en": "A constitutional monarchy", "ar_ex": "ملكية دستورية" },
  { "id": 137, "en": "official", "ar": "رسمي", "pronounce": "أُوفِشَل", "ex_en": "Official document", "ar_ex": "وثيقة رسمية" },
  { "id": 138, "en": "parliament", "ar": "برلمان", "pronounce": "پَارْلِمِنْت", "ex_en": "The parliament building", "ar_ex": "مبنى البرلمان" },
  { "id": 139, "en": "opinion", "ar": "رأي", "pronounce": "أُوپِنْيَن", "ex_en": "In my opinion", "ar_ex": "في رأيي" },
  { "id": 140, "en": "poison", "ar": "سم", "pronounce": "پُويْزِن", "ex_en": "A deadly poison", "ar_ex": "سم قاتل" },
  { "id": 141, "en": "politician", "ar": "سياسي", "pronounce": "پُولِتِشِن", "ex_en": "A famous politician", "ar_ex": "سياسي مشهور" },
  { "id": 142, "en": "process", "ar": "عملية", "pronounce": "پْرُوسِس", "ex_en": "A long process", "ar_ex": "عملية طويلة" },
  { "id": 143, "en": "republic", "ar": "جمهورية", "pronounce": "رِپَبْلِك", "ex_en": "An Arab republic", "ar_ex": "جمهورية عربية" },
  { "id": 144, "en": "stage", "ar": "مسرح / مرحلة", "pronounce": "سْتِيْج", "ex_en": "The final stage", "ar_ex": "المرحلة النهائية" },
  { "id": 145, "en": "vote", "ar": "يصوت / يقترع", "pronounce": "ڤُوت", "ex_en": "Vote for me", "ar_ex": "صوت لي" },
  { "id": 146, "en": "amount", "ar": "كمية / مقدار", "pronounce": "أمَاوْنْت", "ex_en": "A huge amount", "ar_ex": "كمية ضخمة" },
  { "id": 147, "en": "announce", "ar": "يعلن", "pronounce": "أنَاوْنْس", "ex_en": "Announce the news", "ar_ex": "أعلن الأخبار" },
  { "id": 148, "en": "apart from", "ar": "بصرف النظر عن / باستثناء", "pronounce": "أپَارْت فْرُوم", "ex_en": "Apart from that", "ar_ex": "بصرف النظر عن ذلك" },
  { "id": 149, "en": "believe", "ar": "يصدق / يعتقد", "pronounce": "بِلِيڤ", "ex_en": "I believe you", "ar_ex": "أنا أصدقك" },
  { "id": 150, "en": "benefit", "ar": "فائدة / منفعة", "pronounce": "بِنِفِت", "ex_en": "A great benefit", "ar_ex": "منفعة عظيمة" },
  { "id": 151, "en": "calculate", "ar": "يحسب", "pronounce": "كَالْكْيُلِيت", "ex_en": "Calculate the cost", "ar_ex": "احسب التكلفة" },
  { "id": 152, "en": "confirm", "ar": "يؤكد", "pronounce": "كُنْفِيرْم", "ex_en": "Confirm the booking", "ar_ex": "أكد الحجز" },
  { "id": 153, "en": "criticise", "ar": "ينتقد", "pronounce": "كْرِتِسَايْز", "ex_en": "Do not criticise others", "ar_ex": "لا تنتقد الآخرين" },
  { "id": 154, "en": "criticism", "ar": "انتقاد / نقد", "pronounce": "كْرِتِسِزِم", "ex_en": "Constructive criticism", "ar_ex": "نقد بناء" },
  { "id": 155, "en": "demonstrate", "ar": "يوضح / يتظاهر", "pronounce": "دِمُنْسْتْرِيت", "ex_en": "Demonstrate the idea", "ar_ex": "وضح الفكرة" },
  { "id": 156, "en": "furious", "ar": "غاضب جداً", "pronounce": "فْيُورْيَس", "ex_en": "He was furious", "ar_ex": "كان غاضبا جدا" },
  { "id": 157, "en": "insist", "ar": "يصر", "pronounce": "إنْسِسْت", "ex_en": "I insist on it", "ar_ex": "أصر على ذلك" },
  { "id": 158, "en": "instant", "ar": "فوري / لحظي", "pronounce": "إنْسْتَانْت", "ex_en": "Instant coffee", "ar_ex": "قهوة سريعة التحضير" },
  { "id": 159, "en": "media", "ar": "وسائل الإعلام", "pronounce": "مِيدْيَا", "ex_en": "Social media", "ar_ex": "وسائل التواصل الاجتماعي" },
  { "id": 160, "en": "satisfying", "ar": "مُرضٍ / مشبع", "pronounce": "سَاتِسْفَايِنْغ", "ex_en": "A satisfying meal", "ar_ex": "وجبة مشبعة" },
  { "id": 161, "en": "source", "ar": "مصدر", "pronounce": "سُورْس", "ex_en": "The main source", "ar_ex": "المصدر الرئيسي" },
  { "id": 162, "en": "topic", "ar": "موضوع", "pronounce": "تُوپِك", "ex_en": "An interesting topic", "ar_ex": "موضوع مثير للاهتمام" }
];