const levelCLASS10_Words = [
  { "id": 1, "en": "ability", "ar": "قدرة", "pronounce": "أبِيلِتي", "ex_en": "He has great ability", "ar_ex": "لديه قدرة عظيمة" },
  { "id": 2, "en": "academic", "ar": "أكاديمي", "pronounce": "أكادِيمِك", "ex_en": "Academic success is good", "ar_ex": "النجاح الأكاديمي جيد" },
  { "id": 3, "en": "achieve", "ar": "يحقق / ينجز", "pronounce": "أتشِيڤ", "ex_en": "Achieve your goals", "ar_ex": "حقق أهدافك" },
  { "id": 4, "en": "actual(ly)", "ar": "فعلي / في الواقع", "pronounce": "أكْتْشُوَل(ي)", "ex_en": "This is actual size", "ar_ex": "هذا هو الحجم الفعلي" },
  { "id": 5, "en": "AD (Anno Domini)", "ar": "ميلادي", "pronounce": "إي دي", "ex_en": "Born in 2000 AD", "ar_ex": "ولد عام 2000 ميلادي" },
  { "id": 6, "en": "afterwards", "ar": "بعد ذلك", "pronounce": "آفْتَرْوَرْدْز", "ex_en": "We can eat afterwards", "ar_ex": "يمكننا أن نأكل بعد ذلك" },
  { "id": 7, "en": "all over", "ar": "في كل مكان", "pronounce": "أُول أوڤَر", "ex_en": "Travel all over the world", "ar_ex": "سافر في كل أنحاء العالم" },
  { "id": 8, "en": "alter", "ar": "يغير / يعدل", "pronounce": "أُولْتَر", "ex_en": "Alter the dress size", "ar_ex": "عدل مقاس الفستان" },
  { "id": 9, "en": "among", "ar": "بين", "pronounce": "أمُونْغ", "ex_en": "A wolf among sheep", "ar_ex": "ذئب بين الأغنام" },
  { "id": 10, "en": "anxious(ly)", "ar": "قلق", "pronounce": "أنْكْشَس", "ex_en": "I feel anxious today", "ar_ex": "أشعر بالقلق اليوم" },
  { "id": 11, "en": "appear", "ar": "يظهر", "pronounce": "أپِير", "ex_en": "Stars appear at night", "ar_ex": "النجوم تظهر ليلاً" },
  { "id": 12, "en": "apply", "ar": "يطبق / يتقدم بطلب", "pronounce": "أپْلاي", "ex_en": "Apply for the job", "ar_ex": "تقدم بطلب للوظيفة" },
  { "id": 13, "en": "archaeological", "ar": "أثري", "pronounce": "آركِيُولُوجِيكَل", "ex_en": "An archaeological site", "ar_ex": "موقع أثري" },
  { "id": 14, "en": "architectural", "ar": "معماري", "pronounce": "آركِتِكْتْشُرَل", "ex_en": "Great architectural design", "ar_ex": "تصميم معماري عظيم" },
  { "id": 15, "en": "ascend", "ar": "يصعد", "pronounce": "أسِنْد", "ex_en": "Ascend the mountain", "ar_ex": "اصعد الجبل" },
  { "id": 16, "en": "atmosphere", "ar": "غلاف جوي", "pronounce": "أتْمُوسْفِير", "ex_en": "The earth's atmosphere", "ar_ex": "الغلاف الجوي للأرض" },
  { "id": 17, "en": "available", "ar": "متاح / متوفر", "pronounce": "أڤِيْلَبِل", "ex_en": "Tickets are available", "ar_ex": "التذاكر متاحة" },
  { "id": 18, "en": "average", "ar": "متوسط", "pronounce": "أڤَرِدْج", "ex_en": "Below average score", "ar_ex": "درجة تحت المتوسط" },
  { "id": 19, "en": "avoid", "ar": "يتجنب", "pronounce": "أڤُويْد", "ex_en": "Avoid bad friends", "ar_ex": "تجنب أصدقاء السوء" },
  { "id": 20, "en": "balanced", "ar": "متوازن", "pronounce": "بالَنْسْد", "ex_en": "Eat a balanced diet", "ar_ex": "تناول غذاء متوازنا" },
  { "id": 21, "en": "base", "ar": "قاعدة / أساس", "pronounce": "بِيس", "ex_en": "A solid base", "ar_ex": "قاعدة صلبة" },
  { "id": 22, "en": "basic", "ar": "أساسي", "pronounce": "بِيسِك", "ex_en": "Learn basic English", "ar_ex": "تعلم الإنجليزية الأساسية" },
  { "id": 23, "en": "bean", "ar": "فاصولياء / حبة", "pronounce": "بِين", "ex_en": "Eat some green beans", "ar_ex": "تناول بعض الفاصولياء الخضراء" },
  { "id": 24, "en": "bend", "ar": "يثني / ينحني", "pronounce": "بِنْد", "ex_en": "Bend your knees", "ar_ex": "اثنِ ركبتيك" },
  { "id": 25, "en": "beyond", "ar": "وراء / أبعد من", "pronounce": "بِيُونْد", "ex_en": "Go beyond the limits", "ar_ex": "اذهب أبعد من الحدود" },
  { "id": 26, "en": "bionic", "ar": "إلكتروني حيوي", "pronounce": "بايُونِك", "ex_en": "A bionic arm", "ar_ex": "ذراع إلكترونية" },
  { "id": 27, "en": "bone", "ar": "عظم", "pronounce": "بُون", "ex_en": "A broken bone", "ar_ex": "عظم مكسور" },
  { "id": 28, "en": "brain", "ar": "دماغ", "pronounce": "بْرِين", "ex_en": "Use your brain", "ar_ex": "استخدم دماغك" },
  { "id": 29, "en": "by far", "ar": "إلى حد بعيد", "pronounce": "باي فار", "ex_en": "The best by far", "ar_ex": "الأفضل إلى حد بعيد" },
  { "id": 30, "en": "calcium", "ar": "كالسيوم", "pronounce": "كالْسِيَم", "ex_en": "Milk has calcium", "ar_ex": "الحليب به كالسيوم" },
  { "id": 31, "en": "calorie", "ar": "سعرة حرارية", "pronounce": "كالُوري", "ex_en": "Burn a calorie", "ar_ex": "احرق سعرة حرارية" },
  { "id": 32, "en": "capture", "ar": "يمسك / يأسر", "pronounce": "كاپْتْشَر", "ex_en": "Capture the bird", "ar_ex": "أمسك الطائر" },
  { "id": 33, "en": "carbohydrate", "ar": "كربوهيدرات", "pronounce": "كارْبُوهايْدْرِيت", "ex_en": "Rice is carbohydrate", "ar_ex": "الأرز كربوهيدرات" },
  { "id": 34, "en": "care", "ar": "عناية / رعاية", "pronounce": "كِير", "ex_en": "Take care of it", "ar_ex": "اعتنِ به" },
  { "id": 35, "en": "career", "ar": "مسيرة مهنية", "pronounce": "كارِير", "ex_en": "A long career", "ar_ex": "مسيرة مهنية طويلة" },
  { "id": 36, "en": "carry out", "ar": "ينفذ", "pronounce": "كاري آوت", "ex_en": "Carry out the plan", "ar_ex": "نفذ الخطة" },
  { "id": 37, "en": "Christianity", "ar": "المسيحية", "pronounce": "كْرِسْتِيانِتي", "ex_en": "Christianity is a religion", "ar_ex": "المسيحية ديانة" },
  { "id": 38, "en": "college", "ar": "كلية", "pronounce": "كُولِدْج", "ex_en": "Go to college", "ar_ex": "اذهب للكلية" },
  { "id": 39, "en": "competitive", "ar": "تنافسي", "pronounce": "كُمْپِتِتِڤ", "ex_en": "A competitive market", "ar_ex": "سوق تنافسي" },
  { "id": 40, "en": "connect", "ar": "يربط / يتصل", "pronounce": "كُنِكْت", "ex_en": "Connect the cables", "ar_ex": "اربط الكابلات" },
  { "id": 41, "en": "consist of", "ar": "يتكون من", "pronounce": "كُنْسِسْت أوف", "ex_en": "Consist of parts", "ar_ex": "يتكون من أجزاء" },
  { "id": 42, "en": "contain", "ar": "يحتوي على", "pronounce": "كُنْتِين", "ex_en": "Contain sugar", "ar_ex": "يحتوي على السكر" },
  { "id": 43, "en": "creature", "ar": "مخلوق", "pronounce": "كْرِيتْشَر", "ex_en": "A strange creature", "ar_ex": "مخلوق غريب" },
  { "id": 44, "en": "cruel", "ar": "قاسٍ", "pronounce": "كْرُول", "ex_en": "Do not be cruel", "ar_ex": "لا تكن قاسيا" },
  { "id": 45, "en": "daily", "ar": "يومي", "pronounce": "دِيْلي", "ex_en": "A daily routine", "ar_ex": "روتين يومي" },
  { "id": 46, "en": "deal with", "ar": "يتعامل مع", "pronounce": "دِيل وِذ", "ex_en": "Deal with the issue", "ar_ex": "تعامل مع المشكلة" },
  { "id": 47, "en": "decision", "ar": "قرار", "pronounce": "دِسِژِن", "ex_en": "A hard decision", "ar_ex": "قرار صعب" },
  { "id": 48, "en": "decrease", "ar": "يقلل / ينخفض", "pronounce": "دِكْرِيس", "ex_en": "Decrease the volume", "ar_ex": "اخفض الصوت" },
  { "id": 49, "en": "deeply", "ar": "بعمق", "pronounce": "دِيپْلي", "ex_en": "Breathe deeply", "ar_ex": "تنفس بعمق" },
  { "id": 50, "en": "defend", "ar": "يدافع", "pronounce": "دِفِنْد", "ex_en": "Defend your country", "ar_ex": "دافع عن وطنك" },
  { "id": 51, "en": "depth", "ar": "عمق", "pronounce": "دِپْث", "ex_en": "The depth of the sea", "ar_ex": "عمق البحر" },
  { "id": 52, "en": "describe", "ar": "يصف", "pronounce": "دِسْكْرَايْب", "ex_en": "Describe the picture", "ar_ex": "صف الصورة" },
  { "id": 53, "en": "despite", "ar": "بالرغم من", "pronounce": "دِسْپَايْت", "ex_en": "Despite the rain", "ar_ex": "بالرغم من المطر" },
  { "id": 54, "en": "destination", "ar": "وجهة", "pronounce": "دِسْتِنِيْشِن", "ex_en": "Reach the destination", "ar_ex": "صل للوجهة" },
  { "id": 55, "en": "determined", "ar": "مصمم / عازم", "pronounce": "دِتِيرْمِنْد", "ex_en": "A determined person", "ar_ex": "شخص مصمم" },
  { "id": 56, "en": "development", "ar": "تطور / تنمية", "pronounce": "دِڤِلُوپْمِنْت", "ex_en": "Urban development", "ar_ex": "تنمية حضرية" },
  { "id": 57, "en": "diary", "ar": "مذكرات", "pronounce": "دَايَري", "ex_en": "Write in a diary", "ar_ex": "اكتب في مذكرات" },
  { "id": 58, "en": "diet", "ar": "نظام غذائي", "pronounce": "دَايِت", "ex_en": "A healthy diet", "ar_ex": "نظام غذائي صحي" },
  { "id": 59, "en": "disastrous", "ar": "كارثي", "pronounce": "دِزَاسْتْرَس", "ex_en": "A disastrous event", "ar_ex": "حدث كارثي" },
  { "id": 60, "en": "discovery", "ar": "اكتشاف", "pronounce": "دِسْكَڤَري", "ex_en": "A new discovery", "ar_ex": "اكتشاف جديد" },
  { "id": 61, "en": "dome", "ar": "قبة", "pronounce": "دُوم", "ex_en": "A golden dome", "ar_ex": "قبة ذهبية" },
  { "id": 62, "en": "echo", "ar": "صدى", "pronounce": "إيْكُو", "ex_en": "Hear the echo", "ar_ex": "اسمع الصدى" },
  { "id": 63, "en": "edge", "ar": "حافة", "pronounce": "إدْج", "ex_en": "Edge of the cliff", "ar_ex": "حافة الجرف" },
  { "id": 64, "en": "education", "ar": "تعليم", "pronounce": "إدْيُوكِيْشِن", "ex_en": "Good education", "ar_ex": "تعليم جيد" },
  { "id": 65, "en": "effect", "ar": "تأثير", "pronounce": "إفِكْت", "ex_en": "A bad effect", "ar_ex": "تأثير سيء" },
  { "id": 66, "en": "effective", "ar": "فعال", "pronounce": "إفِكْتِڤ", "ex_en": "An effective medicine", "ar_ex": "دواء فعال" },
  { "id": 67, "en": "event", "ar": "حدث", "pronounce": "إيڤِنْت", "ex_en": "A big event", "ar_ex": "حدث كبير" },
  { "id": 68, "en": "exist", "ar": "يوجد", "pronounce": "إگْزِسْت", "ex_en": "Ghosts do not exist", "ar_ex": "الأشباح لا توجد" },
  { "id": 69, "en": "fail", "ar": "يفشل / يرسب", "pronounce": "فِيل", "ex_en": "Do not fail the exam", "ar_ex": "لا ترسب في الامتحان" },
  { "id": 70, "en": "fake", "ar": "مزيف", "pronounce": "فِيك", "ex_en": "Fake money", "ar_ex": "نقود مزيفة" },
  { "id": 71, "en": "fan", "ar": "مشجع / مروحة", "pronounce": "فان", "ex_en": "A football fan", "ar_ex": "مشجع كرة قدم" },
  { "id": 72, "en": "fibre", "ar": "ألياف", "pronounce": "فايْبَر", "ex_en": "Eat more fibre", "ar_ex": "تناول أليافا أكثر" },
  { "id": 73, "en": "fill", "ar": "يملأ", "pronounce": "فِل", "ex_en": "Fill the cup", "ar_ex": "املأ الكوب" },
  { "id": 74, "en": "filling", "ar": "حشوة", "pronounce": "فِلِنْغ", "ex_en": "Pie filling", "ar_ex": "حشوة الفطيرة" },
  { "id": 75, "en": "film", "ar": "فيلم", "pronounce": "فِلْم", "ex_en": "Watch a film", "ar_ex": "شاهد فيلماً" },
  { "id": 76, "en": "fisherman", "ar": "صياد سمك", "pronounce": "فِشَرْمَان", "ex_en": "An old fisherman", "ar_ex": "صياد سمك عجوز" },
  { "id": 77, "en": "flipper", "ar": "زعنفة", "pronounce": "فْلِپَر", "ex_en": "Wear a flipper", "ar_ex": "ارتدِ زعنفة" },
  { "id": 78, "en": "force", "ar": "قوة / يجبر", "pronounce": "فُورْس", "ex_en": "Use force", "ar_ex": "استخدم القوة" },
  { "id": 79, "en": "form", "ar": "شكل / استمارة", "pronounce": "فُورْم", "ex_en": "Fill the form", "ar_ex": "املأ الاستمارة" },
  { "id": 80, "en": "fossil fuel", "ar": "وقود أحفوري", "pronounce": "فُوسِل فْيُول", "ex_en": "Oil is fossil fuel", "ar_ex": "النفط وقود أحفوري" },
  { "id": 81, "en": "frightening", "ar": "مخيف", "pronounce": "فْرَايْتِنِنْغ", "ex_en": "A frightening mask", "ar_ex": "قناع مخيف" },
  { "id": 82, "en": "fuel", "ar": "وقود", "pronounce": "فْيُول", "ex_en": "Car fuel", "ar_ex": "وقود السيارة" },
  { "id": 83, "en": "gas", "ar": "غاز", "pronounce": "گاس", "ex_en": "Turn off the gas", "ar_ex": "أغلق الغاز" },
  { "id": 84, "en": "gather", "ar": "يجمع / يتجمع", "pronounce": "گاذَر", "ex_en": "Gather the wood", "ar_ex": "اجمع الخشب" },
  { "id": 85, "en": "general(ly)", "ar": "عام / عموماً", "pronounce": "جِنِرَل(ي)", "ex_en": "In general", "ar_ex": "بشكل عام" },
  { "id": 86, "en": "generally speaking", "ar": "بصورة عامة", "pronounce": "جِنِرَلي سْپِيكِنْغ", "ex_en": "Generally speaking yes", "ar_ex": "بصورة عامة نعم" },
  { "id": 87, "en": "generation", "ar": "جيل", "pronounce": "جِنِرِيْشِن", "ex_en": "A new generation", "ar_ex": "جيل جديد" },
  { "id": 88, "en": "genuine", "ar": "أصلي", "pronounce": "جِنْيُوِن", "ex_en": "Genuine leather", "ar_ex": "جلد أصلي" },
  { "id": 89, "en": "golden", "ar": "ذهبي", "pronounce": "گُولْدِن", "ex_en": "A golden ring", "ar_ex": "خاتم ذهبي" },
  { "id": 90, "en": "goods", "ar": "بضائع", "pronounce": "گُودْز", "ex_en": "Buy goods", "ar_ex": "اشتر بضائع" },
  { "id": 91, "en": "gram", "ar": "غرام", "pronounce": "گْرام", "ex_en": "One gram of salt", "ar_ex": "غرام واحد من الملح" },
  { "id": 92, "en": "growth", "ar": "نمو", "pronounce": "گْرُوث", "ex_en": "Plant growth", "ar_ex": "نمو النبات" },
  { "id": 93, "en": "high-tech", "ar": "عالي التقنية", "pronounce": "هاي تِك", "ex_en": "High-tech devices", "ar_ex": "أجهزة عالية التقنية" },
  { "id": 94, "en": "hole", "ar": "حفرة / ثقب", "pronounce": "هُول", "ex_en": "A deep hole", "ar_ex": "حفرة عميقة" },
  { "id": 95, "en": "hump", "ar": "سنام", "pronounce": "هَمْپ", "ex_en": "Camel hump", "ar_ex": "سنام الجمل" },
  { "id": 96, "en": "importance", "ar": "أهمية", "pronounce": "إمْپُورْتَنْس", "ex_en": "The importance of water", "ar_ex": "أهمية الماء" },
  { "id": 97, "en": "improve", "ar": "يحسن", "pronounce": "إمْپْرُوڤ", "ex_en": "Improve your skills", "ar_ex": "حسن مهاراتك" },
  { "id": 98, "en": "increase", "ar": "يزيد", "pronounce": "إنْكْرِيس", "ex_en": "Increase the speed", "ar_ex": "زد السرعة" },
  { "id": 99, "en": "inscription", "ar": "نقش", "pronounce": "إنْسْكْرِپْشِن", "ex_en": "An old inscription", "ar_ex": "نقش قديم" },
  { "id": 100, "en": "intelligent", "ar": "ذكي", "pronounce": "إنْتِلِجِنْت", "ex_en": "An intelligent boy", "ar_ex": "ولد ذكي" },
  { "id": 101, "en": "introduction", "ar": "مقدمة", "pronounce": "إنْتْرُودَكْشِن", "ex_en": "A book introduction", "ar_ex": "مقدمة كتاب" },
  { "id": 102, "en": "invention", "ar": "اختراع", "pronounce": "إنْڤِنْشِن", "ex_en": "A great invention", "ar_ex": "اختراع عظيم" },
  { "id": 103, "en": "Judaism", "ar": "اليهودية", "pronounce": "جُودِيزِم", "ex_en": "Judaism religion", "ar_ex": "الديانة اليهودية" },
  { "id": 104, "en": "largely", "ar": "إلى حد كبير", "pronounce": "لارْجْلي", "ex_en": "It is largely true", "ar_ex": "إنه صحيح إلى حد كبير" },
  { "id": 105, "en": "let", "ar": "يسمح / يدع", "pronounce": "لِت", "ex_en": "Let me go", "ar_ex": "دعني أذهب" },
  { "id": 106, "en": "likely", "ar": "محتمل", "pronounce": "لايْكْلي", "ex_en": "It is likely to rain", "ar_ex": "من المحتمل أن تمطر" },
  { "id": 107, "en": "limited", "ar": "محدود", "pronounce": "لِمِتِد", "ex_en": "Limited time", "ar_ex": "وقت محدود" },
  { "id": 108, "en": "literary", "ar": "أدبي", "pronounce": "لِتِرَري", "ex_en": "Literary books", "ar_ex": "كتب أدبية" },
  { "id": 109, "en": "magnificent", "ar": "رائع / عظيم", "pronounce": "ماگْنِفِسِنْت", "ex_en": "A magnificent view", "ar_ex": "منظر رائع" },
  { "id": 110, "en": "make up for", "ar": "يعوض عن", "pronounce": "مِيك أپ فُور", "ex_en": "Make up for the loss", "ar_ex": "عوض عن الخسارة" },
  { "id": 111, "en": "manage", "ar": "يدير / يتمكن", "pronounce": "مانِدْج", "ex_en": "Manage the time", "ar_ex": "أدر الوقت" },
  { "id": 112, "en": "manager", "ar": "مدير", "pronounce": "مانِجَر", "ex_en": "The bank manager", "ar_ex": "مدير البنك" },
  { "id": 113, "en": "match", "ar": "مباراة / يطابق", "pronounce": "ماتْش", "ex_en": "A football match", "ar_ex": "مباراة كرة قدم" },
  { "id": 114, "en": "meanwhile", "ar": "في غضون ذلك", "pronounce": "مِينْوايْل", "ex_en": "Meanwhile I waited", "ar_ex": "في غضون ذلك انتظرت" },
  { "id": 115, "en": "monotheistic", "ar": "توحيدي", "pronounce": "مُونُوثِيِسْتِك", "ex_en": "Monotheistic religion", "ar_ex": "ديانة توحيدية" },
  { "id": 116, "en": "monster", "ar": "وحش", "pronounce": "مُونْسْتَر", "ex_en": "A scary monster", "ar_ex": "وحش مخيف" },
  { "id": 117, "en": "mysterious", "ar": "غامض", "pronounce": "مِسْتِيرْيَس", "ex_en": "A mysterious man", "ar_ex": "رجل غامض" },
  { "id": 118, "en": "mystery", "ar": "لغز / غموض", "pronounce": "مِسْتِري", "ex_en": "Solve the mystery", "ar_ex": "حل اللغز" },
  { "id": 119, "en": "nutrient", "ar": "مادة مغذية", "pronounce": "نْيُوتْرِيِنْت", "ex_en": "Healthy nutrient", "ar_ex": "عنصر غذائي صحي" },
  { "id": 120, "en": "object", "ar": "شيء", "pronounce": "أُوبْجِكْت", "ex_en": "A heavy object", "ar_ex": "شيء ثقيل" },
  { "id": 121, "en": "on the other hand", "ar": "من ناحية أخرى", "pronounce": "أُون ذي أَذَر هَانْد", "ex_en": "On the other hand no", "ar_ex": "من ناحية أخرى لا" },
  { "id": 122, "en": "operate", "ar": "يشغل / يجري عملية", "pronounce": "أُوپِرِيت", "ex_en": "Operate the machine", "ar_ex": "شغل الآلة" },
  { "id": 123, "en": "opportunity", "ar": "فرصة", "pronounce": "أُوپُرْتْيُونِتي", "ex_en": "A good opportunity", "ar_ex": "فرصة جيدة" },
  { "id": 124, "en": "oppress", "ar": "يضطهد", "pronounce": "أُوپْرِس", "ex_en": "Oppress the weak", "ar_ex": "يضطهد الضعيف" },
  { "id": 125, "en": "organize", "ar": "ينظم", "pronounce": "أُورْگانَايْز", "ex_en": "Organize a party", "ar_ex": "نظم حفلة" },
  { "id": 126, "en": "original", "ar": "أصلي", "pronounce": "أُرِجِنَل", "ex_en": "The original plan", "ar_ex": "الخطة الأصلية" },
  { "id": 127, "en": "overweight", "ar": "وزن زائد", "pronounce": "أُوڤَرْوِيْت", "ex_en": "He is overweight", "ar_ex": "هو ذو وزن زائد" },
  { "id": 128, "en": "particular(ly)", "ar": "خاص / بشكل خاص", "pronounce": "پارْتِكْيُولَر", "ex_en": "Particularly you", "ar_ex": "أنت بشكل خاص" },
  { "id": 129, "en": "pasta", "ar": "معكرونة", "pronounce": "پاسْتا", "ex_en": "Eat pasta", "ar_ex": "تناول المعكرونة" },
  { "id": 130, "en": "peaceful(ly)", "ar": "سلمي / هادئ", "pronounce": "پِيسْفُل", "ex_en": "A peaceful place", "ar_ex": "مكان هادئ" },
  { "id": 131, "en": "pie", "ar": "فطيرة", "pronounce": "پاي", "ex_en": "Apple pie", "ar_ex": "فطيرة تفاح" },
  { "id": 132, "en": "pilgrim", "ar": "حاج", "pronounce": "پِلْگْرِم", "ex_en": "A tired pilgrim", "ar_ex": "حاج متعب" },
  { "id": 133, "en": "pineapple", "ar": "أناناس", "pronounce": "پايْن أپِل", "ex_en": "Cut the pineapple", "ar_ex": "اقطع الأناناس" },
  { "id": 134, "en": "point out", "ar": "يشير إلى", "pronounce": "پُويْنْت آوْت", "ex_en": "Point out the mistake", "ar_ex": "أشر إلى الخطأ" },
  { "id": 135, "en": "pollute", "ar": "يلوث", "pronounce": "پُلُوت", "ex_en": "Pollute the water", "ar_ex": "يلوث الماء" },
  { "id": 136, "en": "portion", "ar": "حصة / جزء", "pronounce": "پُورْشِن", "ex_en": "A small portion", "ar_ex": "حصة صغيرة" },
  { "id": 137, "en": "possibility", "ar": "إمكانية", "pronounce": "پُوسِبِلِتي", "ex_en": "A strong possibility", "ar_ex": "إمكانية قوية" },
  { "id": 138, "en": "practical", "ar": "عملي", "pronounce": "پْراكْتِكَل", "ex_en": "A practical idea", "ar_ex": "فكرة عملية" },
  { "id": 139, "en": "pressure", "ar": "ضغط", "pronounce": "پْرِشَر", "ex_en": "Under pressure", "ar_ex": "تحت الضغط" },
  { "id": 140, "en": "prevent", "ar": "يمنع", "pronounce": "پْرِڤِنْت", "ex_en": "Prevent the fire", "ar_ex": "امنع الحريق" },
  { "id": 141, "en": "prevention", "ar": "وقاية", "pronounce": "پْرِڤِنْشِن", "ex_en": "Disease prevention", "ar_ex": "الوقاية من المرض" },
  { "id": 142, "en": "programmer", "ar": "مبرمج", "pronounce": "پْرُوغْرامَر", "ex_en": "A clever programmer", "ar_ex": "مبرمج ذكي" },
  { "id": 143, "en": "protein", "ar": "بروتين", "pronounce": "پْرُوتِين", "ex_en": "Meat has protein", "ar_ex": "اللحم به بروتين" },
  { "id": 144, "en": "put off", "ar": "يؤجل", "pronounce": "پُت أُوف", "ex_en": "Put off the meeting", "ar_ex": "أجل الاجتماع" },
  { "id": 145, "en": "qualification", "ar": "مؤهل", "pronounce": "كْوالِفِكِيْشِن", "ex_en": "A high qualification", "ar_ex": "مؤهل عال" },
  { "id": 146, "en": "ramp", "ar": "منحدر", "pronounce": "رامْپ", "ex_en": "Walk up the ramp", "ar_ex": "امش صعوداً على المنحدر" },
  { "id": 147, "en": "rapid(ly)", "ar": "سريع", "pronounce": "راپِد", "ex_en": "Rapid growth", "ar_ex": "نمو سريع" },
  { "id": 148, "en": "reason", "ar": "سبب", "pronounce": "رِيزِن", "ex_en": "Give me a reason", "ar_ex": "أعطني سببا" },
  { "id": 149, "en": "rebuild", "ar": "يعيد بناء", "pronounce": "رِبِلْد", "ex_en": "Rebuild the wall", "ar_ex": "أعد بناء الجدار" },
  { "id": 150, "en": "record", "ar": "يسجل", "pronounce": "رِكُورْد", "ex_en": "Record the sound", "ar_ex": "سجل الصوت" },
  { "id": 151, "en": "recover", "ar": "يتعافى", "pronounce": "رِكَڤَر", "ex_en": "Recover from illness", "ar_ex": "يتعافى من المرض" },
  { "id": 152, "en": "relieved", "ar": "مرتاح", "pronounce": "رِلِيڤْد", "ex_en": "I feel relieved", "ar_ex": "أشعر بالارتياح" },
  { "id": 153, "en": "remains", "ar": "بقايا / آثار", "pronounce": "رِمِيْنْز", "ex_en": "Ancient remains", "ar_ex": "آثار قديمة" },
  { "id": 154, "en": "researcher", "ar": "باحث", "pronounce": "رِسِيرْتْشَر", "ex_en": "A smart researcher", "ar_ex": "باحث ذكي" },
  { "id": 155, "en": "resort", "ar": "منتجع", "pronounce": "رِزُورْت", "ex_en": "A beach resort", "ar_ex": "منتجع شاطئي" },
  { "id": 156, "en": "resource", "ar": "مورد / مصدر", "pronounce": "رِسُورْس", "ex_en": "A natural resource", "ar_ex": "مورد طبيعي" },
  { "id": 157, "en": "responsible(ly)", "ar": "مسؤول", "pronounce": "رِسْپُونْسِبِل", "ex_en": "Be responsible", "ar_ex": "كن مسؤولا" },
  { "id": 158, "en": "scientific", "ar": "علمي", "pronounce": "سايِنْتِفِك", "ex_en": "Scientific research", "ar_ex": "بحث علمي" },
  { "id": 159, "en": "shark", "ar": "قرش", "pronounce": "شارْك", "ex_en": "A big shark", "ar_ex": "قرش كبير" },
  { "id": 160, "en": "shocked", "ar": "مصدوم", "pronounce": "شُوكْد", "ex_en": "I was shocked", "ar_ex": "كنت مصدوما" },
  { "id": 161, "en": "specialize", "ar": "يتخصص", "pronounce": "سْپِشَلايْز", "ex_en": "Specialize in art", "ar_ex": "يتخصص في الفن" },
  { "id": 162, "en": "spinach", "ar": "سبانخ", "pronounce": "سْپِنِتْش", "ex_en": "Eat spinach", "ar_ex": "تناول السبانخ" },
  { "id": 163, "en": "steady(ily)", "ar": "ثابت", "pronounce": "سْتِدي", "ex_en": "A steady job", "ar_ex": "عمل ثابت" },
  { "id": 164, "en": "starve", "ar": "يجوع / يتضور جوعاً", "pronounce": "سْتَارْڤ", "ex_en": "Do not starve", "ar_ex": "لا تتضور جوعا" },
  { "id": 165, "en": "still", "ar": "ساكن / لا يزال", "pronounce": "سْتِل", "ex_en": "Stand still", "ar_ex": "قف ساكنا" },
  { "id": 166, "en": "stream", "ar": "جدول ماء", "pronounce": "سْتْرِيم", "ex_en": "A small stream", "ar_ex": "جدول ماء صغير" },
  { "id": 167, "en": "strength", "ar": "قوة", "pronounce": "سْتْرِنْگْث", "ex_en": "Show your strength", "ar_ex": "أظهر قوتك" },
  { "id": 168, "en": "stressful", "ar": "مجهد / موتر", "pronounce": "سْتْرِسْفُل", "ex_en": "A stressful day", "ar_ex": "يوم مجهد" },
  { "id": 169, "en": "such as", "ar": "مثل", "pronounce": "سَتْش أز", "ex_en": "Fruits such as apples", "ar_ex": "فواكه مثل التفاح" },
  { "id": 170, "en": "suffer", "ar": "يعاني", "pronounce": "سَفَر", "ex_en": "Suffer from pain", "ar_ex": "يعاني من الألم" },
  { "id": 171, "en": "surface", "ar": "سطح", "pronounce": "سِيرْفِس", "ex_en": "The sea surface", "ar_ex": "سطح البحر" },
  { "id": 172, "en": "surprising(ly)", "ar": "مفاجئ", "pronounce": "سُرْپْرَايْزِنْغ", "ex_en": "A surprising fact", "ar_ex": "حقيقة مفاجئة" },
  { "id": 173, "en": "survive", "ar": "ينجو", "pronounce": "سِرْڤَايڤ", "ex_en": "Survive the cold", "ar_ex": "ينجو من البرد" },
  { "id": 174, "en": "technical", "ar": "تقني / فني", "pronounce": "تِكْنِكَل", "ex_en": "Technical error", "ar_ex": "خطأ تقني" },
  { "id": 175, "en": "technician", "ar": "فني", "pronounce": "تِكْنِشِن", "ex_en": "Call the technician", "ar_ex": "اتصل بالفني" },
  { "id": 176, "en": "teenager (teen)", "ar": "مراهق", "pronounce": "تِينِيْجَر", "ex_en": "A young teenager", "ar_ex": "مراهق شاب" },
  { "id": 177, "en": "thorough(ly)", "ar": "شامل / دقيق", "pronounce": "ثُورُو", "ex_en": "A thorough search", "ar_ex": "بحث دقيق" },
  { "id": 178, "en": "tight", "ar": "ضيق", "pronounce": "تايْت", "ex_en": "A tight shirt", "ar_ex": "قميص ضيق" },
  { "id": 179, "en": "topping", "ar": "طبقة علوية (للطعام)", "pronounce": "تُوپِنْغ", "ex_en": "Pizza topping", "ar_ex": "الطبقة العلوية للبيتزا" },
  { "id": 180, "en": "true", "ar": "صحيح", "pronounce": "تْرُو", "ex_en": "A true story", "ar_ex": "قصة حقيقية" },
  { "id": 181, "en": "underwater", "ar": "تحت الماء", "pronounce": "أنْدَرْوُوتَر", "ex_en": "Underwater diving", "ar_ex": "غوص تحت الماء" },
  { "id": 182, "en": "use", "ar": "استخدام / يستخدم", "pronounce": "يُوز", "ex_en": "Use the pen", "ar_ex": "استخدم القلم" },
  { "id": 183, "en": "vehicle", "ar": "مركبة", "pronounce": "ڤِيِكِل", "ex_en": "A fast vehicle", "ar_ex": "مركبة سريعة" },
  { "id": 184, "en": "vitamin", "ar": "فيتامين", "pronounce": "ڤِيْتَامِين", "ex_en": "Vitamin C", "ar_ex": "فيتامين سي" },
  { "id": 185, "en": "vocational", "ar": "مهني", "pronounce": "ڤُوكِيْشُنَل", "ex_en": "Vocational school", "ar_ex": "مدرسة مهنية" },
  { "id": 186, "en": "warn", "ar": "يحذر", "pronounce": "وُورْن", "ex_en": "Warn the people", "ar_ex": "حذر الناس" },
  { "id": 187, "en": "wealth", "ar": "ثروة", "pronounce": "وِلْث", "ex_en": "Health is wealth", "ar_ex": "الصحة ثروة" },
  { "id": 188, "en": "wheelchair", "ar": "كرسي متحرك", "pronounce": "وِيلْتْشِير", "ex_en": "Need a wheelchair", "ar_ex": "يحتاج لكرسي متحرك" },
  { "id": 189, "en": "whatever", "ar": "أياً كان", "pronounce": "واتِڤَر", "ex_en": "Whatever you want", "ar_ex": "أياً كان ما تريده" },
  { "id": 190, "en": "whereas", "ar": "في حين أن", "pronounce": "وِيرْأز", "ex_en": "I like tea whereas he likes coffee", "ar_ex": "أنا أحب الشاي في حين هو يحب القهوة" },
  { "id": 191, "en": "wonder", "ar": "يتعجب / يتساءل", "pronounce": "وُونْدَر", "ex_en": "I wonder why", "ar_ex": "أتساءل لماذا" },
  { "id": 192, "en": "worrying", "ar": "مقلق", "pronounce": "وُورِيِنْغ", "ex_en": "A worrying news", "ar_ex": "أخبار مقلقة" },
  { "id": 193, "en": "yogurt", "ar": "زبادي / لبن", "pronounce": "يُوگُرْت", "ex_en": "Eat fresh yogurt", "ar_ex": "تناول زبادي طازج" },
  { "id": 194, "en": "about (to)", "ar": "على وشك أن", "pronounce": "أبَاوْت تُو", "ex_en": "About to leave", "ar_ex": "على وشك المغادرة" },
  { "id": 195, "en": "abroad", "ar": "بالخارج (خارج البلاد)", "pronounce": "أبْرُود", "ex_en": "Travel abroad", "ar_ex": "سافر للخارج" },
  { "id": 196, "en": "accept", "ar": "يقبل", "pronounce": "أكْسِپْت", "ex_en": "Accept the gift", "ar_ex": "اقبل الهدية" },
  { "id": 197, "en": "accurate(ly)", "ar": "دقيق", "pronounce": "أكْيُورِيت", "ex_en": "Accurate answer", "ar_ex": "إجابة دقيقة" },
  { "id": 198, "en": "afford", "ar": "يقدر مالياً / يطيق", "pronounce": "أفُورْد", "ex_en": "I cannot afford it", "ar_ex": "لا أقدر عليه مالياً" },
  { "id": 199, "en": "against", "ar": "ضد", "pronounce": "أگِيْنْسْت", "ex_en": "Against the wall", "ar_ex": "ضد الجدار" },
  { "id": 200, "en": "alive", "ar": "على قيد الحياة", "pronounce": "ألايْڤ", "ex_en": "Keep it alive", "ar_ex": "أبقه حيا" },
  { "id": 201, "en": "along with", "ar": "جنباً إلى جنب مع", "pronounce": "ألُونْغ وِذ", "ex_en": "Along with friends", "ar_ex": "مع الأصدقاء" },
  { "id": 202, "en": "apartment", "ar": "شقة", "pronounce": "أپَارْتْمِنْت", "ex_en": "A big apartment", "ar_ex": "شقة كبيرة" },
  { "id": 203, "en": "appointment", "ar": "موعد", "pronounce": "أپُويْنْتْمِنْت", "ex_en": "A doctor appointment", "ar_ex": "موعد طبيب" },
  { "id": 204, "en": "approach", "ar": "يقترب / نهج", "pronounce": "أپْرُوتْش", "ex_en": "Approach the door", "ar_ex": "اقترب من الباب" },
  { "id": 205, "en": "arrange", "ar": "يرتب", "pronounce": "أرِيْنْج", "ex_en": "Arrange the books", "ar_ex": "رتب الكتب" },
  { "id": 206, "en": "arrangement", "ar": "ترتيب", "pronounce": "أرِيْنْجْمِنْت", "ex_en": "A good arrangement", "ar_ex": "ترتيب جيد" },
  { "id": 207, "en": "(house) arrest", "ar": "إقامة جبرية / اعتقال", "pronounce": "هَاوس أرِسْت", "ex_en": "Under house arrest", "ar_ex": "قيد الإقامة الجبرية" },
  { "id": 208, "en": "as (= while)", "ar": "بينما / كما", "pronounce": "أز", "ex_en": "As I said before", "ar_ex": "كما قلت سابقا" },
  { "id": 209, "en": "at last", "ar": "أخيراً", "pronounce": "أت لاسْت", "ex_en": "At last we arrived", "ar_ex": "أخيرا وصلنا" },
  { "id": 210, "en": "at least", "ar": "على الأقل", "pronounce": "أت لِيسْت", "ex_en": "At least one", "ar_ex": "على الأقل واحد" },
  { "id": 211, "en": "attach", "ar": "يرفق / يربط", "pronounce": "أتاش", "ex_en": "Attach the file", "ar_ex": "أرفق الملف" },
  { "id": 212, "en": "attack", "ar": "يهاجم", "pronounce": "أتاك", "ex_en": "Attack the enemy", "ar_ex": "هاجم العدو" },
  { "id": 213, "en": "avalanche", "ar": "انهيار جليدي", "pronounce": "أڤَلانْش", "ex_en": "A huge avalanche", "ar_ex": "انهيار جليدي ضخم" },
  { "id": 214, "en": "breathe", "ar": "يتنفس", "pronounce": "بْرِيذ", "ex_en": "Breathe fresh air", "ar_ex": "تنفس هواء نقيا" },
  { "id": 215, "en": "business", "ar": "عمل تجاري / شركة", "pronounce": "بِزْنِس", "ex_en": "A good business", "ar_ex": "عمل تجاري جيد" },
  { "id": 216, "en": "cancel", "ar": "يلغي", "pronounce": "كانْسِل", "ex_en": "Cancel the flight", "ar_ex": "ألغِ الرحلة" },
  { "id": 217, "en": "canteen", "ar": "مقصف / كافتيريا", "pronounce": "كانْتِين", "ex_en": "Eat in canteen", "ar_ex": "كل في المقصف" },
  { "id": 218, "en": "castle", "ar": "قلعة", "pronounce": "كاسِل", "ex_en": "An old castle", "ar_ex": "قلعة قديمة" },
  { "id": 219, "en": "closed", "ar": "مغلق", "pronounce": "كْلُوزْد", "ex_en": "The door is closed", "ar_ex": "الباب مغلق" },
  { "id": 220, "en": "clue", "ar": "دليل / مفتاح لغز", "pronounce": "كْلُو", "ex_en": "Give me a clue", "ar_ex": "أعطني دليلا" },
  { "id": 221, "en": "colourful", "ar": "ملون", "pronounce": "كَلَرْفُل", "ex_en": "A colourful bird", "ar_ex": "طائر ملون" },
  { "id": 222, "en": "combine", "ar": "يجمع / يدمج", "pronounce": "كُمْبَايْن", "ex_en": "Combine the ideas", "ar_ex": "ادمج الأفكار" },
  { "id": 223, "en": "condition", "ar": "حالة / شرط", "pronounce": "كُنْدِشِن", "ex_en": "A bad condition", "ar_ex": "حالة سيئة" },
  { "id": 224, "en": "control", "ar": "يتحكم / سيطرة", "pronounce": "كُنْتْرُول", "ex_en": "Control the car", "ar_ex": "تحكم بالسيارة" },
  { "id": 225, "en": "cost", "ar": "تكلفة / يكلف", "pronounce": "كُوسْت", "ex_en": "High cost", "ar_ex": "تكلفة عالية" },
  { "id": 226, "en": "cross", "ar": "يعبر", "pronounce": "كْرُوس", "ex_en": "Cross the street", "ar_ex": "اعبر الشارع" },
  { "id": 227, "en": "cultivate", "ar": "يزرع / يفلح", "pronounce": "كَلْتِڤِيْت", "ex_en": "Cultivate the land", "ar_ex": "ازرع الأرض" },
  { "id": 228, "en": "cultural", "ar": "ثقافي", "pronounce": "كَلْتْشُرَل", "ex_en": "Cultural heritage", "ar_ex": "تراث ثقافي" },
  { "id": 229, "en": "decorate", "ar": "يزين", "pronounce": "دِكُورِيْت", "ex_en": "Decorate the room", "ar_ex": "زين الغرفة" },
  { "id": 230, "en": "definite", "ar": "محدد / مؤكد", "pronounce": "دِفِنِت", "ex_en": "A definite answer", "ar_ex": "إجابة مؤكدة" },
  { "id": 231, "en": "delighted", "ar": "مسرور جداً", "pronounce": "دِلَايْتِد", "ex_en": "I am delighted", "ar_ex": "أنا مسرور جدا" },
  { "id": 232, "en": "depart", "ar": "يغادر", "pronounce": "دِپَارْت", "ex_en": "Depart now", "ar_ex": "غادر الآن" },
  { "id": 233, "en": "destruction", "ar": "دمار", "pronounce": "دِسْتْرَكْشِن", "ex_en": "Mass destruction", "ar_ex": "دمار شامل" },
  { "id": 234, "en": "destructive", "ar": "مدمر", "pronounce": "دِسْتْرَكْتِڤ", "ex_en": "A destructive storm", "ar_ex": "عاصفة مدمرة" },
  { "id": 235, "en": "director", "ar": "مدير / مخرج", "pronounce": "دَايْرِكْتَر", "ex_en": "The film director", "ar_ex": "مخرج الفيلم" },
  { "id": 236, "en": "district", "ar": "منطقة / مقاطعة", "pronounce": "دِسْتْرِكْت", "ex_en": "A quiet district", "ar_ex": "منطقة هادئة" },
  { "id": 237, "en": "dream", "ar": "حلم / يحلم", "pronounce": "دْرِيم", "ex_en": "A sweet dream", "ar_ex": "حلم جميل" },
  { "id": 238, "en": "editor", "ar": "محرر", "pronounce": "إدِتَر", "ex_en": "News editor", "ar_ex": "محرر أخبار" },
  { "id": 239, "en": "emergency", "ar": "حالة طوارئ", "pronounce": "إمِيرْجِنْسي", "ex_en": "In case of emergency", "ar_ex": "في حالة الطوارئ" },
  { "id": 240, "en": "energetic", "ar": "نشيط", "pronounce": "إنِرْجِتِك", "ex_en": "An energetic kid", "ar_ex": "طفل نشيط" },
  { "id": 241, "en": "escape", "ar": "يهرب / هروب", "pronounce": "إسْكِيْپ", "ex_en": "Escape the prison", "ar_ex": "اهرب من السجن" },
  { "id": 242, "en": "exact(ly)", "ar": "دقيق (بالضبط)", "pronounce": "إگْزَاكْت", "ex_en": "Exactly right", "ar_ex": "صحيح بالضبط" },
  { "id": 243, "en": "exam", "ar": "امتحان", "pronounce": "إگْزَام", "ex_en": "A hard exam", "ar_ex": "امتحان صعب" },
  { "id": 244, "en": "except (for)", "ar": "باستثناء", "pronounce": "إكْسِپْت", "ex_en": "All except you", "ar_ex": "الجميع باستثنائك" },
  { "id": 245, "en": "exhausted", "ar": "منهك", "pronounce": "إگْزُوسْتِد", "ex_en": "I am exhausted", "ar_ex": "أنا منهك" },
  { "id": 246, "en": "exile", "ar": "ينفي / منفى", "pronounce": "إگْزَايْل", "ex_en": "Go into exile", "ar_ex": "يذهب إلى المنفى" },
  { "id": 247, "en": "experiment", "ar": "تجربة", "pronounce": "إكْسْپِرِمِنْت", "ex_en": "A science experiment", "ar_ex": "تجربة علمية" },
  { "id": 248, "en": "explosion", "ar": "انفجار", "pronounce": "إكْسْپْلُوجِن", "ex_en": "A loud explosion", "ar_ex": "انفجار مدوٍ" },
  { "id": 249, "en": "farmland", "ar": "أرض زراعية", "pronounce": "فَارْمْلانْد", "ex_en": "Rich farmland", "ar_ex": "أرض زراعية خصبة" },
  { "id": 250, "en": "faulty", "ar": "معيب / به خلل", "pronounce": "فُولْتي", "ex_en": "A faulty wire", "ar_ex": "سلك معيب" },
  { "id": 251, "en": "feed", "ar": "يطعم", "pronounce": "فِيد", "ex_en": "Feed the cat", "ar_ex": "أطعم القطة" },
  { "id": 252, "en": "field", "ar": "حقل", "pronounce": "فِيلْد", "ex_en": "A green field", "ar_ex": "حقل أخضر" },
  { "id": 253, "en": "fire engine", "ar": "سيارة إطفاء", "pronounce": "فَايَر إنْجِن", "ex_en": "A red fire engine", "ar_ex": "سيارة إطفاء حمراء" },
  { "id": 254, "en": "fire station", "ar": "محطة إطفاء", "pronounce": "فَايَر سْتِيْشِن", "ex_en": "Near fire station", "ar_ex": "قرب محطة الإطفاء" },
  { "id": 255, "en": "firefighter", "ar": "رجل إطفاء", "pronounce": "فَايَرْفَايْتَر", "ex_en": "A brave firefighter", "ar_ex": "رجل إطفاء شجاع" },
  { "id": 256, "en": "flame", "ar": "لهب", "pronounce": "فْلِيْم", "ex_en": "A bright flame", "ar_ex": "لهب ساطع" },
  { "id": 257, "en": "flexible", "ar": "مرن", "pronounce": "فْلِكْسِبِل", "ex_en": "A flexible body", "ar_ex": "جسم مرن" },
  { "id": 258, "en": "forest", "ar": "غابة", "pronounce": "فُورِسْت", "ex_en": "A dark forest", "ar_ex": "غابة مظلمة" },
  { "id": 259, "en": "frame", "ar": "إطار", "pronounce": "فْرِيْم", "ex_en": "A picture frame", "ar_ex": "إطار صورة" },
  { "id": 260, "en": "free (for)", "ar": "مجاني / حر", "pronounce": "فْرِي", "ex_en": "It is free", "ar_ex": "إنه مجاني" },
  { "id": 261, "en": "get to", "ar": "يصل إلى", "pronounce": "گِت تُو", "ex_en": "Get to the top", "ar_ex": "صل إلى القمة" },
  { "id": 262, "en": "give up", "ar": "يستسلم", "pronounce": "گِڤ أپ", "ex_en": "Never give up", "ar_ex": "لا تستسلم أبدا" },
  { "id": 263, "en": "GPS", "ar": "نظام تحديد المواقع", "pronounce": "جِي پِي إس", "ex_en": "Use the GPS", "ar_ex": "استخدم نظام المواقع" },
  { "id": 264, "en": "graduate", "ar": "يتخرج", "pronounce": "گْرَاجْيُوِيْت", "ex_en": "Graduate from school", "ar_ex": "تخرج من المدرسة" },
  { "id": 265, "en": "heat", "ar": "حرارة", "pronounce": "هِيت", "ex_en": "Summer heat", "ar_ex": "حرارة الصيف" },
  { "id": 266, "en": "helpless(ly)", "ar": "عاجز", "pronounce": "هِلْپْلِس", "ex_en": "Feel helpless", "ar_ex": "يشعر بالعجز" },
  { "id": 267, "en": "hill", "ar": "تل", "pronounce": "هِل", "ex_en": "Climb the hill", "ar_ex": "تسلق التل" },
  { "id": 268, "en": "hit", "ar": "يضرب", "pronounce": "هِت", "ex_en": "Hit the ball", "ar_ex": "اضرب الكرة" },
  { "id": 269, "en": "ice", "ar": "جليد / ثلج", "pronounce": "آيْس", "ex_en": "Cold ice", "ar_ex": "جليد بارد" },
  { "id": 270, "en": "in contact", "ar": "على تواصل", "pronounce": "إن كُونْتَاكْت", "ex_en": "Keep in contact", "ar_ex": "ابق على تواصل" },
  { "id": 271, "en": "in the lead", "ar": "في الصدارة", "pronounce": "إن ذي لِيد", "ex_en": "He is in the lead", "ar_ex": "هو في الصدارة" },
  { "id": 272, "en": "interest", "ar": "اهتمام", "pronounce": "إنْتْرِسْت", "ex_en": "Show some interest", "ar_ex": "أظهر بعض الاهتمام" },
  { "id": 273, "en": "interview", "ar": "مقابلة", "pronounce": "إنْتَرْڤْيُو", "ex_en": "A job interview", "ar_ex": "مقابلة عمل" },
  { "id": 274, "en": "island", "ar": "جزيرة", "pronounce": "آيْلَانْد", "ex_en": "A small island", "ar_ex": "جزيرة صغيرة" },
  { "id": 275, "en": "junior", "ar": "ناشئ / مبتدئ", "pronounce": "جُونْيَر", "ex_en": "A junior player", "ar_ex": "لاعب ناشئ" },
  { "id": 276, "en": "kph", "ar": "كم/ساعة", "pronounce": "كِي پِي إتْش", "ex_en": "100 kph speed", "ar_ex": "سرعة 100 كم/ساعة" },
  { "id": 277, "en": "laboratory", "ar": "مختبر", "pronounce": "لَابْرُوتُوري", "ex_en": "A science laboratory", "ar_ex": "مختبر علوم" },
  { "id": 278, "en": "law", "ar": "قانون", "pronounce": "لُو", "ex_en": "Obey the law", "ar_ex": "أطع القانون" },
  { "id": 279, "en": "leisure", "ar": "وقت الفراغ", "pronounce": "لِژَر", "ex_en": "Leisure time", "ar_ex": "وقت الفراغ" },
  { "id": 280, "en": "life raft", "ar": "قارب نجاة", "pronounce": "لَايْف رَافْت", "ex_en": "Use a life raft", "ar_ex": "استخدم قارب نجاة" },
  { "id": 281, "en": "lower", "ar": "يخفض", "pronounce": "لُووَر", "ex_en": "Lower your voice", "ar_ex": "اخفض صوتك" },
  { "id": 282, "en": "measure", "ar": "يقيس", "pronounce": "مِژَر", "ex_en": "Measure the room", "ar_ex": "قس الغرفة" },
  { "id": 283, "en": "melt", "ar": "يذوب", "pronounce": "مِلْت", "ex_en": "Ice will melt", "ar_ex": "الجليد سيذوب" },
  { "id": 284, "en": "might", "ar": "ربما / قد", "pronounce": "مَايْت", "ex_en": "It might rain", "ar_ex": "قد تمطر" },
  { "id": 285, "en": "missing", "ar": "مفقود", "pronounce": "مِسِنْغ", "ex_en": "A missing child", "ar_ex": "طفل مفقود" },
  { "id": 286, "en": "moreover", "ar": "علاوة على ذلك", "pronounce": "مُورْأُوڤَر", "ex_en": "Moreover it is cold", "ar_ex": "علاوة على ذلك الجو بارد" },
  { "id": 287, "en": "mudslide", "ar": "انهيار طيني", "pronounce": "مَدْسْلَايْد", "ex_en": "A dangerous mudslide", "ar_ex": "انهيار طيني خطير" },
  { "id": 288, "en": "nearly", "ar": "تقريباً", "pronounce": "نِيرْلي", "ex_en": "Nearly done", "ar_ex": "انتهى تقريباً" },
  { "id": 289, "en": "office", "ar": "مكتب", "pronounce": "أُوفِس", "ex_en": "My work office", "ar_ex": "مكتب عملي" },
  { "id": 290, "en": "on fire", "ar": "مشتعل", "pronounce": "أُون فَايَر", "ex_en": "The house is on fire", "ar_ex": "المنزل مشتعل" },
  { "id": 291, "en": "or (= if not)", "ar": "أو (وإلا)", "pronounce": "أُور", "ex_en": "Stop or I will call", "ar_ex": "توقف وإلا سأتصل" },
  { "id": 292, "en": "orbit", "ar": "يدور حول / مدار", "pronounce": "أُورْبِت", "ex_en": "Earth orbit", "ar_ex": "مدار الأرض" },
  { "id": 293, "en": "orchard", "ar": "بستان", "pronounce": "أُورْتْشَرْد", "ex_en": "Apple orchard", "ar_ex": "بستان تفاح" },
  { "id": 294, "en": "own (on my ~)", "ar": "خاص / بمفردي", "pronounce": "أُون", "ex_en": "On my own", "ar_ex": "بمفردي" },
  { "id": 295, "en": "paramedic", "ar": "مسعف", "pronounce": "پَارَامِدِك", "ex_en": "Call a paramedic", "ar_ex": "اتصل بمسعف" },
  { "id": 296, "en": "partner", "ar": "شريك", "pronounce": "پَارْتْنَر", "ex_en": "My business partner", "ar_ex": "شريك عملي" },
  { "id": 297, "en": "(travel) permit", "ar": "تصريح سفر", "pronounce": "پِرْمِت", "ex_en": "I need a permit", "ar_ex": "أحتاج تصريحا" },
  { "id": 298, "en": "photography", "ar": "تصوير فوتوغرافي", "pronounce": "فُوتُوغْرَافِي", "ex_en": "Love photography", "ar_ex": "أحب التصوير" },
  { "id": 299, "en": "poetry", "ar": "شعر", "pronounce": "پُووِتْرِي", "ex_en": "Read Arabic poetry", "ar_ex": "اقرأ شعرا عربيا" },
  { "id": 300, "en": "point", "ar": "نقطة", "pronounce": "پُويْنْت", "ex_en": "A good point", "ar_ex": "نقطة جيدة" },
  { "id": 301, "en": "poor", "ar": "فقير / ضعيف", "pronounce": "پُور", "ex_en": "A poor man", "ar_ex": "رجل فقير" },
  { "id": 302, "en": "position", "ar": "موضع / منصب", "pronounce": "پُوزِشِن", "ex_en": "A high position", "ar_ex": "منصب عال" },
  { "id": 303, "en": "practice", "ar": "ممارسة / تدريب", "pronounce": "پْرَاكْتِس", "ex_en": "Practice makes perfect", "ar_ex": "التدريب يصنع الإتقان" },
  { "id": 304, "en": "PS (postscript)", "ar": "ملاحظة", "pronounce": "پِي إس", "ex_en": "PS call me", "ar_ex": "ملاحظة: اتصل بي" },
  { "id": 305, "en": "predict", "ar": "يتنبأ / يتوقع", "pronounce": "پْرِدِكْت", "ex_en": "Predict the future", "ar_ex": "توقع المستقبل" },
  { "id": 306, "en": "pretty", "ar": "جميل / إلى حد ما", "pronounce": "پْرِتِي", "ex_en": "A pretty girl", "ar_ex": "فتاة جميلة" },
  { "id": 307, "en": "prize", "ar": "جائزة", "pronounce": "پْرَايْز", "ex_en": "Win a prize", "ar_ex": "اربح جائزة" },
  { "id": 308, "en": "product", "ar": "منتج", "pronounce": "پْرُودَكْت", "ex_en": "A new product", "ar_ex": "منتج جديد" },
  { "id": 309, "en": "proper(ly)", "ar": "مناسب / بشكل صحيح", "pronounce": "پْرُوپَر", "ex_en": "Do it properly", "ar_ex": "افعلها بشكل صحيح" },
  { "id": 310, "en": "protection", "ar": "حماية", "pronounce": "پْرُوتِكْشِن", "ex_en": "Sun protection", "ar_ex": "حماية من الشمس" },
  { "id": 311, "en": "publish", "ar": "ينشر", "pronounce": "پَبْلِش", "ex_en": "Publish a book", "ar_ex": "انشر كتابا" },
  { "id": 312, "en": "quad bike", "ar": "دراجة رباعية", "pronounce": "كْوَاد بَايْك", "ex_en": "Ride a quad bike", "ar_ex": "اركب دراجة رباعية" },
  { "id": 313, "en": "radiation", "ar": "إشعاع", "pronounce": "رِيْدِيِيْشِن", "ex_en": "Dangerous radiation", "ar_ex": "إشعاع خطير" },
  { "id": 314, "en": "rainfall", "ar": "هطول الأمطار", "pronounce": "رِيْنْفُول", "ex_en": "Heavy rainfall", "ar_ex": "هطول أمطار غزير" },
  { "id": 315, "en": "reading", "ar": "قراءة", "pronounce": "رِيدِنْغ", "ex_en": "I love reading", "ar_ex": "أحب القراءة" },
  { "id": 316, "en": "recycle", "ar": "يعيد تدوير", "pronounce": "رِسَايْكِل", "ex_en": "Recycle paper", "ar_ex": "أعد تدوير الورق" },
  { "id": 317, "en": "refugee", "ar": "لاجئ", "pronounce": "رِفْيُوجِي", "ex_en": "A refugee camp", "ar_ex": "مخيم لاجئين" },
  { "id": 318, "en": "region", "ar": "منطقة / إقليم", "pronounce": "رِيجِن", "ex_en": "A hot region", "ar_ex": "منطقة حارة" },
  { "id": 319, "en": "reply", "ar": "يرد", "pronounce": "رِپْلَاي", "ex_en": "Reply to my email", "ar_ex": "رد على إيميلي" },
  { "id": 320, "en": "research", "ar": "بحث علمي", "pronounce": "رِسِيرْتْش", "ex_en": "Do some research", "ar_ex": "قم ببعض البحث" },
  { "id": 321, "en": "result (as a~)", "ar": "نتيجة", "pronounce": "رِزَلْت", "ex_en": "As a result", "ar_ex": "كنتيجة لذلك" },
  { "id": 322, "en": "riddle", "ar": "لغز", "pronounce": "رِدِل", "ex_en": "Solve this riddle", "ar_ex": "حل هذا اللغز" },
  { "id": 323, "en": "round", "ar": "جولة / دائري", "pronounce": "رَاوْنْد", "ex_en": "A round table", "ar_ex": "طاولة دائرية" },
  { "id": 324, "en": "row", "ar": "صف / يجدف", "pronounce": "رُو", "ex_en": "Sit in a row", "ar_ex": "اجلس في صف" },
  { "id": 325, "en": "rugby", "ar": "رياضة الرغبي", "pronounce": "رَگْبِي", "ex_en": "Play rugby", "ar_ex": "العب الرغبي" },
  { "id": 326, "en": "satellite phone", "ar": "هاتف فضائي", "pronounce": "سَاتِلَايْت فُون", "ex_en": "Use satellite phone", "ar_ex": "استخدم هاتفاً فضائياً" },
  { "id": 327, "en": "satnav", "ar": "ملاحة فضائية", "pronounce": "سَاتْنَاو", "ex_en": "Check the satnav", "ar_ex": "تفقد الملاحة الفضائية" },
  { "id": 328, "en": "scout", "ar": "كشاف", "pronounce": "سْكَاوْت", "ex_en": "A brave scout", "ar_ex": "كشاف شجاع" },
  { "id": 329, "en": "senior", "ar": "كبير / خريج", "pronounce": "سِينْيَر", "ex_en": "Senior manager", "ar_ex": "مدير كبير" },
  { "id": 330, "en": "service", "ar": "خدمة", "pronounce": "سِيرْڤِس", "ex_en": "Room service", "ar_ex": "خدمة الغرف" },
  { "id": 331, "en": "set off", "ar": "ينطلق", "pronounce": "سِت أُوف", "ex_en": "Set off early", "ar_ex": "انطلق مبكرا" },
  { "id": 332, "en": "settle in", "ar": "يستقر", "pronounce": "سِتِل إن", "ex_en": "Settle in the house", "ar_ex": "يستقر في المنزل" },
  { "id": 333, "en": "settlement", "ar": "مستوطنة / تسوية", "pronounce": "سِتِلْمِنْت", "ex_en": "A new settlement", "ar_ex": "مستوطنة جديدة" },
  { "id": 334, "en": "show (someone) round", "ar": "يأخذ في جولة", "pronounce": "شُو رَاوْنْد", "ex_en": "Show him round", "ar_ex": "خذه في جولة" },
  { "id": 335, "en": "similar", "ar": "مشابه", "pronounce": "سِمِلَر", "ex_en": "Similar taste", "ar_ex": "طعم مشابه" },
  { "id": 336, "en": "smoke", "ar": "دخان", "pronounce": "سْمُوك", "ex_en": "Black smoke", "ar_ex": "دخان أسود" },
  { "id": 337, "en": "so far", "ar": "حتى الآن", "pronounce": "سُو فَار", "ex_en": "Good so far", "ar_ex": "جيد حتى الآن" },
  { "id": 338, "en": "spread", "ar": "ينتشر", "pronounce": "سْپْرِد", "ex_en": "News spread fast", "ar_ex": "الأخبار تنتشر بسرعة" },
  { "id": 339, "en": "station", "ar": "محطة", "pronounce": "سْتِيْشِن", "ex_en": "Train station", "ar_ex": "محطة قطار" },
  { "id": 340, "en": "steal", "ar": "يسرق", "pronounce": "سْتِيل", "ex_en": "Do not steal", "ar_ex": "لا تسرق" },
  { "id": 341, "en": "steep", "ar": "شديد الانحدار", "pronounce": "سْتِيپ", "ex_en": "A steep hill", "ar_ex": "تل شديد الانحدار" },
  { "id": 342, "en": "storm", "ar": "عاصفة", "pronounce": "سْتُورْم", "ex_en": "A bad storm", "ar_ex": "عاصفة سيئة" },
  { "id": 343, "en": "storm surge", "ar": "عاصفة بأمواج", "pronounce": "سْتُورْم سِيرْج", "ex_en": "A dangerous storm surge", "ar_ex": "عاصفة بأمواج خطيرة" },
  { "id": 344, "en": "succeed", "ar": "ينجح", "pronounce": "سَكْسِيد", "ex_en": "Work hard to succeed", "ar_ex": "اعمل بجد لتنجح" },
  { "id": 345, "en": "success", "ar": "نجاح", "pronounce": "سَكْسِس", "ex_en": "Great success", "ar_ex": "نجاح عظيم" },
  { "id": 346, "en": "supply", "ar": "يزود / إمداد", "pronounce": "سَپْلَاي", "ex_en": "Water supply", "ar_ex": "إمداد المياه" },
  { "id": 347, "en": "take (someone) out", "ar": "يخرج شخصا", "pronounce": "تِيك آوْت", "ex_en": "Take him out", "ar_ex": "أخرجه" },
  { "id": 348, "en": "temperature", "ar": "درجة حرارة", "pronounce": "تِمْپْرِتْشَر", "ex_en": "High temperature", "ar_ex": "درجة حرارة عالية" },
  { "id": 349, "en": "thanks to", "ar": "بفضل", "pronounce": "ثَانْكْس تُو", "ex_en": "Thanks to you", "ar_ex": "بفضلك" },
  { "id": 350, "en": "think of", "ar": "يفكر في", "pronounce": "ثِنْك أُوف", "ex_en": "Think of an idea", "ar_ex": "فكر في فكرة" },
  { "id": 351, "en": "tornado", "ar": "إعصار", "pronounce": "تُورْنِيْدُو", "ex_en": "A fierce tornado", "ar_ex": "إعصار عنيف" },
  { "id": 352, "en": "track", "ar": "مسار / يتتبع", "pronounce": "تْرَاك", "ex_en": "Keep on track", "ar_ex": "ابق على المسار" },
  { "id": 353, "en": "tragic", "ar": "مأساوي", "pronounce": "تْرَاجِك", "ex_en": "A tragic story", "ar_ex": "قصة مأساوية" },
  { "id": 354, "en": "treasure", "ar": "كنز", "pronounce": "تْرِژَر", "ex_en": "Hidden treasure", "ar_ex": "كنز مخفي" },
  { "id": 355, "en": "treasure hunt", "ar": "بحث عن الكنز", "pronounce": "تْرِژَر هَنْت", "ex_en": "Play treasure hunt", "ar_ex": "العب لعبة البحث عن الكنز" },
  { "id": 356, "en": "treat", "ar": "يعالج / يعامل", "pronounce": "تْرِيت", "ex_en": "Treat him well", "ar_ex": "عامله جيدا" },
  { "id": 357, "en": "turn into", "ar": "يتحول إلى", "pronounce": "تِيرْن إنْتُو", "ex_en": "Turn into ice", "ar_ex": "يتحول إلى جليد" },
  { "id": 358, "en": "unhurt", "ar": "سليم / غير مصاب", "pronounce": "أنْهِيرْت", "ex_en": "He is unhurt", "ar_ex": "إنه غير مصاب" },
  { "id": 359, "en": "university", "ar": "جامعة", "pronounce": "يُونِڤِيرْسِتي", "ex_en": "Go to university", "ar_ex": "اذهب للجامعة" },
  { "id": 360, "en": "usual", "ar": "معتاد", "pronounce": "يُوژُوَل", "ex_en": "As usual", "ar_ex": "كالمعتاد" },
  { "id": 361, "en": "view", "ar": "منظر", "pronounce": "ڤْيُو", "ex_en": "A nice view", "ar_ex": "منظر جميل" },
  { "id": 362, "en": "violent", "ar": "عنيف", "pronounce": "ڤَايُولِنْت", "ex_en": "A violent storm", "ar_ex": "عاصفة عنيفة" },
  { "id": 363, "en": "war", "ar": "حرب", "pronounce": "وُور", "ex_en": "End the war", "ar_ex": "أنهوا الحرب" },
  { "id": 364, "en": "warehouse", "ar": "مستودع", "pronounce": "وِيرْهَاوْس", "ex_en": "A big warehouse", "ar_ex": "مستودع كبير" },
  { "id": 365, "en": "wave", "ar": "موجة", "pronounce": "وِيْڤ", "ex_en": "A big wave", "ar_ex": "موجة كبيرة" },
  { "id": 366, "en": "weigh", "ar": "يَزِن", "pronounce": "وِيْ", "ex_en": "Weigh the bag", "ar_ex": "زِن الحقيبة" },
  { "id": 367, "en": "wildfire", "ar": "حريق غابة", "pronounce": "وَايْلْدْفَايَر", "ex_en": "Stop the wildfire", "ar_ex": "أوقف حريق الغابة" },
  { "id": 368, "en": "write down", "ar": "يدوّن", "pronounce": "رَايْت دَاوْن", "ex_en": "Write down notes", "ar_ex": "دوّن الملاحظات" },
  { "id": 369, "en": "X-ray", "ar": "أشعة سينية", "pronounce": "إكْس رِي", "ex_en": "Take an X-ray", "ar_ex": "خذ أشعة سينية" }
];